### ISSUE TITLE
Improve build artifact ZIP 

### ISSUE THREAD

**Issue by davelab6** [googlefonts/googlesans#100]
Version 3.003 (from https://github.com/googlefonts/googlesans/releases has a `GoogleSans.zip` which unpacks as `/build\ 2/GoogleSans`

I have 2 requests

- [ ] Filename can declare version, eg `GoogleSans-v3_003.zip`
- [ ] Path should not include the first `/build\ 2/GoogleSans` empty top level folders

**Comment by chrissimpkins** [comment]
This duplicates and expands on https://github.com/googlefonts/googlesans/issues/94 :) 

No problem.  We will address this before the next release push.
