### ISSUE TITLE
Add midline horizontal ellipsis (U+22EF)

### ISSUE THREAD

**Issue by davelab6** [googlefonts/googlesans#101]
Similar to #99, a customer team requests an additional glyph:

> “...” default is bottom alignment.  
> We use “...” in tabular view , similar to “--”:  
> “-- = no data  
> “    “ = happening in between two time spots.
>
> <img width="583" alt="Screen Shot 2020-10-15 at 3 49 01 PM" src="https://user-images.githubusercontent.com/261579/96178876-09925880-0efe-11eb-942a-9c0dc582fd2d.png">

@chrissimpkins mentioned that 

> Google Sans / Google Sans Text does include an ellipsis (`U+2026`). This should be positioned on the baseline. It sounds like you may require a new midline horizontal ellipsis (`U+22EF`) to achieve this.

I agree, `U+22EF` should be added.

**Comment by chrissimpkins** [comment]
Added in #371. This will be released in v6.000
