### ISSUE TITLE
Fontbakery CI tests fail because we're overwriting existing conditions

### ISSUE THREAD

**Issue by madig** [googlefonts/googlesans#106]
Something in fontbakery changed since CI was last run on master and now it will fail: https://github.com/googlefonts/googlesans/runs/1452930092

```
[...]
   File "qa/check-googlesans.py", line 384, in <module>
    profile.auto_register(globals())
[...]
fontbakery.checkrunner.NamespaceError: Name "is_italic" is already registered in "conditions" (value: <FontBakeryCondition:is_italic>). Requested registering in "conditions" (value: <FontBakeryCondition:is_italic>).
```

A quick look at `qa/check-googlesans.py` suggests that it is trying to overwrite existing conditions such as `is_italic` and fontbakery will not have it.

**Comment by chrissimpkins** [comment]
Thanks Niko.  It doesn't look like we are using the condition in custom checks.  I don't remember a need to override the upstream definition for the universal profile checks.  Let me take it out and we'll see...

**Comment by chrissimpkins** [comment]
Well, there is good news and there is bad news in #107 ...

Removing the custom conditions works fine.  But it looks like upstream fontbakery universal check profile added a new component of components check that is failing on over 1000 glyphs.  It seems that this fails a default, common design approach that Edd is using here.  So we aren't going to see passes until we either inactivate this check (if we do not feel that it is an appropriate fail) or ask Edd to update 1000+ designs.

**Comment by madig** [comment]
Mh. There's a ufo2ft filter that unnests components at compile time: https://github.com/googlefonts/fontbakery/issues/2961#issuecomment-733745539.

**Comment by chrissimpkins** [comment]
What is file size impact of doing so? That is a significant issue for us.

**Comment by chrissimpkins** [comment]
https://github.com/googlefonts/googlesans/issues/108

Let's hold the discussion in ^^.  I'd like to investigate this issue in a bit more detail to see what environments are involved and the file size tradeoff required to address this test.

**Comment by madig** [comment]
I have not checked but there is only one way to find out!!!!!!!

**Comment by madig** [comment]
Default statics: + ~3 KB
Variable full: + ~ 6-7 KB
Variable subsets: + ~4-5 KB

Without doing any deeper research into it or even testing if the fonts work as before.

**Comment by chrissimpkins** [comment]
> Default statics: + ~3 KB
> Variable full: + ~ 6-7 KB
> Variable subsets: + ~4-5 KB
> 
> Without doing any deeper research into it or even testing if the fonts work as before.

C/P into #108 for discussion with Dave and Nyshadh

**Comment by chrissimpkins** [comment]
This issue is addressed in https://github.com/googlefonts/googlesans/pull/107

The nested components issue in the discussions here is issue https://github.com/googlefonts/googlesans/issues/108
