### ISSUE TITLE
Armenian design UFO source format conversion duplicate layer error

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans#117]
@gorjious 

I attempted the glyphs2ufo script on the glyphs format source files that you plan to submit in a pull request next week.  I get the following error:

```
Glyph '_To.shape': All components of the background layer of 'Mar 31 20, 13:45' will be decomposed.
Glyph '_To.shape': All components of the background layer of 'May 18 20, 14:13' will be decomposed.
Glyph '_To.shape': All components of the background layer of 'May 18 20, 14:19' will be decomposed.
Glyph '_To.shape': All components of the background layer of 'May 18 20, 14:24' will be decomposed.
Glyph '_To.shape': All components of the background layer of 'May 18 20, 14:26' will be decomposed.
Glyph '_To.shape': All components of the background layer of 'May 18 20, 14:27' will be decomposed.
Glyph '_To.shape': All components of the background layer of 'Jun 18 20, 16:13' will be decomposed.
Google Sans Upright Text Bold: Glyph _To.shape, layer Jun 18 20, 16:13: Duplicate glyph layer name
Traceback (most recent call last):
  File "scripts/gs-glyphs2ufo.py", line 37, in <module>
    designspace = glyphsLib.to_designspace(
  File "/Users/chris/code/googlesans/.venv/lib/python3.8/site-packages/glyphsLib/builder/__init__.py", line 111, in to_designspace
    return builder.designspace
  File "/Users/chris/code/googlesans/.venv/lib/python3.8/site-packages/glyphsLib/builder/builders.py", line 294, in designspace
    list(self.masters)  # Make sure that the UFOs are built
  File "/Users/chris/code/googlesans/.venv/lib/python3.8/site-packages/glyphsLib/builder/builders.py", line 257, in masters
    self.to_ufo_glyph(ufo_glyph, layer, layer.parent)
  File "/Users/chris/code/googlesans/.venv/lib/python3.8/site-packages/glyphsLib/builder/glyph.py", line 131, in to_ufo_glyph
    self.to_ufo_glyph_background(ufo_glyph, layer)
  File "/Users/chris/code/googlesans/.venv/lib/python3.8/site-packages/glyphsLib/builder/glyph.py", line 305, in to_ufo_glyph_background
    new_glyph = ufo_layer.newGlyph(glyph.name)
  File "/Users/chris/code/googlesans/.venv/lib/python3.8/site-packages/ufoLib2/objects/layer.py", line 279, in newGlyph
    raise KeyError(f"glyph named '{name}' already exists")
KeyError: "glyph named '_To.shape' already exists"
```

It looks like you have some outlines that are **not exported and include multiple layers with the same name**.  That is the case for the above `_To.shape` glyph that led to this error (layer = `Jun 18 20, 16:13`).  Will you please remove all unexported glyphs from the source files and confirm that all exported glyphs do not have duplicated layer names?

Thanks!

cc @belluzj @madig 

---

### TODO

- [x] remove all unexported glyphs from the Armenian glyphs format source files
- [x] remove all duplicate layers from exported glyphs in the Armenian glyphs format source files

**Comment by gorjious** [comment]
One moment. I will upload a flattened version with only exporting glyphs.

**Comment by gorjious** [comment]
I've uploaded a flattened version with:

   - all components decomposed
   - non-master layers removed
   - bracket layers set to 18
   - non-exportable glyphs are removed

https://github.com/gorjious/google-sans-armenian/commit/b46e774ade97de6e643f7969b9e412ce5ae96ec6

I think the reason for that particular error is because there are two
layers with the same time-stamp.

Is there a final decision on the use of components vs outlines? For
example, if the Armenian hyphen uses the Latin hyphen, can this be
referenced as a component or will it need to be decomposed into an outline.
There are other examples that I am curious to know if they will cause any
issues remaining as components.

**Comment by chrissimpkins** [comment]
Thanks Gor!

I tried to run the UFO transform script on your new source file and am getting a new error:

```
Glyph 'Zedescender-cy': All components of the background layer of 'Sans Regular' will be decomposed.
Glyph 'Zedescender-cy': All components of the background layer of 'Text Regular' will be decomposed.
Glyph 'Zedescender-cy': All components of the background layer of 'Sans Bold' will be decomposed.
Glyph 'Zedescender-cy': All components of the background layer of 'Text Bold' will be decomposed.
Glyph 'Pedescender-cy': All components of the background layer of 'Text Regular' will be decomposed.
Traceback (most recent call last):
  File "scripts/gs-glyphs2ufo.py", line 37, in <module>
    designspace = glyphsLib.to_designspace(
  File "/Users/chris/code/googlesans/.venv/lib/python3.8/site-packages/glyphsLib/builder/__init__.py", line 111, in to_designspace
    return builder.designspace
  File "/Users/chris/code/googlesans/.venv/lib/python3.8/site-packages/glyphsLib/builder/builders.py", line 294, in designspace
    list(self.masters)  # Make sure that the UFOs are built
  File "/Users/chris/code/googlesans/.venv/lib/python3.8/site-packages/glyphsLib/builder/builders.py", line 216, in masters
    self.to_ufo_glyph(ufo_glyph, layer, glyph)
  File "/Users/chris/code/googlesans/.venv/lib/python3.8/site-packages/glyphsLib/builder/glyph.py", line 131, in to_ufo_glyph
    self.to_ufo_glyph_background(ufo_glyph, layer)
  File "/Users/chris/code/googlesans/.venv/lib/python3.8/site-packages/glyphsLib/builder/glyph.py", line 313, in to_ufo_glyph_background
    self.to_ufo_components(new_glyph, background)
  File "/Users/chris/code/googlesans/.venv/lib/python3.8/site-packages/glyphsLib/builder/components.py", line 44, in to_ufo_components
    to_ufo_components_background_decompose(self, ufo_glyph, layer)
  File "/Users/chris/code/googlesans/.venv/lib/python3.8/site-packages/glyphsLib/builder/components.py", line 112, in to_ufo_components_background_decompose
    component.draw(rpen)
  File "/Users/chris/code/googlesans/.venv/lib/python3.8/site-packages/glyphsLib/classes.py", line 2309, in draw
    pen.addComponent(self.name, self.transform)
  File "/Users/chris/code/googlesans/.venv/lib/python3.8/site-packages/fontTools/pens/basePen.py", line 176, in addComponent
    glyph = self.glyphSet[glyphName]
KeyError: '__descender-cy.case'
```

It looks like the __descender-cy.case glyph definition is gone but is still showing up somewhere to suggest that it should be present in the glyph set here.  I'll need to look into this error in more detail to understand what is going on.  

> Is there a final decision on the use of components vs outlines?

It is ok to use traditional components.  Please do not use recursive/nested component definitions (see https://github.com/googlefonts/googlesans/issues/108).

**Comment by madig** [comment]
(I'll look at this on Monday)

**Comment by gorjious** [comment]
Sorry, seems like I accidentally deleted some non-exporting components used
in those Cyrillic letters. I added them back and uploaded the new file.

https://github.com/gorjious/google-sans-armenian/blob/master/source/GoogleSans/GoogleSans_210109_flattened.glyphs

**Comment by madig** [comment]
I can't access your repo unfortunately. Can you please attach the file to a comment here or in a pull request?

PS, there's a script to remove all unimportant layers: https://forum.glyphsapp.com/t/i-want-to-erase-unused-layers-from-all-glyphs/16889/2

**Comment by chrissimpkins** [comment]
Here is the error that I see with the gs-glyphs2ufo script in the latest iteration of the Armenian source:

```
---SNIP---

Glyph 'Ayb-arm': All components of the background layer of 'Sans Bold' will be decomposed.
Traceback (most recent call last):
  File "scripts/gs-glyphs2ufo.py", line 37, in <module>
    designspace = glyphsLib.to_designspace(
  File "/Users/chris/code/googlesans/.venv/lib/python3.8/site-packages/glyphsLib/builder/__init__.py", line 111, in to_designspace
    return builder.designspace
  File "/Users/chris/code/googlesans/.venv/lib/python3.8/site-packages/glyphsLib/builder/builders.py", line 294, in designspace
    list(self.masters)  # Make sure that the UFOs are built
  File "/Users/chris/code/googlesans/.venv/lib/python3.8/site-packages/glyphsLib/builder/builders.py", line 216, in masters
    self.to_ufo_glyph(ufo_glyph, layer, glyph)
  File "/Users/chris/code/googlesans/.venv/lib/python3.8/site-packages/glyphsLib/builder/glyph.py", line 131, in to_ufo_glyph
    self.to_ufo_glyph_background(ufo_glyph, layer)
  File "/Users/chris/code/googlesans/.venv/lib/python3.8/site-packages/glyphsLib/builder/glyph.py", line 313, in to_ufo_glyph_background
    self.to_ufo_components(new_glyph, background)
  File "/Users/chris/code/googlesans/.venv/lib/python3.8/site-packages/glyphsLib/builder/components.py", line 44, in to_ufo_components
    to_ufo_components_background_decompose(self, ufo_glyph, layer)
  File "/Users/chris/code/googlesans/.venv/lib/python3.8/site-packages/glyphsLib/builder/components.py", line 112, in to_ufo_components_background_decompose
    component.draw(rpen)
  File "/Users/chris/code/googlesans/.venv/lib/python3.8/site-packages/glyphsLib/classes.py", line 2309, in draw
    pen.addComponent(self.name, self.transform)
  File "/Users/chris/code/googlesans/.venv/lib/python3.8/site-packages/fontTools/pens/basePen.py", line 176, in addComponent
    glyph = self.glyphSet[glyphName]
KeyError: '_part.cap.arch.down'
```

File attached Niko.

[GoogleSans_Armenian.glyphs.zip](https://github.com/googlefonts/googlesans/files/5795735/GoogleSans_Armenian.glyphs.zip)

**Comment by gorjious** [comment]
Hi Chris and Nikolaus,

I've sent Nikolaus an invite to collaborate on the repo.
I just uploaded a new version with all background layers and guidelines
removed.

https://github.com/gorjious/google-sans-armenian/blob/master/source/GoogleSans/GoogleSans_210111.glyphs

– Gor

**Comment by madig** [comment]
Thanks Gor,
your file now fails with `ValueError: Glyph one.cap: Bracket layer [14] must be within the design space bounds of the Optical size axis: minimum 17, maximum 18`. Did you fork off the project at a stage where the Optical size split was at 14?

Edit: maybe you can try this: in Glyphs.app's language sidebar, select "Armenian", select all glyphs, click "All" in the category sidebar, select Edit -> Invert Selection and hit delete. When asked about unlinking metrics keys, say "cancel". This should remove everything unrelated to your work (I hope).

**Comment by gorjious** [comment]
Yes, that must be what remained from a previous stage of the project and
seems like it was supposed to be a brace layer. In any case, I've removed
the glyphs with the brace layers (I believe these are also removed from the
master source) and shifted the remaining glyphs with bracket layers to 18.

https://github.com/gorjious/google-sans-armenian/blob/master/source/GoogleSans/GoogleSans_210112.glyphs

**Comment by madig** [comment]
That works. Is there an italic files as well? Also, please provide glyph and group name lists to import.

**Comment by gorjious** [comment]
I have a few questions about the formatting of the list.
I've included a draft of the Glyphs, Classes, and Features that are used
(Kerning groups are not yet included)
https://github.com/gorjious/google-sans-armenian/blob/master/source/GoogleSans/GS_Armenian_list_draft

Do you have any feedback on the organisation of this portion?

There is a minor adjustment I need to make the Latin comma (Chris has
requested I include this in my merge source), should this be noted
separately from the Armenian glyphs? I currently have them divided with #
comments.

There are also three types of names of the classes:

   - Armenian specific
   - Shared with Georgian
   - Additions to existing (notes which glyph is added to which class)

I've listed in which features Armenian is being used in. In some cases,
Armenian can be a separate block in the feature code, while in other it is
integrated into different portions. For example, in the locl feature, the
lookup is defined at the top and included under various script tags (these
are all noted with comments in the Glyphs Features).

In terms of naming conventions, for the Armenian specific classes, I have
used the script tag "armn" as opposed to the language tag "HYE". The
Maintainer document seems to suggest to use the all-caps language tag –
will the current naming work?

Should the list of kerning groups be included with the list of
glyphs/classes/features, or a separate list?

For the kerning groups, I have primarily used "arm_" as the prefix. There
are a few punctuation marks which share an existing kerning group name with
Latin (i.e. period, colon, etc.) should these also be included in the list
of kerning groups?

**Comment by chrissimpkins** [comment]
The current list format LGTM Gor.  Thoughts @madig @belluzj?

> There is a minor adjustment I need to make the Latin comma (Chris has
requested I include this in my merge source), should this be noted
separately from the Armenian glyphs?

This is correct and approved.  While this will not be typical in merged i18n work, there will be a Latin glyph set change coming as part of these updates from Gor.

> In terms of naming conventions, for the Armenian specific classes, I have
used the script tag "armn" as opposed to the language tag "HYE". The
Maintainer document seems to suggest to use the all-caps language tag –
will the current naming work?

Here is where we are with the documentation of the approach to script / lang tags atm:

- Kerning groups should contain the name of the script they pertain to. Glyphs.app naming does this automatically by using the glyph name as a group name, which includes a script tag. Example: boBaimai-thai. This avoids name clashes.
- The name or contents of existing groups should only be changed after Google gave the approval.
- Feature code should be organized so that:
feature blocks and lookups are declared separately. This makes merging much easier.
lookups should have descriptive names and should include, where it makes sense, the language and feature tag where they are used. Example: NLD_locl_ij_substitution for a netherlandish lookup that replaces i' j' by ij. See https://docs.microsoft.com/en-us/typography/opentype/spec/languagetags for ISO 639 language tags.

It looks like we are using both script and lang tags in our requirements.  As I understand the docs, we should use:

- script tag in kerning groups
- script tag in glyph names
- language tag (and feature tag) in lookup names

It is not explicit but the examples suggest that this should be lower case for script tags and upper case for lang tags.  I don't typically see ISO tags in all caps.  We should clarify these docs so that this is clear and, ideally, use ISO definitions with ISO  formatting standards.  At the moment, ISO 15924 (script) and ISO 639-X (lang) are under consideration.  Nikolaus and Jany, do you have strong feelings about how to approach this?

> Should the list of kerning groups be included with the list of
glyphs/classes/features, or a separate list?

Please do create a separate list of kerning groups Gor.  The documentation demonstrates how to dump the standard output from the Python script to a text file. You do not need to format the text file dump further.  Let's confirm that we are happy with the script standard output as the default documentation of kerning groups.

> For the kerning groups, I have primarily used "arm_" as the prefix. There
are a few punctuation marks which share an existing kerning group name with
Latin (i.e. period, colon, etc.) should these also be included in the list
of kerning groups?

Jany and Nikolaus, is it simple to perform a "arm_" -> [WHATEVER WE WANT] string replacement during the import or do you want Gor to replace these on his end.  

Gor, `arm` is not part of the ISO standard so I think that *some* change will be required here to meet our requirements.  If we go with lang it will be `hye` vs.` hyw`, if we go with script it will be `Armn`.  Let's see what Nikolaus and Jany think about this.

**Comment by madig** [comment]
Thanks for the list, although I have to cut it up. Please see https://github.com/googlefonts/googlesans/blob/convert-to-ufo/docs/MAINTAINER.md#getting-a-list-of-glyphs-and-kerning-groups for what exactly we need. 

Features we need to import separately, just make sure that _all_ Armenian lookups and groups are defined standalone at the top and are just referred to in feature code. Yes, Glyphs.app likes to put everything inline, that just makes our job much harder and error prone. For feature additions shared with other scripts, well, we'll need you to scrutinize our merge result :)

> There are a few punctuation marks which share an existing kerning group name with Latin (i.e. period, colon, etc.) should these also be included in the list of kerning groups?

You can insert those into existing groups and add the existing kerning group name to the list.

> It is not explicit but the examples suggest that this should be lower case for script tags and upper case for lang tags. I don't typically see ISO tags in all caps. We should clarify these docs so that this is clear and, ideally, use ISO definitions with ISO formatting standards. At the moment, ISO 15924 (script) and ISO 639-X (lang) are under consideration. Nikolaus and Jany, do you have strong feelings about how to approach this?

This is a carry-over from our feature style guidelines. They say:

> Class naming should use the following format:
> 
>     A_B_C_D
>     A - Context-dependent Script system tag - only for Non-Latin scripts
>     B - Context-dependent language system tag
>     C - Context-dependent feature tag
>     D - Class Description string
> 
> E.g.:
> 
>     C: PNUM
>     C_D: PNUM_CURRENCIES
>     C_D: FRAC_PRECOMPOSED
>     A_B_C: CYRL_BGR_LOCL
>     A_C_D_D: GREK_CALT_MARKS_CONTEXT
> 
> Lookup naming should use the following format:
> 
>     A_B_C_D
>     A - Context-dependent Script system tag - only for Non-Latin scripts
>     B - Context-dependent language system tag
>     C - Feature tag
>     D - Lookup description string
> 
> E.g.:
> 
>     B_C_D_D: ROM_locl_cedilla_substitution
>     A_C_D_D: GREK_ccmp_recompose_dieresistonos
>     A_B_C_D: CYRL_BGR_locl_alternates
>     C_D: frac_precomposed

I think the guiding principle here is immediate recognizability, but I suppose that's subjective. To be consistent, we'd also need to reorganize Glyphs.app's output so far...

> Jany and Nikolaus, is it simple to perform a "arm_" -> [WHATEVER WE WANT] string replacement during the import or do you want Gor to replace these on his end.

Can do.

**Comment by chrissimpkins** [comment]
I think that we are all set with the issues here following our discussion today.  I'll open a new thread for the Armenian merge and we'll continue discussions there.
