### ISSUE TITLE
Armenian script merge

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans#121]
Thread for the merge of the Armenian script designs.

@gorjious, please package your sources and testing documents as a zip archive, then drag and drop them into a post in this thread.  Thanks!

cc @madig @belluzj

**Comment by gorjious** [comment]
I am noticing that the `import_groups.txt` isn't filtering some kerning groups for general punctuation glyphs, such as:
asterisk
backslash
bullet
bullet.cap
underscore

I am assuming because there are no kerning groups explicitly assigned for these. For example, the `bullet` kerning groups are empty while a glyph such as the `question` uses the glyph name as the kerning group name. 

Will this cause an issue with glyphs that I've kerned to these glyphs to not transfer over? 
Should these kinds of gylphs with empty kerning groups be assigned a name? 

<img width="416" alt="Screenshot 2021-01-15 at 10 07 14" src="https://user-images.githubusercontent.com/23149420/104756797-801b3e00-5719-11eb-964a-a439879cc034.png">

<img width="411" alt="Screenshot 2021-01-15 at 10 10 37" src="https://user-images.githubusercontent.com/23149420/104757175-f4ee7800-5719-11eb-968d-9d816753a230.png">

**Comment by madig** [comment]
My import script indeed does not import glyph to glyph kerning. That's going on my todo list. Ideally, you only ever kern groups against groups because that saves bytes.

**Comment by chrissimpkins** [comment]
@gorjious do you have any new opsz 18 bracket layer definitions that will be part of this merge?

**Comment by gorjious** [comment]
My file will contain a number of opsz 18 bracket layers for letters and punctuation. 

As I am putting together the testing doc, the font files from Glyphs with these bracket layers (which I previously had at 17.5 then shifted to 18 for the final files) are no longer building correctly. This may not be an issue with the fontmake process, however, I will make sure this is noted in the testing doc.

**Comment by chrissimpkins** [comment]
> My file will contain a number of opsz 18 bracket layers for letters and punctuation. 
> 
> 
> 
> As I am putting together the testing doc, the font files from Glyphs with these bracket layers (which I previously had at 17.5 then shifted to 18 for the final files) are no longer building correctly. This may not be an issue with the fontmake process, however, I will make sure this is noted in the testing doc.

What kind of behavior are you seeing in the bracket builds with fontmake?

**Comment by gorjious** [comment]
Using fontmake from the build-chrissimpkins-georgian-merge branch, so far I've noticed the following errors in the variable font builds (the statics seem to be working fine):


The semicolon.loclARM (calt) reverts to the Latin semicolon at max opsz.

![Screenshot 2021-01-16 at 13 23 40](https://user-images.githubusercontent.com/23149420/104822347-0b223400-57ff-11eb-9549-2a7c2842a3cc.png)
![Screenshot 2021-01-16 at 13 23 56](https://user-images.githubusercontent.com/23149420/104822350-0eb5bb00-57ff-11eb-8b8e-765a32ef60e4.png)

The combining marks (ccmp) are not combining with the uppercase bracket 18 alternate of Է (Eh-arm) at max-opsz.

![Screenshot 2021-01-16 at 13 24 29](https://user-images.githubusercontent.com/23149420/104822639-4c1b4800-5801-11eb-8c18-a4f43fd70fbe.png)
![Screenshot 2021-01-16 at 13 24 37](https://user-images.githubusercontent.com/23149420/104822642-4de50b80-5801-11eb-8188-b22cc85ac608.png)


In smallcaps (smcp) the lowercase letters convert to smallcaps but do not use the bracket 18 variants.

![Screenshot 2021-01-16 at 14 06 13](https://user-images.githubusercontent.com/23149420/104823015-39564280-5804-11eb-9bf3-d62ec454288c.png)
![Screenshot 2021-01-16 at 14 06 18](https://user-images.githubusercontent.com/23149420/104823017-3b200600-5804-11eb-9064-417a9377c59e.png)
![Screenshot 2021-01-16 at 14 06 25](https://user-images.githubusercontent.com/23149420/104823018-3bb89c80-5804-11eb-978d-4140c42c7d95.png)


In smallcaps (c2sc) the uppercase converts to smallcaps at the min-opsz but at the max-opsz, the letters revert to the bracket 18 variants in the uppercase.

![Screenshot 2021-01-16 at 14 10 18](https://user-images.githubusercontent.com/23149420/104823068-a23dba80-5804-11eb-8d99-b8c99c513358.png)
![Screenshot 2021-01-16 at 14 10 22](https://user-images.githubusercontent.com/23149420/104823071-a4077e00-5804-11eb-94dd-2930b443dcad.png)
![Screenshot 2021-01-16 at 14 10 29](https://user-images.githubusercontent.com/23149420/104823073-a4a01480-5804-11eb-84b9-84b72d436008.png)

**Comment by gorjious** [comment]
I tried the same tests by building with fontmake from the ufos/designspace in the master branch, and the same issues with the bracket 18 layers in the smallcaps are present. 

One difference I notice from using the fontmake process in the build-chrissimpkins-georgia-merge branch from the master branch is that the static files are no longer building the bracket 18 layers correctly.

![Screenshot 2021-01-16 at 14 33 09](https://user-images.githubusercontent.com/23149420/104823611-a4097d00-5808-11eb-87b1-9d4c46a5b672.png)
![Screenshot 2021-01-16 at 14 33 13](https://user-images.githubusercontent.com/23149420/104823612-a66bd700-5808-11eb-83b1-7b441f256922.png)
![Screenshot 2021-01-16 at 14 33 30](https://user-images.githubusercontent.com/23149420/104823613-a7046d80-5808-11eb-8524-3aa63a2e30ef.png)
![Screenshot 2021-01-16 at 14 34 31](https://user-images.githubusercontent.com/23149420/104823614-a7046d80-5808-11eb-8133-a80e3a13306e.png)
![Screenshot 2021-01-16 at 14 34 38](https://user-images.githubusercontent.com/23149420/104823615-a79d0400-5808-11eb-90c0-b4927e1166f8.png)
![Screenshot 2021-01-16 at 14 34 53](https://user-images.githubusercontent.com/23149420/104823616-a79d0400-5808-11eb-930c-cb7ec5667b78.png)

Also, the issue ( https://github.com/googlefonts/googlesans/issues/52 ) with the incorrect positioning of the semicolon (comma part is higher at max-opsz) still seems to be present.

![Screenshot 2021-01-16 at 14 51 03](https://user-images.githubusercontent.com/23149420/104823896-cef4d080-580a-11eb-8169-2ff884ddedf5.png)
![Screenshot 2021-01-16 at 14 51 12](https://user-images.githubusercontent.com/23149420/104823900-d0be9400-580a-11eb-94fd-0b00cbb05da2.png)

**Comment by chrissimpkins** [comment]
Please push sources by Monday so that we can have a look.  Ty!

**Comment by gorjious** [comment]
Included in the attachment:

- latest glyphs sources
- list of glyphs for Armenian merge (including Latin "comma")
- kern groups (Manually added the individual glyphs that didn't have assigned kern groups i.e. public.kern1.bullet public.kern2.bullet etc.)
- html testing page with fontmake static and variable font builds (issues are noted on the page)

Regarding the Armenian kern group names, currently, the "arm_" prefix is being used, however, these can be converted to the "armn_" prefix on import, correct?

[GS_Armenian_2021-01-17.zip](https://github.com/googlefonts/googlesans/files/5827937/GS_Armenian_2021-01-17.zip)

**Comment by madig** [comment]
This breaks because there is no kerning group `public.kern1.equal` :o You can only import what exists, so either `equal` gets put into a group or I change the import script to consider single glyphs as well. I guess I'll do the latter...

**Comment by madig** [comment]
Maybe I made a brain oops. So, the script will import all kerning pairs that mention any imported glyph. So, any kerning pair like `(asterisk, something-arm)` will be imported. If you want to change kerning for a glyph that already exists, you can include the name in the glyph list.

**Comment by chrissimpkins** [comment]
@gorjious The Armenian merge is in progress in #129.  Will be in touch with questions/issues.

**Comment by chrissimpkins** [comment]
>  however, these can be converted to the "armn_" prefix on import, correct?

Yes that is my understanding from the conversation that we had with Nikolaus last week.

**Comment by madig** [comment]
Yes.

Currently trying to make sense of the blob that is features.fea. I wish I had a feature file formatter...

**Comment by moyogo** [comment]
> Currently trying to make sense of the blob that is features.fea. I wish I had a feature file formatter...

You can load the feature code with fontTools.feaLib.Parser and parser.parse().asFea() will format it.

**Comment by madig** [comment]
Thanks. The output is somewhat rough, but a good basis to implement a prettifier on.

Merging the features makes me realize how poor fea tooling is.

I found http://adobe-type-tools.github.io/afdko/OpenTypeFeatureFileSpecification.html#2gii-named-glyph-classes -- it says that you can nest class definitions and they'll be flattened for you. So one could write

```
@cap_on = [ #ARMENIAN
dram-arm.cap

franc.cap ringcomb.cap gravecomb.cap acutecomb.cap dieresiscomb.cap ];
```

as

```
@armn_cap_on = [ dram-arm.cap ];

@cap_on = [ @armn_cap_on franc.cap ringcomb.cap gravecomb.cap acutecomb.cap dieresiscomb.cap ];
```

That way, all script-specific definitions can be neatly tucked away somewhere and just referenced where needed.

**Comment by madig** [comment]
@gorjious in `smcp`, there's a lone `sub comma-arm by comma-arm.sc` that is already covered in `lookup armn_smcp_substitution`. Intentional?

There are other discrepancies, e.g. the upright features include "men_xeh-arm.liga.sc" and some others in `@AllLetters` but the italic features do not. Italics have `Men_Now-arm.liga` in `@Uppercase`, uprights do not.

**Comment by madig** [comment]
Also also, the glyphs in `@Uppercase` should probably include `@armn_uppercase` but are missing the ligatures?

**Comment by gorjious** [comment]
The duplicate `sub comma-arm by comma-arm.sc` is not intentional. It must have been automatically generated at some point.

The `@AllLetters`  and `@Uppercase` are classes that Glyphs adds automatically. My features don't make use of them and I don't believe they are used in any of the features. In any case, the discrepancies can be resolved by checking `Generate feature automatically` in Glyphs and clicking the update icon ⟳ next to the class name.
