### ISSUE TITLE
Remove unnecessary unexported glyphs

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans#122]
![102468050-ef354200-4048-11eb-8d08-68eb184907f8](https://user-images.githubusercontent.com/4249591/104728934-a8993d00-5705-11eb-9e8e-11154b124cfa.png)

---

### TODO

- [x] remove G.ss06
- [x] remove peace icon
- [x] remove whiteFrowningFace
- [x] remove whiteSmilingFace
- [x] remove apple

**Comment by chrissimpkins** [comment]
@alexeiva we need your input to address this issue.  Will you please confirm that we do not need the unexported *-cy glyphs in the image in [the OP](https://github.com/googlefonts/googlesans/issues/122#issue-786871202)?

**Comment by dberlow** [comment]
Chris, per our discussion yesterday about the "spurless" or "beardless" G to be rvrn gssub-ed at opsz 18:
1. G.ss06, is only the glyph I found, and only in the regular, i.e. not italic, that fits the design, so that should not be removed as I'll be adding it to the list of checked glyphs and it'll be the subject of the gsub at 18pt.

2. And about descender.cy glyphs, we are replacing all these with versions for U.C. l.c. and small caps. 

3. see next issue on l.c. ldot.

**Comment by chrissimpkins** [comment]
@dberlow:

(1) I don't believe that is the proper outline for the max opsz (opsz = 18) U+0047 G LATIN CAPITAL LETTER G.  And there are other bracket layer definitions @ opsz 18.  I need to track down where all of these outlines wound up after the UFO transition and will open a new issue with this information, ping you on it.  We **do** have all designs that were previously defined in glyphs source "bracket layers" preserved in the UFO masters following the UFO source transition that occurred this morning.  

(2) Got it.  Should we leave these unexported glyphs in the upstream sources?  I don't believe that this is a blocker to remove unexported glyphs in our upstream sources before your work is merged correct?

**Comment by chrissimpkins** [comment]
> @dberlow:
> 
> (1) I don't believe that is the proper outline for the max opsz (opsz = 18) U+0047 G LATIN CAPITAL LETTER G. And there are other bracket layer definitions @ opsz 18. I need to track down where all of these outlines wound up after the UFO transition and will open a new issue with this information, ping you on it. We **do** have all designs that were previously defined in glyphs source "bracket layers" preserved in the UFO masters following the UFO source transition that occurred this morning.
> 
> (2) Got it. Should we leave these unexported glyphs in the upstream sources? I don't believe that this is a blocker to remove unexported glyphs in our upstream sources before your work is merged correct?

@dberlow re: (1) #128

**Comment by alexeiva** [comment]
On Fri, Jan 15, 2021 at 3:48 PM Chris Simpkins <notifications@github.com>
wrote:

> [image: 102468050-ef354200-4048-11eb-8d08-68eb184907f8]
> <https://user-images.githubusercontent.com/4249591/104728934-a8993d00-5705-11eb-9e8e-11154b124cfa.png>
> ------------------------------
> TODO
>
>    - remove G.ss06
>    - remove peace icon
>    - remove whiteFrowningFace
>    - remove whiteSmilingFace
>    - remove apple
>    - confirm Alexei OK with removal of _descender.cy glyphs
>
> Need to make sure that no glyphs are using this component first.
via "Context menu — Show glyphs that use this component."

**Comment by alexeiva** [comment]
> @alexeiva we need your input to address this issue. Will you please confirm that we do not need the unexported *-cy glyphs in the image in [the OP](https://github.com/googlefonts/googlesans/issues/122#issue-786871202)?

It's possible to remove `__descender-cy.case` and `__descender-cy` if you decompose 8 glyphs. 

`__descender-cy.case` is used in 
`Endescender-cy/Pedescender-cy/Chedescender-cy/Eldescender-cy/`

`__descender-cy/` is used in 
`endescender-cy/pedescender-cy/chedescender-cy/eldescender-cy`


![Screenshot 2021-01-19 at 22 37 56](https://user-images.githubusercontent.com/16634089/105084285-2dd67600-5aa7-11eb-8188-5d1708ef78a2.png)

**Comment by chrissimpkins** [comment]
Thanks Alexei! Nikolaus indicated that these outlines are not exported which is the reason that we are considering removal.  There is no problem keeping the components for use in composite glyphs as far as I know. @madig?

**Comment by madig** [comment]
I actually meant that not exporting those _components means that all glyphs that use them get decomposed, driving up the byte count :grimacing: So I just want to set them to export. The other glyphs we don't need can go.

**Comment by chrissimpkins** [comment]
> I actually meant that not exporting those _components means that all glyphs that use them get decomposed, driving up the byte count 😬 So I just want to set them to export. The other glyphs we don't need can go.

Ah!  OK, sorry to bother you with this Alexei.  I misunderstood this issue.  We will convert the _descender glyphs to export so that they can be used as components. 

@madig something that you want to add to https://github.com/googlefonts/googlesans/pull/124 or do this in a separate PR?

**Comment by chrissimpkins** [comment]
I removed the _descender-cy* glyphs from the TODO's in this thread and opened #133 for that issue.  The title doesn't apply to those glyphs.

**Comment by madig** [comment]
*I* must sorry because I should have stopped you but only realized right now!!! Let's make a separate PR.

**Comment by madig** [comment]
(Waiting until we have the other big tickets like #135 and #124 merged to keep down the diff noise)
