### ISSUE TITLE
rvrn substitutions at opsz 18

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans#128]
rvrn substitutions that occur at optical size 18 as of commit https://github.com/googlefonts/googlesans/commit/9277115d6fd870cf7ac3a66af2c26d6d1cd29da6 are documented in the following blocks of the designspace files (note that the lists extend below the visible box if you view this in the post itself, scroll for the full view):

### Roman

https://github.com/googlefonts/googlesans/blob/9277115d6fd870cf7ac3a66af2c26d6d1cd29da6/source/GoogleSans/GoogleSans.designspace#L12-L69

### Italic

https://github.com/googlefonts/googlesans/blob/9277115d6fd870cf7ac3a66af2c26d6d1cd29da6/source/GoogleSans/GoogleSans-Italic.designspace#L11-L67

It appears that the outlines for the bracket layer designs have the file path naming convention:

`[GLYPH NAME]_.B_R_A_C_K_E_T_.18.glyf` 

in the respective UFO master `glyphs` directory.

cc @dberlow

**Comment by madig** [comment]
Yes, glyphsLib writes bracket glyphs from their own layers into standalone glyphs because the DS rules format can only use those.

**Comment by dberlow** [comment]
Not sure what that’s all about, but the ufos only have these Gs, and the ss containing the appropriate-looking glyph is not included in the output file with G.Bracket.
<img width="616" alt="Screen Shot 2021-01-16 at 5 47 16 PM" src="https://user-images.githubusercontent.com/1956494/104908757-e8a22f00-5954-11eb-83fd-8260eb856292.png">

**Comment by chrissimpkins** [comment]
> Not sure what that’s all about, but the ufos only have these Gs, and the ss containing the appropriate-looking glyph is not included in the output file with G.Bracket.

I'm not sure that I follow your comments here @dberlow.  The sources for these "bracket layer" designs are available in our [UFO source files in the master branch of this repository](https://github.com/googlefonts/googlesans/tree/master/source/GoogleSans) on the paths that I posted above. Please let me know if you need additional  details to identify them.

**Comment by dberlow** [comment]
Hey Chris, 
Sorry, I could not get access to those sources right away. Those sources do included the G.BRACKET.18 glyph and I'll
add it to my sources.

It is identical to G.ss06, so I do not know why it's there.

**Comment by chrissimpkins** [comment]
Thanks David. Please see the lists of all of the other bracket layer definitions in https://github.com/googlefonts/googlesans/issues/128#issue-787472889

**Comment by chrissimpkins** [comment]
Additional rvrn opsz=18 subs will be coming in with the Armenian script merge work in #129
