### ISSUE TITLE
Features.fea: Greek groups redefined?

### ISSUE THREAD

**Issue by madig** [googlefonts/googlesans#130]
The Greek groups `@grk_UPPERCASE`, `@grk_lowercase` and `@grk_smallcaps` are defined twice, with the smaller definition winning out. What's the story here?

**Comment by irenevlachou** [comment]
Hi Nikolaus, thanks for noticing! you are right, there are double entries. One is the #automatic one from Glyphs and the other, the one I have manually added (the smaller definition). These classes are only used to define the kaisymbol substitutions, so I would suggest to get rid off the automatic ones that include all polytonic glyphs etc that are not going to occur in this feature. Also these automatic classes are a bit weird; In the @grk_smallcaps are multiple entries of some glyphs and it makes me think if these classes are made for an automatic smcp feature?
<img width="863" alt="GSfea" src="https://user-images.githubusercontent.com/11784297/105022036-ee316f00-5a51-11eb-9c43-7958efffe3ab.png">

**Comment by madig** [comment]
Thanks! I love to remove stuff anyway. PR coming soon.

**Comment by madig** [comment]
(Waiting until we have the other big tickets like #135 and #124 merged to keep down the diff noise)
