### ISSUE TITLE
Export _descender-cy and _descender-cy.case outlines

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans#133]
These outlines are not currently exported.  They are necessary for the Cyrillic designs and are decomposed, unnecessarily replicating component outline data.  @madig recommends that we export these glyphs to achieve a file size savings as composite designs.

Alexei identified the glyphs involved in https://github.com/googlefonts/googlesans/issues/122#issuecomment-763082943

**Comment by madig** [comment]
(Waiting until we have the other big tickets like https://github.com/googlefonts/googlesans/issues/135 and https://github.com/googlefonts/googlesans/pull/124 merged to keep down the diff noise)
