### ISSUE TITLE
Approach to optical size 18 glyph substitutions currently defined with OT rvrn feature (Glyphs "bracket layers")

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans#135]
Nikolaus proposed a transition from the `rvrn` to `rclt` feature to extend optical size dependent glyph substitution support to glyphs that require other feature substitutions.  This issue arose during the merge of the Armenian work in #129 and the discussion began at https://github.com/googlefonts/googlesans/pull/129#discussion_r561889791.

_Let's define the behavior here as **optical size dependent substitution = OSDS** since the "Glyphs bracket layer", "rvrn", "rclt" terminology is application/source format and implementation dependent, and confuses the issue_.

## Issue

From @madig (https://github.com/googlefonts/googlesans/pull/129#discussion_r562023481):

> All bracket glyphs for glyphs swapped in by other features. The problem has been expounded in fonttools/fonttools#1371.
>
>The default behavior in VFs is to use the rvrn feature, which is applied first thing. This is unfortunately incompatible with having bracket glyphs for glpyhs that are swapped in by other features. Take "g", "g.sc" and "g.sc.BRACKET.18" as an example:
>
>In opsz == 17, i.e. for Text, turning the smcp option on results in "g" being replaced by "g.sc". That's as intended.
In opsz == 18, i.e. for Display, you want the end result to be "g.sc.BRACKET.18". However: rvrn runs first ("g.sc" -> "g.sc.BRACKET.18") and finds no "g.sc" to replace (smcp runs later!). It does nothing. Then, the smcp feature runs and replaces "g" by "g.sc". That's your end result rather than "g.sc.BRACKET.18" simply because rvrn ran too early.
As the linked issue explains, there's no easy way out. rclt is not supported by Adobe apps and to make it mostly work with rvrn, you have to, I think, add bracket glyphs for all parent glyphs of bracketed glyphs (i.e. here "g.BRACKET.18") and have rvrn switch that out and add an entry in scmp to replace g.BRACKET.18 with g.sc.BRACKET.18. Put another way, you have to double all your subs for bracket glyphs (e.g. fonttools/fonttools#1371 (comment)).

From https://github.com/googlefonts/googlesans/pull/129#discussion_r561926372:

> AFAIK, rclt is the only sensible way of getting bracket glyphs to work if you want to stack features (it applies substitutions last, rvrn is applied before other features are applied).

We are attempting to fix current production OSDS that do not function appropriately (e.g. small caps swapping noted above by Nikolaus), and anticipate support for new OSDS that will be merged in i18n script merges, including the Armenian merge that is taking place in #129 now.

## Proposed implementation

Designspace configuration change performed in Roman and Italic designspace files in https://github.com/googlefonts/googlesans/pull/129/commits/10dc9d576597fc596fcb57654b11ef9a2d60a4e3

[Designspace attributes specification for rvrn and rclt](https://fonttools.readthedocs.io/en/latest/designspaceLib/readme.html#id22).

## Problem

`rclt` is a global change so **all** current production OSDS will be impacted.  (https://github.com/googlefonts/googlesans/pull/129#discussion_r561975741)

**This will break OSDS support in at least some Adobe applications, including InDesign**. (https://github.com/googlefonts/googlesans/pull/129#discussion_r561926372), reported to Adobe (https://github.com/fonttools/fonttools/issues/2079#issuecomment-705114456)

### Production glyphs with incorrect substitution behavior = bug

- g.sc
- TBD

### Production glyphs that will have change in behavior with or without incorrect substitutions now

Production OSDS are defined in:

https://github.com/googlefonts/googlesans/blob/d459cf79173b02f7a4c39fc0435650dc0237d95e/source/GoogleSans/GoogleSans.designspace#L14-L68

and 

https://github.com/googlefonts/googlesans/blob/d459cf79173b02f7a4c39fc0435650dc0237d95e/source/GoogleSans/GoogleSans-Italic.designspace#L14-L66

### Impact on Google Sans grade axis expansion

TBD

## Alternative approaches

- potential solution to do some busy work duplicating substitutions: fonttools/fonttools#1371 (comment)
- TBD

**Comment by madig** [comment]
There's an Apple CoreText bug that makes rvrn behave like rclt: https://github.com/fonttools/fonttools/issues/2140#issue-777505662. So the solution may be to make everyone use Apple???

**Comment by madig** [comment]
Also remember the other potential solution to do some busy work duplicating substitutions: https://github.com/fonttools/fonttools/issues/1371#issuecomment-437613378

**Comment by chrissimpkins** [comment]
@sannorozco Santiago, will you please let us know when you have an opportunity to test the optical size swapping / rvrn issue with the grade axis work?  I'd like to confirm that this feature will continue to support these substitutions with the change in the design space in David's work.  It will help to inform the solution to the problem here.  Thanks!

**Comment by chrissimpkins** [comment]
cc @gorjious FYI, we are discussing how to address this issue that was recognized during the merge attempt on your source files.

**Comment by chrissimpkins** [comment]
@madig 

This behavior is an important one for us.  There are some critical OSDS supported design features that distinguish the "Google Sans" (i.e. max optical size design) from the "Google Sans Text" (i.e. min optical size design) family.  The most notable from a branding standpoint is the upper case `G` (U+0047).  The max opsz design has the round Google logo / wordmark form and the min opsz design has a more condensed form with a "spur".  OSDS support is required because there are not appropriate interpolated intermediates for the spur in the min opsz master. 

![cap_G](https://user-images.githubusercontent.com/4249591/105394814-09d07d00-5bec-11eb-83a4-c9ad1ad5d807.gif)

There are also functional design changes in GS Text that are supported via OSDS.  These were requested by internal design oversight team members and are not intended for the max opsz designs that are viewed at headline size and larger.  This includes things like the addition of a curved tail on the lower case `y` (U+0079) in the min opsz masters:

![lower_y](https://user-images.githubusercontent.com/4249591/105395614-ed811000-5bec-11eb-8adf-3963e45230f5.gif)

The team did not feel that there were appropriate intermediate interpolated forms for changes like this.

In the last several months we made a transition from min opsz masters @ 14 to min opsz masters @ 17 (with max always defined @ 18) to, for practical purposes, "eliminate" interpolation on the opsz axis.  For now, this is desirable and based on a decision from the creative directors of the project. We do not want interpolation (at all) on the opsz axis.  Internal guidance will steer away from opsz definitions / text set inside the 17 - 18 interval.  It is possible that some team might attempt to animate across this range or expose it to end users in e.g., a text size free text entry field where someone *could* select, say, 17.5 and see opsz interpolation.  Importantly, it is also possible that the opsz approach will change and interpolation will be re-introduced on the optical size axis with expansion of the opsz range.   I say all of this only to make you aware that the solution that we choose here will need to be a durable one, or at least a flexible one, if the project requirements change.

The understanding of environments/applications at issue is a bit muddy at this stage, but it sounds like we can currently state that *at least* Adobe InDesign on all platforms will no longer display OSDS supported max opsz glyphs when the opsz definition transitions from 17 and under to 18 and above.  If I understand the problem correctly, then we are introducing a significant problem to address the lack of OSDS support in some GS/GST glyphs.  We need to review the ones that do not work properly so that we understand how significant the issue is, but IMO, there will be nothing that trumps the upper case `G` issue.  When the wrong `G` shape hits a billboard or newspaper out there somewhere we will hear about it. I'm not sure that the "but we fixed the small caps" explanation will be very well received... :)  

Many / most internal product teams are transitioning from InDesign/Sketch to Figma (side bar: Figma does not support VF's and this is part of the reason that static instances remain important in this project).  I have no knowledge of the breadth of that transition, but I think that it is safe to say that we **do need to support Adobe InDesign**.  I have no idea what ads/marketing teams use.  I do know that the Brand/Marketing teams have provided InDesign sources to us in the past for GS mocks.  Furthermore, some design work may be outsourced to external vendor teams who use tools that do not fall under any internal guidance at Google. And many of our Google Sans type design vendors use Adobe InDesign to test their fonts locally and produce mockups for deliverable presentations. 

cc @Colophon-Foundry @dberlow

**Comment by davelab6** [comment]
I agree with what Chris wrote. 

To double all the subs seems okay to me, to get correct behaviour at a file size cost, that we can file bugs against implemntations for, hassle eng we know to prioritize fixing, and then come back to the fonts in 2 years or whatever, and reduce the filesize because by then implementations are working correctly.

**Comment by chrissimpkins** [comment]
> To double all the subs seems okay to me, to get correct behaviour at a file size cost, that we can file bugs against implemntations for, hassle eng we know to prioritize fixing, and then come back to the fonts in 2 years or whatever, and reduce the filesize because by then implementations are working correctly.

Does anyone have experience with a sharply bent avar definition (e.g. 17 master outlines with min or no interpolation until you hit 17.999 and then there is a sharp interpolation step from 17.999 to 18 master definition) or an extremely short interpolation range (e.g., possible to move the 17 masters to 17.999 without use of avar) to address an issue like this?  Is this possible?   We would have linear interpolation between 17.999 - 18 but it is effectively gone from view.

This would allow us to eliminate all of the *.18 outlines and OSDS substitution data in the fonts so we might be able to both address this problem ~everywhere *and* reduce file size at the same time.

**Comment by chrissimpkins** [comment]
> an extremely short interpolation range (e.g., possible to move the 17 masters to 17.999 without use of avar)

David Berlow is going to give this approach a shot.

**Comment by dberlow** [comment]
There is a commit on this for the G and can be repeated for other glyphs like y.

That depends in agreement that the change from the 17pt master to the 18pt, happens at 17.999999, and that also works.

As the Regular stands now:

1. "bearded" G is changed by rule to G.ss06 at 18.

2. 17 and 18 pt G glyphs are bearded, and G.ss06 are not.

3. Glyphs are complete for all masters of opsz, wght and GRAD.

4. there is now also a G.ss007 varying between the 17 and 18 opsz, regular
wght only and no grades yet.

4a. This is capable of interpolating between the two G forms, so if  a "sharp" opsz change is possible at 17.999999,

4b. this glyph would be the default G (and only G), in opsz 17 and 18, and all the other masters as well.

This makes several options available.

**Comment by madig** [comment]
https://docs.microsoft.com/en-us/typography/opentype/spec/features_pt#tag-rvrn

> When a variable font is used, all of the interpolated variants of a given glyph ID have exactly the same contours and points. It is possible to use glyph variation mechanisms to make significant outline changes, such as reducing strokes in heavy-weight or narrow-width variants, but this approach may be difficult to implement and may not produce desired results for all variation instances. [...] The axis values used to trigger a condition should normally be midway between values used for named instances. This will avoid any possibility of inconsistent behavior in different applications when using named instances that might arise due to small discrepancies in processing the numeric values.

I think we're entering uncharted territory. 😱

**Comment by chrissimpkins** [comment]
> There is a commit on this for the G and can be repeated for other glyphs like y. That depends in agreement that the change from the 17pt master to the 18pt, happens at 17.999999, and that also works. As the Regular stands now: 1. "bearded" G is changed by rule to G.ss06 at 18. 2. 17 and 18 pt G glyphs are bearded, and G.ss06 are not. 3. Glyphs are complete for all masters of opsz, wght and GRAD. 4. there is now also a G.ss007 varying between the 17 and 18 opsz, regular wght only and no grades yet. a. This is capable of interpolating between the two G forms, so if a "sharp" opsz change is possible at 17.999999, b. this glyph would be the default G (and only G), in opsz 17 and 18, and all the other masters as well. This makes several options available.


@dberlow Can you point me to the commit(s) that you are referring to here?  I'd like to have a look at how you are approaching this in the source files.

**Comment by dberlow** [comment]
Source for default here.

www.GitHub.com/googlefonts/GoogleSans-fb/tree/master/sources/GS%20Cubic%20Sources/Regular/Google%20Sans-opsz18-wght400-GRAD0.ufo

**Comment by chrissimpkins** [comment]
> Source for default here.
> GitHub.com/googlefonts/GoogleSans-fb/tree/master/sources/GS%20Cubic%20Sources/Regular/Google%20Sans-opsz18-wght400-GRAD0.ufo

Thanks David!

For my reference, the diff is here: https://github.com/googlefonts/GoogleSans-fb/commit/8cd3c0709835f5456d6fc3ac31d6578f2159fecd

**Comment by chrissimpkins** [comment]
Taking a look at this issue in a subset with `G`, `g`, and `g.sc` only.  I overlooked the fact that the [GLYPH] and [GLYPH].BRACKET.18 are not designed as interpolatable outlines in some of these cases.  Moving the min masters to 17.999 or use of avar and eliminating rvrn substitution obviously requires that to be the case.  Investigating David's approach.

**Comment by madig** [comment]
There's a section in the FontLab 7 manual about this: https://help.fontlab.com/fontlab/7/manual/Release-Notes-7264-3/#notes-about-conditional-glyph-substitution

**Comment by madig** [comment]
Uh! The upright Designspace has the sub `<sub name="g.sc.ss04" with="g.sc.ss04.BRACKET.18"/>` -- shouldn't the sub be `g.sc.lc.ss04.BRACKET.18`? Mind the `.lc`. Otherwise "Ggrumpy" gets you:

![image](https://user-images.githubusercontent.com/380829/106494099-e8a44200-64b1-11eb-943a-3ed717f73ff3.png)

Also, something is wrong with the `y`. Must be a `rvrn` casuality.

**Comment by madig** [comment]
The affected substitutions are all those where the input glyph has no Unicode value, as in, is a result of another substitution:

- Gcommaaccent.alt
- Kcommaaccent.alt
- Rcommaaccent.alt
- g.sc
- g.sc.ss04
- kcommaaccent.alt
- rcommaaccent.alt
- tcommaaccent.alt
- y.sc.lc.ss04
- apostrophe-arm.case
- apostrophe-arm.sc
- ca-arm.sc
- eh-arm.sc
- gim-arm.sc
- jheh-arm.sc
- semicolon.loclARM
- za-arm.sc

**Comment by chrissimpkins** [comment]
> There's a section in the FontLab 7 manual about this: https://help.fontlab.com/fontlab/7/manual/Release-Notes-7264-3/#notes-about-conditional-glyph-substitution

It looks like approach 1 recommended in this document is the approach that we are taking?

**Comment by chrissimpkins** [comment]
> Uh! The upright Designspace has the sub `<sub name="g.sc.ss04" with="g.sc.ss04.BRACKET.18"/>` -- shouldn't the sub be `g.sc.lc.ss04.BRACKET.18`? Mind the `.lc`. Otherwise "Ggrumpy" gets you:
> 
> ![image](https://user-images.githubusercontent.com/380829/106494099-e8a44200-64b1-11eb-943a-3ed717f73ff3.png)
> 
> Also, something is wrong with the `y`. Must be a `rvrn` casuality.

Helpful if I go through and work out all required substitutions across the list that you posted in https://github.com/googlefonts/googlesans/issues/135#issuecomment-771028927 or have you sorted this out already?

**Comment by chrissimpkins** [comment]
I needed to use a pen/paper to work through the new glyph definitions and substitutions required for the g.sc.  :)

I'll start a spreadsheet where we can work through new glyph definitions required, sub 1, and sub 2, ... for the list in https://github.com/googlefonts/googlesans/issues/135#issuecomment-771028927

**Comment by chrissimpkins** [comment]
> semicolon.loclARM

Does the `rvrn` substitution happen before `locl` too?  Yikes.

https://github.com/n8willis/opentype-shaping-documents/blob/master/opentype-shaping-default.md#the-default-shaping-model doesn't mention `rvrn`.

> Note: Strictly speaking, the use of localized-form substitutions is not part of the shaping process, but of the localization process, and could take place at an earlier point while handling the text run. However, shaping engines are expected to complete the application of the locl feature before applying the subsequent GSUB substitutions in the following steps.

**Comment by chrissimpkins** [comment]
> I'll start a spreadsheet where we can work through new glyph definitions required, sub 1, and sub 2, ... for the list in [#135 (comment)](https://github.com/googlefonts/googlesans/issues/135#issuecomment-771028927)

I made a sheet to compare, send to you all

**Comment by chrissimpkins** [comment]
> The upright Designspace has the sub <sub name="g.sc.ss04" with="g.sc.ss04.BRACKET.18"/> -- shouldn't the sub be g.sc.lc.ss04.BRACKET.18

I took a look at the source files.  The ss04 set are "micro caps" that were the original smcp.  As I understand it they were only used for the cap letter forms to indicate file size unit abbreviations like `MB` and `GB`.  I'm not aware of any use cases for lower case versions of the small cap forms.  As of the GS / GST v3.000 release, we developed a new traditionally sized smcp set and the micro caps were moved to ss04 in case they were still in use out there somewhere.

@Colophon-Foundry Edd, do you have any additional background on the lower case "micro cap" forms?  We're running into problems with the bracket layer/rvrn substitution and need to decide how to approach these.  IMO the ss04 lower case set may be a won't fix situation.  I wonder if we can even consider removing the lc forms?   Was `kB` support the rationale for adding a full set of lower case micro caps?

**Comment by Colophon-Foundry** [comment]
I believe so yes. It was so you could write 10Kbs (in micro caps). This was used a long time ago within Pixel (?) I think, but was rightly moved to a stylistic set with the addition of a more rationalised SMCP set.

**Comment by chrissimpkins** [comment]
> I believe so yes. It was so you could write 10Kbs (in micro caps). This was used a long time ago within Pixel (?) I think, but was rightly moved to a stylistic set with the addition of a more rationalised SMCP set.

Thanks Edd!

@madig Let me ask around and see if we are ok to remove these glyphs.  I don't know if they are still in use.

**Comment by chrissimpkins** [comment]
@Colophon-Foundry Edd, if we do need to keep them, is there a design solution that does not involve the bracket layer? The bracket layers are causing problems in chained substitution situations.  This affects all exported non-Unicoded glyphs with bracket layers.

**Comment by chrissimpkins** [comment]
> @Colophon-Foundry Edd, if we do need to keep them, is there a design solution that does not involve the bracket layer? The bracket layers are causing problems in chained substitution situations.  This affects all exported non-Unicoded glyphs with bracket layers.  

This comment applies to the sc.lc.ss04 glyphs only.

**Comment by madig** [comment]
I think we can keep them if someone really wants them but the problem is that there is no `g.sc.lc.ss04` to `rvrn` into? Maybe because the lowercase `g` does not actually have a conditional replacement, only the `G`?

**Comment by chrissimpkins** [comment]
@madig 

Nyshadh is going to attempt a test to understand if anyone is using the `ss04` glyphs.  Let's fix everything that is not `ss04` related and leave those broken for now.  Some (maybe we only keep what is necessary for file size unit abbreviations) or all of the `ss04` set may be removed.

cc @nyshadhr9

**Comment by chrissimpkins** [comment]
> Nyshadh is going to attempt a test to understand if anyone is using the `ss04` glyphs. Let's fix everything that is not `ss04` related and leave those broken for now. Some (maybe we only keep what is necessary for file size unit abbreviations) or all of the `ss04` set may be removed.
> 

Confirmed on an investigation that is as comprehensive as we can do that there is no ss04 use.  We'll remove all but the set of  ss04 glyphs used to support the original file size unit abbreviation intent.  

Most of the other rvrn substitutions in the Latin set should be transitioning to a new approach to address problems identified here.

**Comment by chrissimpkins** [comment]
Superseded by #214
