### ISSUE TITLE
Write fontbakery source test to complain if component transformations across sources differ aside from offset

### ISSUE THREAD

**Issue by madig** [googlefonts/googlesans#136]
It's causing havok over at https://github.com/googlefonts/googlesans/pull/124#issuecomment-763680928.

**Comment by chrissimpkins** [comment]
Likely something worth having in upstream fontbakery.  Let's consider this once there is an implementation here.

**Comment by MariannaPaszkowska** [comment]
Is this checked by the FB check based on the varLib/interpolatable tool? @RickyDaMa

**Comment by RickyDaMa** [comment]
![image](https://github.com/googlefonts/googlesans/assets/113340856/bfd7efb4-8b1b-42d6-873a-32e78a621a44)

Sounds like we shouldn't need this at all now, as thanks to using a more recent compiler this should no longer be an issue

**Comment by belluzj** [comment]
Based on Cosimo's comments in the screenshot, we can close this issue.
