### ISSUE TITLE
Add Hebrew script text runs for shaping regression testing

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans#145]
We need to add a set of definition files with Hebrew script text runs that cover shaping issues to be tested in our new shaping regression test suite (#140)

**Comment by chrissimpkins** [comment]
I reached out to @danielgrumer about this last night.

**Comment by madig** [comment]
I think we need some texts that excercise as much of the Hebrew part of the `ccmp` feature as possible before we know the upgrade in the Armn PR doesn't break anything Hebrew?

**Comment by chrissimpkins** [comment]
> I think we need some texts that excercise as much of the Hebrew part of the `ccmp` feature as possible before we know the upgrade in the Armn PR doesn't break anything Hebrew?

Daniel is working on it. More to come next week.

**Comment by chrissimpkins** [comment]
> I think we need some texts that excercise as much of the Hebrew part of the `ccmp` feature as possible before we know the upgrade in the Armn PR doesn't break anything Hebrew?

I will be speaking with Daniel tomorrow and will try to have tests available early this week.  I took a look at the Hebrew ccmp features over the weekend and I *think* that this will be straightforward.  Let's chat about how broad you feel that we need to cast the net across glyph combinations to test against what is coming in with the Armenian.

**Comment by danielgrumer** [comment]
> I think we need some texts that excercise as much of the Hebrew part of the `ccmp` feature as possible

@madig I'm not sure we need to test so many.
A lot of the contextual kerning form the `kern` feature depends on it. so if the `ccmp` substitutions fails - we’ll see _visual_ results when testing the `kern` feature.

In `ccmp`, only `vavholam-hb` and the `finalCantillationForms` lookup are crucial.

**Comment by chrissimpkins** [comment]
> we’ll see visual results when testing the kern feature.

We don't have visual/rendered form regression automation.  This requires a human.  And it is difficult to put eyes on the fonts (and in some cases, know where to look) every time we create a binary diff with source changes.

To the degree that we can, it would be ideal to visually confirm sub and pos issues as the designs are merged into the production sources, confirm that they are approved by the designer, then fix the shaping values as expected definitions based on that review.  If the shaping output changes as we make source changes (e.g., cleanup our features.fea files https://github.com/googlefonts/googlesans/pull/158, merge a new script https://github.com/googlefonts/googlesans/pull/129, fix a bug https://github.com/googlefonts/googlesans/pull/124, update build dependencies, etc), then we have a signal that it is time to lay eyes on the designs and a map that points to where the inspection is required.  Complete reliance on these shaping regression results relies on a comprehensive set of tests.  We're still trying to decide how comprehensive to make the test set.  The above feedback from you is very helpful to understand this.

**Comment by chrissimpkins** [comment]
Added in #167, #179, #180

**Comment by chrissimpkins** [comment]
Tracking in #161
