### ISSUE TITLE
Build system parallelization

### ISSUE THREAD

**Issue by madig** [googlefonts/googlesans#146]
I'm spending significant amounts of billable time rebuilding fonts and `make` does so sequentially. Look into how to make it go parallel with `-j`.

**Comment by madig** [comment]
Most or all targets are phony, I think for parallelization to work you need to specify actual file targets.

**Comment by chrissimpkins** [comment]
Wouldn't get too hung up on this issue GS Makefile side right now.

This would be fantastic to see on the fontmake/pipeline side.  There was a thread a couple of years ago where we discussed it.  I don't recall where we hit the roadblock.  Will need to dig that thread up.

**Comment by madig** [comment]
It's possible inside the pipeline and I made some test scripts to test each approach at https://github.com/madig/test-generate-instances. I implemented it on on [Cascadia Code](https://github.com/microsoft/cascadia-code/blob/ad49ee6/build.py#L291-L428). Implementing e.g. parallel instance generation in our internal build system was... less straightforward and suddenly the Cascadia Code approach was only little better than doing it serially while consuming a fuckton of memory. Python concurrency is tricky business.

The easiest wins you get is with process-level parallelism, a.k.a. making `make` go parallel. Not writing intermediate steps to disk also helps. That's trivial for VFs, as you read in UFOs and write out TTFs, but for instances, you need to interpolate them from the sources first and _then_ you can compile them in parallel. So, you read, interpolate, write result to disk (or dump in a pickled form), then fire up ufo2ft.compileTTF on the result in parallel.

**Comment by madig** [comment]
In case anyone is wondering where the time is going when e.g. just compiling statics:

![image](https://user-images.githubusercontent.com/380829/107648787-9fec4600-6c74-11eb-83da-39f9ffcec44b.png)

I think there's performance to be had by using skia-pathops for overlap removal compared to booleanOperations.

**Comment by chrissimpkins** [comment]
I believe that this is now complete.  Please reopen if there is more work to do here
