### ISSUE TITLE
Text shaping tests

### ISSUE THREAD

**Issue by madig** [googlefonts/googlesans#149]
Grab bag of thoughts I have on text shaping regression testing.

1. The tests do not help with conditional/bracket glyph testing in statics because statics have their outlines swapped instead of the actual glyph. VFs will show a different glyph name, but statics won't. Visual inspection is necessary.
2. If the output of a run is expected to be identical for all or most fonts, it would be nice to be able to specify this instead of having to look at pages full of identical lines.
3. Maybe the test files should have some more hierarchy and/or parameterization, so one can e.g. test different text runs with different features and/or languages in the same file. Think a `locl_latn` test document where you have the same text block but apply a diffent combination of languages (or even saying that a list of languages should behave the same).

Future potential improvements:

1. A GUI or repurposing of FontGoggles so designers can arrange a "worksheet" of fonts, a bunch of text blocks with feature, script and language toggles and the expected outcome, graphical and hb-shape-like. These worksheets can then be handed in along with the design work.

**Comment by chrissimpkins** [comment]
Related #162 #163

**Comment by chrissimpkins** [comment]
> Maybe the test files should have some more hierarchy and/or parameterization, so one can e.g. test different text runs with different features and/or languages in the same file. Think a locl_latn test document where you have the same text block but apply a diffent combination of languages (or even saying that a list of languages should behave the same).

This is the approach that I took in the PR's that I opened today (tracking in #161) when the behavior is known to differ across langs.  This is an issue for LTR vs. RTL writing systems too.  They will need separate files because of the input requirements for HB if we plan to make these direction definitions explicit rather than relying on HB.

**Comment by MariannaPaszkowska** [comment]
Since we now use the Fontbakery checks, let's suggest those improvements upstream, if still applicable.
