### ISSUE TITLE
frac feature does not turn sequences into precomposed fractions

### ISSUE THREAD

**Issue by madig** [googlefonts/googlesans#150]
The precomposed glyphs are accessible by Unicode value, but `frac` will not produce them.

Text sequence: `1/2 1/3 2/3 1/4 3/4 1/8 3/8 5/8 7/8`

**Comment by chrissimpkins** [comment]
It looks like the encoded glyphs are just composites of the numr form - fraction bar - denominator form that is shaped by the frac feature code.  The shape will be the same if you access the fractional form with a Unicode code point or via the sequence with frac activated.  Do you consider this a bug?

**Comment by chrissimpkins** [comment]
@madig Closing this as a will not fix based on https://github.com/googlefonts/googlesans/issues/150#issuecomment-909370611.  Please reopen if you feel otherwise.

**Comment by madig** [comment]
Not a problem.
