### ISSUE TITLE
Catalan: no ldot?

### ISSUE THREAD

**Issue by madig** [googlefonts/googlesans#159]
There's a feature to turn `L' periodcentered' L` into Ldot, but there's nothing for the lowercase `l`. Is that intentional?

**Comment by chrissimpkins** [comment]
@moyogo Denis, do you happen to know if the lowercase form is required and, if so, is this something that is coming in your Latin expansion work?

**Comment by moyogo** [comment]
Short answer: Yes, I added ldot to the Latin expansion.

Long answer:
Technically /Ldot and /ldot shouldn’t be used directly, /L/periodcentered and /l/periodcentered should be used instead. 
But there is probably text data with those two characters.
Ldot is currently used with the locl Catalan feature `substitution L periodcentered  by Ldot`, because it has the appropriate dot position. I think the /ldot wasn't added because it may have not looked different. However I added a periodcentered variant that is narrower between letters by default, for Catalan and minority languages.

**Comment by chrissimpkins** [comment]
> Short answer: Yes, I added ldot to the Latin expansion.
> 
> Long answer:
> Technically /Ldot and /ldot shouldn’t be used directly, /L/periodcentered and /l/periodcentered should be used instead.
> But there is probably text data with those two characters.
> Ldot is currently used with the locl Catalan feature `substitution L periodcentered by Ldot`, because it has the appropriate dot position. I think the /ldot wasn't added because it may have not looked different. However I added a periodcentered variant that is narrower between letters by default, for Catalan and minority languages.

Thank you very much Denis!

**Comment by chrissimpkins** [comment]
This was added as part of David Berlow's work in GS v4.000

**Comment by chrissimpkins** [comment]
Shouldn't have closed.  It looks like we may need to look into feature support?

**Comment by moyogo** [comment]
The smcp feature is missing `sub ldot by ldot.sc`.

**Comment by chrissimpkins** [comment]
> I think the /ldot wasn't added because it may have not looked different. However I added a periodcentered variant that is narrower between letters by default, for Catalan and minority languages.

Where are we with the design relative to this comment Denis?

**Comment by chrissimpkins** [comment]
Confirming that we only need a [feature code update](https://github.com/googlefonts/googlesans/issues/159#issuecomment-795846041) to close this issue?

**Comment by madig** [comment]
@moyogo is https://github.com/googlefonts/googlesans/issues/159#issuecomment-795846041 the only thing we need to do?

**Comment by moyogo** [comment]
> > I think the /ldot wasn't added because it may have not looked different. However I added a periodcentered variant that is narrower between letters by default, for Catalan and minority languages.
> 
> Where are we with the design relative to this comment Denis?

@chrissimpkins 
I made the periodcentered.loclCat with a narrower advance width than periodcentered, and it kerns with L.

> @moyogo is [#159 (comment)](https://github.com/googlefonts/googlesans/issues/159#issuecomment-795846041) the only thing we need to do?

@madig This has been fixed in 1bc7cdef in #276:
https://github.com/googlefonts/googlesans/blob/0474d6ef19e5fb74e322c87994bdbb29a33a9e5b/source/GoogleSans/family.fea#L1064

**Comment by chrissimpkins** [comment]
Thanks @moyogo!  

> I made the periodcentered.loclCat with a narrower advance width than periodcentered, and it kerns with L.

Where can we find the source with these changes?
