### ISSUE TITLE
Add commit SHA to harfbuzz shaping regression test data files

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans#162]
I think that it would be useful to leave a crumb trail in in our harfbuzz shaping regression test definition files so that we know what binaries we are regression testing against.

Perhaps something like a new `meta` field in the JSON definition files with a `build_commit` definition field.

```json
{
  "meta": {
    "build_commit": "deadbeef",
  },
  "input": {
    "text": [
      "1/2 1/3 2/3 1/4 3/4 1/8 3/8 5/8 7/8",
      "1234567890/1234567890123",
      "11111111111/2222222222222",
      "0/0/0 00/000/00000 0//0",
      "2 1/2 222222222222 1/2"
    ],
    "features": {
      "frac": true
    },
    "comparison_mode": "glyphstream"
  },
}
```

**Comment by chrissimpkins** [comment]
Examples incoming in PR's that I will be submitting today to address #161

**Comment by madig** [comment]
Sounds good, although I suppose we have to keep track of which binary we're using manually. Or we write a commit id into the font.

**Comment by chrissimpkins** [comment]
The safest approach may be to push a `build-*` branch and download the files for JSON updates that are added to support new work.  For previously merged work that has been pushed to prod, I think that we should use [the latest release files](https://github.com/googlefonts/googlesans/releases).

**Comment by chrissimpkins** [comment]
> we write a commit id into the font.

That seems like it might work too!  Read that and use it in the JSON file.

**Comment by chrissimpkins** [comment]
D/W Niko and Jany.  We'll use this approach.  All JSON files updated.
