### ISSUE TITLE
smcp and c2sc broken for BSH, CHU and SRB

### ISSUE THREAD

**Issue by madig** [googlefonts/googlesans#176]
See https://github.com/googlefonts/googlesans/pull/164.

**Comment by chrissimpkins** [comment]
Looks like we need to add the script/lang to the languagesystem defs?  We only have `cyrl BGR` defined.

https://github.com/googlefonts/googlesans/blob/e9bbeaa653d9ff9a4752d3bf4cf45d63975343a4/source/GoogleSans/family_uprights.fea#L11

**Comment by chrissimpkins** [comment]
And Italics only has BGR and MKD.

https://github.com/googlefonts/googlesans/blob/e9bbeaa653d9ff9a4752d3bf4cf45d63975343a4/source/GoogleSans/family_italics.fea#L11-L12

**Comment by madig** [comment]
@moyogo Cosimo says you might know why feaLib doesn't complain about using `language` without a `languagesystem` decl 😮

**Comment by moyogo** [comment]
The Feature Syntax specification isn't clear about this. It seems to be valid to have a `script` or `language` statement that doesn't have a matching `language system` declaration present.

The `language system` statements are to define what applies by default.
The `script` or `language` statements are to specify what script and language system a feature and lookups belong to.

If a `script` and `language` statement doesn't have a matching `language system` then it never has the default features and only has the features where it is specifically called. A bit odd but there might be a corner case for it.

**Comment by moyogo** [comment]
For example

```
language system DFLT dflt;
language system latn CAT;
language system latn ROM;

feature feat {
# Because there is no script or language this applies to all language systems declared above
# DFLT dft, latn CAT, latn ROM but not anything else;
sub one by two;

# This only applies to latn ENG.
script latn;
language ENG;
sub one by three;
} feat;
```

**Comment by anthrotype** [comment]
what does makeotf do in this case?
