### ISSUE TITLE
calt feature substitutions for numeral, colon, numeral sequences (colon.time)

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans#177]
Our `calt` feature code includes the following substitution:

```fea
sub [zero.tf one.tf two.tf three.tf four.tf five.tf six.tf seven.tf eight.tf nine.tf] colon.tf' [zero.tf one.tf two.tf three.tf four.tf five.tf six.tf seven.tf eight.tf nine.tf] by colon.time;
```

The colon.tf has an adv width of 300 and the colon.time has an adv width of 238.  colon.time is a figure aligned colon design intended for hh:mm time displays.

Do we want a new colon glyph that has the same tabular width as the rest of the `*.tf` punctuation and the figure centered vertical alignment of the colon.time glyph?

cc @Colophon-Foundry @dberlow

**Comment by chrissimpkins** [comment]
Possibly addressed in David Berlow's #387.  I need to review

**Comment by MariannaPaszkowska** [comment]
note to self: check if we can have colon.time.tf or need to add it.

**Comment by MariannaPaszkowska** [comment]
It seems that we do not have the "colon.time.tf"

**Comment by davelab6** [comment]
What's the file-size impact?

**Comment by MariannaPaszkowska** [comment]
I expect a small impact. It will be a component, just with different sidebearings, and a small edit in the feature code.

**Comment by MariannaPaszkowska** [comment]
@belluzj, how much effort would be to add this precomposed character? It would be colon.time.tf, centred on a tab width.

**Comment by belluzj** [comment]
@MariannaPaszkowska Eduardo says it should be very fast, around 1 hour of work. Should we push this along with the GRAD fix from https://github.com/googlefonts/googlesans/issues/383#issuecomment-1904366003?

**Comment by MariannaPaszkowska** [comment]
@belluzj great! 
Will this include editing the calt feature code? "colon.time" should be replaced there by "colon.time.tf". 
If not I can do it.

**Comment by belluzj** [comment]
We'll update the feature and the shaping tests
