### ISSUE TITLE
Go through fontbakery outline test reports

### ISSUE THREAD

**Issue by madig** [googlefonts/googlesans#187]
I'm seeing e.g.

```
 >> com.google.fonts/check/outline_jaggy_segments
    Do outlines contain any jaggy segments?
    with build/GoogleSans/static/expert/GoogleSansText-Italic.ttf

      Rationale:                                                                
      This test heuristically detects outline segments which form a             
      particularly small angle, indicative of an outline error. This may cause  
      false positives in cases such as extreme ink traps, so should be regarded 
      as advisory and backed up by manual inspection.                           

    * WARN: The following glyphs have jaggy segments:
        * eternityarmlf: B<<548.0,660.0>-<595.0,690.0>-<656.0,688.0>>/B<<656.0,688.0>-<625.0,697.0>-<597.5,701.0>> = 14.311328809741568 and eternityarmrf: B<<531.0,660.0>-<484.0,690.0>-<423.0,688.0>>/B<<423.0,688.0>-<454.0,697.0>-<481.5,701.0>> = 14.311328809741568 [code: found-jaggy-segments]
```

**Comment by chrissimpkins** [comment]
These are new outline tests that Simon Cozens added to upstream fontbakery ~ month or so ago.  Agree.  We should definitely have a look.  As he notes in the rationale, some of these may be intentional design decisions by the type designer.  

If you come across any in the new Armenian work, we can ask @gorjious to have a look.  

David Berlow may have LGC changes addressing some of these issues that we can upstream from the grade axis work sources.  Edd Harrington/Alexei Vanyashiin/Irene Vlachou may be available to participate in L, C, G (respectively) maintenance design work.  Let's see what we find and then we can discuss how to approach this with design teams.

**Comment by madig** [comment]
In GoogleSans-Bold.ttf, there are some semi-horizontal lines. @alexeiva are these intentional?

![image](https://user-images.githubusercontent.com/380829/120358815-d66ecf00-c2fe-11eb-845e-a0582302d5fd.png)

**Comment by madig** [comment]
There are a couple minor problems with lines not being perfectly vertical or horizontal in the masters, to be seen in the interpolated Text Medium:

![image](https://user-images.githubusercontent.com/380829/120360284-7c6f0900-c300-11eb-91b1-cab7bcff7063.png)
![image](https://user-images.githubusercontent.com/380829/120360340-8db81580-c300-11eb-8e14-abedb717e83e.png)
![image](https://user-images.githubusercontent.com/380829/120360382-9872aa80-c300-11eb-8a0e-571c24864478.png)
![image](https://user-images.githubusercontent.com/380829/120360403-9dcff500-c300-11eb-8ed9-9a91c3601bbd.png)

**Comment by madig** [comment]
I do wonder though if these issues are important enough that we need to look for them in fontbakery? Otherwise I'd say we should disable `com.google.fonts/check/outline_jaggy_segments` and `com.google.fonts/check/outline_semi_vertical` to reduce noise. @chrissimpkins

**Comment by chrissimpkins** [comment]
Thanks for posting these images Nikolaus.  I do think that we should address the off-horizontal and off-vertical warns.  It looks like many of these are valid issues, particularly the ones that are meant to be aligned at global metrics like cap height, x-height, horizontal bars in Latin forms.

 Do any of the jaggy segment warns appear to be valid?

@dberlow are you aware of other similar outline adjustments/cleanup that are necessary following your full Latin glyph set work?  Have you already addressed any of these issues?

**Comment by chrissimpkins** [comment]
> Otherwise I'd say we should disable

Agree with this comment too.  It would be nice if these were included in a separate FB profile (i.e., not in universal) so that we might selectively run them in a separate step of the CI workflow.  I think that we do want ongoing checks as new outlines/updated outlines are under review, but we don't want them to run with all of the other upstream universal profile checks.  IIRC this was discussed as these were being implemented and there was a decision against doing it.  Maybe we can achieve something like this if there is include check filtering support in addition to the excluded check filters?  We exclude from our main FB font CI and run another custom FB profile step in the workflow that only includes these checks.  I don't know if that is possible.

**Comment by alexeiva** [comment]
> In GoogleSans-Bold.ttf, there are some semi-horizontal lines. @alexeiva are these intentional?
> 
> ![image](https://user-images.githubusercontent.com/380829/120358815-d66ecf00-c2fe-11eb-845e-a0582302d5fd.png)

No, all these should be 100% horizontal. I can't find this error in my original sources though.

**Comment by madig** [comment]
They were probably introduced in v4.000 during the grade work.

**Comment by madig** [comment]
> Do any of the jaggy segment warns appear to be valid?

Hard to say, they point out things in merged, static outlines (don't see the warnings in the VF CI logs). I don't think we can reasonably do something about them unless we change the overlap removal algorithm and Cosimo can tell us war stories about that. I can put the two checks into a separate make command?

**Comment by chrissimpkins** [comment]
Feel free to deactivate the checks in the merge PRs for now.  We can look into how to address the outlines and checks after the merges are wrapped up and the GPOS optimizations land for the upcoming release.

**Comment by madig** [comment]
After merges:
1. Add outline_jaggy_segments and outline_semi_vertical to the ignore list inside the profile
2. Make a separate outline chekcing profile with the two with separate Makefile target.

**Comment by chrissimpkins** [comment]
> > In GoogleSans-Bold.ttf, there are some semi-horizontal lines. @alexeiva are these intentional?
> > ![image](https://user-images.githubusercontent.com/380829/120358815-d66ecf00-c2fe-11eb-845e-a0582302d5fd.png)
> 
> No, all these should be 100% horizontal. I can't find this error in my original sources though.

@alexeiva did you happen to come across this issue in your GRAD master review and are changes happening in your in progress edits?

@madig Alexei's Cyrillic GRAD -50 and GRAD +200 master revisions will be available in early Feb.

**Comment by alexeiva** [comment]
> @alexeiva did you happen to come across this issue in your GRAD master review and are changes happening in your in progress edits?

I don't recall any semi-horizontal lines in the -50 +200 GRAD that I inspected.
I will get back on this more precisely next week.

**Comment by alexeiva** [comment]
@chrissimpkins I am working on this branch. 
https://github.com/googlefonts/googlesans/tree/alexeiva-cyr-GRAD-fix

I based my branch on Berlow's branch to sync with the Greek updates. 
https://github.com/googlefonts/googlesans/tree/Berlow-Greek-GRAD-Fixes

I haven't come across semi-horizontal issues in 17-w380-GRAD200. These glyphs you mentioned are fine.

**Comment by MariannaPaszkowska** [comment]
I checked the sources and tested the and fonts in both main and https://github.com/googlefonts/googlesans/actions/runs/7492954905 with FB version 0.10.9 and cannot replicate the issues. 

cc @belluzj
