### ISSUE TITLE
Cyrillic locl Features: smcp and c2sc don't work for Serbian , etc.

### ISSUE THREAD

**Issue by alexeiva** [googlefonts/googlesans#194]
works as intented:
![Screenshot 2021-02-12 at 13 03 44](https://user-images.githubusercontent.com/16634089/107754709-ea33fc80-6d32-11eb-9288-814b3fdb072d.png)

works:
![Screenshot 2021-02-12 at 13 04 29](https://user-images.githubusercontent.com/16634089/107754719-ed2eed00-6d32-11eb-9ed6-4812e023c14d.png)

MKD works:
![Screenshot 2021-02-12 at 13 07 49](https://user-images.githubusercontent.com/16634089/107755060-5f073680-6d33-11eb-949c-5682f6a42afc.png)

BSH, CHU, SRB locales produce no result.
![Screenshot 2021-02-12 at 13 04 34](https://user-images.githubusercontent.com/16634089/107754741-f61fbe80-6d32-11eb-9097-9d379a240eae.png)

I suspect Languagesystem prefix does not include BSH, CHU, SRB locales. It should be:
```
languagesystem cyrl MKD;
languagesystem cyrl SRB;
languagesystem cyrl BGR;
languagesystem cyrl CHU;
languagesystem cyrl BSH;
```

**Comment by madig** [comment]
Which fonts did you test?

**Comment by alexeiva** [comment]
3.003 release, expert fonts

**Comment by madig** [comment]
Right, I think we fixed that. Please try the fonts ("artifacts") in https://github.com/googlefonts/googlesans/actions/runs/559958408.

**Comment by alexeiva** [comment]
yes, it's fixed in artifacts. 

![Screenshot 2021-02-12 at 14 37 18](https://user-images.githubusercontent.com/16634089/107763587-e8bd0100-6d3f-11eb-9f9d-1c3475093534.png)

**Comment by chrissimpkins** [comment]
Thanks Alexei!

**Comment by madig** [comment]
@alexeiva just for clarity, the behavior is correct now for all combinations of uprights and italics, languages, and smcp/c2sc on and off?

**Comment by alexeiva** [comment]
> @alexeiva just for clarity, the behavior is correct now for all combinations of uprights and italics, languages, and smcp/c2sc on and off?

It looks good to me now

**Comment by madig** [comment]
Thanks!
