### ISSUE TITLE
Interpolating feature files

### ISSUE THREAD

**Issue by madig** [googlefonts/googlesans#197]
Currently, any time you use `pos` in the feature file, it won't work for statics, which are going to have the regular master's numbers, because fontmake/fontMath won't interpolate anything stored in the feature file, instead passing on the default source's feature file. Same problem as https://github.com/googlefonts/googlesans/issues/112.

This is going to be an annoying issue in Devanagari and a dealbreaker in Telugu: https://github.com/googlefonts/googlesans/issues/148#issuecomment-778264769

Cosimo has suggested two things:
1. Use the "replace features" feature that Glyphs.app has, not sure we implemented it anywhere? Or,
2. Use `varLib.interpolate_layout` in `fontmake.instantiator`. That'd mean we compile the feature files for each master, which include the appropriate `pos` for whatever, and drop the interpolated feature into the instance.

Denis noted that this needs https://github.com/googlefonts/ufo2ft/pull/458 for delaying inserting `pos` (https://github.com/googlefonts/googlesans/issues/148#issuecomment-778276456).

I reckon this could be interesting for the wider UFO/Designspace ecosystem.

**Comment by anthrotype** [comment]
> Use the "replace features" feature that Glyphs.app has, not sure we implemented it anywhere?

yes, we did implement "Replace Feature" custom parameter in glyphsLib already. The suggestion I hinted at was to add such custom parameter to _both_ the masters (so it gets used when building the master TTFs that get blended into the VF) and the instances (with pos values pre-computed so they match the interpolated ones..)

Option 2. seems neater but require code changes. Option 1. should already work now.

**Comment by madig** [comment]
Mh, so for option 1, fontmake would call into glyphsLib to do the replacement, right?

**Comment by chrissimpkins** [comment]
@madig status here?

**Comment by madig** [comment]
I think we have the tools to "replace features" if need be for instances. I have not tested them however.

**Comment by chrissimpkins** [comment]
No active bugs related to this issue though?

**Comment by madig** [comment]
I don't think so or I don't know about them.

**Comment by chrissimpkins** [comment]
> This is going to be an annoying issue in Devanagari and a dealbreaker in Telugu

OK let's see if anything problematic comes in the Telugu next week.  If not, it looks like we can close this issue.

**Comment by chrissimpkins** [comment]
The Telugu import is in progress.  It sounds like this issue may be addressed in the pipeline?

**Comment by madig** [comment]
We settled on cutting instances.
