### ISSUE TITLE
Collect vendor test documents

### ISSUE THREAD

**Issue by madig** [googlefonts/googlesans#199]
At some point, we should probably collect all the HTML pages, etc., from vendors and commit them to the repo. Using them would require building the fonts first though.

**Comment by chrissimpkins** [comment]
@dberlow David, are all of your grade axis proofing documents available in the GoogleSans-fb repository?

**Comment by MariannaPaszkowska** [comment]
Testing strings for shaping regressions and HTML, where appropriate, were collected.
