### ISSUE TITLE
avar table to prevent e.g. 17.5 pt from showing interpolated forms

### ISSUE THREAD

**Issue by davelab6** [googlefonts/googlesans#201]
@chrissimpkins mentioned in a call today that we might need rollout docs to remind users not to use 17.x pt size, as they'll get undesirable interpolated forms in this case. 

I believe we should have an avar table that prevents those forms, so that at 17.99999 we get the same as 17.

**Comment by chrissimpkins** [comment]
Is there support for float value axis mapping inputs?

**Comment by chrissimpkins** [comment]
> Is there support for float value axis mapping inputs?

I can confirm that this works.

I tested the use of a very sharply "bent" avar table and it looks like we can achieve the abrupt "substitution" behavior without the use of rvrn substitutions.  

This demo sets inputs:outputs of:

- 17:17
- 17.9999:17
- 18:18

![avar](https://user-images.githubusercontent.com/4249591/108804978-d2e3e300-756c-11eb-8ddc-857d090dea71.png)


The top line is a build that uses linear interpolation and the bottom build includes the avar definitions above.

![avar](https://user-images.githubusercontent.com/4249591/108792778-1714ba80-7550-11eb-9086-3db893a50a3d.gif)

Demo sources:

[Avar.zip](https://github.com/googlefonts/googlesans/files/6026364/Avar.zip)

**Comment by davelab6** [comment]
Excellent! Great work Chris

**Comment by chrissimpkins** [comment]
Added and functioning as intended.  This issue will be closed by #240
