### ISSUE TITLE
Google Sans v4 tracker

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans#208]
Google Sans v4 will be a new major release that includes expansion of the LGC character set with grade axis support.  It will be based on the last point release of Google Sans (v3.003) and include ungraded production Hebrew script designs.  We will not include other merged scripts in v4.000. 

### New

- add Latin, Greek, Cyrillic grade axis with a range of -50 to 200 (2 additional masters each for Roman and Italic) (https://github.com/googlefonts/googlesans/issues/209)
- add German double s & smcp form (#215)
- add ldot and feature code to support existing small cap form (#210)

### Change

- refactor LGC to support additional composite designs for file size reduction
- some ASCII glyph refinements to support grade axis expansion (dollar, percent, ampersand)
- some spacing refinements

### Remove

- `aalt` feature and all stylistic alternate forms (move to non-exporting glyphs and exclude from binaries, keep source definitions) (https://github.com/googlefonts/googlesans/issues/211)
- remove all `ss04` microcaps forms that do not support the following file size unit abbreviations: kB, KB, MB, GB, TB, PB, EB (#212)
- remove `ss08` Bulgarian locale stylistic set (we will have many locales that require support and will not be able to include a stylistic set for each locale) (#213)
- Transition LGC opsz rvrn support to interpolated glyph designs with avar table to support the same rvrn substitution behavior(#201, #214)
- Eliminate duplicate Google logo outlines (#152)

### Fix

- Semicolon mixed contour / components (#98)
- Eliminate nested components (#108)
- Scaled dagesh (#134) - this is currently in our master branch, needs to be addressed during the grade axis merge process

**Comment by madig** [comment]
### Kill

- Remove unnecessary unexported glyphs (https://github.com/googlefonts/googlesans/issues/122)

**Comment by madig** [comment]
@chrissimpkins I fear me might drown in chaos unless we organize the switch differently. With Berlow sources still in flux but needing a flag-day merge with updating all testing files, it could turn ugly and take a long time to get back into a known good state. I think we should partition the work into two areas:

1. Work that can be done now:
    1. Remove unnecessary unexported glyphs (#122)
    2. aalt feature and all stylistic alternate forms (move to non-exporting glyphs and exclude from binaries, keep source definitions) (#211)
    3. Remove ss04 and ss08
    4. Eliminate duplicate Google logo outlines (#152)?
    5. Others?
2. Work that needs to be done for the Berlow sources (update test files, ...)

Can you help with organizing it this way? I want to get as much of 1. in before we have the chaos of 2. on our hands.

**Comment by chrissimpkins** [comment]
Let's press the pause button on this side.  The plot thickens downstream.  Talk on Monday.

**Comment by chrissimpkins** [comment]
Pushed for rollout.
