### ISSUE TITLE
Remove ss08 Bulgarian locale feature support, keep Bulgarian locale support in locl feature

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans#213]
We will remove the stylistic set feature code support for the Bulgarian locale.  This is a beneficial feature for reasons including  the lack of simple access to localized forms in design team's design editors.  I ran into this problem last week as I prepared PDF specimens for type design consultants in InDesign. The issue is that we will need to support many locales and don't have the option to include stylistic set support for every locale that will be supported in this typeface.  How then do we choose which locales to prioritize for available stylistic set slots?

I suggest that we not include any ss localized forms in general purpose production builds.  We can save at least one of the 20 stylistic set slots for one-off development build requests.  We are unlikely to be able to support production localization through stylistic sets across the full scope of this project.

cc @alexeiva

**Comment by chrissimpkins** [comment]
Removed downstream in https://github.com/googlefonts/GoogleSans-fb/commit/9ccd2f138af01c02d22661e5b67997b903e9a5f9

**Comment by alexeiva** [comment]
> I suggest that we not include any ss localized forms in general purpose production builds.

That is fine. The duplicate BGR stylistic set is a nice-to-have feature, not a requirement.

**Comment by chrissimpkins** [comment]
Removed downstream and confirmed that they are not present in the binaries following the merge in #240.  This issue will be closed by #240
