### ISSUE TITLE
Transition Latin glyph set optical size rvrn substitution support to compatible opsz interpolation designs + avar table

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans#214]
We are running into a number of problems with optical size axis rvrn support and the approach to address these issues involves glyph duplication with a file size increase.  Our goal has been to "eliminate" opsz interpolation over the min opsz=17 master : max opsz=18 master range.  Ideally, there should be no visible interpolation between opsz 17 and opsz 18, including glyphs that are compatible forms now.

David Berlow worked on compatible versions of the Latin opsz 17 -> 18 rvrn designs and we have an approach to implement this with an avar table that maintains the optical size axis value dependent glyph substitution behavior (https://github.com/googlefonts/googlesans/issues/201).  We will try to establish the abrupt rvrn style substitution behavior as opsz is defined at 18+ across as many of these glyphs as possible.

We will maintain all rvrn substitutions that are included in the Hebrew glyph set for now.

This transition will occur as of the Google Sans v4 release.

**Comment by chrissimpkins** [comment]
@danielgrumer Daniel, we won't be able to fit it into this release but I would appreciate it if you would be willing to have a look at all of the Hebrew rvrn (Glyphs bracket layer) designs and let us know if it will be possible to transition to compatible forms so that we can eliminate the rvrn substitutions and use the same approach in a future point release.  With the avar table, you will not see the interpolated intermediate forms.

**Comment by chrissimpkins** [comment]
Current rvrn definitions:

https://github.com/googlefonts/googlesans/blob/67508ad446a9105a1f25b02d3f4dbe32be138d10/source/GoogleSans/GoogleSans.designspace#L12-L70

**Comment by chrissimpkins** [comment]
rvrn substitutions that will need to remain after the merge of the grade axis expansion work from David Berlow:

- finalpe-hb
- finalpedagesh-hb
- pe-hb
- pedagesh-hb
- perafe-hb
- samekh-hb
- samekhdagesh-hb

`G`, `y`, `semicolon`, `comma`, and `commaccent`, etc from Latin set have compatibilization work in progress.  We are attempting to transition away from rvrn altogether in the Latin set.

**Comment by chrissimpkins** [comment]
@madig these forms will not be completely sorted by tomorrow.  I suggest that we begin the merge and work in parallel with David while he works through the designs to fully address this issue.  The issues at this stage are the following:

- `y` must keep the flat horizontal terminal that it currently has in the opsz 18 design, not transition to a curved tail as in opsz 17
- all punctuation must keep the rounded forms in the opsz 18 designs, not take the stroke without round shape design as used in the opsz 17 design (includes semicolon, comma, and combining mark forms that use the comma shape)

Solution TBD. More info to come from David over the next couple of days.

cc @dberlow @davelab6

**Comment by chrissimpkins** [comment]
We have this working downstream. 👍 

Here is an example of interpolation + avar side-by-side with rvrn subs (Hebrew) on the optical size axis:

![109370890-40935600-7870-11eb-969e-40ac675f1e18](https://user-images.githubusercontent.com/4249591/109371843-b8637f80-7874-11eb-8305-2faedb4a35fd.gif)

Many thanks to David Berlow for all of his hard work on this during the week.  This should address a number of issues that we were facing with the rvrn substitutions and reduce file size.  Slated for release as part of v4

**Comment by danielgrumer** [comment]
Looks good!

**Comment by chrissimpkins** [comment]
Functions as of https://github.com/googlefonts/googlesans/pull/240/commits/b26739deb19ca6740903a69df7499c8851ff868a.  This issue will be closed by #240
