### ISSUE TITLE
[GS v4] Reimplement STAT table

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans#218]
We do not need named instances for non-zero GRAD values

**Comment by madig** [comment]
We do need to name them in the STAT table though.

**Comment by chrissimpkins** [comment]
Nikolaus added the GRAD updates in 8f2f3410e66163d91161c1f1a1ab7c5feeee3816, in open PR #240

**Comment by chrissimpkins** [comment]
Dave Crossland recommends that we use GRAD names `Grade-50` and `Grade200` instead of `-50` and `200`

**Comment by chrissimpkins** [comment]
> Dave Crossland recommends that we use GRAD names `Grade-50` and `Grade200` instead of `-50` and `200`

This gives us this STAT instance format:

"Google Sans Text Bold Grade-50 Italic"

**Comment by chrissimpkins** [comment]
> Dave Crossland recommends that we use GRAD names `Grade-50` and `Grade200` instead of `-50` and `200`

772a71988fa9b1f2ee07a0b88441f8434ba07d8b

**Comment by chrissimpkins** [comment]
This will be closed by #240
