### ISSUE TITLE
Logo ligatures are broken when upper case `G` is in string (calt / liga)

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans#228]
Due to rvrn swapping woes, we don't get the proper logo form defined by 

https://github.com/googlefonts/googlesans/blob/67508ad446a9105a1f25b02d3f4dbe32be138d10/source/GoogleSans/family.fea#L2059

@ opsz 17 we get the correct ligature.  @ opsz 18 we do not.

**Comment by chrissimpkins** [comment]
This also affects the ligature `google_G `.

rvrn shall be banished

**Comment by chrissimpkins** [comment]
and `super_G_logo `

and `G_logo`

and `Glogoligature`

😭

**Comment by chrissimpkins** [comment]
We are attempting to transition away from rvrn here.  Work in progress.

**Comment by madig** [comment]
Fixed in https://github.com/googlefonts/googlesans/pull/200.

- https://github.com/googlefonts/googlesans/pull/200/files#diff-fa9c7729ffdf10595ab661277f75e5d8bac6a45904211096c1e27eca5c1f3ccdR919-R926
- https://github.com/googlefonts/googlesans/pull/200/files#diff-fa9c7729ffdf10595ab661277f75e5d8bac6a45904211096c1e27eca5c1f3ccdR2085-R2092

😁

**Comment by madig** [comment]
BTW this is funny:
![image](https://user-images.githubusercontent.com/380829/109333329-39ac1980-7857-11eb-80b5-4090f8b98f90.png)

**Comment by chrissimpkins** [comment]
Fixed with transition to compatible, interpolated forms + avar

<img width="1711" alt="2021-02-26_21-33-47" src="https://user-images.githubusercontent.com/4249591/109372983-6887b700-787a-11eb-824e-41668e8f22d0.png">

**Comment by chrissimpkins** [comment]
Confirmed logo forms function as expected @ https://github.com/googlefonts/googlesans/pull/240/commits/b26739deb19ca6740903a69df7499c8851ff868a to be merged in #240.  Identified a new issue with GRAD weight changes in Roman only #249
