### ISSUE TITLE
Missing perafe-hb.BRACKET.18 and samekhdagesh-hb.BRACKET.18 in Italic

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans#233]
@danielgrumer We seem to be missing these rvrn substitution opsz 18 glyphs in the Italic set only.  And they are not defined in the Italic set designspace rule set.  Intentional difference for these forms between Roman and Italic?

<img width="1711" alt="2021-02-26_20-03-03" src="https://user-images.githubusercontent.com/4249591/109370334-ded1ec80-786d-11eb-8e2f-f3b07d5211a4.png">

**Comment by danielgrumer** [comment]
This is a mistake then.
Characters should look the same with/without a dagesh.

**Comment by chrissimpkins** [comment]
Let's aim to include this in GS v4.001

**Comment by chrissimpkins** [comment]
Will be closed by #281

**Comment by chrissimpkins** [comment]
Fixed in #281 and will be released in v5.000
