### ISSUE TITLE
Dagesh bug in Roman only

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans#244]
The behaviour has changed as you say (smaller and shifts down in bolder weights) in shindageshshindot-hb shindageshsindot-hb shindagesh-hb in Roman. The dagesh should be a bit lower in finalpedagesh-hb. I think pedagesh-hb is alright.  It used to look like this (in a build from 24 February):

https://user-images.githubusercontent.com/1923747/109797171-0085f780-7c11-11eb-87b3-540ec4f06e6e.mp4

_Originally posted by @moyogo in https://github.com/googlefonts/googlesans/pull/240#issuecomment-789637271_

Feature originally added in #134

**Comment by chrissimpkins** [comment]
Solution from Denis

> This issue is that dagesh-hb is used as a component instead of dagesh-hb.alt in roman styles in all of finalpedagesh-hb, pedagesh-hb, shindageshshindot-hb, shindageshsindot-hb, shindagesh-hb.
The dagesh-hb.alt is used in the italic styles.

**Comment by madig** [comment]
Reverted to pre-merge in https://github.com/googlefonts/googlesans/pull/240/commits/0ad3d168064deedd84402d5895c42edca130907f

**Comment by chrissimpkins** [comment]
Fix visually confirmed in builds at https://github.com/googlefonts/googlesans/commit/0ad3d168064deedd84402d5895c42edca130907f

https://github.com/googlefonts/googlesans/actions/runs/618021761

Thanks all!
