### ISSUE TITLE
U+04C4 Cyrillic small letter ka with hook - grade axis curve change in Italic only

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans#247]
The inferior portion of the glyph has a curve change across the GRAD axis in Italic only.  Observed @ opsz = 17 & opsz=18, across full weight axis.

![cyrillic](https://user-images.githubusercontent.com/4249591/109844391-121fcd00-7c1a-11eb-848f-ee0ac28b49dc.gif)

cc @dberlow 

--- 

### TODO

- [x] fix default form https://github.com/googlefonts/googlesans/pull/282
- [x] fix smcp form (https://github.com/googlefonts/GoogleSans-fb/commit/fb16902f6a51888aac830643059896c76156cd95 was cherry picked in #259)

**Comment by dberlow** [comment]
Thanks! The repair is committed

**Comment by chrissimpkins** [comment]
> Thanks! The repair is committed

Thanks David!

@madig this commit was cherry picked into my GSv4 branch downstream

**Comment by chrissimpkins** [comment]
smcp form fixed with https://github.com/googlefonts/GoogleSans-fb/commit/fb16902f6a51888aac830643059896c76156cd95.  

Default form still requires the same fix

**Comment by chrissimpkins** [comment]
smcp form fix merged in https://github.com/googlefonts/googlesans/pull/259

**Comment by chrissimpkins** [comment]
@dberlow This is the only remaining open bug that I have for v4.000.  Please let me know if you think that you can get to this before Tuesday.  If not, we will push this back to v4.001.

**Comment by chrissimpkins** [comment]
@dberlow this was the other issue that I referred to today.  It was that this was missed in the default set.  I believe that you fixed this in the smcp only.

**Comment by dberlow** [comment]
this is repaired in:
github.com/googlefonts/GoogleSans-fb/tree/main/sources/GS%20Cubic%20Sources/Italic
<img width="835" alt="Screen Shot 2021-03-24 at 4 24 10 PM" src="https://user-images.githubusercontent.com/1956494/112378503-666c1900-8cbd-11eb-98e6-8027251d9e41.png">

**Comment by chrissimpkins** [comment]
This fix will be complete in #282 and released in GS v5.000
