### ISSUE TITLE
Logo ligatures have GRAD weight change in Roman only

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans#249]
The logo form set has a weight change on the GRAD axis in Roman forms only.

@dberlow I seem to recall that you planned not to use grade on these forms?

![logos](https://user-images.githubusercontent.com/4249591/109910363-f0ecca00-7c75-11eb-86b5-3b23a9596c87.gif)

**Comment by dberlow** [comment]
I had to leave this to you. The raw materials to do whatever you'd like from all contours and no grades, to 1 set of contours and grades for all are all available.

**Comment by chrissimpkins** [comment]
> I had to leave this to you. The raw materials to do whatever you'd like from all contours and no grades, to 1 set of contours and grades for all are all available.

OK. Do you have a recommendation about how grade *should* be used here?  Do we want it or not?

**Comment by chrissimpkins** [comment]
I'm going to remove grade on the logos.  I did some cross-script testing yesterday (ungraded Hebrew with graded punctuation and graded Latin alphanumerics embedded) and we're going to need guidance around grade use outside of the Latin set.  When set together, graded chars (including punctuation and figures which are likely to be seen in other scripts) change stroke width with grade changes, but the ungraded script does not.  This is an issue.  Since the logo may appear with other scripts that do not support grade (yet), we'll keep it ungraded for now.

**Comment by chrissimpkins** [comment]
Fixed in #265
