### ISSUE TITLE
Some Cyrillic glyphs use K.alt as base

### ISSUE THREAD

**Issue by madig** [googlefonts/googlesans#251]
https://github.com/googlefonts/googlesans/pull/240#issuecomment-790706276

**Comment by alexeiva** [comment]
https://github.com/googlefonts/googlesans/pull/240#issuecomment-791310914

**Comment by madig** [comment]
Is `K.alt` a more appropriate base glyph than `K` for cyrl?

**Comment by alexeiva** [comment]
Yes. `K` is not appropriate at all.

**Comment by madig** [comment]
Then we can swap `Ka-cy` and `K.alt` (in all glyphs) and continue to enjoy byte-saving component use.

**Comment by chrissimpkins** [comment]
> Yes. `K` is not appropriate at all.

Thanks Alexei!
