### ISSUE TITLE
Add QA check for differences in advance widths and kerning across the GRAD axis masters

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans#253]
This will support the assurance that line length will not change with GRAD axis value changes.

Related https://github.com/googlefonts/googlesans/issues/252

Let's see how this turns out.  It probably belongs upstream if there is a profile that checks UFO's rather than binaries.  If not, we can consider support in upstream fontbakery with a binary testing approach or an entirely separate testing tool.

**Comment by chrissimpkins** [comment]
Per Nikolaus, the approach that we used to import David Berlow's GRAD masters does not allow for differences in kerning across the GRAD masters because we are only taking upstream kerns and replicating across the GRAD masters during the merge process.  It will be useful to add cross-GRAD master kerning checks for regression testing going forward.  Kerning differences should not be an issue for the v4.000 release.

**Comment by madig** [comment]
Kernign can be verified by:

```
nikolaus@DM1248 ~/googlesans (import-berlow-v3)> sha256sum source/GoogleSans/*.ufo/kerning.plist | sort
0920d4dc20ea2f251a9e8bb0ce9baa07e10f4d4d660bd45c153e6ea303fd58b8  source/GoogleSans/GoogleSansItalic-opsz18-wght380-GRAD-50.ufo/kerning.plist
0920d4dc20ea2f251a9e8bb0ce9baa07e10f4d4d660bd45c153e6ea303fd58b8  source/GoogleSans/GoogleSansItalic-opsz18-wght380-GRAD0.ufo/kerning.plist
0920d4dc20ea2f251a9e8bb0ce9baa07e10f4d4d660bd45c153e6ea303fd58b8  source/GoogleSans/GoogleSansItalic-opsz18-wght380-GRAD200.ufo/kerning.plist
0c4669d3cb166e7ceaf598cf28652221336a5cc235a62e8b04e0c98400043b82  source/GoogleSans/GoogleSansItalic-opsz17-wght734-GRAD0.ufo/kerning.plist
219b003f96e298d95af248fc62ac2e45f482fb23b8c0c63f15b84fc57b4b80ec  source/GoogleSans/GoogleSansItalic-opsz18-wght734-GRAD0.ufo/kerning.plist
25faabceea1159ecd576ef5c823727f148fca3577f86b06345fb3d51a46c74d7  source/GoogleSans/GoogleSans-opsz18-wght734-GRAD0.ufo/kerning.plist
5c659eecd006520d3a606b06b94e0c1980faec3bcdb096bb7dac2a046d1c7b65  source/GoogleSans/GoogleSans-opsz17-wght734-GRAD0.ufo/kerning.plist
e7897ce6fd8393843bed2e933d268838118d6abdf2285e6b52a635c78bea25bc  source/GoogleSans/GoogleSansItalic-opsz17-wght380-GRAD-50.ufo/kerning.plist
e7897ce6fd8393843bed2e933d268838118d6abdf2285e6b52a635c78bea25bc  source/GoogleSans/GoogleSansItalic-opsz17-wght380-GRAD0.ufo/kerning.plist
e7897ce6fd8393843bed2e933d268838118d6abdf2285e6b52a635c78bea25bc  source/GoogleSans/GoogleSansItalic-opsz17-wght380-GRAD200.ufo/kerning.plist
ede655ea270fcf32e2c5f72116d44cca7ccbfedf14a2808fea1c5eef60133c12  source/GoogleSans/GoogleSans-opsz18-wght380-GRAD-50.ufo/kerning.plist
ede655ea270fcf32e2c5f72116d44cca7ccbfedf14a2808fea1c5eef60133c12  source/GoogleSans/GoogleSans-opsz18-wght380-GRAD0.ufo/kerning.plist
ede655ea270fcf32e2c5f72116d44cca7ccbfedf14a2808fea1c5eef60133c12  source/GoogleSans/GoogleSans-opsz18-wght380-GRAD200.ufo/kerning.plist
fb03724429f14b3faf2f376ed07584a9f54bd5462d1117608adff8d4b791c1ba  source/GoogleSans/GoogleSans-opsz17-wght380-GRAD-50.ufo/kerning.plist
fb03724429f14b3faf2f376ed07584a9f54bd5462d1117608adff8d4b791c1ba  source/GoogleSans/GoogleSans-opsz17-wght380-GRAD0.ufo/kerning.plist
fb03724429f14b3faf2f376ed07584a9f54bd5462d1117608adff8d4b791c1ba  source/GoogleSans/GoogleSans-opsz17-wght380-GRAD200.ufo/kerning.plist
```

**Comment by chrissimpkins** [comment]
Tight down to the order and spacing of the text in the kerning definitions. 🚀

**Comment by chrissimpkins** [comment]
@madig use a SHA hash string comparison check on the kerning.plist files for now?  This would be simple.  Do you have something fancy in mind?

**Comment by madig** [comment]
For now, yes. As long as kerning is only in kerning.plist, a SHA string will do.

**Comment by chrissimpkins** [comment]
Added a Python implementation of [the hash comparison approach that Nikolaus recommended](https://github.com/googlefonts/googlesans/issues/253#issuecomment-791550938) in https://github.com/googlefonts/googlesans/pull/345

This will run in our GH Actions CI.

**Comment by chrissimpkins** [comment]
@madig any recent thoughts about how to approach the adv width checks across GRAD axis masters?

Will bump this back to the v9 milestone.

**Comment by madig** [comment]
Not yet, but a fontbakery source check should suffice. (Checking kerning on binaries is harder)

**Comment by Hoolean** [comment]
Let's consider picking this back up for the next release cycle, as it would give forewarning for issues [such as we saw](https://github.com/googlefonts/googlesans/pull/517#issuecomment-1303648162) in #517.

This is the current output of Nikolaus' `find-width-diffs.py` script:

```
UFO GoogleSans-opsz17-wght380-GRAD-50.ufo width mismatches compared to GoogleSans-opsz17-wght380-GRAD0.ufo:
  semicolon.loclARM
UFO GoogleSans-opsz17-wght380-GRAD200.ufo width mismatches compared to GoogleSans-opsz17-wght380-GRAD0.ufo:
  semicolon.loclARM
UFO GoogleSans-opsz18-wght380-GRAD200.ufo width mismatches compared to GoogleSans-opsz18-wght380-GRAD0.ufo:
  semicolon.loclARM
UFO GoogleSansItalic-opsz17-wght380-GRAD-50.ufo width mismatches compared to GoogleSansItalic-opsz17-wght380-GRAD0.ufo:
  baht.tf
  semicolon.loclARM
UFO GoogleSansItalic-opsz17-wght380-GRAD200.ufo width mismatches compared to GoogleSansItalic-opsz17-wght380-GRAD0.ufo:
  semicolon.loclARM
UFO GoogleSansItalic-opsz18-wght380-GRAD-50.ufo width mismatches compared to GoogleSansItalic-opsz18-wght380-GRAD0.ufo:
  Men_Ech-arm.liga
  men_xeh-arm.liga.sc
  semicolon.loclARM
UFO GoogleSansItalic-opsz18-wght380-GRAD200.ufo width mismatches compared to GoogleSansItalic-opsz18-wght380-GRAD0.ufo:
  Men_Ech-arm.liga
  semicolon.loclARM
  ```
  
  Having this integrated into FontBakery would be very helpful : )

**Comment by chrissimpkins** [comment]
> Having this integrated into FontBakery would be very helpful : )

@felipesanches

**Comment by madig** [comment]
Oh, I'm not sure this would fit nicely into fontbakery, because it is actually tricky to do this on final fonts. It's much easier to write a custom check that works on the sources.

**Comment by felipesanches** [comment]
> Oh, I'm not sure this would fit nicely into fontbakery, because it is actually tricky to do this on final fonts. It's much easier to write a custom check that works on the sources.

Fontbakery can have checks on source files as well.

**Comment by madig** [comment]
Yes, but are GRAD semantics universal enough to put it in a Google Fonts check? What about non-UFO/DS sources?

**Comment by felipesanches** [comment]
Fontbakery can have checks on GlyphsApp source files using glyphslib

**Comment by MariannaPaszkowska** [comment]
following our discussion in the meeting @madig Let's remove the custom GS kerning checks on GRAD and use the upstream ones (from Font Bakery)
