### ISSUE TITLE
Proper localized form for Serbian ge-cy (U+0433) in Roman and Italic

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans#255]
Our feature code specifies the MKD form in Italics only:

https://github.com/googlefonts/googlesans/blob/5bd2cb8897bc055e661c662927ff942df074f166/source/GoogleSans/family_italics.fea#L23-L25

But there is a SRB localized form in the glyph set with a different design.  The Roman feature code does not define this substitution either so the ge-cy.loclSRB glyph is not used in the design and the subsetter removes it.

Is the feature code incorrect here?  If not, is it ok to remove this .loclSRB glyph from the source files altogether?

@alexeiva

**Comment by alexeiva** [comment]
> But there is a SRB localized form in the glyph set with a different design. 

Strange.  I don't see `ge-cy.loclSRB` in my original sources. 

![Screenshot 2021-03-05 at 13 07 50](https://user-images.githubusercontent.com/16634089/110100759-d28ce880-7db3-11eb-8e90-ea28b65a0556.png)

`ge-cy.loclSRB` should be the same shape as `ge-cy.loclMKD`

>The Roman feature code does not define this substitution either so the ge-cy.loclSRB glyph is not used in the design and the subsetter removes it.
> 
> Is the feature code incorrect here? 

The code is correct. 

> If not, is it ok to remove this .loclSRB glyph from the source files altogether?

I suggest removing `ge-cy.loclSRB`.

**Comment by chrissimpkins** [comment]
Perfect!  That's what we needed to know.  I hate it when new glyphs materialize out of thin air! :)

**Comment by chrissimpkins** [comment]
The behavior is correct, the feature files are properly specified, the shaping regression files have the correct / expected output data, and the subsetter is doing its thing appropriately.  

The only thing that we need to do here is remove ge-cy.loclSRB.  Will address this in v4.001
