### ISSUE TITLE
Cyrillic small letter straight U (U+04AF) does not have grade support, Italic only

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans#262]

**Comment by madig** [comment]
There are two, ustrait and ustraight, which are copies of each other. Maybe they were renamed between 3.003 and Master.  One can be deleted

**Comment by moyogo** [comment]
I think it was a typo than was fixed but the original copy of the glyph remained.

**Comment by chrissimpkins** [comment]
Ty! It looks like both Roman and Italic use the ustraight versions.  Perhaps only the ustrait was graded in Italic?  I'll check.

**Comment by chrissimpkins** [comment]
Yep, you are correct. That is the problem.  Only the ustrait-cy was graded in Italic but ustraight-cy is the form that is used.  Will fix it.  Thank you very much!

**Comment by chrissimpkins** [comment]
Note to self:

Italic only -50 and 200 masters need to have ustraight-cy outlines replaced with ustrait-cy outlines.

**Comment by madig** [comment]
Maybe rename the glyph again now

**Comment by chrissimpkins** [comment]
> Maybe rename the glyph again now

Don't understand.  From / to?

**Comment by madig** [comment]
ustrait -> ustraight. This was a renaming in Glyphs.app at some point.

**Comment by chrissimpkins** [comment]
These are duplicates.  This suggestion simply means eliminate the ustrait glyphs correct?  #263

**Comment by madig** [comment]
Yes, whatever is worse should go 🚶

**Comment by chrissimpkins** [comment]
It looks like ustraight-cy is what is used in production.  The ustrait-cy were left behind.  But, ustrait-cy got the grade in Italic.  ustraight-cy did not.  Too many *-cy.  We'll clean house after we push this release.
