### ISSUE TITLE
Remove duplicate logo forms

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans#264]
The following glyphs are duplicates of *.logo designs, are not defined in features, and can be removed from the glyph set:

- Glogo
- ologo
- glogo
- llogo
- elogo
- Googlelogo

**Comment by madig** [comment]
Those carry PUA codepoints though. Do we know if they're used by anyone? Otherwise, I'd love to purge them.

**Comment by chrissimpkins** [comment]
Documenting our decision on this here.  We will move the PUA code points to the glyphs listed in the OP and remove all of the `*.logo` versions.  It is not clear if anyone is actually using the PUA's but we'll keep them to avoid breakage.

**Comment by madig** [comment]
You mean delete the `logo` variants without the dot? The features use the one with the dot.
