### ISSUE TITLE
Google Sans v4.000 Release Candidate 1

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans#268]
v4.000 release candidate files are now available.

[Changelog](https://github.com/googlefonts/googlesans/blob/main/CHANGELOG.md)

[Build archive](https://github.com/googlefonts/googlesans/releases/download/v4.000-rc.1/GoogleSans-v4.000-rc.1.zip)

Open for any/all on this repository to download and review.  Please have a look and let me know if you see any issues.

**Comment by madig** [comment]
Is there something specific you want us to test?

**Comment by chrissimpkins** [comment]
> Is there something specific you want us to test?

No specific requests.  David Berlow is taking a look through all of the new grade work.  Open for any/all to dog food if you have the time.
