### ISSUE TITLE
Negative circled sans-serif digit glyphs require slant and grade support

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans#269]
U+278A - U+2793

The DINGBAT NEGATIVE CIRCLED SANS-SERIF [numeral] glyphs have the following issues as of the GoogleSans 4.000 RC1 builds.

- GS Italic opsz 17 are not slanted forms, wght 400-700
- GS Italic opsz 18, wght 700 is not slanted, wght 400 are slanted
- GS Roman opsz 18 and 17 do not have grade support (Italic does)

**Comment by dberlow** [comment]
•  GS Italic opsz 17 are slanted forms, wght
<img width="1074" alt="Screen Shot 2021-03-24 at 2 59 06 PM" src="https://user-images.githubusercontent.com/1956494/112368510-8990cb80-8cb1-11eb-9c4a-f155de8582eb.png">
 400-700

•  GS Italic opsz 18, wght 700 is slanted like wght 400 
<img width="1126" alt="Screen Shot 2021-03-24 at 3 01 18 PM" src="https://user-images.githubusercontent.com/1956494/112368828-e1c7cd80-8cb1-11eb-8bd3-7c11f2cfd020.png">

Those are all here: github.com/googlefonts/GoogleSans-fb/tree/main/sources/GS%20Cubic%20Sources/Italic

•  GS Italic Grades removed on numbers in circles.

**Comment by chrissimpkins** [comment]
Merging this in #311 and ~~will release in GS v5~~ (see below).  Thank you David!

**Comment by chrissimpkins** [comment]
> Merging this in #311 and will release in GS v5. Thank you David!

Check that.  Blocked on https://github.com/googlefonts/googlesans/pull/311#issuecomment-857212084
