### ISSUE TITLE
Issues with glyphs composed with Eng-tail and eng-tail

### ISSUE THREAD

**Issue by moyogo** [googlefonts/googlesans#284]
Eng = U+014a
eng = U+014b

Test string: `Ŋŋ`

1. Eng has been recomposed as `Eng= N + Eng-tail` but Eng-tail is misplaced in some masters or adds a corner between the diagonal and the vertical stem of the tail in some masters.

The fix would probably be to adjust Eng-tail as it is only used in Eng at the moment. It can be reused in a few glyphs in the Latin extension PR.

GoogleSans-opsz18-wght734-GRAD0
<img width="564" alt="image" src="https://user-images.githubusercontent.com/1923747/112720428-25ab1480-8ef6-11eb-8d7a-471636954dc8.png">

it is slightly misplaced in GoogleSansItalic-opsz17-wght380-GRAD200 and GoogleSansItalic-opsz18-wght380-GRAD200
<img width="218" alt="image" src="https://user-images.githubusercontent.com/1923747/112720612-52abf700-8ef7-11eb-839a-59e0fa403c3d.png">
<img width="216" alt="image" src="https://user-images.githubusercontent.com/1923747/112720607-4a53bc00-8ef7-11eb-9d97-5f1126a54eff.png">

2. eng-tail is now used to compose eng, eng.sc, dje-cy, elhook-cy. It is either too narrow or misplaced in some glyphs in some masters. One issue is that it matches the stem width of el-cy used in elhook-cy which is slightly narrower than the stem width of n used in eng or h used in dje-cy. The stem width difference is more noticeable in some Roman masters but there is a one unite difference in some Italic masters. The vertical weight of the eng-tail is also too heavy in some masters.

The fix could be to fix the vertical weight of the tail and to adjust the stem width of el-cy and eng-tail, and make a separate eng-tail.sc for eng.sc to remove the corner. The eng-tail and the potential eng-tail.sc can be reused in the Latin extension PR.

For example in GoogleSans-opsz18-wght380-GRAD200: 
<img width="907" alt="image" src="https://user-images.githubusercontent.com/1923747/112720647-89820d00-8ef7-11eb-9ae4-969d064ed87d.png">
or GoogleSans-opsz17-wght380-GRAD200:
<img width="909" alt="image" src="https://user-images.githubusercontent.com/1923747/112720727-044b2800-8ef8-11eb-84c7-fdf765f1ae94.png">

The vertical weight of the stroke is too heavy in GoogleSans-opsz18-wght380-GRAD50 and GoogleSans-opsz17-wght380-GRAD50:
<img width="895" alt="image" src="https://user-images.githubusercontent.com/1923747/112720748-39f01100-8ef8-11eb-8011-3e445b6e8370.png">
<img width="877" alt="image" src="https://user-images.githubusercontent.com/1923747/112720751-407e8880-8ef8-11eb-901d-1f1e11a53224.png">

**Comment by chrissimpkins** [comment]
Thank you very much Denis! What environment are you viewing the forms in?

@dberlow is this a change that you made?

**Comment by chrissimpkins** [comment]
And @moyogo is this something that affects forms with the tail shape in your global Latin expansion?

**Comment by moyogo** [comment]
@chrissimpkins I could reuse that component or create similar ones if the aim is to reduce file size.

However, while this can work in upright styles when the design allows it but can be problematic in italics where diagonals may not exactly overlap and would create artifacts at large sizes.
<img width="108" alt="image" src="https://user-images.githubusercontent.com/1923747/112855108-6d709e00-90a6-11eb-83a5-1b1fcbbf2434.png">

There are a few glyphs in the Latin expansion that could use this, for example the Eng-tail could be used in Ƒ Ꜧ Ɲ Ŋ-variant and the eng-tail could be used in ƒ ꜧ ɲ.
Similar components could be used for:
- Ɋ Ɽ Ʈ
- ɖ ɋ ɽ ʈ
- Ɓ Ɗ Ɦ Ƥ Ƭ, but not with the current design.
- ɓ ɠ ɗ ƥ ʠ ƭ
- Ƈ Ɠ

Generally, I think proper outlines behave better for these kind of hooks or tails. For example, j has not been modified to be composed of i + eng-tail.

**Comment by chrissimpkins** [comment]
OK with me if you fully decompose the hooks including the Eng glyphs.  The file size impact should be minimal and the savings shouldn't be at the expense of design quality.

**Comment by dberlow** [comment]
In the Regular, there was a misplaced tail and two tails that had not been grade min treated. Those are fixed. 

In the Italic, everything is positioned and graded correctly, but there is no master at opsz17 wght 700 GRAD200 so  I'll have to look at what's making that wander.

**Comment by chrissimpkins** [comment]
Roman should be fixed downstream as of https://github.com/googlefonts/GoogleSans-fb/commit/d06423559b48684fa5e795fffacda337ab294cb0

Italic still under review

**Comment by chrissimpkins** [comment]
> In the Regular, there was a misplaced tail and two tails that had not been grade min treated. Those are fixed.
>
>In the Italic, everything is positioned and graded correctly, but there is no master at opsz17 wght 700 GRAD200 so I'll have to look at what's making that wander.

@dberlow David, what is the status of the review of the **italic** Eng / eng tail issue?

**Comment by chrissimpkins** [comment]
@dberlow any update on the eng tail italics?

**Comment by dberlow** [comment]
Everything I knew of was fixed, we only need to look to see if opsz17 wght 700 GRAD200 is aligned properly, regular and italic.

**Comment by chrissimpkins** [comment]
This was your comment in https://github.com/googlefonts/googlesans/issues/284#issuecomment-858080358

> In the Italic, everything is positioned and graded correctly, but there is no master at opsz17 wght 700 GRAD200 so I'll have to look at what's making that wander.

**Comment by chrissimpkins** [comment]
We have not imported anything on this side to review any of this work.  Your builds are the source of truth at the moment.

**Comment by chrissimpkins** [comment]
Opened #332 with import of the `Eng` and `Eng-tail` fixes in David's sources

**Comment by chrissimpkins** [comment]
@dberlow Here are views of GRAD endpoints @ wght=700 with the latest Eng and Eng-tail updates in your repository. It looks like there is still some positioning work to do in the italic, GRAD 200 end of the design space? We'll also need to review Denis' comments in https://github.com/googlefonts/googlesans/issues/284#issue-842496329 on the `eng` (lower case) tail.

### GRAD -50

<img width="1628" alt="2021-07-08_14-42-56" src="https://user-images.githubusercontent.com/4249591/124974467-d4cdb080-dffa-11eb-867c-be04b6613312.png">


### GRAD +200

<img width="1628" alt="2021-07-08_14-39-52" src="https://user-images.githubusercontent.com/4249591/124974383-b8ca0f00-dffa-11eb-960e-9ef0dea5bf84.png">

**Comment by dberlow** [comment]
Getting close!

As far as I recall there is no master at these locations, so I will need to load the latest masters and use Skateboard to track down the issue.

**Comment by chrissimpkins** [comment]
I'll merge what we have as is for v5 and leave this open to wrap up the rest of the work in the next release (v6)

**Comment by chrissimpkins** [comment]
Partial fix for upper case `Eng` tail issue merged in https://github.com/googlefonts/googlesans/pull/332 and will land in GS v5

**Comment by dberlow** [comment]
I redefined all  Eng and eng as glyphs, decomposing, removing overlap and checking compatibility of all 14 styles. 
Blocked from commit or fork. 
Files on Drive and shared:
https://drive.google.com/file/d/16_fRKRuvNZrmmiIz9RIUa0QNk6HV54Fy/view?usp=sharing

Missing BRACKET glyph issue also filed on repo.

**Comment by chrissimpkins** [comment]
> I redefined all Eng and eng as glyphs, decomposing, removing overlap and checking compatibility of all 14 styles.
> Blocked from commit or fork.
> Files on Drive and shared:
> https://drive.google.com/file/d/16_fRKRuvNZrmmiIz9RIUa0QNk6HV54Fy/view?usp=sharing
> 
> Missing BRACKET glyph issue also filed on repo.

Great! Thanks David!

**Comment by chrissimpkins** [comment]
Imported David's changes in #379. This will be released in v6.000
