### ISSUE TITLE
Clean out anchor propagation exclusion list after anti-rvrn merges

### ISSUE THREAD

**Issue by madig** [googlefonts/googlesans#288]

**Comment by chrissimpkins** [comment]
Can you expand on what needs to be done here @madig?

**Comment by madig** [comment]
This needs to be removed: https://github.com/googlefonts/googlesans/blob/3e8151514f691f14bc4b0733c67f9d24d69aa24b/scripts/internal/normalize.py#L104-L140

**Comment by madig** [comment]
Actually, let's leave the code in, since all referenced glyphs are still present in the sources.

**Comment by chrissimpkins** [comment]
Close this issue?

**Comment by madig** [comment]
For now, yes. Reopen (or just remove entries) when we actually clear out all BRACKET glpyhs.
