### ISSUE TITLE
Compressing kerning

### ISSUE THREAD

**Issue by madig** [googlefonts/googlesans#292]
As I found in https://github.com/googlefonts/googlesans/pull/274#issuecomment-820433543, the kerning data currently has an outsized impact on file size due to suboptimal use of space.

This can be tackled from at least two sides:

1. Trimming kerning in general, as we proposed/will propose
2. Splitting kerning data up to make better use of the allocated space

I'll need to find the right level for doing point two. Denis suggested splitting kerning data by script. Should no good heuristic be found, I'll need to look into sparse matrix splitting to increase density.

**Comment by madig** [comment]
(Jany just pointed out that for VFs, my script needs to check for kerning variations, too, or the amount of zeros might be measured as too high)

**Comment by chrissimpkins** [comment]
What happens on a round trip through the subsetter with removal of Armenian? Does the subsetter pull everything that comes in back out?

**Comment by madig** [comment]
Subsetting to the glyph list present before the merge brings static master size back down roughly were it was, ditto for the VF. The lookup organization stays, but the class table has less entries.

**Comment by chrissimpkins** [comment]
> Subsetting to the glyph list present before the merge brings static master size back down roughly were it was, ditto for the VF. The lookup organization stays, but the class table has less entries.

This is good to hear.  Ty!

**Comment by chrissimpkins** [comment]
This will be implemented as of v5.000
