### ISSUE TITLE
Merge Gurmukhi script

### ISSUE THREAD

**Issue by kalapi** [googlefonts/googlesans#293]
Hello @madig, @belluzj, and @chrissimpkins,

Here are the sources for the Gurmukhi. 

Please let me know if you have any question. 

Best,
Kalapi

[GoogleSans_Gurmukhi_R01.zip](https://github.com/googlefonts/googlesans/files/6322249/GoogleSans_Gurmukhi_R01.zip)

**Comment by belluzj** [comment]
Thanks Kalapi, Nikolaus will have a look at the sources later today, and @jonpinhorn will be merging the feature code starting Monday.

**Comment by madig** [comment]
Can't merge this because `danda-deva` is in a group already in Deva but is put in a different group here 🤔 

If you need to access Deva stuff, maybe put Gurmukhi into your Deva files?

**Comment by kalapi** [comment]
Hi @madig,

Looking at this now. Adding the Gurmukhi to Devanagari might be very messy. There are two possible minimally invasive directions:

1. I change the kerning class name to the same as the Devanagari.
2. Suffix `danda-deva` and `dbldanda-deva` with `.loclGURM` and add it to the `locl` feature?

**Comment by madig** [comment]
Hm, strategy 1 might be best if the glyphs in question really are the same thing and should kern the same? If they are actually `.loclGURM` variants, they could still use the same group name if they should kern the same.

**Comment by kalapi** [comment]
The glyphs are different, so `1` is not possible. There is no kerning associated with them, should I just remove the group name?

**Comment by madig** [comment]
Yes. Kerning groups only make sense if they are actually used in kerning :)

**Comment by madig** [comment]
Removing dead kerning groups manually.

But oh no! There's a `semicolon.loclGURM.BRACKET.18`. Please don't reintroduce bracket layers. Can you do semicolons without them?

**Comment by kalapi** [comment]
~Sorry, that shouldn't be in there. Which master (upright or italic)?~

Nevermind, got it and removed!

**Comment by madig** [comment]
Also, the dottedCircle seems to be different from the Deva one, different anchors etc. Gonna revert that.

**Comment by madig** [comment]
The italic has an outline-incompatible 'four-gurmukhi'.

**Comment by kalapi** [comment]
@madig Here's the updated package:

[GoogleSans_Gurmukhi_R02.zip](https://github.com/googlefonts/googlesans/files/6335746/GoogleSans_Gurmukhi_R02.zip)

**Comment by madig** [comment]
Thanks. Do you really want to overwrite dottedCircle from Deva with the new one here?

**Comment by kalapi** [comment]
Nope. I find that it may be really difficult to have 1 dotted circle represent all marks across all scripts. For now we can keep the one from Deva.

**Comment by kalapi** [comment]
Additionally there is a 'disabled' `locl` feature in there which will have to be re-enabled when the `gurmukhi.fea` is being created. It may be as simple as uncommenting the code.

**Comment by jonpinhorn** [comment]
Hi @kalapi, 

From what I can see with your web tester document everything seems to be working as expected after the merge. The only thing I'd point to is the anchoring on the addak bindi (mark to mark) isn't composing well on both Italic styles compared to Upright. It looks like the bindi sits much too low.

Great stuff, as always.

![image](https://user-images.githubusercontent.com/8477580/115551620-3c4d4d00-a2a3-11eb-853e-37e106e78158.png)
![image](https://user-images.githubusercontent.com/8477580/115551666-4e2ef000-a2a3-11eb-9e49-57e96a139237.png)

**Comment by kalapi** [comment]
Thanks @jonpinhorn, will look into this right away!

**Comment by kalapi** [comment]
Hello @jonpinhorn & @madig,

Please find the latest sources attached. I've fixed a few other minor issues with anchors but they shouldn't cause trouble. 

Let me know if you have any questions. :)

[GoogleSans_Gurmukhi_R03.zip](https://github.com/googlefonts/googlesans/files/6351945/GoogleSans_Gurmukhi_R03.zip)

**Comment by madig** [comment]
Thanks, I did a fresh import over at #295. Can you please also provide us with a suite of shaping regression tests like for Deva?

**Comment by kalapi** [comment]
Hi @madig they're in `docs>qa>shaping_input`

**Comment by madig** [comment]
Oh didn't see those. Thanks 😬

**Comment by chrissimpkins** [comment]
Merged in https://github.com/googlefonts/googlesans/pull/295
