### ISSUE TITLE
Remove unused kerning groups

### ISSUE THREAD

**Issue by madig** [googlefonts/googlesans#294]
```python
from pathlib import Path
from ufoLib2 import Font

for p in Path("source/GoogleSans").glob("*.ufo"):
    print(p)
    u = Font.open(p)
    used = set()
    for f,s in u.kerning:
        used.add(f)
        used.add(s)
    for n in list(u.groups):
        if n not in used:
            del u.groups[n]
    u.save()
```

Maybe even make this part of the merge script 🤔

**Comment by chrissimpkins** [comment]
This is cleanup.  Per Nikolaus we can add this to the normalizer.

**Comment by chrissimpkins** [comment]
The kerning group cleanup will be merged in https://github.com/googlefonts/googlesans/pull/317

**Comment by chrissimpkins** [comment]
The kerning group cleanup source will be added to the normalize.py source which runs on new script imports in PR #317
