### ISSUE TITLE
Review kerning `a` - `l` 

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans#30]
A team reported that they feel that the spacing between `a` (U+0061) and `l` (U+006C) is too narrow in Google Sans (production version).

Examples:

<img width="190" alt="kerning-a-l" src="https://user-images.githubusercontent.com/4249591/63820294-a4089480-c916-11e9-8503-80ef09e91140.png">

<img width="89" alt="1nlkq-image" src="https://user-images.githubusercontent.com/4249591/63820300-a66aee80-c916-11e9-82ec-1f66c33ef236.png">

---

Transferred from https://github.com/Colophon-Foundry/google-sans/issues/109

**Comment by chrissimpkins** [comment]
@Colophon-Foundry Will you please review this issue and let me know if you feel that we are ok to close it?  IIRC we discussed this and you did not feel that there is a problem here.

**Comment by Colophon-Foundry** [comment]
Yeah I'm happy that there's not an issue and it feels right to me

**Comment by chrissimpkins** [comment]
Thanks Edd!
