### ISSUE TITLE
Getting an accurate per mil stem value in GS

### ISSUE THREAD

**Issue by dberlow** [googlefonts/googlesans#302]
In the Google Sans pixel and watch projects, there was no XOPQ created, as the opsz and wght came as instances from the original design. 

With the implementation and assignment of os/2 wght values to wght and GRAD, having XOPQ values for composition would be as useful as in the Amstelvar and Roboto Flex projects. I.e, knowing what the stem value is in 1/1000.

So setting up a faux XOPQ could work like this; create masters for every Extreme location in the design space, I.e the wght and wdth max and min, the grade max and min and the size max and min, and all their combinations, with only the “H” stem adjusted to the value of H’s stem at each master. 

We then have the max and min values for XOPQ, can define the axis and build a font that hides the axis or we can delete it after we run parama-roundup. If we leave it, the H will change, but if we then apply the change to a version of the glyph outside of Unicode, train parama-roundup on its point index instead of the “H”, no one will find it, the axis will show an accurate XOPQ, and practically no space will be taken up in the file.

**Comment by chrissimpkins** [comment]
Trying to understand these comments David.  Possible to sketch up as visuals?  I don't follow what you are planning here.

**Comment by davelab6** [comment]
I'm confused why you'd want to create new XOPQ masters. Why not parama-roundup the H stems of the existing masters?

**Comment by chrissimpkins** [comment]
@dberlow Please weigh in on what actions need to be taken here when you have a chance.  Thanks!

**Comment by dberlow** [comment]
Never mind, thanks. Time for these things is gone.
