### ISSUE TITLE
stray off-curve points

### ISSUE THREAD

**Issue by dberlow** [googlefonts/googlesans#305]
opsz18-wght400-GRAD-50-XTRA0 has two points that are not properly located, and though currently have no effect on shape, could cause issues unless updated.

<img width="769" alt="Screen Shot 2021-05-30 at 4 44 59 PM" src="https://user-images.githubusercontent.com/1956494/120119559-64638200-c166-11eb-821c-1dab31683023.png">

**Comment by chrissimpkins** [comment]
These are the teal colored points in the image and they should be removed?

**Comment by chrissimpkins** [comment]
@dberlow David, we can take an update with a fix for this issue anytime. Please let me know how you would like to approach this.

**Comment by dberlow** [comment]
This is fixed and committed… in the watch version. I’ll check the rest.

**Comment by chrissimpkins** [comment]
> This is fixed and committed… in the watch version. I’ll check the rest.

Thanks David! This only affects the opsz18-wght400-GRAD-50 master? Please let us know when you complete the review and what we need to merge here

**Comment by dberlow** [comment]
Fixed all of Pixel version and committed.

**Comment by chrissimpkins** [comment]
Commit where this was addressed https://github.com/googlefonts/GoogleSans-fb/commit/13b24fcc7746bf3ad3a284b4c06792a9a6c2c521

**Comment by chrissimpkins** [comment]
@madig I can confirm that https://github.com/googlefonts/GoogleSans-fb/commit/13b24fcc7746bf3ad3a284b4c06792a9a6c2c521 is where David addressed this issue but I need to check on what happens after the updates that he pushed to address the #311 blocker.  `2` numr forms appear to be edited in this commit.  Tracking this down and will try to summarize what needs to be imported to address both issues.

**Comment by chrissimpkins** [comment]
Also to prevent confusion, by "Pixel version" he means the source in this repository (googlefonts/googlesans).

**Comment by chrissimpkins** [comment]
Addressed in https://github.com/googlefonts/googlesans/pull/326

This will be released in v5.000
