### ISSUE TITLE
Some Armenian glyphs have proprietary #anchors

### ISSUE THREAD

**Issue by madig** [googlefonts/googlesans#308]
Vo-arm and vew-arm.sc specifically have `#exit`, which is a Glyphs.app-specific way of marking component attachment points. Needs a review to see if the pipeline does the right thing.

**Comment by anthrotype** [comment]
https://github.com/googlefonts/ufo2ft/pull/476

**Comment by gorjious** [comment]
Oh no. These should have been removed. I must have missed it being overlayed on a node. My apologizes. 
There shouldn't be any `#exit` or `#entry` anchors. The only glyphs that should have an anchor are the following, and it should only be a `top` anchor.

Ayb-arm
Vo-arm
Et-arm
Ini-arm
Yiwn-arm
Ech-arm
Eh-arm
Oh-arm

ayb-arm.sc
vo-arm.sc
et-arm.sc
ini-arm.sc
yiwn-arm.sc
ech-arm.sc
eh-arm.sc
oh-arm.sc

ayb-arm
vo-arm
et-arm
ini-arm
yiwn-arm
ech-arm
eh-arm
oh-arm
ech_yiwn-arm

**Comment by chrissimpkins** [comment]
@madig Simple to automate removal of the `#` anchors in our production UFO sources? 

@gorjious how widely implemented are these anchors across the Armenian glyph set?   Mind pasting a string that includes a combination of glyph forms that we can use to test changes?

**Comment by gorjious** [comment]
Looks like it is only `Vo-arm` and `vew-arm.sc` glyphs that have the `#exit` anchors. They are leftover from decomposing a component. They can simply be deleted from those two glyphs and it will have no effect on any other glyphs or features. No need for testing.

**Comment by madig** [comment]
> Simple to automate removal of the # anchors in our production UFO sources?

Yes.

**Comment by chrissimpkins** [comment]
> > Simple to automate removal of the # anchors in our production UFO sources?
> 
> Yes.

Ty, let's do it.
