### ISSUE TITLE
Remove unused [18] glyph outlines

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans#312]
These are still around after our transition away from rvrn forms.  Let's remove them from all masters.

https://github.com/googlefonts/googlesans/pull/310#issuecomment-856847216

**Comment by chrissimpkins** [comment]
I am reconsidering this suggestion. I wonder if we want to either keep them as unexported glyphs or create a detailed list of where the rvrn existed and changes were made to work around the issue in case we ever have to revisit the opsz interpolation issue.  e.g., opsz becomes a wider axis that requires interpolated forms. We'll need to know what glyphs are involved.

**Comment by madig** [comment]
We can keep them as unexported glyphs.
