### ISSUE TITLE
Disable outline check on CI

### ISSUE THREAD

**Issue by madig** [googlefonts/googlesans#316]
https://github.com/googlefonts/googlesans/pull/315

Figure out where an outline check would be most useful and hook it in there.

**Comment by belluzj** [comment]
Nikolaus suggests that these outlines checks are best done in the font editor, outside of CI. Nowadays there's Behdad's PDF report of kinks, which could be done in the CI, but really should be used by designers throughout the design process?

**Comment by belluzj** [comment]
Make sure this check is inactive in the CI. Marianna already reviews the PDF at the release stage.

**Comment by belluzj** [comment]
This check is currently active in the CI, as per the screenshot below. I will open a PR to disable it.

![image](https://github.com/googlefonts/googlesans/assets/3616772/4630907d-87a4-4ed1-81ed-f659c52b17ee)

**Comment by MariannaPaszkowska** [comment]
indeed, it's best if the interpolation checks happen only on merge to main and release. @belluzj 
this is low priority for GS

**Comment by RickyDaMa** [comment]
> it's best if the interpolation checks happen only on merge to main and release

I've updated #633 with this behaviour, as the previous PR was outdated (not supporting the latest Fontbakery version)
