### ISSUE TITLE
Latin: Add single story 'a' via stylistic set

### ISSUE THREAD

**Issue by davelab6** [googlefonts/googlesans#318]
A UXR study yielded this quote, 

> We are finding Roboto difficult to read for the users that we co-design with in the cognitive accessibility space (individuals with reading and developmental disabilities). We are continually asked to re-do our materials with fonts that use the a without the hook, and I'm now defaulting to Poppins in materials we need to share with collaborators with lived experience. — P005, UXD, Research

That suggests to me that Roboto, GS and Noto Sans and Serif should offer single story 'a' and 'g' via stylistic set. Possibly that could be a component of the Greek `α` (0x03B1, Greek Small Letter Alpha Unicode Character).

**Comment by chrissimpkins** [comment]
We have a default single story `g` and the single story `a` is there, but we just removed support via `aalt` as of v4.000 IIRC.  I don't believe that the single story `a` is set as an exporting glyph at this stage.  This was part of the attempt to eliminate UX designer-driven decisions about what forms define the brand.  This was a decision by Damien and Jonathan to move away from any stylistic alternate designs.  

In light of that info, let me know if you'd still like to proceed with adding access to stylistic alternates back to the set.

**Comment by davelab6** [comment]
Adding back just the a and it's accents sgtm

**Comment by chrissimpkins** [comment]
Added to v6 update!

**Comment by chrissimpkins** [comment]
The following glyphs will be included:


- a.alt 
- aacute.alt 
- abreve.alt 
- abreveacute.alt 
- abrevedotbelow.alt 
- abrevegrave.alt 
- abrevehookabove.alt 
- abrevetilde.alt 
- acircumflex.alt 
- acircumflexacute.alt 
- acircumflexdotbelow.alt 
- acircumflexgrave.alt 
- acircumflexhookabove.alt 
- acircumflextilde.alt 
- adieresis.alt 
- adotbelow.alt 
- agrave.alt 
- ahookabove.alt 
- amacron.alt 
- aogonek.alt 
- aring.alt 
- aringacute.alt 
- atilde.alt 
- ae.alt 
- aeacute.alt 

These will need to be removed from the non-export lists and require new stylistic set feature support.

Test string:

```
aáăắặằẳẵâấậầẩẫäạàảāąåǻãæǽ
```

**Comment by chrissimpkins** [comment]
#318

**Comment by chrissimpkins** [comment]
This will be implemented in a new ss08 feature.  

We will also need to add these forms to the smcp feature subs.

**Comment by chrissimpkins** [comment]
> This will be implemented in a new ss08 feature.
> 
> We will also need to add these forms to the smcp feature subs.

and `a.alt` to the `ordn` feature

**Comment by chrissimpkins** [comment]
@davelab6 Files with single story `a` support are available in https://github.com/googlefonts/googlesans/suites/3333381250/artifacts/78171587 if you'd like to have a look.  Added to ss08  and includes smcp + ordn fea support.

Test string:

```
aáăắặằẳẵâấậầẩẫäạàảāąåǻãæǽ
```

**Comment by chrissimpkins** [comment]
Added in #360.  Will be released in v6.000

**Comment by chrissimpkins** [comment]
@davelab6 This will be released in v6.000 later today. Is there someone on the UXD Research team who would be interested to have a look?
