### ISSUE TITLE
Berlow source updates for GS/GST v5.000

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans#322]
### Figure 2 off curve points

**Note** use a commit at or after that mentioned in the `numr/dnom/circled figs` fix section to import the changes here.  See note below.

https://github.com/googlefonts/googlesans/issues/305

Pushed to googlefonts/GoogleSans-fb repo at commit https://github.com/googlefonts/GoogleSans-fb/commit/13b24fcc7746bf3ad3a284b4c06792a9a6c2c521

Requires import of:

- `two.ss03`
- `two.cap`
- `two`
- `two.sc`
- `two.tf`
- `two.sansSerifBlackCircled`
- `two.numerator`

The changes appear to differ across masters in that commit and it looks like not every master will have an update for all of the above fig forms.

### numr/dnom/circled figs grade fix

**Note** this commit should be considered the current source of truth for any `two` forms that are edited to address the issue above.  We should import at or after the commit in this section to address both figure issues.  I think that the `two.numerator` form changed here relative to the edits that were made above.

https://github.com/googlefonts/googlesans/issues/269
Open PR: https://github.com/googlefonts/googlesans/pull/311

All fixes in place in googlefonts/GoogleSans-fb repository as of commit https://github.com/googlefonts/GoogleSans-fb/commit/8db5f0c335af6aa721fc93b4f60d441a57d67a79

This addresses the grade in the circled figure forms and the side effects that occurred in the numr/dnom forms.  

Requires import of:

- all `one-nine.sansSerifBlackCircled` fig outlines across masters
- all `one-nine.sansSerifCircled` fig outlines across masters
- all `zero-nine.numerator` fig outlines across masters
- `SansSerifCircle` outline across masters

cc @madig I'll confirm these changes with David later today and then we will be ready to import the edits.  I'll continue to update this thread with any other work that he has done to address scheduled v5 changes.

**Comment by chrissimpkins** [comment]
Confirmed all info above with D Berlow.  @madig green light on these imports

**Comment by madig** [comment]
No circled zero glyphs and no two.ss03 in Italic. Importing the rest in a new PR.

**Comment by chrissimpkins** [comment]
> No circled zero glyphs and no two.ss03 in Italic. Importing the rest in a new PR.

Apologies! Yes this is correct.
