### ISSUE TITLE
Polytonic upper case Greek accented spacing updates

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans#323]
From Irene Vlachou

Pushed in commit 1f5788c106b6e0c229b7e772547ce0ae64355b6d

**Comment by irenevlachou** [comment]
latest update bc1e99398928151857eeb3cec908a85f2342cd42

Composed glyphs:
dasia.case tonos.sc psili.sc varia.sc dasia.sc

Update of left side-bearing in accents UC GRK (no changes in kerning):
Alphatonos Epsilontonos Etatonos Iotatonos Omicrontonos Upsilontonos Omegatonos Alphapsili Alphadasia Alphapsilivaria Alphadasiavaria Alphapsilioxia Alphadasiaoxia Alphapsiliperispomeni Alphadasiaperispomeni Alphavaria Alphaoxia Alphapsiliprosgegrammeni Alphadasiaprosgegrammeni Alphapsilivariaprosgegrammeni Alphadasiavariaprosgegrammeni Alphapsilioxiaprosgegrammeni Alphadasiaoxiaprosgegrammeni Alphapsiliperispomeniprosgegrammeni Alphadasiaperispomeniprosgegrammeni Epsilonpsili Epsilondasia Epsilonpsilivaria Epsilondasiavaria Epsilonpsilioxia Epsilondasiaoxia Epsilonvaria Epsilonoxia Etapsili Etadasia Etapsilivaria Etadasiavaria Etapsilioxia Etadasiaoxia Etapsiliperispomeni Etadasiaperispomeni Etavaria Etaoxia Etaprosgegrammeni Etapsiliprosgegrammeni Etadasiaprosgegrammeni Etapsilivariaprosgegrammeni Etadasiavariaprosgegrammeni Etapsilioxiaprosgegrammeni Etadasiaoxiaprosgegrammeni Etapsiliperispomeniprosgegrammeni Etadasiaperispomeniprosgegrammeni Iotapsili Iotadasia Iotapsilivaria Iotadasiavaria Iotapsilioxia Iotadasiaoxia Iotapsiliperispomeni Iotadasiaperispomeni Iotavaria Iotaoxia Omicronpsili Omicrondasia Omicronpsilivaria Omicrondasiavaria Omicronpsilioxia Omicrondasiaoxia Omicronvaria Omicronoxia Rhodasia Upsilondasia Upsilondasiavaria Upsilondasiaoxia Upsilondasiaperispomeni Upsilonvaria Upsilonoxia Omegapsili Omegadasia Omegapsilivaria Omegadasiavaria Omegapsilioxia Omegadasiaoxia Omegapsiliperispomeni Omegadasiaperispomeni Omegavaria Omegaoxia Omegapsiliprosgegrammeni Omegadasiaprosgegrammeni Omegapsilivariaprosgegrammeni Omegadasiavariaprosgegrammeni Omegapsilioxiaprosgegrammeni Omegadasiaoxiaprosgegrammeni Omegapsiliperispomeniprosgegrammeni Omegadasiaperispomeniprosgegrammeni Alphapsiliprosgegrammeni.ad Alphadasiaprosgegrammeni.ad Alphapsilivariaprosgegrammeni.ad Alphadasiavariaprosgegrammeni.ad Alphapsilioxiaprosgegrammeni.ad Alphadasiaoxiaprosgegrammeni.ad Alphapsiliperispomeniprosgegrammeni.ad Alphadasiaperispomeniprosgegrammeni.ad Etapsiliprosgegrammeni.ad Etadasiaprosgegrammeni.ad Etapsilivariaprosgegrammeni.ad Etadasiavariaprosgegrammeni.ad Etapsilioxiaprosgegrammeni.ad Etadasiaoxiaprosgegrammeni.ad Etapsiliperispomeniprosgegrammeni.ad Etadasiaperispomeniprosgegrammeni.ad Omegapsiliprosgegrammeni.ad Omegadasiaprosgegrammeni.ad Omegapsilivariaprosgegrammeni.ad Omegadasiavariaprosgegrammeni.ad Omegapsilioxiaprosgegrammeni.ad Omegadasiaoxiaprosgegrammeni.ad Omegapsiliperispomeniprosgegrammeni.ad Omegadasiaperispomeniprosgegrammeni.ad

**Comment by chrissimpkins** [comment]
Thanks Irene! We will have a look over the upcoming week and will be in touch with any questions.

**Comment by chrissimpkins** [comment]
Merged in #384. This will be released in GS/GST v6.000
