### ISSUE TITLE
Review Armenian calt punctuation centering feature code

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans#324]
Related: https://github.com/googlefonts/googlesans/pull/310#issuecomment-867914010

We may need to edit the contextual punctuation position change due to the issue identified in https://github.com/googlefonts/googlesans/pull/319#issuecomment-866192552

**Comment by madig** [comment]
@gorjious 

How bout

```
lookup armn_calt_shift_punctuation {
	# Shifting punctuation to lower x-height
	pos @armn_lowercase @armn_calt_punctuation_centered' <0 -16 0 0>;
	pos @armn_lowercase @armn_calt_punctuation_all @armn_calt_punctuation_centered' <0 -16 0 0>;
	pos @armn_lowercase @armn_calt_punctuation_all @armn_calt_punctuation_all @armn_calt_punctuation_centered' <0 -16 0 0>;

	pos @armn_calt_punctuation_centered' @armn_lowercase <0 -16 0 0>;
	pos @armn_calt_punctuation_centered' @armn_calt_punctuation_all @armn_lowercase <0 -16 0 0>;
	pos @armn_calt_punctuation_centered' @armn_calt_punctuation_all @armn_calt_punctuation_all @armn_lowercase <0 -16 0 0>;
} armn_calt_shift_punctuation;
```

0-2 back, 0-2 forth from a lowercase letter. Should cover your examples in https://github.com/googlefonts/googlesans/pull/310#issuecomment-870788504. Do you have examples for where you want `punct_center, punct_all, punct_all, lowercase_letter`?

It also means we still need to maintain two punctuation classes.

Georgian could use the same structure.
