### ISSUE TITLE
Missing y.BRACKET.18 wght=400, GRAD=-50 glyph causing error

### ISSUE THREAD

**Issue by dberlow** [googlefonts/googlesans#334]
Google Sans Text Regular GRAD -50

y.BRACKET.18

**Comment by madig** [comment]
Hm yeah. That one fell off somewhere.

@chrissimpkins what's the plan for glyphs in the skip export list again? I think we should take an opportunity some time to remove all redundant glyphs.

**Comment by chrissimpkins** [comment]
Thanks David.  How is this used? What is the error?

**Comment by chrissimpkins** [comment]
> Hm yeah. That one fell off somewhere.
> 
> @chrissimpkins what's the plan for glyphs in the skip export list again? I think we should take an opportunity some time to remove all redundant glyphs.

https://github.com/googlefonts/googlesans/issues/312#issuecomment-866178189

**Comment by chrissimpkins** [comment]
@dberlow Will you please let us know what error happens here?  I don't know how to reproduce and troubleshoot this issue.
