### ISSUE TITLE
Devanagari locl feature support for punctutation

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans#336]
From https://github.com/googlefonts/googlesans/issues/304#issuecomment-851984728

Also, the following glyphs are unreachable (no Unicode value, no sub in features, not used as components):

    asterisk.loclDEVA
    braceleft.loclDEVA
    braceright.loclDEVA
    bracketleft.loclDEVA
    bracketright.loclDEVA
    colon.loclDEVA
    comma.loclDEVA
    ellipsis.loclDEVA
    exclam.loclDEVA
    parenleft.loclDEVA
    parenright.loclDEVA
    period.loclDEVA
    question.loclDEVA
    quotedblleft.loclDEVA
    quotedblright.loclDEVA
    quoteleft.loclDEVA
    quoteright.loclDEVA
    rh-deva
    semicolon.loclDEVA
    v-deva.alt5
    yy-deva.alt4

**Comment by kalapi** [comment]
Hi Chris, 

I see that the Devanagari pull request is closed, on which branch/pull request should I add the OT layout code?

**Comment by chrissimpkins** [comment]
Feel free to paste the required fea code into this thread or open a new PR based on the production sources in the main branch.

**Comment by chrissimpkins** [comment]
The Devanagari fea file is here: https://github.com/googlefonts/googlesans/blob/main/source/GoogleSans/devanagari.fea

**Comment by chrissimpkins** [comment]
Will be closed by https://github.com/googlefonts/googlesans/pull/337

**Comment by chrissimpkins** [comment]
@kalapi are the `rh-deva`, `v-deva.alt5`, and `yy-deva.alt4` something that need to be addressed in the current PR?

**Comment by kalapi** [comment]
@chrissimpkins I was going to address this after the fonts compiled 😅 . We'll address the remaining glyphs in the next build. I want to make sure we've addressed their usage properly.

**Comment by chrissimpkins** [comment]
Compiling fonts locally to update glyphsetdef and shaping files.  Should be able to push shortly for the full CI check.

**Comment by chrissimpkins** [comment]
The localized ellipsis forms appear to change three dot spacing in the opposite direction over the optical size 17 <--> 18 transition across Roman and Italic sources.
