### ISSUE TITLE
Review new S Asian layout features + Fonts API pipeline subsetter

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans#341]
There is a second pass subsetter defined in the internal Fonts API pipeline (first pass subset occurs in the builds here).  We'll need to review the new layout features that were added with the Devanagari and Gurmukhi merges to confirm that these make it through this second subsetter stage before they are pushed as web fonts in the Fonts API.

Defined for the var font files in https://github.com/googlefonts/googlesans/blob/3e7ed3abe3ae1143497c35010847f434870a5d48/qa/check-fea.py#L145-L240

cc @nyshadhr9 @davelab6 @rsheeter @kalapi

**Comment by davelab6** [comment]
FontTools subset module has indic shaper features listed here, which won't be dropped in the 2nd pass

https://github.com/fonttools/fonttools/blob/main/Lib/fontTools/subset/__init__.py#L2527-L2529

**Comment by rsheeter** [comment]
This seems like it could be tested directly by sandboxing the fonts with the new features (or examining an existing font that has them), getting font urls from the css api, and then checking if the fonts hve the features in question.

**Comment by chrissimpkins** [comment]
Reviewed the new features with Nyshadh today.  It looks like the `hist` feature may be the only new feature that is dropped by default.  We will add this to the exclude list in the METADATA.pb file and test this by pushing to sandbox following the release push on Friday.  Nyshadh will be able to move these through the sandbox pipeline for this testing.  We can release a patch update if we come across anything else that is missing.

**Comment by chrissimpkins** [comment]
@kalapi In case you ever need it, the fea list that Dave [linked above ](https://github.com/googlefonts/googlesans/issues/341#issuecomment-877428030)

https://github.com/fonttools/fonttools/blob/aae11e45c29f4d07770574ce8577e6e61bc2b15c/Lib/fontTools/subset/__init__.py#L2527-L2529

includes the set of S Asian-specific features that the fontTools subsetter *keeps in the fonts* by default.

**Comment by chrissimpkins** [comment]
The first pass subsetter in our GH Actions **explicitly preserves all layout features**.  

https://github.com/googlefonts/googlesans/blob/fe094ae7671210f7210c47222ad72b406b10d2aa/scripts/gs-subset.py#L50

There are no changes required in the first pass subset config.

**Comment by chrissimpkins** [comment]
> Reviewed the new features with Nyshadh today. It looks like the `hist` feature may be the only new feature that is dropped by default. We will add this to the exclude list in the METADATA.pb file and test this by pushing to sandbox following the release push on Friday. Nyshadh will be able to move these through the sandbox pipeline for this testing. We can release a patch update if we come across anything else that is missing.

https://github.com/googlefonts/googlesans/pull/348
https://github.com/googlefonts/googlesans/pull/349

**Comment by chrissimpkins** [comment]
D/W Nyshadh following our v5 push last Friday.  He will notify me when the files are available in the sandbox API so that we can confirm that all of the new layout features make it through the full Fonts API pipeline.

**Comment by chrissimpkins** [comment]
Nyshadh pushed the files to the sandbox API this week.  ~~The new `hist` fea appears to be missing on my first run through the files.  We'll investigate further~~

Edit: my error, this is present in the script where it is required.
