### ISSUE TITLE
Move opsz=18 figures to cap height

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans#344]
This will address the FreeType autohinter associated figure top alignment bug noted in https://github.com/googlefonts/googlesans/issues/31

I met with Werner Lemberg to discuss this issue. There does not appear to be a way to address it other than moving the figures up to cap height or modifying the way that the FT autohinter performs feature analysis.

Design change approved by @davelab6

**Comment by davelab6** [comment]
This is moving numerals already existing in a stylistic set to the default glyphs, and moving the default glyphs to a new stylistic set? If so, perhaps you could do it directly Chris?

**Comment by dberlow** [comment]
It was at my initial suggestion, this change was recommended. So, even if hints and not sense is the reason;), if Chris is busy, this would be a good "Final" FB GS V3 + GRAD deliverable?

The list of figures and other related glyphs with uppercase versions is below.
/zero.alt.cap /one.alt.cap /six.alt.cap /seven.alt.cap /nine.alt.cap /zero.cap /one.cap /two.cap /three.cap /four.cap /five.cap /six.cap /seven.cap /eight.cap /nine.cap /bullet.cap /numbersign.cap /baht.cap /cent.cap /currency.cap /dollar.cap /dong.cap /euro.cap /franc.cap /hryvnia.cap /lira.cap /liraTurkish.cap /peso.cap /ruble.cap /rupeeIndian.cap /sterling.cap /tenge.cap /tugrik.cap /won.cap /yen.cap /percent.cap /pertenthousand.cap /perthousand.cap /at.cap /degree.cap /centigrade.cap /fahrenheit.cap /sheqel.cap /dram-arm.cap /lari.cap 

They look like this.
<img width="812" alt="Screen Shot 2021-07-10 at 7 13 25 AM" src="https://user-images.githubusercontent.com/1956494/125161100-6bf74d00-e14e-11eb-9c9b-f7b16db254ea.png">

There are also other glyphs with the ".cap"  extension I think we can leave out.
<img width="525" alt="Screen Shot 2021-07-10 at 7 14 32 AM" src="https://user-images.githubusercontent.com/1956494/125161154-b8428d00-e14e-11eb-942e-4909883d34cb.png">

And the other thing is what to suffix them with. ".short" and even ".shorter" already taken.

Phinney, Famira and Black discuss them here without naming them.
https://www.quora.com/Why-do-many-typeface-designs-employ-lining-numerals-that-are-shorter-than-their-capital-letters

 It could be that whoever decided on the figure sets of GS only read this, and nothing else.
Thomas:
"With OpenType formatting capabilities, it is even possible for a type designer to implement even more varieties of numbers all in the same font. Rarely done, but one can create:

default figures, slightly smaller than caps, different from the full-size lining figures invoked by actively formatting as lining
cap-sized lining figures invoked by all-caps formatting
small-cap height figures, turned on by small cap formatting
Not many type designers go quite this far, although it is sometimes tempting!"

Let us know, we're happy to do this.

**Comment by chrissimpkins** [comment]
Thanks David.  I'll speak with you about this in more detail.  I'm working through our planned changes for the v6 release and should have a better idea about timing soon.

**Comment by chrissimpkins** [comment]
I d/w David Berlow this week.  He does not feel that **outline/spacing** changes will be required to address this.  He is happy with the current cap height forms and recommends that we directly swap out the existing forms as the new Unicode encoded defaults.

**Comment by chrissimpkins** [comment]
Reviewed the cap height fig outlines in the opsz 18 masters today.  They have wider adv width metrics c/w the current sub-cap height defaults.  We are going to run into H metrics changes with a direct replacement.  Will require review.

**Comment by chrissimpkins** [comment]
> Reviewed the cap height fig outlines in the opsz 18 masters today. They have wider adv width metrics c/w the current sub-cap height defaults. We are going to run into H metrics changes with a direct replacement. Will require review.

ping @belluzj as our default opsz18 master fig height changes planned this quarter may affect the spacing/kerning work that your design team is doing

**Comment by madig** [comment]
He'll be back next week.

**Comment by chrissimpkins** [comment]
> He'll be back next week.

Thanks Nikolaus.  No urgency on this issue.  Just making sure that your team is aware.  I am not sure how we will approach this at the moment.  It is turning into a bigger issue than originally planned.

**Comment by chrissimpkins** [comment]
Here is the H metrics comparison between the default opsz 18 figs and the *.cap cap height forms.  The cap height outlines are more widely spaced.

![GS-cap-height-figs](https://user-images.githubusercontent.com/4249591/131141686-2075bec5-37c4-449d-a6e5-c8a595664ffc.png)

**Comment by dberlow** [comment]
I redrew the default's (GoogleSans-opsz18-wght380-GRAD0) default figures to cap height , maintaining their widths.
[GoogleSans-opsz18-wght380-GRAD0-FIGREDO.ufo.zip](https://github.com/googlefonts/googlesans/files/7073224/GoogleSans-opsz18-wght380-GRAD0-FIGREDO.ufo.zip)

There are issues illustrated in the picture below.
I examined the glyphs in the default with the ".cap" extension to the glyph name, that minus three dashes, is included in each sample. 
Top: the old default, I show the H and it's alignment.

Second: the old ".cap" versions.

Third: new defaults

Bottom: existing ".tf",  tabular versions which were of mixed height and should be corrected.

<img width="957" alt="Old, old cap,new, tf" src="https://user-images.githubusercontent.com/1956494/131265607-92b0a641-df34-4cc3-a6fd-1fbd349835fe.png">

There are 12 master styles (default and bold, GRAD min and max, regular and italic), affected, (11 more if this is right.)

There are also some component sharing issue that need to be straightened out. 
  1. like the "C" and "F" used with degree sign, can now reference "C" and "F", instead of special shortened ones.
  2. when a glyph, like "bullet"  is shifted to the new alignment, its use in composing other bullets needs editing.

We can talk next week.

**Comment by chrissimpkins** [comment]
cc @belluzj https://github.com/googlefonts/googlesans/issues/344#issuecomment-907876544 is the information from David that I mentioned to you.

**Comment by chrissimpkins** [comment]
@dberlow do you suggest that we re-draw all cap height fig forms across the opsz 18 masters?  The fig outlines are already cap height in all of the opsz 17 masters.  Are the new outlines in the opsz18-wght380-GRAD0 master compatible with the opsz 17 outlines or will those need to be revised as well?

And what are your thoughts about the new spacing?  Is it an improvement to keep the wider spacing with taller forms?

**Comment by chrissimpkins** [comment]
Re:

> There are also some component sharing issue that need to be straightened out.

Sg. Let's discuss this issue further.

**Comment by chrissimpkins** [comment]
Moving this to the GS v9.000 release at Fonts eng team request

**Comment by chrissimpkins** [comment]
D/W Evan and Nyshadh today. We will need to move this back to the Q4 2022 / v11.000 release.

**Comment by belluzj** [comment]
Closed by https://github.com/googlefonts/googlesans/pull/412
