### ISSUE TITLE
Use `public.openTypeCategories` to organize GDEF table

### ISSUE THREAD

**Issue by madig** [googlefonts/googlesans#346]
The per-master GDEF table definition in features.fea is, IIRC, the only real reason we currently have per-master feature files. With the updated pipeline, we can now store that information in a structured form in lib.plist and the compiler will pick it up. Much cleaner, and no need to run the normalizer to update the GDEF definition. Also, maybe correct ligature carets in statics because GDEF is filled in after interpolation?

**Comment by chrissimpkins** [comment]
> Also, maybe correct ligature carets in statics because GDEF is filled in after interpolation?

Have an example string that demos this issue?

**Comment by madig** [comment]
No, but in the statics, the non-default instances have their ligature carets (e.g. in `ffi`) at the default instance's position.

**Comment by chrissimpkins** [comment]
`ffi` and that info is what I need.  Ty

**Comment by madig** [comment]
Wrote a script: https://gitlab.gnome.org/GNOME/cantarell-fonts/-/blob/cd132c6164eeb9c189b9ec87d58f05ffb0fb8c58/scripts/update-gdef.py

**Comment by madig** [comment]
Just running this script on our sources results in different GDEF data, which is missing various glyphs like `zh-deva*`. Not sure what's going on, investigating tomorrow.

**Comment by madig** [comment]
Ugh. Will go ahead with Thai first and try to fiddle this into submission another time... I don't know why the output of the old code has more stuff in it than the new one...

**Comment by chrissimpkins** [comment]
No worries Nikolaus.  👍
