### ISSUE TITLE
GPOS file size optimizations 2

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans#351]
From @simoncozens:

> The idea is to use a custom mark feature writer than quantises anchors to the nearest 10 units. That allows more anchor tables to be shared.  I'm not quite sure what the right place for it is. It is a general purpose tool, but requires setting custom parameters. I'll make a ufo2ft PR in the first instance.

~~https://github.com/googlefonts/ufo2ft/pull/513~~
https://github.com/googlefonts/ufo2ft/pull/516

**Comment by chrissimpkins** [comment]
@simoncozens How do you define your new approach (https://github.com/googlefonts/ufo2ft/pull/516) in UFO sources so that these changes are used in a fontmake pipeline?

**Comment by simoncozens** [comment]
Put this in the top-level `<lib>` element of your designspace file:

```xml
      <key>com.github.googlei18n.ufo2ft.featureWriters</key>
      <array>
        <dict>
          <key>class</key>
          <string>MarkFeatureWriter</string>
          <key>options</key>
          <dict>
            <key>mode</key>
            <string>skip</string>
            <key>quantization</key>
            <integer>8</integer>
          </dict>
        </dict>
      </array>
```

**Comment by chrissimpkins** [comment]
#386

**Comment by chrissimpkins** [comment]
Will push these edits back to the v9.000 release per Fonts eng request

**Comment by khaledhosny** [comment]
FWIW, if file size really a concern, you can save ~40KB from each VF font by dropping glyph names (e.g. using version 3 post table).

**Comment by madig** [comment]
https://github.com/googlefonts/googlesans/issues/115

**Comment by khaledhosny** [comment]
> #115

Thanks, I missed that one.

**Comment by belluzj** [comment]
I'm reposting here a comment from Chris in the GSF engineering chat, replying to file size saving reports here: https://github.com/googlefonts/googlesans/pull/386#issuecomment-1768137624

> Thanks for the additional data on the potential max file size savings.  I think that we abandon this mark quant effort in favor of other higher priority areas.  I don't see that level of file size savings impacting decisions to land the family, and it is bound to make it more challenging to land because it pixel-level shifts marks.  Worth having a look at this in GS Flex, though.  We're much more open to change in GS Flex v2 and it would be interesting to understand if the impact happens to be greater for some reason there.

So this can be closed, but the same issue should be opened on GS Flex, right?
