### ISSUE TITLE
Add Telugu script support

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans#356]
The Telugu import will take place during Q3 2021 and we intend to release this work in the v6.000 build.

**Comment by chrissimpkins** [comment]
We will tentatively begin the merge work in late August.  Confirming dates with all teams involved.

**Comment by chrissimpkins** [comment]
Import will begin on Aug 27.  Universal Thirst confirmed that sources will be ready. DaMa team has required personnel lined up.

**Comment by chrissimpkins** [comment]
Date revised to begin on Sept 3.  Kalapi will submit a PR by the end of next week.

**Comment by chrissimpkins** [comment]
Moving to the v7.000 release.  The design team requires more time.  Working on a new import date.

**Comment by chrissimpkins** [comment]
New import start date is Oct 7.   Sources/metadata/docs will be available for import by that day.

**Comment by chrissimpkins** [comment]
Import was revised to Q1 2022 with release in v8.

I spoke with Kalapi today and he plans to have the sources in a PR by next week.

**Comment by chrissimpkins** [comment]
Moved to v9 release

**Comment by chrissimpkins** [comment]
@madig @belluzj Source delivery date confirmed as April 15.  We'll begin work on the contextual kerning issues at that stage.

cc @kalapi

**Comment by kalapi** [comment]
Hello @madig, @belluzj & @chrissimpkins,

Attaching the latest package of the Telugu herewith. 

There may be a few changes over the course of the next few days.

Please let me know if you have any questions.

[2022-04-18_GoogleSansTelugu_V1.000_BETA01.zip](https://github.com/googlefonts/googlesans/files/8506667/2022-04-18_GoogleSansTelugu_V1.000_BETA01.zip)

**Comment by madig** [comment]
Thanks. First import in #481, without the QA stuff. Even the reference fonts look broken across a span of the test HTML though? Our import looks even more broken (see below, longer strings = ours). What changes are you working on?

![telugu](https://user-images.githubusercontent.com/380829/164243290-abba398e-f256-419f-bfe3-f3647c4f4528.gif)

**Comment by kalapi** [comment]
Hi @madig,

Can you send me this strings and identify the cluster that seems broken to you in the reference fonts?

**Comment by madig** [comment]
Duh, wait, I was being stupid and forgot to compile the feature file.

**Comment by madig** [comment]
The string now matches, though it is hard to compare the whole of the web test to our fonts because vertical font metrics differ, so text shifts back and forth... Can you please ensure your fonts use the same vertical metrics as the upstream fonts?

**Comment by kalapi** [comment]
Hi @madig 

Here's an updated package

[2022-04-25_GoogleSansTelugu_V1.000_BETA02.zip](https://github.com/googlefonts/googlesans/files/8556775/2022-04-25_GoogleSansTelugu_V1.000_BETA02.zip)

**Comment by chrissimpkins** [comment]
Thanks Kalapi.  What changed?

**Comment by madig** [comment]
Ah, I see the per-master positioning now. I'll need to dig into how to swap feature code for the static instances.

**Comment by kalapi** [comment]
@madig It seems to work out-of-the-box in fontmake. I generated the test/reference binaries using fontmake.

**Comment by kalapi** [comment]
> Thanks Kalapi. What changed?

Hi @chrissimpkins A lot of minor mark positioning inconsistencies and updates to the vertical metrics.

**Comment by madig** [comment]
Did you test with just variable font generation or also statics?

**Comment by kalapi** [comment]
> Did you test with just variable font generation or also statics?

Both.

**Comment by madig** [comment]
Can you please give me some test strings that would exercise all the contextual positioning?

**Comment by kalapi** [comment]
> Can you please give me some test strings that would exercise all the contextual positioning?

Hi @madig, you can use the following string:

```త్క్ఝత ల్య్హల క్ఖ్హక ఠ్ల్హక క్ష్లక```

**Comment by madig** [comment]
Thanks. I suppose the intended effect is to go from 

![image](https://user-images.githubusercontent.com/380829/166222440-80ac177c-4aca-4b5e-878b-9cd8249b9e10.png)

to

![image](https://user-images.githubusercontent.com/380829/166222455-7151fdd2-6638-48f8-979f-f8f518ff7be6.png)

yes?

**Comment by madig** [comment]
Hrm. Having trouble making the shifting work in my import (I get what's in the first picture above). Trying to dig into what is going on.

Also, @kalapi, my import scripts declare dh-telugu, bh-telugu, ch-telugu and ddh-telugu bases. Is that correct? These are missing from your GDEF feature table.

**Comment by kalapi** [comment]
Hi @madig,

No harm in them being categorised as such, but they will never have any attachments. Those glyphs get replaced by alternates when in context with marks. 

Have a look at this string on FontGoggles `భ్ భ్ర్ భ్ఖ్ `. You can see in the image that the drop is shorter in the version with below marks. 

<img width="329" alt="Screenshot 2022-05-02 at 5 56 07 PM" src="https://user-images.githubusercontent.com/15804460/166299528-d2bf24da-514c-4d05-91b6-2c3449266849.png">

**Comment by madig** [comment]
Ok, I'll keep them that way then. Can confirm the text shapes as you show it.

Can you please tell me what else you're working on for Telugu and when you can deliver shaping test files?

**Comment by kalapi** [comment]
I'm not working on anything else. We're good to go for now :)

**Comment by madig** [comment]
Cool. Can you please create the usual set of regression test strings that test as much shaping functionaly as possible?

**Comment by kalapi** [comment]
Yes, i'm travelling today. I'll compile them and upload them ASAP.

**Comment by kalapi** [comment]
@madig @chrissimpkins 

- Adds minor changes (one line each) to the PSTS and HALN features
- Adds TOML regression tests

[2022-05-11_GoogleSansTelugu_V1.000_BETA03.zip](https://github.com/googlefonts/googlesans/files/8664588/2022-05-11_GoogleSansTelugu_V1.000_BETA03.zip)

**Comment by madig** [comment]
Thanks. I spy an unused `@TEL_allJaLigatures` group though?

**Comment by madig** [comment]
Also, I get the following warning:

> WARN The following spacing glyphs may be in the GDEF mark glyph class by mistake: uni0C3E (U+0C3E), uni0C41 (U+0C41), uni0C42 (U+0C42), uni0C43 (U+0C43), uni0C44 (U+0C44), uni0C4A (U+0C4A), uni0C4B (U+0C4B) and uni0C4C (U+0C4C) [code: spacing-mark-glyphs]

**Comment by madig** [comment]
Oh, also also: Does Telugu need another vertical metrics adjustment?

**Comment by kalapi** [comment]
@madig Sorry for the late response on this. 

- I'll check the OTL and GDEF items you've mentioned. 
- The sources have the VM matched to the Latin. I'm guessing that the win-values might need to be updated. I'll check this too.

**Comment by kalapi** [comment]
Hello @madig

Attaching an updated package here. The only thing updated is the removal of the `@TEL_allJaLigatures` group from the upright sources and reference fonts. 

The GDEF warning is a false positive. The respective glyphs are spacing-combining marks and need to be classified as Marks even though they don't have anchors. I've included base-mark ligatures for every possible combination and they will never be used but need to be there as they are the Unicode primitives. 

[2022-05-18_GoogleSansTelugu_V1.000_BETA04.zip](https://github.com/googlefonts/googlesans/files/8714742/2022-05-18_GoogleSansTelugu_V1.000_BETA04.zip)

**Comment by madig** [comment]
Thanks! Ok, good to know. I noticed your provided binary fonts don't contain the interpolated Medium, did you compile it and make sure it matches what you want to see?

**Comment by madig** [comment]
Oh also, we found that e.g. space and probably other shared glyphs like dottedCircle have different widths, have you made sure your design works with the upstream space width?

**Comment by kalapi** [comment]
Hey both these issues should be fine. In the case of the Space glyph the only difference is in the max-opsz bold (i.e. 226 instead of 236) this should be fine.

**Comment by madig** [comment]
Ok, though it does make comparing your fonts and our import a bit harder.

Our QA person has started to write up an internal doc report, but is not finished yet (more next week). Please request access from your preferred work account and have a look at the findings, primarily those where we found things both in your supplied fonts and our import. We'd like to get a clarification on your intent in these cases :)

**Comment by kalapi** [comment]
Where can I access your latest builds?

**Comment by madig** [comment]
Oops, sorry, you may need to request access.

**Comment by kalapi** [comment]
Hi @madig

Here's an updated package addressing some of the issues highlighted in the review document. 

[2022-05-24_GoogleSansTelugu_V1.000_BETA05.zip](https://github.com/googlefonts/googlesans/files/8762410/2022-05-24_GoogleSansTelugu_V1.000_BETA05.zip)

**Comment by chrissimpkins** [comment]
> Hi @madig
> 
> 
> 
> Here's an updated package addressing some of the issues highlighted in the review document. 
> 
> 
> 
> [2022-05-24_GoogleSansTelugu_V1.000_BETA05.zip](https://github.com/googlefonts/googlesans/files/8762410/2022-05-24_GoogleSansTelugu_V1.000_BETA05.zip)

@madig i spoke with Kalapi today and these changes should address the current round of design feedback

**Comment by madig** [comment]
Thanks. I think there are a few questions left for Kalapi, otherwise the review has concluded and the tester gave their green light :)

**Comment by kalapi** [comment]
Fixed the last remaining issues. Thanks @madig!

[2022-05-30_GoogleSansTelugu_V1.000_BETA06.zip](https://github.com/googlefonts/googlesans/files/8799659/2022-05-30_GoogleSansTelugu_V1.000_BETA06.zip)

**Comment by madig** [comment]
Thanks. Did you change any of the variable pos statements in the features? I have to wade through all of them to find out.

**Comment by kalapi** [comment]
Nope :)

**Comment by chrissimpkins** [comment]
Closed by #481
