### ISSUE TITLE
Import Tamil designs

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans#357]
The Tamil import will take place during Q3 2021 and we plan to release this expansion in GS v6.000.

**Comment by chrissimpkins** [comment]
We will tentatively begin the import in early/mid September.  Confirming dates with all teams involved.

**Comment by chrissimpkins** [comment]
Import will begin on Sept 3.  Universal Thirst confirmed that the sources will be ready.  DaMa team has personnel lined up for this script.

**Comment by chrissimpkins** [comment]
Date revised to begin on Aug 27.  We will swap the Tamil and Telugu imports.  Kalapi will submit a PR with the changes this week.

**Comment by kalapi** [comment]
Hello @belluzj & @madig!

Hope you're doing well. I'm still packaging the release. I estimate about an hour or two before I can send it over. Will attach it here once i'm done.

**Comment by kalapi** [comment]
Hi @madig,

Attaching the files below. Here are some notes:

1. Both sources contain commented OTL code & glyph-classes for the `locl` and `tnum` feature which will have to be uncommented at the time of building the `tamil.fea`
2. Both sources contain 'international' figures in proportional and tabular spacing resized to the Tamil design's proportions. This is because Tamil no longer uses it's own numerals (however, the Tamil numerals are included for the sake of Unicode completeness and Bureau of Indian Standards compliance). 
3. The international figures contain brace layers inherited from the original Latin design.

Please let me know if you have any questions and thank in advance!

P.S.: I will add another zip file containing the shaping web-tester for Jonny tomorrow. 

[GoogleSans_Tamil_R01.zip](https://github.com/googlefonts/googlesans/files/7068272/GoogleSans_Tamil_R01.zip)

**Comment by madig** [comment]
I tried to do a quick import before going on holidays (back on the 7th) and the script fails on brace layers. They seem to be below opsz<17? Are they intentional? If so, I need to invest some time into supporting brace layers.

**Comment by kalapi** [comment]
The brace layers are from the Latin numerals (implemented in 'one.loclTAML' in the upright and in 'one.loclTAML', 'six.loclTAML', and 'nine.loclTAML' in the italic) so they should already be implemented upstream in some form. But if it's too much work I'm fine with them being removed.

**Comment by chrissimpkins** [comment]
IIRC we removed all brace layers from the figures.

**Comment by belluzj** [comment]
Hello @kalapi! Thanks for the sources. We have started the Tamil import (Robert Pratley is QA'ing the merge this time) and we have 2 questions so far:
* Any news about the web tester?
* The import list contains glyphs that probably should not be imported from the Tamil, OK to not import them?
  - .notdef
  - NULL
  - CR
  - space
  - nbspace
  - zerowidthspace
  - zerowidthjoiner
  - zerowidthnonjoiner
  - dottedCircle

**Comment by chrissimpkins** [comment]
@belluzj I spoke with Gunnar today.  It is ok to skip the import of all of these glyphs. Thanks Jany.

**Comment by chrissimpkins** [comment]
@belluzj It looks like the CI fails on our glyph set / order check.  The definition files can be updated with https://github.com/googlefonts/googlesans/blob/main/scripts/gs-update-glyphset-qa-files.py on local builds of all static and VF format files at a commit where all glyph set changes are stable.

**Comment by belluzj** [comment]
Thanks, I did that and now it fails because of changes to the space glyph, I'll make sure to keep the previous version and push again.

**Comment by chrissimpkins** [comment]
Did Kalapi provide a glyph import list?  They probably included some of these glyphs for testing purposes.  We will only need to import the Tamil specific glyph set which is bound to be a subset of the overall glyph set in the source files.  With the exception of Armenian where we discussed a Latin glyph set change in advance, there have been no teams pushing changes to existing design work during the script import process.

**Comment by belluzj** [comment]
Yes he did provide a glyph import list, that's what I used and then noticed the changes to these glyphs. I just pushed a commit that reverts changes to these glyphs.

**Comment by chrissimpkins** [comment]
I see the glyph lists in his archive.  We can remove all of the control chars, non-localized space glyphs, etc. that already exist in the glyph set.  I think that this will be all non- `*-taml` and `*loclTAML` glyph names at the top of the file.

**Comment by madig** [comment]
For the other merges I just removed those glyphs because I assumed they were dev glyphs.

**Comment by chrissimpkins** [comment]
It is interesting that the space glyph changes the shaping metrics though.  Question to Kalapi in https://github.com/googlefonts/googlesans/pull/374#issuecomment-909317899 to see if we need a localized space for Tamil.

**Comment by belluzj** [comment]
Here is a first series of questions for @kalapi:

1. The Google Sans Tamil Text Medium otf from Kalapi is Italic:
![image1](https://user-images.githubusercontent.com/3616772/131546756-915885d5-4496-495d-99dc-df583f685a0c.png)

2. About not importing Kalapi's /dottedCircle: Dotted circle is used as a component in some glyphs, so the difference in vertical positioning between main and Kalapi's delivery will have an impact on the design of these unless we implement a negative component shift:

    - oMatra-tamil
    - ooMatra-tamil
    - auMatra-tamil

3. Fonts have been drawn with open corners exterior to the contour. This gets removed from the provided sources in the provided otf fonts, but retained in the ttf’s produced by the pipeline (ttf in outline, otf in fill): 

![image2](https://user-images.githubusercontent.com/3616772/131546860-8d098357-1b8e-463d-b0c6-7481a8fdeacc.png)

4. Anchors are not consistent across upright and italic in:
  
    - sa_iMatra-tamil
    - ha_iMatra-tamil
    - k_ssa_iMatra-tamil
    - ca_uMatra-tamil

5. NOT TAMIL: There are some floating points in all sources, occasionally in outlines, but more often in anchor coordinates

**Comment by kalapi** [comment]
Hi @belluzj,

> * Any news about the web tester?

I have been travelling for the last few days. I was hoping to do more on the trip but because of network access issues and family commitments I couldn't send this over. I will do so now in the next couple of hours. 

> * The import list contains glyphs that probably should not be imported from the Tamil, OK to not import them?
>   
>   * .notdef
>   * NULL
>   * CR
>   * space
>   * nbspace
>   * zerowidthspace
>   * zerowidthjoiner
>   * zerowidthnonjoiner
>   * dottedCircle

Yes, you can remove them.

**Comment by kalapi** [comment]
> 1. The Google Sans Tamil Text Medium otf from Kalapi is Italic:

 - Will fix this

> 2. About not importing Kalapi's /dottedCircle: Dotted circle is used as a component in some glyphs, so the difference in vertical positioning between main and Kalapi's delivery will have an impact on the design of these unless we implement a negative component shift:

 - Interesting! Didn't think about this. Should I decompose these glyphs? That may be the easiest route. 

> 3. Fonts have been drawn with open corners exterior to the contour. This gets removed from the provided sources in the provided otf fonts, but retained in the ttf’s produced by the pipeline (ttf in outline, otf in fill)

 - I'll run a `remove overlap` and re-send along with other changes. 

> 1. Anchors are not consistent across upright and italic in:

- These are superfluous, caused by decomposing components, will fix this too. 

@belluzj A question: Should I remove the control glyphs and update the glyph-list text files before sending you the fixed sources?

**Comment by kalapi** [comment]
- [x] Web-tester
- [x] Remove brace-layers from numerals
- [x] Italic medium
- [x] Superfluous anchors in `sa_iMatra-tamil`, `ha_iMatra-tamil`, `k_ssa_iMatra-tamil`, and `ca_uMatra-tamil`
- [x] Remove overlap for 'open' terminal glyphs. 
- [x] Import dottedCircle from latest sources
- [x] Remove control glyphs from import list

**Comment by belluzj** [comment]
Yes if you can remove the control glyphs from the import lists in your next archive that would be good. I did so already on my side (just deleted the first few lines) but for consistency let's not include them anymore from now on.

About the dotted circle, you could decompose but that would increase file size, instead you could copy-paste the dottedCircle outline from main into your font, and adjust the position of the component in your Tamil glyphs to look as intended using the outline from main. That would be the cleanest solution, without decomposing things needlessly.

Thanks in advance!

**Comment by kalapi** [comment]
@belluzj Attaching the updated sources here. All the issues reported have been fixed. I've also added the web-testing page in the `docs` folder. 

Please let me know if you have any questions

[GoogleSans_Tamil_R02.zip](https://github.com/googlefonts/googlesans/files/7092761/GoogleSans_Tamil_R02.zip)

**Comment by belluzj** [comment]
@kalapi This new zip doesn't contain source files? 
![image](https://user-images.githubusercontent.com/3616772/131709233-12f7338b-fab6-4b13-9936-9afe433ebdc3.png)

**Comment by kalapi** [comment]
Sorry, Don't know how that happened!

[GoogleSans_Tamil_R02.zip](https://github.com/googlefonts/googlesans/files/7093016/GoogleSans_Tamil_R02.zip)

**Comment by belluzj** [comment]
I imported the new sources in #374 and our designer will do another round of checks tomorrow. I noticed one thing just now: some components have been decomposed, is that on purpose? e.g.

https://github.com/googlefonts/googlesans/pull/374/commits/6826c2bca82681e9194b892ad20d3ca5e2f5be81#diff-01bee5c18fad8d8feaf329aaddbbd4869a264e9ee6fe7a32e5eb900de8c540b3L30

**Comment by kalapi** [comment]
Yes, this is on purpose, thanks!

**Comment by belluzj** [comment]
@kalapi Two more comments from our designer:
1. /one.loclTAML is not resized in the Bold Italic Text source - coming from provided sources 
![image14](https://user-images.githubusercontent.com/3616772/131844587-f472cb9c-718d-4574-918b-fcbdb2c18a85.png)

2. OPSZ 17 sources: /question.loclTAML design is different to /question and /question.loclDEVA: 
(shown below: /question, /question.loclDEVA, /question.loclTAML)
![image12](https://user-images.githubusercontent.com/3616772/131844611-209b8a75-824d-4d87-b9c0-56e3e2e512b9.png)

**Comment by belluzj** [comment]
Our designer also suggests that in feature code, we don't mention the `languagesystem tml2 TAM` language at all and register all the code under `tml2 dflt`, because we believe that the numbers and punctuation are not specific to the Tamil language but should be active whenever the script is used. This echoes the point that Ben Mitchell made in https://github.com/googlefonts/googlesans/pull/361#issuecomment-900580287

@kalapi Are you OK with us dropping references to TAM?

**Comment by kalapi** [comment]
@belluzj

1. Weird re. both 1 & 2, will fix these and resend.
2. Yes the TAM language tag can be removed. I'll remove this in `R03` too

**Comment by kalapi** [comment]
Fixed all three issues: 

[GoogleSans_Tamil_R03.zip](https://github.com/googlefonts/googlesans/files/7099897/GoogleSans_Tamil_R03.zip)

**Comment by belluzj** [comment]
#374 is ready for review

**Comment by chrissimpkins** [comment]
Closed by #374
