### ISSUE TITLE
Compliance with Bureau of Indian Standards (BIS) Devanagari script requirements

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans#359]
Additional Sanskrit glyphs required for [BIS compliance](http://htmlpreview.github.io/?https://github.com/googlei18n/noto-source/blob/main/test/BIS-Indic-ondevice-tests.html):

- U+0900 DEVANAGARI SIGN INVERTED CANDRABINDU
- U+0951 DEVANAGARI STRESS SIGN UDATTA
- U+0952 DEVANAGARI STRESS SIGN ANUDATTA
- U+0953 DEVANAGARI GRAVE ACCENT
- U+0954 DEVANAGARI ACUTE ACCENT

These glyphs will be added in GS/GST v6.000

@davelab6 @marekjez86

**Comment by chrissimpkins** [comment]
@kalapi Will we be receiving these changes during either the Telugu or Tamil import?

**Comment by chrissimpkins** [comment]
Confirmed with UT team that these changes will be available during Q3 for our v6 release.  Date TBD at this stage.

**Comment by kalapi** [comment]
Hi @chrissimpkins,

Attaching the latest Devanagari package with the 5 characters required by the BIS.

Please let me know if you have any questions. 

[GoogleSans_Devanagari_R04.zip](https://github.com/googlefonts/googlesans/files/7093559/GoogleSans_Devanagari_R04.zip)

**Comment by chrissimpkins** [comment]
Thanks Kalapi!

**Comment by chrissimpkins** [comment]
Glyph names for import:

```
invertedCandraBindu-deva
udatta-deva
anudatta-deva
grave-deva
acute-deva
```

**Comment by chrissimpkins** [comment]
Imported in #378
