### ISSUE TITLE
Consistent glyph naming guidance & updates

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans#368]
Thanks! So glyphs like `nikhahit_maiEk-thai` (listed under "additional glyphs" in https://github.com/googlefonts/googlesans/pull/361#issuecomment-889869092) are left named like that. Ideally they are named like `uni0E4D_uni0E48`.

@chrissimpkins this is currently handled inconsistently across scripts... not sure if we should retroactively change this, as e.g. Adobe apps may rely on old names when users embedded them into documents by accident...

_Originally posted by @madig in https://github.com/googlefonts/googlesans/issues/361#issuecomment-898557960_

**Comment by chrissimpkins** [comment]
> Adobe apps may rely on old names when users embedded them into documents by accident

@madig can you expand on what you consider a problem here?  I don't understand this comment

**Comment by madig** [comment]
Adobe apps can embed glyphs into documents by glyph name instead of Unicode text, so if you change them, documents will end up broken.

**Comment by chrissimpkins** [comment]
Got it.  What scripts are involved?

**Comment by madig** [comment]
Scan the qa/definitions files for glyph names with a `_`, those that aren't concatenations of AGLFN glyph names are affected.

**Comment by chrissimpkins** [comment]
OK, you indicated that this affected multiple scripts.   We can look into this in more detail if we don't understand the problem yet.

**Comment by madig** [comment]
I see -hb, -arm, -deva and now -thai :) Basically, ligatures need their own entry in each lib.plist's `public.postscriptNames`.
