### ISSUE TITLE
Italic Figures `6` and `9` opsz 17, GRAD -50 artifacts

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans#372]
@dberlow I came across this issue with the Italic `6` and `9` in views @ opsz 17, GRAD -50:

<img width="1628" alt="2021-08-25_16-34-58" src="https://user-images.githubusercontent.com/4249591/130861050-d0adf5cd-f588-4d1f-9488-1bbcbd3ffd69.png">

Mind having a look?

Builds @ https://github.com/googlefonts/googlesans/commit/0b66df686919630caca7909d39300fcc29bd0b7a in the archive below:

[GoogleSans-figure-tests.zip](https://github.com/googlefonts/googlesans/files/7049791/GoogleSans-figure-tests.zip)

**Comment by chrissimpkins** [comment]
Sources: https://github.com/googlefonts/googlesans/tree/main/source/GoogleSans

**Comment by chrissimpkins** [comment]
D/W David today. We will plan to fix this in the v6.000 release

**Comment by dberlow** [comment]
Enclosed fixed.

[GoogleSansItalic-opsz17-wght380-GRAD-50.ufo.zip](https://github.com/googlefonts/googlesans/files/7072239/GoogleSansItalic-opsz17-wght380-GRAD-50.ufo.zip)

**Comment by chrissimpkins** [comment]
Thanks David!

**Comment by chrissimpkins** [comment]
Merged David's updates in https://github.com/googlefonts/googlesans/pull/377

Visually confirmed the fix.  Thanks David!
