### ISSUE TITLE
Review GRAD -50 / GRAD +200 mark weights

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans#383]
Irene mentioned to me today that she identified some incorrect GRAD -50 / GRAD +200 mark weights while she was working on component updates in the Greek glyph set.  This included:

- dieresistonos
- semi-circle mark forms
- circumflex
- acute

We will need to review the mark designs to identify the full set of glyphs and masters involved.

**Comment by MariannaPaszkowska** [comment]
Note to self: Was it fixed here: https://github.com/googlefonts/googlesans/pull/597 ?

**Comment by belluzj** [comment]
@MariannaPaszkowska Eduardo also looked into this on the main branch and says that "most of them seem correct, the only issue I've found is in the upright dieresistonos in the 200 grad, which is indeed lighter."

Before investigating more and potentially fixing the odd one that is still lighter, Eduardo wants to clarify what is meant by "semi-circle mark forms", is it perispomeni, psili, breve?

Marianna, please let us know if we should fix the lighter one, and whether Eduardo should review more marks beyond those.

**Comment by MariannaPaszkowska** [comment]
@belluzj Many thanks for the review! Let's review all perispomeni, psili, and breve, and also, please let's fix that lighter upright dieresistonos in the 200 grad.
