### ISSUE TITLE
HarfBuzz 2.9.1 subsetter crashes on VF

### ISSUE THREAD

**Issue by madig** [googlefonts/googlesans#385]
Posting here because I don't want to post GS info to a public repo. @garretrieger I was told to ping you :)

1. Get Google Sans main, commit 8a2ba84db7508df70256ad8eb80ebbaa4ca30ba7
2. `fontmake --verbose WARNING -m googlesans/source/GoogleSans/GoogleSans.designspace -o variable`
3. `hb-subset.exe --glyphs="*" --layout-features="*" --drop-tables-="*" variable_ttf/GoogleSans-VF.ttf -o GoogleSans-VF-out.ttf`

> error: Operation failed. Probably a bug. File github issue.

**Comment by garretrieger** [comment]
I'll look into it.

**Comment by garretrieger** [comment]
Confirmed this is an offset overflow issue in the GPOS table. https://github.com/harfbuzz/harfbuzz/pull/3198 already partly addresses this. It cleans up most of the overflows, but there's still some left. I'll dig in further and see if I can make more improvements.

**Comment by garretrieger** [comment]
If given more rounds the repacker is able to arrive at a solution. The problem appears that there are a extremely high number of shared nodes which require duplicating. Currently the resolver will only do one duplication per round. I should be able to update the resolver to do multiple duplications per round.

**Comment by garretrieger** [comment]
Fixed version of the repacker is here: https://github.com/googlefonts/harfbuzz/tree/multi_duplicate

I'll PR that once harfbuzz/harfbuzz#3198 is merged.

**Comment by garretrieger** [comment]
This should now be fixed on harfbuzz head (specifically fixed by https://github.com/harfbuzz/harfbuzz/commit/efda2f14e104eedfee7da50ba2d22ba9a9ae376b)

**Comment by chrissimpkins** [comment]
Thank you very much for working on this Garret.  Much appreciated

**Comment by chrissimpkins** [comment]
@madig ok to close?

**Comment by madig** [comment]
Yes. I will retry once a new HarfBuzz lands.
