### ISSUE TITLE
Cap ht figures complete

### ISSUE THREAD

**Issue by dberlow** [googlefonts/googlesans#387]
sources committed, 
Documentation shared.

let me know if issues. 

Thanks.

**Comment by chrissimpkins** [comment]
Compiled source revision 2b2c9497bd7c51063edfd7b97d9d3a0c15e16fd0

I am seeing the following error:

```
fontmake: Error: In 'GoogleSans/GoogleSans.designspace': Generating fonts from Designspace failed:

Couldn't merge the fonts, because some values were different, but should have
been the same. This happened while performing the following operation:
GSUB.table.LookupList.Lookup[13][0].LookAheadCoverage[0].glyphs[0]

The problem is likely to be in Google Sans Regular GRAD-50 Regular:
Expected to see [0]==plus, instead saw periodcentered

make[1]: *** [VARIABLE_BUILD_PATH_UPRIGHT_TARGET] Error 1
make[1]: *** Waiting for unfinished jobs....
fontmake: Error: In 'GoogleSans/GoogleSans-Italic.designspace': Generating fonts from Designspace failed:

Couldn't merge the fonts, because some values were different, but should have
been the same. This happened while performing the following operation:
GSUB.table.LookupList.Lookup[13][0].LookAheadCoverage[0].glyphs[0]

The problem is likely to be in Google Sans Text Bold Italic Regular:
Expected to see [0]==plus, instead saw periodcentered

make[1]: *** [VARIABLE_BUILD_PATH_ITALIC_TARGET] Error 1
```

I'll have a more detailed look into this issue.

**Comment by dberlow** [comment]
This does not look related to the glyphs I changed and is a gsub error from somewhere else.

**Comment by chrissimpkins** [comment]
> This does not look related to the glyphs I changed and is a gsub error from somewhere else.

Thanks David.  I'll have a look.

**Comment by sannorozco** [comment]
It seems to be the glyph order on that master.

**Comment by sannorozco** [comment]
This has happened to me before, where there was a different glyphorder on a
plist somewhere else

**Comment by madig** [comment]
Make sure the public.glyphOrder lib key is the same across all participating masters. This should probably be caught in ufo2ft or something...

**Comment by chrissimpkins** [comment]
Thanks Santiago and Nikolaus!  Nikolaus is that error message from ufo2ft?

**Comment by madig** [comment]
It's from fontTools.varLib, specifically from the font merging code.

**Comment by chrissimpkins** [comment]
From D Berlow:

---

The proportionally spaced sub-cap ht figures have been redrawn to cap ht figures on the same widths as the legacy sub-cap ht figures.

The tabular figures were already at cap ht. and were not changed, and the cap ht figures were also left unchanged.

The affected glyphs are listed below:
numbersign dollar percent zero one two three four five six seven eight nine cent sterling yen zero.alt one.alt six.alt seven.alt nine.alt One-roman Two-roman Three-roman Four-roman Five-roman Six-roman Seven-roman Eight-roman Nine-roman Ten-roman Eleven-roman Twelve-roman Fifty-roman Hundred-roman Fivehundred-roman Thousand-roman Onethousandcd-roman Fivethousand-roman Tenthousand-roman numbersign.tf baht dong euro florin franc hryvnia lira liraTurkish peso ruble rupeeIndian tenge tugrik won baht.cap cent.cap cent.tf currency.tf dollar.tf dong.tf euro.tf florin.tf franc.tf hryvnia.tf lira.tf liraTurkish.tf peso.tf ruble.tf rupeeIndian.tf sterling.tf tenge.tf tugrik.tf won.tf yen.tf degree pertenthousand perthousand centigrade fahrenheit sheqel sheqel.tf zeropercent

The whole series got changes to the /centigrade /fahrenheit composites, changing from sub-cap ht “specials” to default C and F. This is why 17 pt masters are listed below.

The completed regular styles are complete.
GoogleSans-opsz17-wght380-GRAD-50.ufo
GoogleSans-opsz17-wght380-GRAD0.ufo
GoogleSans-opsz17-wght380-GRAD200.ufo
GoogleSans-opsz17-wght734-GRAD0.ufo
GoogleSans-opsz18-wght380-GRAD-50.ufo
GoogleSans-opsz18-wght380-GRAD0.ufo
GoogleSans-opsz18-wght380-GRAD200.ufo
GoogleSans-opsz18-wght734-GRAD0.ufo

The Italic is complete as well.
GoogleSans-opsz17-wght380-GRAD-50.ufo
GoogleSans-opsz17-wght380-GRAD0.ufo
GoogleSans-opsz17-wght380-GRAD200.ufo
GoogleSans-opsz17-wght734-GRAD0.ufo
GoogleSans-opsz18-wght380-GRAD-50.ufo
GoogleSans-opsz18-wght380-GRAD0.ufo
GoogleSans-opsz18-wght380-GRAD200.ufo
GoogleSans-opsz18-wght734-GRAD0.ufo

**Comment by madig** [comment]
https://github.com/googlefonts/googlesans/pull/412

**Comment by belluzj** [comment]
Merged in https://github.com/googlefonts/googlesans/pull/412
