### ISSUE TITLE
Review / revise new localized Tamil figure forms

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans#389]
New Tamil locale-specific international figure heights are being added in #374.  @kalapi and team will review these forms in a Linux/FreeType environment to confirm that we are not going to run into the same issues that we have in #31 (related #344).  The review will take place before we release the outlines in v6

cc @kalapi

**Comment by kalapi** [comment]
As @chrissimpkins predicted, the figures do jump on Linux/FreeType (figure below; tested on Raspibian).

![GSSA_Tamil_Numerals-Raspibian](https://user-images.githubusercontent.com/15804460/135276025-84071881-b112-404d-b15a-a026e7a8af17.png)

I'll try a fix where the numerals are the same height as the other Tamil chars to test if they still have varying heights. 

- [x] Resize localised Tamil numerals.

**Comment by chrissimpkins** [comment]
D/W Kalapi today. He feels that it is important for the Tamil locale international figures to have this height alignment relative to the Tamil letterforms.  Based on my previous conversations with Werner Lemberg, I am not optimistic that shifting them to any height other than Latin cap height will address the top alignment issue in FT figure grid fitting, but let's definitely have a look.  I suggest that we go with these new Tamil fig forms in our v6.000 release.  Let's follow up with the design edit assessment and then consider work on FT if that doesn't address it.  Werner was open to this and mentioned that it might affect oldstyle figs too.

cc @belluzj @madig re: possible FT feature analysis / autohinter work

cc @dberlow as a FYI because you just worked on the default opsz 18 figs.  Nothing actionable.  Just pointing out more figure height headaches... :)

**Comment by kalapi** [comment]
Hello @chrissimpkins et. all

I scaled the numerals to the Tamil character height, and this seems to have fixed the problem (see below):

![2021-09-30-GSSA_Tamil_Numerals_Raspibian](https://user-images.githubusercontent.com/15804460/135399398-5403cf73-e938-4fac-be2a-c8f1f7fa3f1d.png)

**Comment by chrissimpkins** [comment]
Very interesting.  Did you eliminate overshoots?

**Comment by chrissimpkins** [comment]
Kalapi, will you package up your builds and those HTML test docs in a zip archive and share them in this thread with me?  I'll have a look in a couple of other Linux envs.

**Comment by kalapi** [comment]
Hi Chris, 

Adding the R04 package with heights of the localised numerals fixed. 

As per your request, I've also included the test HTML along with the above screenshots (date-stamped).

Let me know if you need anything else.

[GoogleSans_Tamil_R04.zip](https://github.com/googlefonts/googlesans/files/7313675/GoogleSans_Tamil_R04.zip)

**Comment by chrissimpkins** [comment]
@kalapi It looks like your test HTML docs are using the otf format builds.  Have you had a look at the ttf builds?  We release TT fonts and the FreeType env grid fit may well be different for this issue.

**Comment by kalapi** [comment]
Following up from yesterday's conversation; I initially tested the uprights as TTFs and the screenshot supplied was using TTFs. But if you're reviewing them anyway, let me know if the output is different from mine.

**Comment by chrissimpkins** [comment]
#408

**Comment by chrissimpkins** [comment]
@kalapi do you mind having a look at the `seven.loclTAML` glyph?  It looks like the point order changes across masters and fontmake won't compile:

```
ERROR:cu2qu.ufo:Glyphs named 'seven.loclTAML' have incompatible segment types:
  1: ('curve', 'curve', 'curve', 'curve', 'line', 'line', 'line', 'line')
  2: ('line', 'line', 'line', 'line', 'curve', 'curve', 'curve', 'curve')
  7: ('curve', 'curve', 'curve', 'curve', 'line', 'line', 'line', 'line')
  8: ('line', 'line', 'line', 'line', 'curve', 'curve', 'curve', 'curve')
fontmake: Error: In 'GoogleSans/GoogleSans.designspace': Generating fonts from Designspace failed: fonts contains incompatible glyphs: 'seven.loclTAML'
```

Appears to be a Roman source file only issue.

Build ==> https://github.com/googlefonts/googlesans/runs/3886050772?check_suite_focus=true

Thanks

**Comment by chrissimpkins** [comment]
Fixed in f07dc53fdafe3d362b41407854e74ff955d8c805

The `seven.loclTAML` point order was different across the masters.

**Comment by chrissimpkins** [comment]
> Fixed in [f07dc53](https://github.com/googlefonts/googlesans/commit/f07dc53fdafe3d362b41407854e74ff955d8c805)
> 
> The `seven.loclTAML` point order was different across the masters.

@kalapi Please make sure that you pull this update into your files.  They don't compile as is.

**Comment by chrissimpkins** [comment]
I had a look at these changes (PR #408) in an Ubuntu 20.04 environment across the full Material 3 Google Sans (i.e. opsz 18 design) type ramp guidance.  It looks like there are still height issues at sizes that are relevant to Google.  The 18 and 28 sizes are affected and it looks like it is due to the overshoots on the `6`, `7`, and `9`. 

Arrows in image below show the problem @ size 18


<img width="1458" alt="2021-10-19_14-56-00" src="https://user-images.githubusercontent.com/4249591/138140971-eedd4e1b-d702-4344-976a-d021b07c6adf.png">

Thoughts about either making the terminals horizontal or dropping the overshoots/undershoots on the angled terminals to see if we can eliminate the issue?  I'm interested in your thoughts about how such a change impacts other platforms if we stick with angled terminals in these figures.

Archive with my changes in your test documents to support VF ttf builds and Tamil locale attached below.

[GSSATamil-NumeralsTestLinux.zip](https://github.com/googlefonts/googlesans/files/7383164/GSSATamil-NumeralsTestLinux.zip)

**Comment by kalapi** [comment]
Hi Chris, i'm travelling at the moment and don't have access to my Linux test rig. I've made some fixes in the sources, can you test the new binaries when you have time and let me know if this mod fixed it?

[GoogleSans_Tamil_R05.zip](https://github.com/googlefonts/googlesans/files/7425587/GoogleSans_Tamil_R05.zip)

**Comment by chrissimpkins** [comment]
Thanks Kalapi! Happy to have a look.  What are the fixes?

**Comment by kalapi** [comment]
I've fixed the heights for 6 and 9 in all weights and styles such that the top and bottom (of the 6 and 9 respectively) don't extend into the overshoot. And for the 7, in the max-opsz, I reduced the height of the leg such that it also does not extend into the overshoot.

**Comment by chrissimpkins** [comment]
> ERROR:cu2qu.ufo:Glyphs named 'seven.loclTAML' have incompatible segment types:
  1: ('curve', 'curve', 'curve', 'curve', 'line', 'line', 'line', 'line')
  2: ('line', 'line', 'line', 'line', 'curve', 'curve', 'curve', 'curve')
  7: ('curve', 'curve', 'curve', 'curve', 'line', 'line', 'line', 'line')
  8: ('line', 'line', 'line', 'line', 'curve', 'curve', 'curve', 'curve')
fontmake: Error: In 'GoogleSans/GoogleSans.designspace': Generating fonts from Designspace failed: fonts contains incompatible glyphs: 'seven.loclTAML'


You didn't fix your seven.loclTAML in the [latest version of the designs](https://github.com/googlefonts/googlesans/issues/389#issuecomment-952801472)  :)   See https://github.com/googlefonts/googlesans/issues/389#issuecomment-943669199 and https://github.com/googlefonts/googlesans/issues/389#issuecomment-946981112

**Comment by chrissimpkins** [comment]
Well, good news and bad news.  The stems no longer extend below and above.  But now they appear too short at some sizes. Goldilocks principle... :) 

Shown @ 32 in an Ubuntu 21.10 environment + Chromium browser:

<img width="1298" alt="2021-11-03_17-02-35" src="https://user-images.githubusercontent.com/4249591/140193108-b46dc354-cb7a-4dca-9023-f7f6ac193fac.png">

I suggest that we position the max/min point of the angled terminals at the same y coordinate as the round overshoots and undershoots.  It looks like this is 596 and -16.  Maybe this does the trick?

**Comment by chrissimpkins** [comment]
I discussed the latest revision with Kalapi and we are going to stick with the designs as of the revisions in https://github.com/googlefonts/googlesans/issues/389#issuecomment-952801472 (as shown in https://github.com/googlefonts/googlesans/issues/389#issuecomment-960085295).  We are running into similar issues with the cap height default figure transition and this size-specific issue may be the best alignment that we can achieve in environments where manual instructions are ignored by default.
