### ISSUE TITLE
dje-cy (U+0452) tail misalignment, incorrect weight

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans#399]
Related to #332 #379 

The CYRILLIC SMALL LETTER DJE (U+0452) tail is misaligned in some areas of the designspace:

<img width="1628" alt="2021-09-29_11-26-58" src="https://user-images.githubusercontent.com/4249591/135300425-1d78e34c-1f95-4165-b14e-71835b9a0124.png">

and has an inappropriate weight in others:

<img width="1628" alt="2021-09-29_11-29-08" src="https://user-images.githubusercontent.com/4249591/135300591-f5b66311-2292-45a8-9eb8-39ae9201f230.png">

We addressed this by decomposing the tail component outline in other glyphs and will likely need to do the same here.

**Comment by chrissimpkins** [comment]
cc @alexeiva as part of your Q4 Cyrillic glyph set review

**Comment by chrissimpkins** [comment]
These revisions are in progress and should land in v8.000.  Moving the milestone.

**Comment by chrissimpkins** [comment]
@alexeiva Was this addressed in your Cyrillic updates?

**Comment by alexeiva** [comment]
> @alexeiva Was this addressed in your Cyrillic updates?

I just checked — this isn't fixed in my glyphs sources.  I will re-upload the sources.

**Comment by alexeiva** [comment]
I updated the .glyphs archive: https://github.com/googlefonts/googlesans/issues/456#issuecomment-1067099090


<img width="939" alt="Screenshot 2022-03-14 at 20 28 30" src="https://user-images.githubusercontent.com/16634089/158227866-be762e47-fa23-4a36-99aa-26b4441d087b.png">

<img width="976" alt="Screenshot 2022-03-14 at 20 28 32" src="https://user-images.githubusercontent.com/16634089/158227851-f6137ff0-3c44-410f-b918-736763759995.png">

**Comment by belluzj** [comment]
Fixed in https://github.com/googlefonts/googlesans/pull/598
