### ISSUE TITLE
eng.sc (U+014B) tail misalignment, weight inconsistency

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans#400]
Related to #332 #379

The LATIN SMALL LETTER ENG (U+014B) **small cap** tail is misaligned in some areas of the designspace:

<img width="1628" alt="2021-09-29_11-37-49" src="https://user-images.githubusercontent.com/4249591/135302055-5463ab17-d524-4277-860b-37650d39e155.png">

and has an inappropriate weight (too heavy) in others:

<img width="1628" alt="2021-09-29_11-38-31" src="https://user-images.githubusercontent.com/4249591/135302232-ade06ac1-6019-4060-829e-1aa3eaf121ca.png">

We addressed this by decomposing the tail component outline in other glyphs and will likely need to do the same here.

**Comment by MariannaPaszkowska** [comment]
Let's check if this has been fixed in v11.001.

**Comment by belluzj** [comment]
@MariannaPaszkowska Eduardo checked the main branch and reports:

> The /eng.alt.sc and the other Eng shapes seems to be correct at the sources. I assumed it was relating the eng tail component that they were using, but the shape is decomposed now.
