### ISSUE TITLE
Decompose tail component on elhook-cy (U+0513)

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans#401]
Related https://github.com/googlefonts/googlesans/issues/381

(CYRILLIC SMALL LETTER EL WITH HOOK, U+0513)

Following the changes in #399 and #400, this will be the only composite glyph that uses the engtail component outline.  Let's decompose and eliminate the tail component from the glyph set altogether.

**Comment by chrissimpkins** [comment]
cc @alexeiva as part of your Q4 Cyrillic glyph set review

**Comment by alexeiva** [comment]
@chrissimpkins yes, I see the problem in the UFO sources in main. Will edit this in the Cyrillic branch and submit a PR.

Can you point me to the GRAD sources — are they in a branch?

**Comment by chrissimpkins** [comment]
Thanks Alexei!

The grade masters can be found in our production source directory: https://github.com/googlefonts/googlesans/tree/main/source/GoogleSans

The file paths indicate the area of the design space across wght/GRAD axes and the Roman/Italic styles.  Our GRAD range is -50 to +200.  GoogleSans = opsz 18 and GoogleSansText = opsz 17.   Please let me know if you have any other questions.  Thanks!
