### ISSUE TITLE
Review Greek small caps subs in Adobe applications

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans#403]
actually it's only in Adobe apps, InDesign 16.4 and Illustrator 25.4.1

_Originally posted by @irenevl in https://github.com/googlefonts/googlesans/issues/157#issuecomment-930963024_

Per Irene, our Greek smcp GSUB shaping does not work in the above Adobe application versions.  Let's look into it.

**Comment by chrissimpkins** [comment]
@irenevl you are seeing this on the default macOS versions of the Adobe applications correct?

**Comment by irenevlachou** [comment]
I think it's the latest, no Beta version,  Big Sur version 11.6 (20G165)

**Comment by chrissimpkins** [comment]
Ty!

**Comment by chrissimpkins** [comment]
This looks like a `smcp` bug in Adobe products.  `c2sc` seems to work.  

I tested it in InDesign 2021 (macOS) vs. Figma (desktop version, macOS).  Both c2sc and smcp appear to function without issues in Figma:

### InDesign

<img width="672" alt="372RLUjqTCeP3mT" src="https://user-images.githubusercontent.com/4249591/137962451-587881fb-912b-490d-a867-69979e527557.png">


### Figma
<img width="769" alt="9VBiobcLKB8Ywae" src="https://user-images.githubusercontent.com/4249591/137962467-2d272ed6-301e-4373-8a89-6c3a157269cd.png">


I'll reach out to the Adobe team to let them know/troubleshoot further.
