### ISSUE TITLE
Import script should print a list of affected pre-existing glyphs

### ISSUE THREAD

**Issue by madig** [googlefonts/googlesans#411]
Random idea: when importing something from a vendor and overwriting an existing glyph, the script should search the UFO for affected glyphs, i.e. print a list of composites that have the changed glyphs plus any downstream glyphs of those.

Example: the font contains the glyphs `a`, `dieresiscomb`, `adieresis`, `circumflexcomb`, and `adieresiscircumflex` (which is `adieresis` + `circumflexcomb`). Importing a new `dieresiscomb` is going to affect `adieresis` directly and `adieresiscircumflex` indirectly. The importer should be made aware of both to check that they still look as intended.

**Comment by belluzj** [comment]
Will there be more imports of new scripts into GS? If not, maybe we can close this issue.
