### ISSUE TITLE
Remove `<note>` elements

### ISSUE THREAD

**Issue by madig** [googlefonts/googlesans#418]
I see a lot of junk hanging around.

**Comment by chrissimpkins** [comment]
time to de-junkify?

**Comment by chrissimpkins** [comment]
OK to forge ahead with this when time permits.

**Comment by madig** [comment]
I suggest we clean up some things _after_ you tagged v7. That way, we can keep a bunch of distracting diffs out of the way.

**Comment by chrissimpkins** [comment]
> I suggest we clean up some things _after_ you tagged v7. That way, we can keep a bunch of distracting diffs out of the way.

Incoming.  We should release today.

**Comment by chrissimpkins** [comment]
https://github.com/googlefonts/googlesans/releases/tag/v7.000

**Comment by chrissimpkins** [comment]
https://github.com/googlefonts/googlesans/pull/441#issuecomment-1021479223

Asks if we want to continue to do this as part of the import source normalization process so that we avoid UFO note annotations altogether in prod source.
