### ISSUE TITLE
Update all Postscript names

### ISSUE THREAD

**Issue by madig** [googlefonts/googlesans#419]
Passing the list of glyph names through Glyphs.app, I find various different production names. We should update them wholesale with whatever Glyphs.app says probabaly. glyphsLib inference is unfortunately unreliable.

**Comment by anthrotype** [comment]
You should file an issue against glyphsLib detailing the differences. It may be a different GlyphData.xml or some missing logic or a bug

**Comment by madig** [comment]
Also: there are diffs between upright and italic production names. Groan.

**Comment by chrissimpkins** [comment]
> Also: there are diffs between upright and italic production names. Groan.

Is the Roman v. Italic difference a glyphsLib issue?  or this is coming from definitions that design teams used in sources?

**Comment by madig** [comment]
I'm not sure, It might also be a slip-up. The glyphsets of upright and itralic are not equivalent so there's room for diffs.

**Comment by madig** [comment]
Reported at https://github.com/googlefonts/glyphsLib/issues/770 and Khaled already submitted a PR :)

The openTypeCategory detection needs a looking at next, but that's a separate issue.

**Comment by chrissimpkins** [comment]
Ty!
