### ISSUE TITLE
Cleanup: Unreachable glyphs

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans#426]
During the Lao script import (https://github.com/googlefonts/googlesans/pull/416), our CI tests report the following list of unreachable glyphs. Defined as (1) not Unicode encoded; (2) not covered by substitution feature code.

           • Imacron.1                                                          
           • descender3cy                                                       
           • descender2cy                                                       
           • Ohorn.1                                                            
           • uni03020309.cap                                                    
           • Oslashbar                                                          
           • tickcy                                                             
           • Uogonekcomb                                                        
           • obarredbarsc                                                       
           • lslash.1                                                           
           • dcroatbar                                                          
           • ticklccy                                                           
           • Cfigureht                                                          
           • flig1                                                              
           • tecydash                                                           
           • dieresislcUkraine                                                  
           • oslash.sc.1                                                        
           • descendercy                                                        
           • descender3cy.sc                                                    
           • oslashbar                                                          
           • Uhorn.1                                                            
           • tailsccy                                                           
           • tickcy.sc                                                          
           • percentbar                                                         
           • flig2                                                              
           • Ffigureht                                                          
           • Tbar.1                                                             
           • tbar.1                                                             
           • uni05BC.alt                                                        
           • Kastrokecy.case                                                    
           • descender1sccy                                                     
           • tcaron.1                                                           
           • hastroke.sc                                                        
           • upturnsccy                                                         
           • descenderlc1cy                                                     
           • Ethbar                                                             
           • Ghestrokecasecy                                                    
           • ethbar.sc                                                          
           • dieresisYicy                                                       
           • aogonek.1                                                          
           • SansSerifCircle                                                    
           • numerobar                                                          
           • tcedilla                                                           
           • upturnlccy                                                         
           • Uogonekcomb.1                                                      
           • tlig.1                                                             
           • hbarbar.sc                                                         
           • uni03060309.cap                                                    
           • kastrokebarcy.sc                                                   
           • asteriskcomb                                                       
           • DCroatbar                                                          
           • rlig                                                               
           • oobarredcy                                                         
           • Hbarbar                                                            
           • ghestrokecy.sc                                                     
           • upturncy                                                           
           • descenderlc2cy.sc                                                  
           • ohorn.1                                                            
           • taillccy                                                           
           • hookabovecomb.cap                                                  
           • ghestrokebarcasecy                                                 
           • brevecombcy                                                        
           • descenderlc2cy                                                     
           • Aring.1                                                            
           • aring.sc.1                                                         
           • engtail                                                            
           • Lslash.1                                                           
           • descenderlc3cy                                                     
           • Ustrokecy.case                                                     
           • Obarcy                                                             
           • tailcy                                                             
           • lslash.sc.1                                                        
           • tbar.sc.1                                                          
           • zeropercent                                                        
           • dieresisscUkraine                                                  
           • thetabar.sc                                                        
           • dieresisUkraine                                                    
           • ohorn.sc.1                                                         
           • aringacute.1                                                       
           • obarredbarcy

**Comment by madig** [comment]
False positives, see https://github.com/googlefonts/fontbakery/issues/3523.

**Comment by chrissimpkins** [comment]
> False positives, see [googlefonts/fontbakery#3523](https://github.com/googlefonts/fontbakery/issues/3523).

Ty!  I updated the thread with the glyph list that we are seeing here.

**Comment by chrissimpkins** [comment]
Should be fixed as of https://github.com/googlefonts/fontbakery/pull/3540. Thanks @simoncozens!

Let's see in the next fontbakery release.

**Comment by chrissimpkins** [comment]
Seems to be gone as of the CI tests run in #451. Closing.
