### ISSUE TITLE
Review Notes; Greek opsz17-wght380-GRAD- 50

### ISSUE THREAD

**Issue by dberlow** [googlefonts/googlesans#431]
**Upper case:**
Delta: thinner that Alpha — Corrected
Lambda: thinner that Alpha — Corrected
Sigma: diagonals a bit thin — Corrected
Omega: uneven on thickness — Corrected
Kaisymbol: middle diagonal too heavy — Corrected

**Lower case:**
gamma: diagonals too thin — Corrected
epsilon: uneven thickness — Corrected
zeta: top right connection too thick — Corrected
lambda: uneven thickness — Corrected
xi: uneven thickness — Corrected
rho: too thin on top left side  — Corrected
sigmafinal: uneven thickness — Corrected

**Smallcaps**
delta.sc: too wide compare to alpha.sc — Corrected
lambda.sc: too wide compare to alpha.sc  — Corrected
sigma.sc: too thin _(is composite of sigmafinal.sc)_ — Corrected
phi.sc: too wide — Corrected
omega.sc: too wide — Corrected
kaisymbol.sc: wrong weight -  — Corrected

**Comment by MariannaPaszkowska** [comment]
related #595

**Comment by belluzj** [comment]
Fixed in https://github.com/googlefonts/googlesans/pull/597
