### ISSUE TITLE
Review Notes; Greek opsz17-wght380-GRAD- 50 Part II

### ISSUE THREAD

**Issue by dberlow** [googlefonts/googlesans#432]
**Accents and related composites**
tonos: too thin — corrected
varia: too thin (like tonos) — corrected
oxia: too thin (like tonos) — corrected via composite

dieresistonos: dieresis too small — corrected
dieresistonos.case — _glyph does not seems to exist_
dieresistonos.sc — corrected via composite
dialytikavaria: wrong weight — corrected
dialytikavaria.case — corrected via composite
dialytikavaria.sc — corrected via composite
dasia: wrong weight — corrected
dasiavaria — corrected via composite

See also Greek diacritic follow-up issue #next

**Comment by MariannaPaszkowska** [comment]
This will be closed by #595

**Comment by belluzj** [comment]
Fixed in https://github.com/googlefonts/googlesans/pull/597
