### ISSUE TITLE
missing diacritics on Greek

### ISSUE THREAD

**Issue by dberlow** [googlefonts/googlesans#433]
/iotatonos.sc /omicrontonos.sc /omegatonos.sc /alphatonos.sc /epsilontonos.sc /etatonos.sc 

…missing tonos?
<img width="885" alt="Gone tonos?" src="https://user-images.githubusercontent.com/1956494/149173636-ec267345-864b-4c0e-9764-4d2827b5f737.png">

/alphapsilivaria.sc /alphadasiavaria.sc /alphavaria.sc /epsilonpsilivaria.sc /epsilondasiavaria.sc /epsilonvaria.sc /etapsilivaria.sc /etadasiavaria.sc /etavaria.sc /iotapsilivaria.sc /iotadasiavaria.sc /iotavaria.sc /omicronpsilivaria.sc /omicrondasiavaria.sc /omicronvaria.sc /upsilonpsilivaria.sc /upsilondasiavaria.sc /upsilonvaria.sc /omegapsilivaria.sc /omegadasiavaria.sc /omegavaria.sc 

…missing varia?
<img width="828" alt="Gone varias?" src="https://user-images.githubusercontent.com/1956494/149173646-7a41cbc7-ea06-4695-b085-a942b94178a0.png">

**Comment by irenevlachou** [comment]
hi David! no-no, I followed the logic that the default set of small caps "behaves" like an UC greek, where the accents and breathings are omitted*. And then we have an alternate set tha treats the accented small caps as lower case derivatives. A much more rearer use. That set can be accessed through ss06 I think.

*In UC setting the OS takes care of it, so there is no need for duplicated sets. Actually it doesn't work in all OS but that something we go and complain to apple and w3c and don't fix in the fonts.

**Comment by chrissimpkins** [comment]
OK to close?

**Comment by dberlow** [comment]
Okay on the i accented glyphs. 


On Jan 12, 2022, at 4:30 PM, Chris Simpkins ***@***.***> wrote:

﻿
OK to close?
