### ISSUE TITLE
Review Greek GRAD -50 edits Part III

### ISSUE THREAD

**Issue by dberlow** [googlefonts/googlesans#434]
dasiaoxia — Corrected by composite
dasiavaria.case — Corrected by composite
dasiaoxia.case — Corrected by composite
dasiavaria.sc — Corrected by composite
dasiaoxia.sc  — Corrected by composite

perispomenidasia, perispomenidasia.sc & perispomenidasia.case — _Does not seem to exist_

**Comment by dberlow** [comment]
All committed in the branch /Berlow Greek GRAD fixes.

**Comment by chrissimpkins** [comment]
> All committed in the branch /Berlow Greek GRAD fixes.

@dberlow are the lists of glyphs included in the new issue reports today all that we need to import from your masters or are there new component glyph definitions added to the set, or revisions of existing components?

**Comment by dberlow** [comment]
No composite combinations any other changes were made other than the contour edits to glyphs listed in the review, and the glyphs that used the edited glyphs in composites.

So, besides the edited contours, there will be some changes to the composite instructions for x placement, but the glyphs used in the composites remain the same. 

So, there are no new component glyph definitions, but some were changes as their parts were narrowed or otherwise revised.

On Jan 12, 2022, at 4:33 PM, Chris Simpkins ***@***.***> wrote:

﻿
All committed in the branch /Berlow Greek GRAD fixes.

@dberlow are the lists of glyphs included in the new issue reports today all that we need to import from your masters or are there new component glyph definitions added to the set?

**Comment by MariannaPaszkowska** [comment]
Let's rebase the branch, open a new PR and review this.
THanks @belluzj

**Comment by MariannaPaszkowska** [comment]
Closed with #597 Thank you all for your hard work on this!
