### ISSUE TITLE
Add Bangla script support

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans#445]

**Comment by kalapi** [comment]
Uploading Round 01 Beta package herewith:

[2022-02-11_GoogleSansBangla_V1.000_BETA01.zip](https://github.com/googlefonts/googlesans/files/8051928/2022-02-11_GoogleSansBangla_V1.000_BETA01.zip)

**Comment by chrissimpkins** [comment]
Thanks Kalapi!

**Comment by madig** [comment]
@kalapi thanks! what's the difference between GoogleSansBangla-Upright.glyphs and GoogleSansBangla-Upright 2.glyphs?

**Comment by madig** [comment]
Ah, glyph clashes. @kalapi please import the following glyphs into your sources and make sure your design works with them (or make targeted changes and tell us about them):

* space
* nbspace
* zerowidthspace
* zerowidthjoiner
* zerowidthnonjoiner
* dottedCircle
* danda-deva
* dbldanda-deva

You can use

* https://github.com/googlefonts/googlesans/suites/5295652895/artifacts/164231110 (uprights)
* and https://github.com/googlefonts/googlesans/suites/5295652895/artifacts/164231109 (italics)

**Comment by kalapi** [comment]
> @kalapi thanks! what's the difference between GoogleSansBangla-Upright.glyphs and GoogleSansBangla-Upright 2.glyphs?

Don't know how that happened. You can ignore it for now!

**Comment by kalapi** [comment]
- [x] space
- [x] nbspace
- [x] zerowidthspace
- [x] zerowidthjoiner
- [x] zerowidthnonjoiner
- [x] dottedCircle
- [x] danda-deva (renamed to `danda-deva.loclBENG` and added to `locl` feature)
- [x] dbldanda-deva (renamed to `dbldanda-deva.loclBENG` and added to `locl` feature)

**Comment by kalapi** [comment]
Round 2

**Note**: The `dottedCirrcle` glyph in the upstream italic sources (the ones you've linked to above) seems to throw a metrics issue for the RSB. 

[2022-02-15_GoogleSansBangla_V1.000_BETA02.zip](https://github.com/googlefonts/googlesans/files/8067894/2022-02-15_GoogleSansBangla_V1.000_BETA02.zip)

**Comment by madig** [comment]
Thanks :) I extracted the features from the .glyphs files. 

* Why is the locl feature disabled?
* Also, can you please update all glyph names containing "candrabindu-beng" to "candraBindu-beng"? The capital B is important for glyph metadata :) 
* Also also! Please run the following script in the macro panel and then save the file as the last step:

```py
# MenuTitle: Embed Glyph Metadata in Current Font

"""Embeds production name, category and sub category into each glyph of the current font."""

import logging

for glyph in Glyphs.font.glyphs:
    info = Glyphs.glyphInfoForName(glyph.name)
    if info is None:
        logging.warning("No info for %s", glyph.name)
        continue
    if info.productionName is not None:
        glyph.storeProductionName = True
        glyph.productionName = info.productionName
    if info.category is not None:
        glyph.storeCategory = True
        glyph.category = info.category
    if info.subCategory is not None:
        glyph.storeSubCategory = True
        glyph.subCategory = info.subCategory
```

It embeds various things into the glyph which helps me with importing them :)

**Comment by kalapi** [comment]
@madig 

The `locl` feature is disabled at import because when generating fonts from Glyphs to test, it doesn't compile because of the missing glyphs in the substitution rule. I can enable it just before sending you a package if that's more convenient. We did the same thing during the Gurmukhi merge. 

Will do the other tasks and update a new package in a bit.

**Comment by kalapi** [comment]
- [x] un-Disables `locl` feature
- [x] Updates glyph names and references in OTL code
- [x] Embed MetaData

**Comment by kalapi** [comment]
Hi @madig, here you go! 

[2022-02-16_GoogleSansBangla_V1.000_BETA03.zip](https://github.com/googlefonts/googlesans/files/8080406/2022-02-16_GoogleSansBangla_V1.000_BETA03.zip)

**Comment by madig** [comment]
Thanks. Weird though, now the following glyphs aren't recognized as bases anymore by our scripts but are marked as such in the GDEF in the import files:

* iiMatra-beng
* auLength-beng
* iiMatra-beng.long
* iiMatra-beng.tta-beng.long
* iiMatra-beng.nub
* iiMatra-beng.nubWide
* iiMatra-beng.tta-beng.short

I wonder if it matters.

**Comment by madig** [comment]
Also! I found the glyph name "iMatra_reph_candraBindu.tta-beng.long", which seems to not be recognized by Glyphs.app for making a production name. It works with this name: "iMatra_reph_candraBindu_tta-beng.short" -> "uni09BF09B009CD0981099F.short". Note the ".tta" instead of "_tta". Is there a special reason you chose the ".tta" name?

**Comment by kalapi** [comment]
> Thanks. Weird though, now the following glyphs aren't recognized as bases anymore by our scripts but are marked as such in the GDEF in the import files:
> 
> * iiMatra-beng
> * auLength-beng
> * iiMatra-beng.long
> * iiMatra-beng.tta-beng.long
> * iiMatra-beng.nub
> * iiMatra-beng.nubWide
> * iiMatra-beng.tta-beng.short
> 
> I wonder if it matters.

Yes, all these glyphs need to be BASEs in the GDEP since they have anchors and are used as contexts in GSUB.

**Comment by kalapi** [comment]
> Also! I found the glyph name "iMatra_reph_candraBindu.tta-beng.long", which seems to not be recognized by Glyphs.app for making a production name. It works with this name: "iMatra_reph_candraBindu_tta-beng.short" -> "uni09BF09B009CD0981099F.short". Note the ".tta" instead of "_tta". Is there a special reason you chose the ".tta" name?

No particular reason, /_tta/ is fine as well. Do you want me to rename it in the sources and re-send?

**Comment by madig** [comment]
Yes please. Maybe have a look at your compiled fonts to see what other glyphs should have proper uni names but don't. E.g. fontbakery flags some of the glyphs mentioned above because they go over the name length limit :)

Please also have a look at the names I posted above, e.g. "iiMatra-beng.tta-beng.long" should maybe be "iiMatra_tta-beng.long" if it makes more sense? Typically, you want only one "-beng" part in the glyph names, which would apply to all parts of the ligature.

**Comment by kalapi** [comment]
I will work on this tomorrow and send you an updated package.

**Comment by kalapi** [comment]
Attaching No.4 herewith:
[2022-02-18_GoogleSansBangla_V1.000_BETA04.zip](https://github.com/googlefonts/googlesans/files/8099459/2022-02-18_GoogleSansBangla_V1.000_BETA04.zip)

**Comment by madig** [comment]
Thanks, but the following glyphs

* n_ttha_iMatra-beng
* ss_ttha_iMatra-beng
* tth_ba_iMatra-beng
* tth_ra_iMatra-beng
* ttha_iMatra-beng

point to _smart.iMatra_ttha-beng which doesn't exist? Continuing next week.

**Comment by kalapi** [comment]
> Thanks, but the following glyphs
> 
> * n_ttha_iMatra-beng
> * ss_ttha_iMatra-beng
> * tth_ba_iMatra-beng
> * tth_ra_iMatra-beng
> * ttha_iMatra-beng
> 
> point to _smart.iMatra_ttha-beng which doesn't exist? Continuing next week.

Those are glyph references in the background. I'll sanitize and re-send. Apologies for the back and forth.

**Comment by kalapi** [comment]
Round 5!

[2022-02-19_GoogleSansBangla_V1.000_BETA05.zip](https://github.com/googlefonts/googlesans/files/8101465/2022-02-19_GoogleSansBangla_V1.000_BETA05.zip)

**Comment by madig** [comment]
Thanks! Now I get fontbakery a warning and failure:

* Is iMatra-beng.rephCandraBinduTta.short a ligature? If so, the name of these glyphs should be modified like in https://github.com/googlefonts/googlesans/issues/445#issuecomment-1042055149
* The OS/2 usWinAscent is fixed at 1116 but some glyphs like iMatra-beng.rephCandraBinduTta.long go above, which will lead to clipping.

The latter is a problem. @chrissimpkins

**Comment by chrissimpkins** [comment]
Mind posting a string of tall/deep glyphs Kalapi?

**Comment by kalapi** [comment]
Hi @madig,

I've fixed the GDEF for those glyphs. Now there are only either BASE or MARK glyphs. The naming for `iMatra-beng.rephCandraBinduTta.short` is fine as is because the suffix `rephCandraBinduTta` describes only the base glyph it works with.

It's ok if these are clipped for now since these are super rare but they need to be handled properly instead of breaking. 

@chrissimpkins I've added `bangla_default_ortho_tallest_combos.toml` for the tallest glyphs. Will also include the string below:

`র্টিঁ র্ক্টিঁ র্ট্বিঁ র্ট্রিঁ র্ট্মিঁ র্ট্ট্রিঁ র্ণ্টিঁ র্ণ্ট্রিঁ র্ন্টিঁ র্ন্ট্রিঁ র্প্টিঁ র্ফ্টিঁ র্ল্টিঁ র্ল্ট্রিঁ র্ষ্টিঁ র্ষ্ট্রিঁ র্স্টিঁ র্স্ট্রিঁ`

New package attached:
[2022-02-22_GoogleSansBangla_V1.000_BETA06.zip](https://github.com/googlefonts/googlesans/files/8115248/2022-02-22_GoogleSansBangla_V1.000_BETA06.zip)

**Comment by madig** [comment]
The "problem" is that the production name is over the 31 character limit. Not a deal breaker, but an annoying warning :) I suppose I can clip the name with a script.

I had a cursory look at the glyph metadata between beta 5 and 6 and found some weird changes, e.g. the production name for ss_tta-beng was uni09B709CD099F before and is uni09B709CD0997 now (‎099F BENGALI LETTER TTA vs. ‎0997 BENGALI LETTER GA). Huh?

Also, I do see some ligatures still? E.g. rr_ba-beng is declared a GDEF ligature.

**Comment by kalapi** [comment]
Okay, looking into this now.

**Comment by madig** [comment]
Are the changes in Beta 6 needed? If so, for what? Our internal review starts tomorrow and I need to prepare _something_.

**Comment by belluzj** [comment]
Hello, sorry I miscommunicated with Nikolaus about when our internal review starts. We've just slightly moved the start of the designer review to Monday 28th, to make sure we have final sources by then. I hope that will work?

**Comment by kalapi** [comment]
Hello @madig and @belluzj 

That's great, thanks, but i'll work this out today. 

Nikolaus, the changes are required because in Indic scripts none of the bases can be ligatures. That messes up the shaping royally. I'm going through the glyph data and fix anything incorrect production name associations.

**Comment by kalapi** [comment]
Hi @madig

Here's a new package for you, please test it and let me know what you find. 

[Uploading 2022-02-24_GoogleSansBangla_V1.000_BETA07.zip…]()

**Comment by madig** [comment]
@kalapi thanks, but something went wrong and I get no clickable link 😬

**Comment by kalapi** [comment]
> @kalapi thanks, but something went wrong and I get no clickable link 😬

😓 [2022-02-24_GoogleSansBangla_V1.000_BETA07.zip](https://github.com/googlefonts/googlesans/files/8133802/2022-02-24_GoogleSansBangla_V1.000_BETA07.zip)

**Comment by madig** [comment]
Thanks! The import_glyphs.txt file contains iMatra-beng.rephTta.long and iMatra-beng.rephCandraBinduTta.long which don't exist anymore?

**Comment by kalapi** [comment]
This should fix it (🤞🏾)

[2022-02-24_GoogleSansBangla_V1.000_BETA07.zip](https://github.com/googlefonts/googlesans/files/8133893/2022-02-24_GoogleSansBangla_V1.000_BETA07.zip)

**Comment by madig** [comment]
Thanks. So, here's a first cut of fonts:
[GoogleSans.zip](https://github.com/googlefonts/googlesans/files/8134439/GoogleSans.zip)

Giving it a quick look in the test documents, I see a bit of breakage here and there. Can you please have a look before I pass this over to our designers?

Here's a CSV of glyph data, also including GDEF category: [new2.csv](https://github.com/googlefonts/googlesans/files/8134444/new2.csv) -- you may want to cross-check, there are still ligatures in there.

**Comment by kalapi** [comment]
I thing the GlyphData script you gave me may be doing that, pulling the glyph info from Glyphs' default GlyphData instead of ours. In the latest package, i've included our GlyphData.xml in the `docs` folder. It has data for every glyph included in the font. can you check that and see if you're able to apply the contents of that info to the source and then parse?

**Comment by kalapi** [comment]
Sorry, I seem to have missed those three. I'll check again and i'll check the first cuts. But the problem is still the embed script. It's pulling the wrong data from the default GlyphData.

**Comment by madig** [comment]
Can you please put the GlyphData.xml next to your glyphs files, reopen them and run the script again? It should then embed the data from your XML. If not, I'll need to ping Georg.

**Comment by kalapi** [comment]
I was finally able to embed the correct glyph info. Please try the following package.
 
The following has been updated:

 - `import_glyphs_italic.txt` & `import_glyphs.txt`
 - `GlyphData.xml`
 - All reference fonts
 - Both sources

[2022-02-25_GoogleSansBangla_V1.000_BETA08.zip](https://github.com/googlefonts/googlesans/files/8139424/2022-02-25_GoogleSansBangla_V1.000_BETA08.zip)

**Comment by madig** [comment]
Thanks. Fresh fonts at https://github.com/googlefonts/googlesans/suites/5444632437/artifacts/172880702 and https://github.com/googlefonts/googlesans/suites/5444632437/artifacts/172880703, please have a look.

**Comment by madig** [comment]
I see breakage in "জ্জ্ব", "ন্ড্র", "ন্থ্র", "ন্ধ্র", "ল্ড্র" and "স্ক্ল" from the Included Conjuncts section.

Can you please use `fontmake -g GoogleSansBangla-Upright.glyphs -o variable` to compile test fonts and test them in your test page?

**Comment by kalapi** [comment]
@madig I have no idea what's happening. I looked into so many things. The feature code in the UFOs and the original Glyphs source is the same, but the compiled `GSUB` tables are completely different 😓

In the VF's`GDEF` table, the `[GDEF] glyph classes` subtable is exactly the same but the `[GDEF] item variation store` is completely different between the binaries generated by Glyphs and Fontmake.

**Comment by madig** [comment]
Hm, they use different compilers, so I'm not surprised the tables are totally different. Do you maybe have time to hop on a video call?

**Comment by madig** [comment]
There's something going on. See your reference fonts

![image](https://user-images.githubusercontent.com/380829/155743708-8304e93d-6254-448a-bbf9-f8c7ac1d3f59.png)

versus our fonts

![image](https://user-images.githubusercontent.com/380829/155743863-5f464ba1-f871-48a2-b5b7-1afd69467ee8.png)

Trying to understand it...

**Comment by kalapi** [comment]
This is a compiler issue. I've fixed it for fontmake by moving sub. rules around. It should be good now. 

Here's Build 9 (🤦🏽‍♂️)

[2022-02-25_GoogleSansBangla_V1.000_BETA09.zip](https://github.com/googlefonts/googlesans/files/8142461/2022-02-25_GoogleSansBangla_V1.000_BETA09.zip)

**Comment by madig** [comment]
That fixes it indeed, thanks! Very curious that the order was the cause here, though lookups are roughly applied in the order they're declared IIUC. I'll have a look around the test document a bit.

These glyphs are candidates for regression tests.

**Comment by madig** [comment]
I now get broken/different ক্ন্ ক্ল্ ক্ষ্ন্ ক্ষ্ব্ ক্ষ্র্ খ্ব্ গ্গ্ . Can you please have a look?

**Comment by madig** [comment]
Also র্রূ seems to wiggle its mark between your and our fonts.

Otherwise, I can spot no diffs between the default settings of your and our upright variable font.

**Comment by madig** [comment]
(did you change anything other than the features in Beta 9? The bottom part of ষ্বি moves between your and our italic VF)

**Comment by madig** [comment]
In the Italic, দ্ভু and দ্ভূ  and দ্ভৃ and others with the same base are broken in our font. Also, ক্ন্  is different/broken. Also, র্রূ and ৰ্রূ wiggles their mark.

**Comment by kalapi** [comment]
Hi can you send me comparison screenshots?

**Comment by madig** [comment]
Not at my work computer, but just drop your and our font into http://www.cyreal.org/Font-Testing-Page/ and type the sequences.

**Comment by kalapi** [comment]
Hi @madig, hope you had a restful weekend. Please go ahead with the shaping tests today and we'll fix whatever you find. Better to do that than to change the code base one small issue at a time.

**Comment by madig** [comment]
Ok, I passed everything over to our QA person. Let's see.

**Comment by madig** [comment]
Our QA guy finished up his report; the most salient thing he found is that anchors are inconsistent between uprights and italics (will check his findings on Monday):


*   ⚠️ WARNGlyph 'l\_ka-beng' has different anchors in different masters:  
    Text Italic has anchors: bottom, top  
    Text Bold Italic has anchors: bottom, top  
    Italic has anchors: bottom, top  
    Bold Italic has anchors: bottom, top  
    Text Regular has anchors: bottom, bottomright, top  
    Text Bold has anchors: bottom, bottomright, top  
    Regular has anchors: bottom, bottomright, top  
    Bold has anchors: bottom, bottomright, top
*   ⚠️ WARNGlyph 'bh\_ra\_uMatra-beng' has different anchors in different masters:  
    Text Italic has anchors: bottom, top  
    Text Bold Italic has anchors: bottom, top  
    Italic has anchors: bottom, top  
    Bold Italic has anchors: bottom, top  
    Text Regular has anchors: top  
    Text Bold has anchors: top  
    Regular has anchors: top  
    Bold has anchors: top
*   ⚠️ WARNGlyph 'dh\_ma-beng' has different anchors in different masters:  
    Text Italic has anchors: bottom, bottomright, top  
    Text Bold Italic has anchors: bottom, bottomright, top  
    Italic has anchors: bottom, bottomright, top  
    Bold Italic has anchors: bottom, bottomright, top  
    Text Regular has anchors: bottom, top  
    Text Bold has anchors: bottom, top  
    Regular has anchors: bottom, top  
    Bold has anchors: bottom, top
*   ⚠️ WARNGlyph 'ttha\_iMatra-beng' has different anchors in different masters:  
    Text Italic has anchors: bottom, top  
    Text Bold Italic has anchors: bottom, top  
    Italic has anchors: bottom, top  
    Bold Italic has anchors: bottom, top  
    Text Regular has anchors: top, topRight  
    Text Bold has anchors: top, topRight  
    Regular has anchors: top, topRight  
    Bold has anchors: top, topRight
*   ⚠️ WARNGlyph 'bh\_ra\_uuMatra-beng' has different anchors in different masters:  
    Text Italic has anchors: bottom, top  
    Text Bold Italic has anchors: bottom, top  
    Italic has anchors: bottom, top  
    Bold Italic has anchors: bottom, top  
    Text Regular has anchors: top  
    Text Bold has anchors: top  
    Regular has anchors: top  
    Bold has anchors: top
*   ⚠️ WARNGlyph 'ss\_ttha\_iMatra-beng' has different anchors in different masters:  
    Text Italic has anchors: bottom, top  
    Text Bold Italic has anchors: bottom, top  
    Italic has anchors: bottom, top  
    Bold Italic has anchors: bottom, top  
    Text Regular has anchors: top  
    Text Bold has anchors: top  
    Regular has anchors: top  
    Bold has anchors: top
*   ⚠️ WARNGlyph 'd\_ma-beng' has different anchors in different masters:  
    Text Italic has anchors: bottom, bottomright, top  
    Text Bold Italic has anchors: bottom, bottomright, top  
    Italic has anchors: bottom, bottomright, top  
    Bold Italic has anchors: bottom, bottomright, top  
    Text Regular has anchors: bottom, top  
    Text Bold has anchors: bottom, top  
    Regular has anchors: bottom, top  
    Bold has anchors: bottom, top
*   ⚠️ WARNGlyph 'dd-beng.half1' has different anchors in different masters:  
    Text Italic has anchors: bottomright, nukta, top  
    Text Bold Italic has anchors: bottomright, nukta, top  
    Italic has anchors: bottomright, nukta, top  
    Bold Italic has anchors: bottomright, nukta, top  
    Text Regular has anchors: bottomright, nukta, nukta.alt, top  
    Text Bold has anchors: bottomright, nukta, nukta.alt, top  
    Regular has anchors: bottomright, nukta, nukta.alt, top  
    Bold has anchors: bottomright, nukta, nukta.alt, top
*   ⚠️ WARNGlyph 'tth\_ba\_iiMatra-beng' has different anchors in different masters:  
    Text Italic has anchors: bottom, top, topLeft  
    Text Bold Italic has anchors: bottom, top, topLeft  
    Italic has anchors: bottom, top, topLeft  
    Bold Italic has anchors: bottom, top, topLeft  
    Text Regular has anchors: top, topLeft  
    Text Bold has anchors: top, topLeft  
    Regular has anchors: top, topLeft  
    Bold has anchors: top, topLeft
*   ⚠️ WARNGlyph 'nn\_ttha\_iiMatra-beng' has different anchors in different masters:  
    Text Italic has anchors: top, topLeft  
    Text Bold Italic has anchors: top, topLeft  
    Italic has anchors: top, topLeft  
    Bold Italic has anchors: top, topLeft  
    Text Regular has anchors: bottom, top, topLeft  
    Text Bold has anchors: bottom, top, topLeft  
    Regular has anchors: bottom, top, topLeft  
    Bold has anchors: bottom, top, topLeft
*   ⚠️ WARNGlyph 'j\_ra\_uMatra-beng' has different anchors in different masters:  
    Text Italic has anchors: bottom, top  
    Text Bold Italic has anchors: bottom, top  
    Italic has anchors: bottom, top  
    Bold Italic has anchors: bottom, top  
    Text Regular has anchors: top  
    Text Bold has anchors: top  
    Regular has anchors: top  
    Bold has anchors: top
*   ⚠️ WARNGlyph 'iMatra\_candraBindu-beng' has different anchors in different masters:  
    Text Italic has anchors: \_top  
    Text Bold Italic has anchors: \_top  
    Italic has anchors: \_top  
    Bold Italic has anchors: \_top  
    Text Regular has no anchors.  
    Text Bold has no anchors.  
    Regular has no anchors.  
    Bold has no anchors.
*   ⚠️ WARNGlyph 'j\_jha-beng' has different anchors in different masters:  
    Text Italic has anchors: bottom, top  
    Text Bold Italic has anchors: bottom, top  
    Italic has anchors: bottom, top  
    Bold Italic has anchors: bottom, top  
    Text Regular has anchors: bottom, bottomright, top  
    Text Bold has anchors: bottom, bottomright, top  
    Regular has anchors: bottom, bottomright, top  
    Bold has anchors: bottom, bottomright, top
*   ⚠️ WARNGlyph 'aa-beng' has different anchors in different masters:  
    Text Italic has no anchors.  
    Text Bold Italic has no anchors.  
    Italic has no anchors.  
    Bold Italic has no anchors.  
    Text Regular has anchors: bottom, top  
    Text Bold has anchors: bottom, top  
    Regular has anchors: bottom, top  
    Bold has anchors: bottom, top
*   ⚠️ WARNGlyph 'd\_ba-beng' has different anchors in different masters:  
    Text Italic has anchors: \_bottomright, bottom, top  
    Text Bold Italic has anchors: \_bottomright, bottom, top  
    Italic has anchors: \_bottomright, bottom, top  
    Bold Italic has anchors: \_bottomright, bottom, top  
    Text Regular has anchors: bottom, top  
    Text Bold has anchors: bottom, top  
    Regular has anchors: bottom, top  
    Bold has anchors: bottom, top
*   ⚠️ WARNGlyph 'j\_ra\_uuMatra-beng' has different anchors in different masters:  
    Text Italic has anchors: bottom, top  
    Text Bold Italic has anchors: bottom, top  
    Italic has anchors: bottom, top  
    Bold Italic has anchors: bottom, top  
    Text Regular has anchors: top  
    Text Bold has anchors: top  
    Regular has anchors: top  
    Bold has anchors: top
*   ⚠️ WARNGlyph 'ttha\_iiMatra-beng' has different anchors in different masters:  
    Text Italic has anchors: top, topLeft  
    Text Bold Italic has anchors: top, topLeft  
    Italic has anchors: top, topLeft  
    Bold Italic has anchors: top, topLeft  
    Text Regular has anchors: bottom, top, topLeft  
    Text Bold has anchors: bottom, top, topLeft  
    Regular has anchors: bottom, top, topLeft  
    Bold has anchors: bottom, top, topLeft
*   ⚠️ WARNGlyph 'g\_dha-beng' has different anchors in different masters:  
    Text Italic has anchors: bottom, bottomright, top  
    Text Bold Italic has anchors: bottom, bottomright, top  
    Italic has anchors: bottom, bottomright, top  
    Bold Italic has anchors: bottom, bottomright, top  
    Text Regular has anchors: bottom, top  
    Text Bold has anchors: bottom, top  
    Regular has anchors: bottom, top  
    Bold has anchors: bottom, top
*   ⚠️ WARNGlyph 'aaMatra-beng' has different anchors in different masters:  
    Text Italic has anchors: top  
    Text Bold Italic has anchors: top  
    Italic has anchors: top  
    Bold Italic has anchors: top  
    Text Regular has no anchors.  
    Text Bold has no anchors.  
    Regular has no anchors.  
    Bold has no anchors.
*   ⚠️ WARNGlyph 'nn\_ttha\_iMatra-beng' has different anchors in different masters:  
    Text Italic has anchors: bottom, top  
    Text Bold Italic has anchors: bottom, top  
    Italic has anchors: bottom, top  
    Bold Italic has anchors: bottom, top  
    Text Regular has anchors: bottom, top, topRight  
    Text Bold has anchors: bottom, top, topRight  
    Regular has anchors: bottom, top, topRight  
    Bold has anchors: bottom, top, topRight
*   ⚠️ WARNGlyph 'd\_bha-beng' has different anchors in different masters:  
    Text Italic has no anchors.  
    Text Bold Italic has no anchors.  
    Italic has no anchors.  
    Bold Italic has no anchors.  
    Text Regular has anchors: bottom, top  
    Text Bold has anchors: bottom, top  
    Regular has anchors: bottom, top  
    Bold has anchors: bottom, top

**Comment by kalapi** [comment]
Hi @madig 

Hope you had a good weekend. I'll check and fix the anchor issues. We have a couple other fixes (from your previous report) in the pipeline. 

My only question at this point is: Is the above anchor report include all the issues or are there more and this is just a truncated list/report?

**Comment by kalapi** [comment]
@madig 

This package contains all the fixes.

[2022-03-07_GoogleSansBangla_V1.000_BETA10.zip](https://github.com/googlefonts/googlesans/files/8196567/2022-03-07_GoogleSansBangla_V1.000_BETA10.zip)

**Comment by madig** [comment]
Thanks!

The full report says that he can't reproduce these:

* Renders differently: ক্ন্ ক্ল্ ক্ষ্ন্ ক্ষ্ব্ ক্ষ্র্ খ্ব্ গ্গ্
* র্রূ and ৰ্রূ seem to wiggle its mark between their and our fonts
* The bottom part of ষ্বি moves between their and our italic VF

and the following point might be caused by missing anchors:

* In the Italic, দ্ভু and দ্ভূ and দ্ভৃ and others with the same base are broken in our font. Also, ক্ন্ is different/broken.

As a general comment, he found

* There are differences between italics and uprights, eg. missing anchors, components vs outlines, node structure of unmerged outlines. 

Thought these may not be relevant (except anchors) because we don't interpolate.

I'll have a look again with your newest sources.

**Comment by madig** [comment]
Ok, none of the issues I found seem to happen anymore. Please have a look yourself:

* statics: https://github.com/googlefonts/googlesans/suites/5561025827/artifacts/179605507
* variable: https://github.com/googlefonts/googlesans/suites/5561025827/artifacts/179605508

**Comment by kalapi** [comment]
This is all good! We're good to merge! Thanks for your patience!!!
