### ISSUE TITLE
Use HarfBuzz as subsetter instead of fontTools?

### ISSUE THREAD

**Issue by madig** [googlefonts/googlesans#448]
As a way to dog-food it and think about how to deploy something that is not available on PyPI :) Or! Extending https://pypi.org/project/uharfbuzz/ to give access to the subsetter?

**Comment by chrissimpkins** [comment]
I really like this idea.  What is the status?  Is it ready for prime time?

One downside is that we are likely to encounter a compile duration time sink on every build unless we can cache it between builds in some fashion.  Can it be apt package manager installed in the GH runner Ubuntu environment?

**Comment by madig** [comment]
I don't know :) there is only one way to find out.

If we adapt uharfbuzz, we get binary wheels for free. If not, we need to grab a newer version than is likely available in packaging systems.

**Comment by chrissimpkins** [comment]
How about we try this in Flex and port it back to production Google Sans once we understand it?

**Comment by chrissimpkins** [comment]
We discussed this last week and will begin testing soon.

**Comment by madig** [comment]
https://github.com/harfbuzz/uharfbuzz/issues/102 here's the issue for it. Cosimo says it might take a couple days of figuring out which API to expose, stirring the source files (is the subsetter part of the amalgamated sources?) and copy-pasting code around. He suggests:

> basically, i'd first look at the c headers, familiarise with the interface (maybe look at how the hb-subset executable uses that) and then design a pythonic API to expose with cython, then go on implement that

**Comment by chrissimpkins** [comment]
related https://github.com/fonttools/fonttools/pull/2552

**Comment by chrissimpkins** [comment]
Marked with the v9 milestone.  Let's look into this quarter if there is time.
