### ISSUE TITLE
Glyphs sources converted from UFO appears to create a lot of alignment/horizontal metric errors.

### ISSUE THREAD

**Issue by NeilSureshPatel** [googlefonts/googlesans#452]
After running `make gs-ufo2glyphs` on the UFO sources in [https://github.com/googlefonts/googlesans/tree/neilsureshpatel-ethiopic](url) and opening the glyphs sources in Glyphs 2 (2.6.7 (1357)) I see a lot of glyphs flagged for alignment issues. The problem seems to affect glyphs that are on the GRAD masters and specifically those that have side-bearings that are linked explicitly other glyphs. Side-bearings that are inherited from a component are not affected. 

I have attached the generated Glyphs sources. Some of the errors are quite small, one or two units. In other cases, like the Georgian characters, the error is quite large. It appears that outlines for the Georgian characters do not change on the GRAD masters, which would explain the large errors since the side-bearings for Georgian characters are linked to Latin characters, which do have changes on the GRAD masters.

[GoogleSans-UFO2Glyphs.zip](https://github.com/googlefonts/googlesans/files/7973234/GoogleSans-UFO2Glyphs.zip)
.

**Comment by chrissimpkins** [comment]
Thoughts about our roundtrip source @belluzj @madig?

**Comment by madig** [comment]
Ah, hm. We never test the ufo2glyphs way and most scripts have no GRADing; we indiscriminately copy ungraded copies into the GRAD masters, so the metric data can be off. Select all glyphs and do "keep metrics", i.e. change nothing. Focus on the script you have control over :)

**Comment by NeilSureshPatel** [comment]
OK, I was concerned that if we were to use the ufo2glyphs to create new working sources for an update down the road that we would inject problems on the scripts other than the one we are working on. If the other scripts get merged back in after an update, then there is nothing to worry about. I was able to update our original Ethiopic Glyphs sources to change the kerning class names last night so I there is no need for us to have to work from sources created with ufo2glyphs.

**Comment by madig** [comment]
I typically import following a glyph name list :) only glyphs referenced therein plus their constituents if composite are imported, the rest is ignored.
