### ISSUE TITLE
[Khmer] Separation of ligature strokes Ba (U+1794) and Aa (U+17B6), and Ba (U+1794) and Au (U+17C5) @ bold weight + opsz 17

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans#454]
Identified during Khmer import in #417 

There is separation of the ligature strokes in these letters + vowel forms as shown in the image below:

<img width="1886" alt="2022-02-07_14-32-45" src="https://user-images.githubusercontent.com/4249591/152859236-b371d22a-a1ca-4661-8459-10b05ba8a746.png">

This occurs in the bold weight @ opsz 17 area of the design space only.  There are issues in both the Roman and Italic masters.

cc @cadsondemakoffice

**Comment by cadsondemakoffice** [comment]
Thank you very much @chrissimpkins we will check. and report the results soon.

**Comment by chrissimpkins** [comment]
Fixes from Tep to address this issue and the issue in #453:

- Updated `topright` and `bottomright` positions in `ba_aaSign-khmer` and `ba_auSign-khmer` glyphs
- Increased the width of `uuMark-khmer` and `uaMark-khmer`
- Shorten the flat hook in `uaMark-khmer.below2`
- Added a new glyphs: `ro-khmer.pre2.narrow` (ន្ទ្រូ ន្ទ្រួ)
- Updated the OT features adding lookup for `ro-khmer.pre2.narrow`
- Removed vertical PS hints in Italic masters
- Updated stroke width at the bottom bowl of `ro-khmer.pre2` in Italic (5 units)
- Updated width of: /ahsda-khmer.
- Updated italic of U+19E0 to U+19FF.
- No new anchors added. Some anchors might have been shifted a few units in on x.


[GoogleSansKH-20220220.zip](https://github.com/googlefonts/googlesans/files/8143509/GoogleSansKH-20220220.zip)

I need to clarify the changes that he described in the documentation above before we import the fixes.

cc @madig Let's plan to import this after we wrap up the Bangla merge.

**Comment by chrissimpkins** [comment]
I spoke with Tep today.  He made the glyph changes listed above and there were a handful of minor changes in the italic masters to address legibility issues that he recognized and are not documented in our tracker.  He is going to export a newline delimited list of all edited glyph names from his Glyphs application and forward it to me so that we know what we need to import.

The feature code update will be a a new `km_ro_pre2_narrow` lookup added in the below base substitution (`blws`) feature.  This is the OT fea that he indicated in the comment "Updated the OT features adding lookup for ro-khmer.pre2.narrow".  It will be used to address #453 and includes shaping information for the new `ro-khmer.pre2.narrow` glyph.

I'll update this thread when we have the full glyph set.  We're aiming to work on this in March following the Bangla import.

**Comment by chrissimpkins** [comment]
Full list of changes from Tep to address this issue and #453 below:

---

Here is the overview of the updates:

Overview:
- Updated `topright` and `bottomright` positions in `ba_aaSign-khmer` and `ba_auSign-khmer` glyphs
- Increased the width of `uuMark-khmer` and `uaMark-khmer`
- Shorten the flat hook in `uaMark-khmer.below2`
- Added a new glyphs: `ro-khmer.pre2.narrow` (ន្ទ្រូ ន្ទ្រួ)
- Updated the OT features adding lookup for `ro-khmer.pre2.narrow`
- Removed vertical PS hints in Italic masters
- Updated stroke width at the bottom bowl of `ro-khmer.pre2` in Italic (5 units)
- Updated width of: /ahsda-khmer.
- Updated italic of U+19E0 to U+19FF.
- No new anchors added. Some anchors might have been shifted a few units on x.

Edited glyphs
-------------------
Upright & Italic:
	ro-khmer.pre2.narrow (new)
	ba_aaSign-khmer
	ba_auSign-khmer
	uuMark-khmer
	uaMark-khmer
	uuMark-khmer.below2
	uaMark-khmer.below2
	ahsda-khmer

Italic:
	ro-khmer.pre2
	pathamasat-khmer
	muoykoet-khmer
	piikoet-khmer
	beikoet-khmer
	buonkoet-khmer
	pramkoet-khmer
	pramMuoykoet-khmer
	pramPiikoet-khmer
	pramBeikoet-khmer
	pramBuonkoet-khmer
	dapkoet-khmer
	dapMuoykoet-khmer
	dapPiikoet-khmer
	dapBeikoet-khmer
	dapBuonkoet-khmer
	dapPramkoet-khmer
	tuteyasat-khmer
	muoyroc-khmer
	piiroc-khmer
	beiroc-khmer
	buonroc-khmer
	pramroc-khmer
	pramMuoyroc-khmer
	pramPiiroc-khmer
	pramBeiroc-khmer
	pramBuonroc-khmer
	daproc-khmer
	dapMuoyroc-khmer
	dapPiiroc-khmer
	dapBeiroc-khmer
	dapBuonroc-khmer
	dapPramroc-khmer

**Comment by chrissimpkins** [comment]
Updated sources are available in https://github.com/googlefonts/googlesans/issues/454#issuecomment-1051106483

**Comment by chrissimpkins** [comment]
Will begin work on #454 and #453 this week

**Comment by madig** [comment]
Importing these files breaks the upright ro/vo mark attachment in the following strings:

* រ្រុរ្រូរ្រួ
* វ្រុវ្រូវ្រួ
* រូ​វូ​

Investigating...

**Comment by madig** [comment]
Oh right, it's the old issue about marks being converted differently and me having to move marks manually. Tep, can you please run the following script in Glyph.app's macro window: https://github.com/googlefonts/googlesans/issues/445#issuecomment-1040477159 and upload the .glyphs files again?

**Comment by madig** [comment]
(or @chrissimpkins, please see above, not sure Tep reads this issue?)

**Comment by chrissimpkins** [comment]
@madig I ran [the script](https://github.com/googlefonts/googlesans/issues/445#issuecomment-1040477159) across the [roman and italic Glyphs sources](https://github.com/googlefonts/googlesans/issues/454#issuecomment-1051106483) using Glyphs 2

Warnings in the Glyphs macro window:

```
WARNING:root:No info for qoo-khmer
WARNING:root:No info for qooVariant-khmer
WARNING:root:No info for yaSign-khmer
WARNING:root:No info for ieSign-khmer
WARNING:root:No info for eSign-khmer
WARNING:root:No info for aeSign-khmer
WARNING:root:No info for aiSign-khmer
WARNING:root:No info for ooSign-khmer
WARNING:root:No info for oeSign-khmer
WARNING:root:No info for qoo-khmer.below
WARNING:root:No info for yaSign-khmer.below2
WARNING:root:No info for ieSign-khmer.below2
WARNING:root:No info for yaSign-khmer.up
WARNING:root:No info for ieSign-khmer.up
WARNING:root:No info for yaSign-khmer.below2.up
WARNING:root:No info for ieSign-khmer.below2.up
WARNING:root:No info for NULL
```

Source files attached in the archive below.  I can loop in Tep if this doesn't address the issue.  Please let me know. Thanks!

[nw_script.zip](https://github.com/googlefonts/googlesans/files/8262937/nw_script.zip)
