### ISSUE TITLE
Dotted circle attachment

### ISSUE THREAD

**Issue by madig** [googlefonts/googlesans#458]
We now fail on the new fontbakery check:

```
 >> Check:   com.google.fonts/check/dotted_circle
    Desc:    Ensure dotted circle glyph is present and can attach marks.
    Files:   GoogleSansText-Regular.ttf

     FAIL The following glyphs could not be attached to the dotted circle
          glyph: - uni0A75 - uni0A51 - And uni0A4D [code:
          unattached-dotted-circle-marks]
    Result: FAIL
```

Gurmukhi in this case.

**Comment by chrissimpkins** [comment]
@kalapi see https://github.com/googlefonts/googlesans/issues/458#issue-1150389218

**Comment by chrissimpkins** [comment]
Will work around this issue with #461 and I'll speak with Kalapi about it next week.

**Comment by chrissimpkins** [comment]
Maybe we use this? https://github.com/googlefonts/ufo2ft/pull/593

**Comment by chrissimpkins** [comment]
I spoke with Kalapi about this today.  He is going to look into the issue and will be back in touch with us.

**Comment by madig** [comment]
The circle filter is very interesting! I think we should play with it once it lands (as we need to update ufo2ft then).

**Comment by chrissimpkins** [comment]
@kalapi Will you please let us know if this is something that you can fit in this month?

**Comment by chrissimpkins** [comment]
@madig I spoke with Kalapi today. He will push these updates tomorrow.
