### ISSUE TITLE
`opsz` axis is not working on Firefox + macOS (only)

### ISSUE THREAD

**Issue by khaledhosny** [googlefonts/googlesans#462]
I‘m not sure if this is a known issue, but Google Sans `opsz` axis does not seem to be working reliably on Firefox (for macOS). I noticed this first with Google Sans Arabic, but found the same issue with Google Sans, so I wonder if it is something related to the design space setup or the build pipeline.

Firefox (above `opsz `is set to 18, below 17):
![Firefox](https://user-images.githubusercontent.com/93914/156454513-32455e4c-b1f2-4df4-aba0-eeb32d4d0e7b.png)

Chrome:
![Chrome](https://user-images.githubusercontent.com/93914/156455015-a6a3444e-25cc-4430-89ab-4fad0cf6bcd6.png)

**Comment by madig** [comment]
It works in my tester clone. Try a different size unit?

**Comment by khaledhosny** [comment]
It does not work for me using either `font-variation-settings` or `font-optical-sizing`, there is slight change in the outlines like what you see if you set `opsz` axis to 17.9, but the big shift that should happen at 18 does not happen.

**Comment by madig** [comment]
`font-optical-sizing: auto;` works for me when using 17px and 18px side-by-side, same with `font-optical-sizing: none; font-variation-settings: 'opsz' 18, 'wght' 400, 'GRAD' 0;` and changing `opsz`.

**Comment by madig** [comment]
Doh! I overlooked the "macOS" part. Yeah, can confirm this does not work on the latest stable Firefox on macOS.

**Comment by davelab6** [comment]
Do other opsz fonts work?😅

**Comment by khaledhosny** [comment]
The other fonts with opsz on http://axis-praxis.org/ seem to work.

**Comment by chrissimpkins** [comment]
I wonder if it doesn't like our avar approach?

https://github.com/googlefonts/googlesans/blob/e9a47444edb976f9a26e83e9367ff6f5df1d5810/source/GoogleSans/GoogleSans.designspace#L4-L7

This is the only thing that I can think of that might be unique to the opsz axis in this family.

**Comment by chrissimpkins** [comment]
To be clear based on Niko's comment above, this does work on Firefox + Windows, but not Firefox + macOS?  What is the "tester clone" environment?

**Comment by khaledhosny** [comment]
> I wonder if it doesn't like our avar approach?
> 
> https://github.com/googlefonts/googlesans/blob/e9a47444edb976f9a26e83e9367ff6f5df1d5810/source/GoogleSans/GoogleSans.designspace#L4-L7
> 
> This is the only thing that I can think of that might be unique to the opsz axis in this family.

Seems so, if I remove the `<map input="17.990000" output="17.100000"/> ` line, the 18 opsz show correctly (but of course now moving between 17 and 18 shows the undesired interpolation this line was preventing).

**Comment by khaledhosny** [comment]
I’m convinced this is a Firefox bug, so I think I’ll make a test file that I can publicly share and report the issue.

**Comment by khaledhosny** [comment]
> To be clear based on Niko's comment above, this does work on Firefox + Windows, but not Firefox + macOS? What is the "tester clone" environment?

Didn’t test on Windows, but it works in Firefox for Android, so apparently a macOS-specific issue in Firefox.

Also while testing this I noticed that Chrome does not apply `opsz` by default for web fonts, but applies it for installed fonts, not sure if this is a known issue.

**Comment by madig** [comment]
> What is the "tester clone" environment?

https://github.com/impallari/font-testing-page

**Comment by chrissimpkins** [comment]
> Also while testing this I noticed that Chrome does not apply opsz by default for web fonts, but applies it for installed fonts, not sure if this is a known issue.

What OS?

**Comment by khaledhosny** [comment]
> > Also while testing this I noticed that Chrome does not apply opsz by default for web fonts, but applies it for installed fonts, not sure if this is a known issue.
> 
> What OS?

macOS and Android.

**Comment by khaledhosny** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1758147

**Comment by chrissimpkins** [comment]
I'll fill in details on untested platforms so that we understand the full scope of the issue and can raise other reports if necessary.  The use of avar for this is definitely a hack but I believe an OT valid one, so I agree with you that these may be considered browser bugs.  I wonder if we are bumping up against float precision issues.  We could try reducing the level of precision in the avar definitions to see if that addresses it. Alternatively we could bag the opsz avar altogether.  It was meant as a project-specific one unit opsz axis workaround for rvrn chained substitution problems that we ran into.  It wouldn't be a huge deal if there is interpolation from 17 - 18.  With the exception of a situation where a variable axis is exposed to end users and they drag across this range, someone animates across it (guidance has always suggested that this is a no no), or end users have the option to set text size at float values between 17 and 18, it will not be seen.

**Comment by chrissimpkins** [comment]
> https://bugzilla.mozilla.org/show_bug.cgi?id=1758147

Thank you very much for posting the report Khaled.

**Comment by chrissimpkins** [comment]
FWIW, this approach to opsz avar will need to go away with any future opsz axis range expansion so this might provide us with an opportunity to begin to think about how that looks.

**Comment by khaledhosny** [comment]
> Alternatively we could bag the opsz avar altogether

So far the current setup seems to be working everywhere I can test it, except Firefox for macOS, so I’d wait until we hear back from Mozilla, but otherwise your suggestion does not seem like a bad one since interpolating between 17 and 18 shouldn’t be an issue in practice as you outlined.

**Comment by chrissimpkins** [comment]
You also indicated the following [above](https://github.com/googlefonts/googlesans/issues/462#issuecomment-1059130278):

> Also while testing this I noticed that Chrome does not apply opsz by default for web fonts, but applies it for installed fonts, not sure if this is a known issue.

Did I misunderstand the issue in Chrome?

**Comment by khaledhosny** [comment]
I think Chrome issue is unrelated, but I need to test with other fonts. In Chrome `opsz` works correctly when manually set, but when using web fonts it does not automatically use the right `opsz` value based on font size. Installed fonts work correctly either way.

**Comment by khaledhosny** [comment]
The `avar` hack does not make a difference with Chrome, the behavior is reproduced either way. If the font is installed `opsz` is applied automatically based on font size, and not if the font is used as a web font.

**Comment by chrissimpkins** [comment]
It looks like the Firefox bug report was triaged.  No response yet.

**Comment by khaledhosny** [comment]
I’m starting to lean towards disabling that hack and live with it.

**Comment by chrissimpkins** [comment]
> I’m starting to lean towards disabling that hack and live with it.

_Edit_: Remove the opsz avar?

**Comment by khaledhosny** [comment]
> > I’m starting to lean towards disabling that hack and live with it.
> 
> Remove the avar table?

Or keep the `wght` mapping and drop the `opsz` mapping.

**Comment by chrissimpkins** [comment]
This was tagged as a bug in Firefox as part of their triage process.  It looks like they marked it as low priority for fix.

**Comment by chrissimpkins** [comment]
Discussed this issue with @justvanrossum and @JeremieHornus today.  This may be an issue in our GS CJK builds too.  Just is looking into it.

**Comment by belluzj** [comment]
Marianna says: let's reproduce the issue on GS and then try fixing the font by tweaking the numbers like the Mozilla person replied in Khaled's report, but as a backlog/low priority task. @Hoolean FYI

**Comment by madig** [comment]
A workaround is this, according to https://bugzilla.mozilla.org/show_bug.cgi?id=1758147:

```xml
    <axis tag="opsz" name="Size" minimum="17" maximum="18" default="18">
      <map input="17" output="17"/>
      <map input="17.9" output="17.01"/> <!-- 17.01 instead of 17.1 -->
      <map input="18" output="18"/>
    </axis>
```

**Comment by madig** [comment]
I sent Jonathan a mail to ask what we can do to help get the bug fixed.
