### ISSUE TITLE
Significant compile time performance hit with Ethiopic script import

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans#464]
Seen in https://github.com/googlefonts/googlesans/pull/451

Our VF format compile times increased from ~ 6 - 8 mins to ~ 14 - 15 mins.  Let's review and discuss.  Something seems odd about the two fold increase in compile time with these changes.

Related: #298 
Related topic (undocumented on this repo): incremental transition to Rust based libs in fontmake / Rust based compiler development.

**Comment by belluzj** [comment]
It could be due to the GPOS file size optimization:
* Ethiopic has lots of new GPOS to go through
* the GPOS optimization is still run in a silly way in fontmake (1 time per master, then the masters are merged with varLib, then once more on the result of the merge) when actually only the last time on the VF is needed. I was waiting for the fontTools config module to sort this out.

I could make a branch without the GPOS optimization just to see whether that's where the extra time comes from.

**Comment by madig** [comment]
Note: on my PC, in `build-bangla`, turning on GPOS compression makes total compile times go from 8:30 mins to ~12 mins.

FWIW, e.g. in the VF, we waste ~half of the time on compressing intermediate masters that only need to be compressed in a final step:

![image](https://user-images.githubusercontent.com/380829/157433241-53cc37e1-9abe-47e8-b9cb-d7769a1a48d8.png)

**Comment by belluzj** [comment]
Maybe I should propose a temporary solution in fontmake to turn off the compression for intermediate masters using the environment variable instead of waiting for the proper fonttools config module?

**Comment by madig** [comment]
Mh yeah, maybe temporarily pop `FONTTOOLS_GPOS_COMPACT_MODE` from `os.environ` while doing the intermediates and putting it back for thefinal step? I think this needs some fiddling in fontmake though to figure out what the end goal is, as in, don't do this if you want to output interpolatable-ttf. Or something.

**Comment by chrissimpkins** [comment]
Is there time to work on this soon'ish?  The commit-based CI is going to slow down significantly during the iterative work that happens during script imports.

**Comment by madig** [comment]
(Anecdote: I keep removing the env var from the Makefile while iterating and then keep accidentally commiting the change. Grrr)

**Comment by belluzj** [comment]
> Is there time to work on this soon'ish?

Yes we'll have a look, it's supposed to be relatively easy.

**Comment by madig** [comment]
https://github.com/googlefonts/ufo2ft/pull/599 cuts VF compilation time roughly half but does not help for instance generation. Not sure how to mitigate this? We do want compression during script integration to gauge size increases at the end...

**Comment by chrissimpkins** [comment]
"for a secret font project" lol

**Comment by chrissimpkins** [comment]
> [googlefonts/ufo2ft#599](https://github.com/googlefonts/ufo2ft/pull/599) cuts VF compilation time roughly half but does not help for instance generation. Not sure how to mitigate this? We do want compression during script integration to gauge size increases at the end...

I believe that we've eliminated the static instance builds in all non-`build*` prefix branches?  Probably ok to push the PR's to branches that do not build the statics and run manual static instance build checks at key points during the import process?  And definitely at the end of revision work before merge.

**Comment by chrissimpkins** [comment]
> cuts VF compilation time roughly half 

and this is good news!

**Comment by madig** [comment]
> I believe that we've eliminated the static instance builds in all non-build* prefix branches?

Yes, but all script import branches are `build-*` branches. I mean I build locally anyway with the env var disabled but hm. It's almost as if we need to go full DevOps with dotenv files and stuff.

**Comment by chrissimpkins** [comment]
Yes.  I am suggesting that we abandon the practice of using `build-*` branches for imports in the future as a workaround until a static instance speedup is in place.  We can confirm that the statics pass once after the import happens and again just prior to the merge since we usually make some changes between those two stages of the import process.  I don't think that they need to be tested at every commit.  The import PR's generally have a significant number of commits as we iterate based on issues that we identify and rebase.

**Comment by chrissimpkins** [comment]
The latest Bangla import branch is using 30 mins of billable Enterprise runner time **per commit**.  Let's discontinue the use of `build-*` branches for active PR work beginning immediately.  Push to a build branch only when you need to build assets for download and review.

**Comment by chrissimpkins** [comment]
> Any progress on the GPOS packing 

https://github.com/googlefonts/ufo2ft/pull/599 was merged.  We'll look into a pipeline dependency update for the v9 release.

**Comment by madig** [comment]
Interesting tidbit: I ran https://pypi.org/project/memray/ on fontmake building a GS VF from the build-bangla branch and got this report: [memray-flamegraph-fontmake.421.html.zip](https://github.com/googlefonts/googlesans/files/8542024/memray-flamegraph-fontmake.421.html.zip)

![image](https://user-images.githubusercontent.com/380829/164741983-49005f5d-eb0f-4263-a2f1-2ddec1496f44.png)

Peak memory usage was 3 GB, merging the OTL tables alone peaked at 1.2 GB. Not sure if this is the overflow fixing stuff? fontmake's compatibility checker allocates a lot, too, for reasons not immediately obvious to me (reloading glyphs from disk?). Something deepcopying kerning stuff accounts for a lot of allocations:

![image](https://user-images.githubusercontent.com/380829/164742331-6763e3cb-ed79-4b1d-8d0b-62257eb83dff.png)

Noto Sans was much less interesting, though it still peaked at 780 MB.

**Comment by chrissimpkins** [comment]
Do we know if we are spending alot of time in execution that leads to these warnings?

> WARNING:fontTools.ttLib.tables.otBase:hb.repack failed to serialize 'GPOS', reverting to pure-python serializer; the error message was: RepackerError

If so, can we avoid the hb packing attempt altogether?

**Comment by madig** [comment]
We can't, because the option to do so is not exposed anywhere AFAICS.

According to py-spy, we spend ~9% of the runtime gather data for HB and then doing something with it I guess when compiling a single VF.

**Comment by chrissimpkins** [comment]
It looks like we can turn off HB packing at the subsetter level:

https://github.com/fonttools/fonttools/blob/42e4d66184be1acda05bed1896da6d61c084835e/Lib/fontTools/subset/__init__.py#L155-L156

**Comment by madig** [comment]
Mh yeah, but the major time sink is compiling the font in the first place.

**Comment by chrissimpkins** [comment]
Latest release build including the new ttf-interpolatable format files [is now 50 mins](https://github.com/googlefonts/googlesans/pull/504#issuecomment-1140039560).

**Comment by chrissimpkins** [comment]
Are we feeling better about where we are now @belluzj @madig @Hoolean?

**Comment by belluzj** [comment]
Yes the bigger runner is helping a lot. We'll still come back to investigating pypi and updating dependencies to get Garret's faster GPOS packing, but it's not a blocking issue anymore. We could close this one.
