### ISSUE TITLE
Potential GDEF miscategorization of some glyphs

### ISSUE THREAD

**Issue by madig** [googlefonts/googlesans#466]
Fontbakery complains about the following glyphs:

Non-mark glyphs should not be a GDEF mark (`com.google.fonts/check/gdef_non_mark_chars`):

* U+0A03 GURMUKHI SIGN VISARGA
* U+0BBF TAMIL VOWEL SIGN I
* U+0BC1 TAMIL VOWEL SIGN U
* U+0BC2 TAMIL VOWEL SIGN UU

And, probably redundantly, these spacing glyphs should not be a GDEF mark (`com.google.fonts/check/gdef_spacing_marks`):

* uni0A03 (U+0A03)
* uni0BBF (U+0BBF)
* uni0BBF.alt (unencoded)
* uni0BC1 (U+0BC1)
* uni0BC2 (U+0BC2)

These warnings are annoying because they fill multiple screens. @kalapi can we recategorize these glyphs somehow to satisfy fontbakery? Or are the warnings wrong?

**Comment by chrissimpkins** [comment]
I spoke with Kalapi today.  He is going to have a look through the list of glyphs above and will respond in this thread.  On a quick glance through the sources, he felt that some may be incorrectly labeled as warnings, others are possibly real issues.

**Comment by kalapi** [comment]
Hi @madig, 

I've applied a patch for the above issue in the Tamil package. Attaching the files with this comment. Gurmukhi patch coming up. 

[2022-03-18_GoogleSansTamil_V1.010_BETA01.zip](https://github.com/googlefonts/googlesans/files/8304092/2022-03-18_GoogleSansTamil_V1.010_BETA01.zip)

**Comment by kalapi** [comment]
Here is the Gurmukhi package addressing the issue of the Visarga (U+0A03) and also the dotted circle issue from #458 

[2022-03-19_GoogleSans_Gurmukhi.zip](https://github.com/googlefonts/googlesans/files/8308662/2022-03-19_GoogleSans_Gurmukhi.zip)

**Comment by chrissimpkins** [comment]
Thank you very much Kalapi!

**Comment by madig** [comment]
@kalapi Thanks. Can you please explain the changes in Tamil?

* The dotted circle is losing a lot of anchors, why? Have you tested the impact on other scripts, i.e. Khmer?
* What are the changes done to iiMatra*, anusvara and pulli?

Also, can you please run the script in https://github.com/googlefonts/googlesans/issues/445#issuecomment-1040477159 again to ensure we aren't losing valuable metadata on conversion?

**Comment by kalapi** [comment]
Hi @madig,

Maybe i'm misunderstanding the issue with the `dottedCircle` glyph but the anchors in the Tamil sources only supports marks for the Tamil script.

The changes to iiMatra, anusvara, and pulli is the collapse of their advance width to zero. 

Also, I just realised that for the Tamil I sent you a ZIP with multiple other (older) packages included. Please let me know what you're expecting with regards to the dottedCircle anchors, i'll update as necessary and send you a new package.

**Comment by madig** [comment]
Ok, so I'll just not import dottedCircle :) unless you made changes to it that you want us to land? If so, please use the latest dottedCircle and update it accordingly, you can use the files from https://github.com/googlefonts/googlesans/actions/runs/1994507398 when the job is done running.

Also, what changes are done to the quotes?

I see now that some warnings for Tamil are fixed, but they are still misclassified. Please run the script to embed the proper information into the files.

**Comment by kalapi** [comment]
Hi @madig 

The changes to the quotes are the shape differences between the two optical sizes. This was not included in the last release.

Attaching an updated package. This should fix all the classifications. 

[2022-03-21_GoogleSansTamil_V1.010_BETA01_R02.zip](https://github.com/googlefonts/googlesans/files/8315693/2022-03-21_GoogleSansTamil_V1.010_BETA01_R02.zip)

**Comment by madig** [comment]
Thanks, will have a look. Please do the same for the Gurmukhi package, including explaining the changes.

**Comment by kalapi** [comment]
Here is the Gurmukhi package: 

Changes:

- Fixes original GDEF issue in Visarga (U+0A03 GURMUKHI SIGN VISARGA)
- Changes anchor names on `uni0A75`, `uni0A51`, and `uni0A4D` which were causing issue #458 
- Decomposes transformed component `udaat-gurmukhi`
- Updates shapes of `comma`, `semicolon`, and all quotes to include optical size differences
- Adds anchors in component glyphs to solve propagation issue
- Embeds GlyphData info

[2022-03-21_GoogleSans_Gurmukhi_R02.zip](https://github.com/googlefonts/googlesans/files/8315913/2022-03-21_GoogleSans_Gurmukhi_R02.zip)

**Comment by madig** [comment]
Thanks again. I'm looking at the Tamil dottedCircle and some anchors are gone again? Are your changes there intended and necessary? I'd rather not import them unless you have tested them with all scripts that use them. I can provide new upstream sources after a first import batch.

**Comment by kalapi** [comment]
Sorry, I should've removed it from the glyph list file. Please ignore it. Even in the Gurmukhi.

**Comment by madig** [comment]
Ok.

Also, the "k_ssa-tamil" glyph is now a base instead of a ligature, is that intentional?

**Comment by kalapi** [comment]
Yes, no 'ligature' GDEF types in Indic scripts :)

**Comment by madig** [comment]
So, fontbakery still complains about iMatra-tamil, uuMatra-tamil, iMatra-tamil.alt and uMatra-tamil being spacing _and_ a GDEF mark, which was the initial issue. The question here is, are they really marks in the GDEF sense or bases? Fontbakery complains about any GDEF mark that also spaces.

**Comment by kalapi** [comment]
That's strange because the fonts i'm producing on my end don't have those glyphs even listed in the GDEF. Here is how they're classified in Unicode:

- `iMatra-tamil`: mark; spacing-combining
- `uuMatra-tamil`: mark; spacing-combining
- `iMatra-tamil.alt`: unencoded but classification same as `iMatra-tamil`
- `uMatra-tamil`: mark; spacing-combining

In the case of Google Sans these are Bases because neither attach to other bases.

I'm still puzzled about how they're being defined as marks despite the embeded info saying `Letter`; `Spacing`

**Comment by madig** [comment]
Hm, have you modified them in any way? They are not on the import list actually.

**Comment by kalapi** [comment]
Ah no, I haven't modified them. Maybe we should import the entire list since we've changed/updates the glyph-data classification across the set?

**Comment by kalapi** [comment]
Hi @madig, adding packages with the full list of glyphs to import. 

Tamil: [2022-03-21_GoogleSansTamil_V1.010_BETA01_R03.zip](https://github.com/googlefonts/googlesans/files/8317249/2022-03-21_GoogleSansTamil_V1.010_BETA01_R03.zip)

Gurmukhi: [2022-03-21_GoogleSans_Gurmukhi_R03.zip](https://github.com/googlefonts/googlesans/files/8317260/2022-03-21_GoogleSans_Gurmukhi_R03.zip)

**Comment by madig** [comment]
Thanks. I refreshed the Tamil metadata and it seems to work as intended now.

I noticed `u-gurmukhi` is a base in the italics but unclassified in the uprights. Intentional?

**Comment by kalapi** [comment]
Strange again, no they should both be bases. :/

**Comment by madig** [comment]
Ok, the normalization script took care of it :)

Please test the artifacts in https://github.com/googlefonts/googlesans/actions/runs/2018425945.

Here's the glyph metdata:

|name                  |postscript_name    |unicodes|opentype_category|
|----------------------|-------------------|--------|-----------------|
|anusvara-tamil        |uni0B82            |0B82    |mark             |
|visarga-tamil         |uni0B83            |0B83    |                 |
|a-tamil               |uni0B85            |0B85    |                 |
|aa-tamil              |uni0B86            |0B86    |                 |
|i-tamil               |uni0B87            |0B87    |                 |
|ii-tamil              |uni0B88            |0B88    |                 |
|u-tamil               |uni0B89            |0B89    |                 |
|uu-tamil              |uni0B8A            |0B8A    |                 |
|e-tamil               |uni0B8E            |0B8E    |                 |
|ee-tamil              |uni0B8F            |0B8F    |                 |
|ai-tamil              |uni0B90            |0B90    |                 |
|o-tamil               |uni0B92            |0B92    |                 |
|oo-tamil              |uni0B93            |0B93    |                 |
|au-tamil              |uni0B94            |0B94    |base             |
|ka-tamil              |uni0B95            |0B95    |base             |
|nga-tamil             |uni0B99            |0B99    |base             |
|ca-tamil              |uni0B9A            |0B9A    |base             |
|ja-tamil              |uni0B9C            |0B9C    |base             |
|nya-tamil             |uni0B9E            |0B9E    |base             |
|tta-tamil             |uni0B9F            |0B9F    |base             |
|nna-tamil             |uni0BA3            |0BA3    |base             |
|ta-tamil              |uni0BA4            |0BA4    |base             |
|na-tamil              |uni0BA8            |0BA8    |base             |
|nnna-tamil            |uni0BA9            |0BA9    |base             |
|pa-tamil              |uni0BAA            |0BAA    |base             |
|ma-tamil              |uni0BAE            |0BAE    |base             |
|ya-tamil              |uni0BAF            |0BAF    |base             |
|ra-tamil              |uni0BB0            |0BB0    |base             |
|rra-tamil             |uni0BB1            |0BB1    |base             |
|la-tamil              |uni0BB2            |0BB2    |base             |
|lla-tamil             |uni0BB3            |0BB3    |base             |
|llla-tamil            |uni0BB4            |0BB4    |base             |
|va-tamil              |uni0BB5            |0BB5    |base             |
|sha-tamil             |uni0BB6            |0BB6    |base             |
|ssa-tamil             |uni0BB7            |0BB7    |base             |
|sa-tamil              |uni0BB8            |0BB8    |base             |
|ha-tamil              |uni0BB9            |0BB9    |base             |
|aaMatra-tamil         |uni0BBE            |0BBE    |                 |
|iMatra-tamil          |uni0BBF            |0BBF    |                 |
|iiMatra-tamil         |uni0BC0            |0BC0    |mark             |
|uMatra-tamil          |uni0BC1            |0BC1    |                 |
|uuMatra-tamil         |uni0BC2            |0BC2    |                 |
|eMatra-tamil          |uni0BC6            |0BC6    |                 |
|eeMatra-tamil         |uni0BC7            |0BC7    |                 |
|aiMatra-tamil         |uni0BC8            |0BC8    |                 |
|oMatra-tamil          |uni0BCA            |0BCA    |base             |
|ooMatra-tamil         |uni0BCB            |0BCB    |base             |
|auMatra-tamil         |uni0BCC            |0BCC    |base             |
|pulli-tamil           |uni0BCD            |0BCD    |mark             |
|om-tamil              |uni0BD0            |0BD0    |                 |
|aulengthmark-tamil    |uni0BD7            |0BD7    |base             |
|zero-tamil            |uni0BE6            |0BE6    |                 |
|one-tamil             |uni0BE7            |0BE7    |                 |
|two-tamil             |uni0BE8            |0BE8    |                 |
|three-tamil           |uni0BE9            |0BE9    |                 |
|four-tamil            |uni0BEA            |0BEA    |                 |
|five-tamil            |uni0BEB            |0BEB    |                 |
|six-tamil             |uni0BEC            |0BEC    |                 |
|seven-tamil           |uni0BED            |0BED    |                 |
|eight-tamil           |uni0BEE            |0BEE    |                 |
|nine-tamil            |uni0BEF            |0BEF    |                 |
|ten-tamil             |uni0BF0            |0BF0    |                 |
|onehundred-tamil      |uni0BF1            |0BF1    |                 |
|onethousand-tamil     |uni0BF2            |0BF2    |                 |
|day-tamil             |uni0BF3            |0BF3    |                 |
|month-tamil           |uni0BF4            |0BF4    |                 |
|year-tamil            |uni0BF5            |0BF5    |                 |
|debit-tamil           |uni0BF6            |0BF6    |                 |
|credit-tamil          |uni0BF7            |0BF7    |                 |
|asabove-tamil         |uni0BF8            |0BF8    |                 |
|rupee-tamil           |uni0BF9            |0BF9    |                 |
|number-tamil          |uni0BFA            |0BFA    |                 |
|k_ssa-tamil           |uni0B950BCD0BB7    |        |base             |
|iMatra-tamil.alt      |uni0BBF.alt        |        |                 |
|iiMatra-tamil.alt     |uni0BC0.alt        |        |mark             |
|ka_iMatra-tamil       |uni0B950BBF        |        |                 |
|ca_iMatra-tamil       |uni0B9A0BBF        |        |                 |
|ja_iMatra-tamil       |uni0B9C0BBF        |        |                 |
|nya_iMatra-tamil      |uni0B9E0BBF        |        |                 |
|tta_iMatra-tamil      |uni0B9F0BBF        |        |                 |
|ta_iMatra-tamil       |uni0BA40BBF        |        |                 |
|na_iMatra-tamil       |uni0BA80BBF        |        |                 |
|ma_iMatra-tamil       |uni0BAE0BBF        |        |                 |
|rra_iMatra-tamil      |uni0BB10BBF        |        |                 |
|la_iMatra-tamil       |uni0BB20BBF        |        |                 |
|llla_iMatra-tamil     |uni0BB40BBF        |        |                 |
|ssa_iMatra-tamil      |uni0BB70BBF        |        |                 |
|sa_iMatra-tamil       |uni0BB80BBF        |        |                 |
|ha_iMatra-tamil       |uni0BB90BBF        |        |                 |
|k_ssa_iMatra-tamil    |uni0B950BCD0BB70BBF|        |                 |
|ja_iiMatra-tamil      |uni0B9C0BC0        |        |                 |
|ma_iiMatra-tamil      |uni0BAE0BC0        |        |                 |
|rra_iiMatra-tamil     |uni0BB10BC0        |        |                 |
|la_iiMatra-tamil      |uni0BB20BC0        |        |                 |
|llla_iiMatra-tamil    |uni0BB40BC0        |        |                 |
|ssa_iiMatra-tamil     |uni0BB70BC0        |        |                 |
|sa_iiMatra-tamil      |uni0BB80BC0        |        |                 |
|ha_iiMatra-tamil      |uni0BB90BC0        |        |                 |
|k_ssa_iiMatra-tamil   |uni0B950BCD0BB70BC0|        |                 |
|sh_ra_iiMatra-tamil   |uni0BB60BCD0BB00BC0|        |                 |
|ka_uMatra-tamil       |uni0B950BC1        |        |                 |
|nga_uMatra-tamil      |uni0B990BC1        |        |                 |
|ca_uMatra-tamil       |uni0B9A0BC1        |        |                 |
|nya_uMatra-tamil      |uni0B9E0BC1        |        |                 |
|tta_uMatra-tamil      |uni0B9F0BC1        |        |                 |
|nna_uMatra-tamil      |uni0BA30BC1        |        |                 |
|ta_uMatra-tamil       |uni0BA40BC1        |        |                 |
|na_uMatra-tamil       |uni0BA80BC1        |        |                 |
|nnna_uMatra-tamil     |uni0BA90BC1        |        |                 |
|pa_uMatra-tamil       |uni0BAA0BC1        |        |                 |
|ma_uMatra-tamil       |uni0BAE0BC1        |        |                 |
|ya_uMatra-tamil       |uni0BAF0BC1        |        |                 |
|ra_uMatra-tamil       |uni0BB00BC1        |        |                 |
|rra_uMatra-tamil      |uni0BB10BC1        |        |                 |
|la_uMatra-tamil       |uni0BB20BC1        |        |                 |
|lla_uMatra-tamil      |uni0BB30BC1        |        |                 |
|llla_uMatra-tamil     |uni0BB40BC1        |        |                 |
|va_uMatra-tamil       |uni0BB50BC1        |        |                 |
|ssa_uMatra-tamil      |uni0BB70BC1        |        |                 |
|sa_uMatra-tamil       |uni0BB80BC1        |        |                 |
|ha_uMatra-tamil       |uni0BB90BC1        |        |                 |
|k_ssa_uMatra-tamil    |uni0B950BCD0BB70BC1|        |                 |
|ka_uuMatra-tamil      |uni0B950BC2        |        |                 |
|nga_uuMatra-tamil     |uni0B990BC2        |        |                 |
|ca_uuMatra-tamil      |uni0B9A0BC2        |        |                 |
|nya_uuMatra-tamil     |uni0B9E0BC2        |        |                 |
|tta_uuMatra-tamil     |uni0B9F0BC2        |        |                 |
|nna_uuMatra-tamil     |uni0BA30BC2        |        |                 |
|ta_uuMatra-tamil      |uni0BA40BC2        |        |                 |
|na_uuMatra-tamil      |uni0BA80BC2        |        |                 |
|nnna_uuMatra-tamil    |uni0BA90BC2        |        |                 |
|pa_uuMatra-tamil      |uni0BAA0BC2        |        |                 |
|ma_uuMatra-tamil      |uni0BAE0BC2        |        |                 |
|ya_uuMatra-tamil      |uni0BAF0BC2        |        |                 |
|ra_uuMatra-tamil      |uni0BB00BC2        |        |                 |
|rra_uuMatra-tamil     |uni0BB10BC2        |        |                 |
|la_uuMatra-tamil      |uni0BB20BC2        |        |                 |
|lla_uuMatra-tamil     |uni0BB30BC2        |        |                 |
|llla_uuMatra-tamil    |uni0BB40BC2        |        |                 |
|va_uuMatra-tamil      |uni0BB50BC2        |        |                 |
|ssa_uuMatra-tamil     |uni0BB70BC2        |        |                 |
|sa_uuMatra-tamil      |uni0BB80BC2        |        |                 |
|ha_uuMatra-tamil      |uni0BB90BC2        |        |                 |
|k_ssa_uuMatra-tamil   |uni0B950BCD0BB70BC2|        |                 |
|period.loclTAML       |                   |        |                 |
|comma.loclTAML        |                   |        |                 |
|colon.loclTAML        |                   |        |                 |
|semicolon.loclTAML    |                   |        |                 |
|ellipsis.loclTAML     |                   |        |                 |
|exclam.loclTAML       |                   |        |                 |
|question.loclTAML     |                   |        |                 |
|asterisk.loclTAML     |                   |        |                 |
|parenleft.loclTAML    |                   |        |                 |
|parenright.loclTAML   |                   |        |                 |
|braceleft.loclTAML    |                   |        |                 |
|braceright.loclTAML   |                   |        |                 |
|bracketleft.loclTAML  |                   |        |                 |
|bracketright.loclTAML |                   |        |                 |
|quotedblleft.loclTAML |                   |        |                 |
|quotedblright.loclTAML|                   |        |                 |
|quoteleft.loclTAML    |                   |        |                 |
|quoteright.loclTAML   |                   |        |                 |
|zero.loclTAML         |                   |        |                 |
|one.loclTAML          |                   |        |                 |
|two.loclTAML          |                   |        |                 |
|three.loclTAML        |                   |        |                 |
|four.loclTAML         |                   |        |                 |
|five.loclTAML         |                   |        |                 |
|six.loclTAML          |                   |        |                 |
|seven.loclTAML        |                   |        |                 |
|eight.loclTAML        |                   |        |                 |
|nine.loclTAML         |                   |        |                 |
|zero.loclTAML.tf      |                   |        |                 |
|one.loclTAML.tf       |                   |        |                 |
|two.loclTAML.tf       |                   |        |                 |
|three.loclTAML.tf     |                   |        |                 |
|four.loclTAML.tf      |                   |        |                 |
|five.loclTAML.tf      |                   |        |                 |
|six.loclTAML.tf       |                   |        |                 |
|seven.loclTAML.tf     |                   |        |                 |
|eight.loclTAML.tf     |                   |        |                 |
|nine.loclTAML.tf      |                   |        |                 |
|slash.loclTAML        |                   |        |                 |

And:

|name                  |postscript_name    |unicodes|opentype_category|
|----------------------|-------------------|--------|-----------------|
|adakbindi-gurmukhi    |uni0A01            |0A01    |mark             |
|bindi-gurmukhi        |uni0A02            |0A02    |mark             |
|visarga-gurmukhi      |uni0A03            |0A03    |                 |
|a-gurmukhi            |uni0A05            |0A05    |base             |
|aa-gurmukhi           |uni0A06            |0A06    |base             |
|i-gurmukhi            |uni0A07            |0A07    |base             |
|ii-gurmukhi           |uni0A08            |0A08    |base             |
|u-gurmukhi            |uni0A09            |0A09    |base             |
|uu-gurmukhi           |uni0A0A            |0A0A    |base             |
|ee-gurmukhi           |uni0A0F            |0A0F    |base             |
|ai-gurmukhi           |uni0A10            |0A10    |base             |
|oo-gurmukhi           |uni0A13            |0A13    |base             |
|au-gurmukhi           |uni0A14            |0A14    |base             |
|ka-gurmukhi           |uni0A15            |0A15    |base             |
|kha-gurmukhi          |uni0A16            |0A16    |base             |
|ga-gurmukhi           |uni0A17            |0A17    |base             |
|gha-gurmukhi          |uni0A18            |0A18    |base             |
|nga-gurmukhi          |uni0A19            |0A19    |base             |
|ca-gurmukhi           |uni0A1A            |0A1A    |base             |
|cha-gurmukhi          |uni0A1B            |0A1B    |base             |
|ja-gurmukhi           |uni0A1C            |0A1C    |base             |
|jha-gurmukhi          |uni0A1D            |0A1D    |base             |
|nya-gurmukhi          |uni0A1E            |0A1E    |base             |
|tta-gurmukhi          |uni0A1F            |0A1F    |base             |
|ttha-gurmukhi         |uni0A20            |0A20    |base             |
|dda-gurmukhi          |uni0A21            |0A21    |base             |
|ddha-gurmukhi         |uni0A22            |0A22    |base             |
|nna-gurmukhi          |uni0A23            |0A23    |base             |
|ta-gurmukhi           |uni0A24            |0A24    |base             |
|tha-gurmukhi          |uni0A25            |0A25    |base             |
|da-gurmukhi           |uni0A26            |0A26    |base             |
|dha-gurmukhi          |uni0A27            |0A27    |base             |
|na-gurmukhi           |uni0A28            |0A28    |base             |
|pa-gurmukhi           |uni0A2A            |0A2A    |base             |
|pha-gurmukhi          |uni0A2B            |0A2B    |base             |
|ba-gurmukhi           |uni0A2C            |0A2C    |base             |
|bha-gurmukhi          |uni0A2D            |0A2D    |base             |
|ma-gurmukhi           |uni0A2E            |0A2E    |base             |
|ya-gurmukhi           |uni0A2F            |0A2F    |base             |
|ra-gurmukhi           |uni0A30            |0A30    |base             |
|la-gurmukhi           |uni0A32            |0A32    |base             |
|lla-gurmukhi          |uni0A33            |0A33    |base             |
|va-gurmukhi           |uni0A35            |0A35    |base             |
|sha-gurmukhi          |uni0A36            |0A36    |base             |
|sa-gurmukhi           |uni0A38            |0A38    |base             |
|ha-gurmukhi           |uni0A39            |0A39    |base             |
|nukta-gurmukhi        |uni0A3C            |0A3C    |mark             |
|aaMatra-gurmukhi      |uni0A3E            |0A3E    |base             |
|iMatra-gurmukhi       |uni0A3F            |0A3F    |                 |
|iiMatra-gurmukhi      |uni0A40            |0A40    |base             |
|uMatra-gurmukhi       |uni0A41            |0A41    |mark             |
|uuMatra-gurmukhi      |uni0A42            |0A42    |mark             |
|eeMatra-gurmukhi      |uni0A47            |0A47    |mark             |
|aiMatra-gurmukhi      |uni0A48            |0A48    |mark             |
|ooMatra-gurmukhi      |uni0A4B            |0A4B    |mark             |
|auMatra-gurmukhi      |uni0A4C            |0A4C    |mark             |
|halant-gurmukhi       |uni0A4D            |0A4D    |mark             |
|udaat-gurmukhi        |uni0A51            |0A51    |mark             |
|khha-gurmukhi         |uni0A59            |0A59    |base             |
|ghha-gurmukhi         |uni0A5A            |0A5A    |base             |
|za-gurmukhi           |uni0A5B            |0A5B    |base             |
|rra-gurmukhi          |uni0A5C            |0A5C    |base             |
|fa-gurmukhi           |uni0A5E            |0A5E    |base             |
|zero-gurmukhi         |uni0A66            |0A66    |                 |
|one-gurmukhi          |uni0A67            |0A67    |                 |
|two-gurmukhi          |uni0A68            |0A68    |                 |
|three-gurmukhi        |uni0A69            |0A69    |                 |
|four-gurmukhi         |uni0A6A            |0A6A    |                 |
|five-gurmukhi         |uni0A6B            |0A6B    |                 |
|six-gurmukhi          |uni0A6C            |0A6C    |                 |
|seven-gurmukhi        |uni0A6D            |0A6D    |                 |
|eight-gurmukhi        |uni0A6E            |0A6E    |                 |
|nine-gurmukhi         |uni0A6F            |0A6F    |                 |
|tippi-gurmukhi        |uni0A70            |0A70    |mark             |
|addak-gurmukhi        |uni0A71            |0A71    |mark             |
|iri-gurmukhi          |uni0A72            |0A72    |base             |
|ura-gurmukhi          |uni0A73            |0A73    |base             |
|ekonkar-gurmukhi      |uni0A74            |0A74    |                 |
|yakash-gurmukhi       |uni0A75            |0A75    |mark             |
|abbreviation-gurmukhi |uni0A76            |0A76    |                 |
|danda-deva.loclGURM   |uni0964.loclGURM   |        |                 |
|dbldanda-deva.loclGURM|uni0965.loclGURM   |        |                 |
|rakar-gurmukhi        |uni0A4D0A30        |        |mark             |
|va-gurmukhi.below     |uni0A4D0A35        |        |mark             |
|ha-gurmukhi.below     |uni0A4D0A39        |        |mark             |
|ca-gurmukhi.below     |uni0A4D0A1A        |        |mark             |
|tta-gurmukhi.below    |uni0A4D0A1F        |        |mark             |
|ta-gurmukhi.below     |uni0A4D0A24        |        |mark             |
|ya-gurmukhi.psts      |uni0A4D0A2F        |        |base             |
|eeMatra-gurmukhi.short|uni0A47.short      |        |mark             |
|aiMatra-gurmukhi.short|uni0A48.short      |        |mark             |
|ooMatra-gurmukhi.short|uni0A4B.short      |        |mark             |
|auMatra-gurmukhi.short|uni0A4C.short      |        |mark             |
|tippi-gurmukhi.short  |uni0A70.short      |        |mark             |
|addak-gurmukhi.short  |uni0A71.short      |        |mark             |
|headline-gurmukhi     |headline           |        |                 |
|headline-gurmukhi.short|headline.short     |        |                 |
|headline-gurmukhi.shorter|headline.shorter   |        |                 |
|period.loclGURM       |                   |        |                 |
|comma.loclGURM        |                   |        |                 |
|colon.loclGURM        |                   |        |                 |
|semicolon.loclGURM    |                   |        |                 |
|ellipsis.loclGURM     |                   |        |                 |
|exclam.loclGURM       |                   |        |                 |
|question.loclGURM     |                   |        |                 |
|asterisk.loclGURM     |                   |        |                 |
|parenleft.loclGURM    |                   |        |                 |
|parenright.loclGURM   |                   |        |                 |
|braceleft.loclGURM    |                   |        |                 |
|braceright.loclGURM   |                   |        |                 |
|bracketleft.loclGURM  |                   |        |                 |
|bracketright.loclGURM |                   |        |                 |
|quotedblleft.loclGURM |                   |        |                 |
|quotedblright.loclGURM|                   |        |                 |
|quoteleft.loclGURM    |                   |        |                 |
|quoteright.loclGURM   |                   |        |                 |

**Comment by kalapi** [comment]
Good to go!
