### ISSUE TITLE
Add Sinhala script support

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans#469]
Sources will be available on the repository: Aug 18

**Comment by kalapi** [comment]
Hi @chrissimpkins was this supposed to be Odia instead of Sinhala?

**Comment by chrissimpkins** [comment]
Old issue tracker from last quarter.  The timing in the first post needs to be updated.  The schedule is still as we discussed last week.  Thanks Kalapi!

**Comment by kalapi** [comment]
Hello @Hoolean, @madig, @belluzj, and @chrissimpkins 

Uploading the latest Sinhala package here:

[2022-08-23_GoogleSansSinhala_V1.000_BETA01.zip](https://github.com/googlefonts/googlesans/files/9411741/2022-08-23_GoogleSansSinhala_V1.000_BETA01.zip)

Please let me know if you have any questions/fixes

**Comment by chrissimpkins** [comment]
Thanks Kalapi!

**Comment by madig** [comment]
Hi Kalapi! Can you please take [Our Built Fonts After Merge.zip](https://github.com/googlefonts/googlesans/files/9453844/Our.Built.Fonts.After.Merge.zip) for a spin before we pass it to our QAers?

**Comment by chrissimpkins** [comment]
Kalapi found an issue and will push a new package to you with a fix. Addresses a CoreText specific issue

**Comment by kalapi** [comment]
Thanks @madig I've checked the binaries and found that there was an issue with shaping on Safari (CoreText) related to GDEF classification that i've now fixed. This is what was happening on Safari:

<img width="540" alt="Screenshot 2022-09-01 at 10 45 51" src="https://user-images.githubusercontent.com/15804460/188008297-2b235cf2-a25e-40d8-8e50-db58808ef24e.png">

It's now fixed in files generated by us:

<img width="465" alt="Screenshot 2022-09-01 at 4 53 52 PM" src="https://user-images.githubusercontent.com/15804460/188010869-e6900267-fbb3-4831-bfe8-bc248e20c1a4.png">

Here is the latest package:

[2022-09-01_GoogleSansSinhala_V1.000_BETA02.zip](https://github.com/googlefonts/googlesans/files/9473324/2022-09-01_GoogleSansSinhala_V1.000_BETA02.zip)

**Comment by Hoolean** [comment]
Thank you for the sources @kalapi; those look great! : )

We will be starting our QA today :+1:

**Comment by Hoolean** [comment]
Hello @kalapi @chrissimpkins @MariannaPaszkowska!

I am happy to share Hanna's QA feedback internal doc for the merged Sinhala sources :tada: Please let us know if you have any questions :)

**Comment by kalapi** [comment]
Thanks @Hoolean, access requested :)

**Comment by Hoolean** [comment]
> Thanks @Hoolean, access requested :)

Hi @kalapi, for some reason I cannot see the invite; would you be able to shoot me your email/Google account? I will add it manually : )

**Comment by kalapi** [comment]
Sure, it's `kalapi@universalthirst.com`

**Comment by Hoolean** [comment]
Shared 🚀

**Comment by kalapi** [comment]
Hello @Hoolean,

Adding an updated package below which addresses the issues in the doc above. I've responded to the line items in the document but i'll summarise the fixes below:

1. Fixes a 1 unit difference in the space glyph in the italic max-opsz master.
2. Fixes default height of `iMatra-sinhala` and `iiMatra-sinhala`
3. Fixes outline issues in reported glyphs, mainly the corner overlaps for inktrap sizes.
4. Fixes `semicolon.loclSINH` by outlining the comma component in the italic master

[2022-09-10_GoogleSansSinhala_V1.000_BETA03.zip](https://github.com/googlefonts/googlesans/files/9539565/2022-09-10_GoogleSansSinhala_V1.000_BETA03.zip)

**Comment by chrissimpkins** [comment]
Thank you very much Kalapi!

**Comment by Hoolean** [comment]
Thank you for the fixes @kalapi; we have now merged them all in :)

I think your TTFs may be missing from the latest package; would you be able to attach them here? Then, we will proceed with the final QA 🚀

**Comment by kalapi** [comment]
Hi @Hoolean, strange that I skipped adding the binaries. Here you go:

[2022-09-10_GoogleSansSinhala_V1.000_BETA03.zip](https://github.com/googlefonts/googlesans/files/9557654/2022-09-10_GoogleSansSinhala_V1.000_BETA03.zip)

**Comment by belluzj** [comment]
Thank you Kalapi, received and forwarded to Hanna for review!

**Comment by kalapi** [comment]
Hi @belluzj 

Here's a new package with minor fixes:

- Fixes component position for `iMatra-sinhala` in `nyi-sinhala`, `jnyi-sinhala`, `ny_ri-sinhala`, and `jny_ri-sinhala` in both sources and all masters.

[2022-09-13_GoogleSansSinhala_V1.000_BETA04.zip](https://github.com/googlefonts/googlesans/files/9558927/2022-09-13_GoogleSansSinhala_V1.000_BETA04.zip)

**Comment by Hoolean** [comment]
Hello @kalapi! I can confirm that Hanna has found all behaviour in the latest sources to be correct. Thanks again for your hard work :tada:

@chrissimpkins @MariannaPaszkowska As discussed, we will move to prepare the branch for merging, and notify you as soon as it is ready for review :+1:
