### ISSUE TITLE
Provide interpolatable TTFs as part of releases

### ISSUE THREAD

**Issue by khaledhosny** [googlefonts/googlesans#471]
For merging Google Sans into Google Sans Arabic (which will remain a separate family), we merge TTF masters and build variable fonts from them instead of doing a source merge with all the complications of differences in build tooling.

To do that, we need interpolatable TTFs for Google Sans. For now, I built them with manually with:
```
fontmake -m source/GoogleSans/GoogleSans.designspace -o ttf-interpolatable --output-dir build/GoogleSans/ttf-interpolatable
```

But it would be nice if there were a make target for this and the TTFs be part of the release (may be in a separate tarball), so that updating the Latin part of the Arabic font is as streamlined as possible.

(P.S. I tried instantiating masters from the variable font, and it worked for most part until I found out that quite a few glyphs ended up not being compatible after instantiation and varLib was ignoring them).

**Comment by chrissimpkins** [comment]
I want to support this Khaled.  We're bumping up against significant compile time increases across our VF and static font formats (#464) and this will lead to a revision of the GH Action runner workflow definitions that we use for our CI/QA and releases.  We can look into this as part of the GHA refactor effort.  

Out of interest, how long does it take you to compile upstream interpolatable TTF's locally?

**Comment by khaledhosny** [comment]
On my machine:
```
$ time fontmake --verbose WARNING -m source/GoogleSans/GoogleSans.designspace -o ttf-interpolatable --output-dir build/GoogleSans/ttf-interpolatable

real	7m44.850s
user	7m37.397s
sys	0m3.307s
$ time fontmake --verbose WARNING -m source/GoogleSans/GoogleSans.designspace -o variable --output-dir build/GoogleSans/variable/

real	7m17.740s
user	7m13.721s
sys	0m3.369s
```

So building interpolatable TTFs take essentially the same time as building variable font with the GPOS optimization.

**Comment by khaledhosny** [comment]
I used the files from https://github.com/googlefonts/googlesans/releases/tag/v8.001-beta.2 and everything was fine, thanks!
