### ISSUE TITLE
Coordinating stylistic sets across script-specific families

### ISSUE THREAD

**Issue by khaledhosny** [googlefonts/googlesans#473]
In Google Sans Arabic we currently have an `ss01` feature defined (and might add more), but after merging in Google Sans which also defines an `ss01` feature the behavior of the feature would be depend on the script and I don’t think it is a good idea.

I think we should rename the feature in Google Sans Arabic, but what feature tag to use? Currently Google Sans uses `ss01` to `ss08` so we could use `ss09`, but I don’t know if Google Sans is planning to add more stylistic sets in the future.

I think we need a way to coordinate this. One way is to use, say, `ss09`, `ss10`, etc. in Google Sans Arabic and add a note in Google Sans sources about this so it does not use them.

**Comment by chrissimpkins** [comment]
We are steering teams away from use of stylistic sets in general. Nearly every script development team has proposed at least one stylistic set and we've found other approaches or abandoned them altogether in every case.  How are you using them?

**Comment by khaledhosny** [comment]
The current stylistic set is for accessing alternate form of `meem-ar `(this variant is also mapped using `locl` feature for certain languages), and @Gue3bara indicated he wants a stylistic set feature for the swash kaf (i.e. mapping `kaf-ar` to `swashkaf-ar`). Up to @Gue3bara to decide if the stylistic sets are required or not.
