### ISSUE TITLE
Bengali ligature horizontal stroke width / alignment changes

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans#476]
I noticed a "hazy bulging" appearance in the horizontal stroke at the top of the uuMatra ligature forms in macOS 10.15.7 + Font Goggles 1.4.4.  There is not a clean, crisp horizontal stroke broadly across these forms.  It looks like the horizontal stroke widths +/- alignment are different as you transition from left to right across the outline.  

I enlarged the tops of the glyphs and created this animation.  Click to enlarge and have a look at the white underlay beneath the blue as I hover over portions of the glyphs.  Those white pixel lines (sometimes above and below, sometimes only above or below) are what cause this bulging appearance across the horizontal strokes.  This seems to occur across the full design space.

![bengali-horizontal](https://user-images.githubusercontent.com/4249591/159573667-00f17072-acbb-472f-a88b-fd04d1b54f28.gif)

Test string: `রূ জ্রূ ব্রূ গ্রূ ত্রূ থ্রূ দ্রূ ধ্রূ ন্দ্রূ প্রূ ব্রূ ম্রূ শ্রূ স্রূ স্লূ`

**Comment by chrissimpkins** [comment]
This issue also occurs in the alternate iiMatras

![bangla-iimatra](https://user-images.githubusercontent.com/4249591/159791452-8c5a44ed-80ac-4684-b77c-9cc55cad6f2f.gif)

**Comment by chrissimpkins** [comment]
Also seen in the alternate iMatras with reph

Test string: `র্মি র্কি র্ল্রি র্দ্ভি র্স্ত্বি র্ণ্মি র্ষ্ফি র্প্মি র্ম্দ্রি র্ঙ্মি র্ব্বি র্ড্ডি র্ল্ঘি র্জ্জি র্ক্ষ্মি`

**Comment by chrissimpkins** [comment]
Alternate iMatras with Candrabindu

Test string: `মিঁ কিঁ ল্রিঁ দ্ভিঁ স্ত্বিঁ ণ্মিঁ ষ্ফিঁ প্মিঁ ম্দ্রিঁ ঙ্মিঁ ব্বিঁ ড্ডিঁ ল্ঘিঁ জ্জিঁ ক্ষ্মিঁ`

**Comment by chrissimpkins** [comment]
Alternate iMatras with Candrabindu and Reph

Test string: `র্মিঁ র্কিঁ র্ল্রিঁ র্দ্ভিঁ র্স্ত্বিঁ র্ণ্মিঁ র্ষ্ফিঁ র্প্মিঁ র্ম্দ্রিঁ র্ঙ্মিঁ র্ব্বিঁ র্ড্ডিঁ র্ল্ঘিঁ র্জ্জিঁ র্ক্ষ্মিঁ`

**Comment by chrissimpkins** [comment]
Initial eMatra

Test string: `ককে কে`

**Comment by chrissimpkins** [comment]
Initial aiMatra

Test string: `ককৈ কৈ`

**Comment by chrissimpkins** [comment]
![2022-03-23_17-09-14](https://user-images.githubusercontent.com/4249591/159796389-2acd3fc4-48b9-41af-8b8e-606e3ae61a8c.png)

**Comment by chrissimpkins** [comment]
I'll stop documenting here.  I'd like to turn this back over to @kalapi and team for a general review of the stem widths and alignments on horizontal strokes.  This appears to be a broad issue across the glyph set.

**Comment by chrissimpkins** [comment]
Possibly related? https://github.com/microsoft/cascadia-code/issues/362

**Comment by davelab6** [comment]
> Possibly related? [microsoft/cascadia-code#362](https://github.com/microsoft/cascadia-code/issues/362)

I believe that's a different issue, intra-glyph, while this is inter-glyph. I believe its a "feature not a bug" choice of the macOS text rendering team, where two overlapping shapes with the same height will, where overlapped, add more opacity to the "fringe" of antialiasing, and that's maybe desirable for general graphics but not type, yet type isn't special cased. 

I believe if the font outlines in on the UPM grid are the same height, there's nothing to do here and the bug resolution might be to document this somewhere in the GS docs.

**Comment by belluzj** [comment]
It could be a manifestation of the "coincident edges" effect when you superimpose on screen two vector shapes that have been rasterized with alpha separately beforehand: https://wh0.github.io/2019/11/05/rasterization.html

(I agree with Dave that if the horizontal line is the same height on both sides then there's nothing more you can do)

**Comment by chrissimpkins** [comment]
Thanks for all of this information! 

It sounds like the problem occurs when those coincident edges do not cover an entire pixel dimension and is a long-standing problem in 2D vector rasterization.  I'm surprised that this is the first time that we are seeing it in GS. Maybe it is only noticeable here because of the number and vertical position  consistency of these horizontal strokes across the set.

I wonder if [workarounds used in other visual design areas](https://graphicdesign.stackexchange.com/questions/73601/is-there-a-reason-hillary-clintons-logo-has-hidden-notches) changes the effect?  Not suggesting that we should do this.  But it may be a design approach to address it.

I'll confirm with Kalapi that the horizontal stroke widths are, in fact, designed at the same UPM dimensions and we can decide if there is anything else to do.

**Comment by chrissimpkins** [comment]
D/W Kalapi.  Confirmed environment-specific rasterization issue with the coincident edge overlaps.  Long-standing issue.  We will not address this issue further.
