### ISSUE TITLE
Set OVERLAP_SIMPLE and OVERLAP_COMPOUND bits in VF format build glyf table when a glyph has overlaps

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans#478]
https://github.com/google/fonts/issues/4405

As I understand it, the above recommendation from Dave was based on an Android text rendering environment issue with TT format VF files that include overlapping contours (note: **this is not in static instances with overlaps, including those instantiated from VF's**). 

Need to look into details of the problem in the Android environment and the non-Android env consequences of doing this. There may be rasterization performance degradation in some environments if we ignore whether a glyph actually has an overlap with an impl like https://github.com/google/fonts/issues/4405#issuecomment-1077650700

Relevant background threads list:

- https://github.com/fonttools/fonttools/issues/2059
- https://github.com/twardoch/test-fonts/tree/master/varia/160413-EvenOddTT
- http://web.archive.org/web/19980207055200/http://fonts.apple.com:80/ttrefman/RM06/Chap6GXIntro.html
- https://github.com/googlefonts/ufo2ft/issues/402
- ...

**Comment by chrissimpkins** [comment]
History of glyf table overlap bit flags from [1998 era Apple QuickDraw GX documentation](http://web.archive.org/web/19980207055200/http://fonts.apple.com:80/ttrefman/RM06/Chap6GXIntro.html):

> There are two changes connected with the 'glyf' table, dealing with overlapping contours and compound glyph components under rotation.
>
> Overlapping contours
>
>One addition to the 'glyf' table is the designation of glyphs with overlapping contours. This is not needed for rendering by TrueType scalers, but is needed when a TrueType font must be converted to a Type 1 Font and rendered on a printer under some Level 2 PostScript implementations.
>
>Since the introduction of the original 'glyf' format, Level 2 Postscript has been introduced. Some printers that incorporate Level 2 Postscript use an even-odd fill algorithm for Type 1 fonts rather than the non-zero winding number fill that was used in previous PostScript implementations. Therefore, to accurately translate a TrueType font to a Type 1 font for use on the Level 2 printers, glyphs with overlapping contours must be simplified, so it is necessary to know which glyphs have overlapping contours. Glyphs that are not properly flagged will be rendered on these printers with white space holes where the contours overlap.
>
>For simple glyphs, you should set bit 6 of the first Outline Flag byte to 1 if the unhinted glyph outline has overlapping contours or if variation controls or hinting controls can ever cause any of the contours to overlap. Otherwise this bit should be set to 0.
>
>For compound glyphs, you should set bit 10 of the flags word in the first component to 1 if any of the component glyphs can ever have overlapping contours or if the contours of any component can ever overlap the contours of another component in the compound glyph. Otherwise set this bit to 0. Note that bit 4 of this flag word is designated for flagging overlapping contours in some old documentation. This bit is obsolete and is ignored by all scalers.

**Comment by chrissimpkins** [comment]
The glyf overlap bit flags are not compiled into woff2 format builds

https://github.com/google/woff2/issues/117

There was a 2021 W3 Web Fonts working group proposal to change this https://lists.w3.org/Archives/Public/public-webfonts-wg/2021May/0011.html

**Comment by chrissimpkins** [comment]
Description of an issue with VF overlaps that arose with Cascadia Code VF in FT environment

https://github.com/microsoft/cascadia-code/issues/350

Notable:

> FreeType will handle overlapping contours in the next release but it will require OVELAP_SIMPLE or OVERLAP_COMPOUND set. We understand that those flags are optional in variation fonts but oversampling quadruples the rendering time. Buyer beware.

and 

> My understanding aligns with yours—for variable fonts, MacOS acts as if the OVERLAP_SIMPLE and OVERLAP_COMPOUND flags are present, even if not actually set in font.
>
>Seems that FreeType is the only rasterizer that actually cares if the flags are present in a variable font.

**Comment by chrissimpkins** [comment]
More background

https://github.com/googlefonts/ufo2ft/issues/402

**Comment by madig** [comment]
Regarding "how many overlaps": measuring Google Sans with Bangla, I get:

> 5026 glyphs, 1911 overlapping contours (38.02%), 386 overlapping components (7.68%)

**Comment by chrissimpkins** [comment]
That is very helpful!

How are you detecting the overlap?

**Comment by chrissimpkins** [comment]
> That is very helpful!
> 
> How are you detecting the overlap?

I'm reading your posts out of sequence.  Here is the script

https://github.com/google/fonts/issues/4405#issuecomment-1079185880

**Comment by madig** [comment]
Yeah the discussion is a bit all over the place. I can simply implement a bit-setter script if you want? We use one in production internally and encountered no problems related to them so far.

**Comment by chrissimpkins** [comment]
Sgtm. Let's use your selective bit flag setting approach since we are at 38% of the glyph set affected.  It isn't clear what the rasterization impact is by using faster raster modes on the remaining 62%, but there isn't much downside to that gain based on the overlap computation times that you showed (and working under the assumption that we will not cause new problems in other raster environments).  The compile time impact will likely be a drop in the bucket for us. :) 

It's good to hear that you've run into no problems when you set these bits.

**Comment by madig** [comment]
New numbers for GS+Bangla with new script (see other thread):

> GoogleSans[GRAD,opsz,wght].ttf 5026 glyphs, 2444 overlapping contours (48.63%), 1806 overlapping components (35.93%)

**Comment by chrissimpkins** [comment]
> New numbers for GS+Bangla with new script (see other thread):
> 
> > GoogleSans[GRAD,opsz,wght].ttf 5026 glyphs, 2444 overlapping contours (48.63%), 1806 overlapping components (35.93%)

Ty!

**Comment by chrissimpkins** [comment]
Added to v9 release work

**Comment by madig** [comment]
Note to self for when implementing a script: https://github.com/google/fonts/issues/4405#issuecomment-1086668763

**Comment by chrissimpkins** [comment]
Also note https://github.com/google/fonts/issues/4405#issuecomment-1090011615

**Comment by chrissimpkins** [comment]
We will need to include this change in our v9 builds.  Let's prioritize development of the script that is required to support it sometime during the next two months.

**Comment by chrissimpkins** [comment]
D/W Nikolaus and Jany today. We will start with Nikolaus's existing script that sets overlap flags selectively, but aggressively.  It may set overlap bit flags on some glyphs that do not have overlaps and this may affect performance.  @m4rc1e is working on a more conservative/selective solution.  We will watch for additional updates on Marc's script, introduce these changes when they are available.

**Comment by chrissimpkins** [comment]
Addressed in #494

This will be released in v8.001
