### ISSUE TITLE
Fix UPM scaling script to support all design source layers

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans#48]
There is an opsz axis interpolation issue in the builds as of the 2000 UPM scaling work @ https://github.com/googlefonts/googlesans/commit/e9d0308c9c1dd5b5966b6b88fde190eab74b9aab:

![VF-figures](https://user-images.githubusercontent.com/4249591/83684894-c15d4400-a5b5-11ea-8d15-8c6636a3ab4a.gif)

cc @Colophon-Foundry

**Comment by chrissimpkins** [comment]
Builds available here: https://github.com/googlefonts/googlesans/suites/752150981/artifacts/7734536

**Comment by chrissimpkins** [comment]
Looks like this happens only at the figures that have brace layers defined.  They are different in the italics and the upright source files. And it looks like they are defined at 15 for numeral `1` and 16 for `6` and `9`.

**Comment by anthrotype** [comment]
I believe that gist of mine is only scaling the foreground default UFO layer. We should also scale all the other layers as well.

**Comment by chrissimpkins** [comment]
Change this:

https://github.com/googlefonts/googlesans/blob/e9d0308c9c1dd5b5966b6b88fde190eab74b9aab/scripts/scale_ufo.py#L91-L100

to:

```python
def _scale_glyphs(font, scale_factor):
    scale = TransformationsFilter(ScaleX=scale_factor * 100, ScaleY=scale_factor * 100)
    scale(font)

    for layer in font.layers:    
        for glyph in layer.keys():
            glyph.width *= scale_factor
            glyph.height *= scale_factor
```

?

**Comment by anthrotype** [comment]
That's only scaling the advances, we need to also transform the glyph contours, components, anchors, etc. That is done by the transformations filter. I need to check it the API allows to scale specific non-default layers
