### ISSUE TITLE
Idea: Use e.g. nox instead of make for project management

### ISSUE THREAD

**Issue by madig** [googlefonts/googlesans#482]
Usage of `make` is why I initially set up WSL on my work machine, because I didn't want to deal with fiddling make into submission on my Windows machine. I recently rediscovered https://cjolowicz.github.io/posts/hypermodern-python-02-testing/#test-automation-with-nox, which talks about https://nox.thea.codes/en/stable/. It is a tool providing a Python-scriptable entry point into your Python project's management. See the bottom of the documentation index page to see which projects use it and what the noxfile.py files look like.

There are also other, pure command runners, like https://github.com/casey/just/, that will just run shell scripts.

This is more of an idea than a call for action. The current jumble of scripts feels a bit tedious to use sometimes...

**Comment by MariannaPaszkowska** [comment]
idea: consider moving to builder2 CC: @chrissimpkins
