### ISSUE TITLE
QA/validate metrics key (automatically?) and prune invalid ones, maybe

### ISSUE THREAD

**Issue by belluzj** [googlefonts/googlesans#489]
Metrics keys are useful metadata about the glyphs, as they provide insight to contributors into "design constraints" that original designers meant to follow while setting sidebearings; they also provide automation in the right font editors (Glyphs.app mostly, but also FontLab which is compatible with some of the Glyphs.app syntax) to maintain these constraints and keep the linked values in sync.

However, if a contributor doesn't use a compatible editor for example, or in any way sets the actual metrics to values that do not satisfy the constraints of the metrics keys, and doesn't also delete/update the relevant metrics keys, then the keys become a liability because:
* they represent false/contradictory information about the glyphs
* they might trigger automated changes to the sidebearings later, in some other contributor's compatible editor, which will "helpfully" apply the metrics keys and thus create unwanted changes.

Ideally we would like to keep metrics key, because they're useful information, but only keep them when they're in sync with the current values of the glyphs sidebearings. To achieve that we would need a fontbakery check (for example) that only allows metrics keys if they're currently satisfied in the sources, and an associated clean-up script to remove stale keys.

Example: in PR https://github.com/googlefonts/googlesans/pull/333 we (Dalton Maag) have updated the spacing of the Latin glyphs, and we've merged the value changes but we haven't tried to merge the metrics keys (I think our designers have been using a mix of metrics keys and "FontLab recipes"). Our designers when working on that PR have reported that existing metrics keys did not all reflect the current state of sidebearings.

After merging their changes, we should at least remove existing metrics that are not satisfied anymore, or potentially look into also importing the new metrics keys where relevant (they might be using FontLab notation instead of Glyphs.app notation).

All that being said, metrics keys are merely meta-data, they don't influence the built fonts, so this issue may not be the highest priority. We could also choose to drop all the metrics keys.

**Comment by chrissimpkins** [comment]
Can you point to Glyphs and/or FontLab docs on how these data are used in the editors?

**Comment by madig** [comment]
* https://glyphsapp.com/learn/spacing#g-sidebearing-arithmetics
* https://help.fontlab.com/fontlab/7/manual/Editing-Glyph-Metrics/#using-simple-expressions

**Comment by MariannaPaszkowska** [comment]
might be useful for GS Flex
