### ISSUE TITLE
Transition to static instance builds from variable font builds instead of direct compile from DS+UFO sources

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans#492]
From @madig:

I talked to Cosimo regarding instance generation, and he also names binary interpolation and instancing. I propose that we 

1. Get https://github.com/googlefonts/googlesans/pull/487 in
2. Change the instance build process to use `fonttools varLib.instancer` to cut static instances from the VFs
3. Work out any issues we find (leave composite overlaps as is to keep size down?)
4. Deal with Telugu

The instancer is in use by Google Fonts AFAIU and makes variating features straightforward to support.

_Originally posted by @madig in https://github.com/googlefonts/googlesans/issues/481#issuecomment-1117245497_

**Comment by madig** [comment]
Done.
