### ISSUE TITLE
GHA VM out of memory during compile following addition of ttf-interpolatable build targets

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans#503]
💣  https://github.com/googlefonts/googlesans/actions/runs/2384983867

```
Killed
make[1]: *** [Makefile:122: VARIABLE_BUILD_PATH_UPRIGHT_TARGET] Error 137
```

Looks like we may need to remove some of the parallelism @madig?  Can't prep the v8.001 release

**Comment by madig** [comment]
Aaargh. I'll try removing gpos compression... And maybe the compatibility checker? Not sure if I can easily turn that one off.

**Comment by chrissimpkins** [comment]
We want the env var defined GPOS compression in our release builds.  You mean turn off on ttf-interpolatable builds only, or turn off the hb GPOS packer?

**Comment by madig** [comment]
I'd turn it off for the ttf-interpolatable builds only. I'm not sure if we can turn off the hb repacker, as it is automatically used when uharfbuzz is available. Stopping it from being used requires setting some option I think, which we currently can't do from just fontmake IIUC.

**Comment by madig** [comment]
The other measure of course is to not produce everything in parallel. So we can `make -j gs-vf gs-statics` but need to `make -j gs-compatible` as a second step.

**Comment by chrissimpkins** [comment]
It's going to be slow but I am not opposed.  I think that we should be thinking about the pypy3 transition soon.  Release compiles are in the 30+ min range now...

**Comment by chrissimpkins** [comment]
Addressed in https://github.com/googlefonts/googlesans/pull/504

Compile time ~ 50 mins with the changes...
