### ISSUE TITLE
Add acaron U+01CE

### ISSUE THREAD

**Issue by madig** [googlefonts/googlesans#505]
![grafik](https://user-images.githubusercontent.com/380829/173122543-e9f71fc6-a091-470c-b33e-3e83e7c0daff.png)

**Comment by chrissimpkins** [comment]
@belluzj We can add this glyph addition to the request in #511 if there is time/interest

**Comment by chrissimpkins** [comment]
Tentatively added this to v11.000

**Comment by chrissimpkins** [comment]
Is there a straightforward way to test what exemplar / auxiliary sets individual code points exist in?  How can we understand what language support is involved here?

**Comment by madig** [comment]
Do you mean if there's an easy way to bin glyphs by language? There is stuff like the CLDR and we have an internal, curated database. Would you like us to investigate acaron impact?

**Comment by chrissimpkins** [comment]
> Do you mean if there's an easy way to bin glyphs by language? There is stuff like the CLDR and we have an internal, curated database. Would you like us to investigate acaron impact?

Yep!  Not urgent.  But yes, it would be useful to know what languages we pick up entirely or partially by adding the lowercase acaron.

**Comment by belluzj** [comment]
@chrissimpkins, do you think you could revive the highlighted suggestion in this  internal document?

![image](https://user-images.githubusercontent.com/3616772/203005577-bf29159a-fe9d-43a6-b141-e4dfbcdd6458.png)

It had some examples already, but I can't access it anymore. Thanks in advance!

**Comment by madig** [comment]
According to our language database and double-checked with https://scriptsource.org, acaron is used by the languages Lingala, Ngomba, Yangben, Bafut (maybe), Akoose (maybe), Aghem, Ewondo, Ngiemboon and Basaa.

Edit: ScriptSource itself has its own listing: https://scriptsource.org/cms/scripts/page.php?item_id=character_detail_use&key=U0001CE

**Comment by MariannaPaszkowska** [comment]
@madig @belluzj Is there a PR associated with this? Can we target this for our EOQ2 release?

**Comment by belluzj** [comment]
@MariannaPaszkowska There is no PR for this at the moment, because at the time Chris decided against it, see this closed comment in the following document's history: 
![image](https://github.com/googlefonts/googlesans/assets/3616772/3275ebea-25e3-4274-8bf2-1565dbc426f7)

**Comment by belluzj** [comment]
That being said, I will enquire in our font development team to know how fast they can add this one glyph to Google Sans. It shouldn't be too complicated as it's a composite but still it always takes a bit of time to review the changes. 

Edit: if, as Chris suggests, there is another bundle of additional glyphs that will be developed soon, it could be interesting to group this one with the next batch of new glyphs.

**Comment by belluzj** [comment]
Was added in commit: https://github.com/googlefonts/googlesans/commit/4a495075ff67c7429521ab54c20c38366c1d9174
