### ISSUE TITLE
Unmix scripts in shaping tests

### ISSUE THREAD

**Issue by madig** [googlefonts/googlesans#514]
Following the discussion in the Font Engineering and Tools chat (which I can't link to because I can't find a link), the test suite should not mix scripts. HarfBuzz alone does not do run itemization to split scripts apart, which would happen in any real application though, so we're testing things that wouldn't happen in reality.

This currently only affects some Armenian test files. We should probably unmix them (or reduce them or remove them) and emit a warning on mixing scripts. The other possibility is pulling in PyICU or something to get a libraqm, to do splitting ourselves.

**Comment by chrissimpkins** [comment]
Do we understand why we need mixed script testing for Armenian?

@gorjious can you weigh in on our Armenian regression test strings?

**Comment by madig** [comment]
Relevant chat at https://chat.google.com/room/AAAAmakukgk/qfiygI7YB3E

**Comment by gorjious** [comment]
Hi just seeing this now. I can't check the test strings at the moment but if I remember correctly the strings that had mixed scripts were testing if certain punctuation marks (hyphens, guillimets, etc) were shifting down together in probable cases when Armenian would be used alongside Latin, and when the language was set to Armenian.

**Comment by madig** [comment]
Hm. I'd need to determine what a real world application would do in that case. Are you targeting any specific app with that test?

**Comment by gorjious** [comment]
Not necessarily for a specific app just making sure the feature code would work...browsers would be the main target.

These are some of the mixed script testing strings.
«գնում եմ NYC։»
«գնում եմ NYC»
«New York-եմ գնում։»

So if a text is set to `<html lang="hy">` the text should be primarily Armenian which would also reflect in the positioning of punctuation marks, such guillemets and hyphens, which shift down to account for the lower Armenian x-height. 

The test is to check when there is another script mixed in, such as Latin, that the punctuation shifting still occurs everywhere throughout the text. The thought is to avoid one guillemet shifting while the other doesn't.

**Comment by chrissimpkins** [comment]
I believe that we addressed this by eliminating the mixed script checks that were included in Armenian, correct?  Can we close this issue?

**Comment by madig** [comment]
We haven't removed the mixing yet, I'll look at this for #516.

**Comment by madig** [comment]
Looking at what's changed in `armenian_locl_hy.json` and `armenian_locl_en.json`, the kerning of Latin glyphs was lost, because we split kerning into per-script lookups and only run the lookups for the current script. Both files specify "armn", so Latin kerning is ignored. This is by design and is not a problem in e.g. browsers, because they do segment text into per-script runs, where the Latin and Armenian kerning is applied to their respective runs as expected. Our test suite won't do that because it's actually tricky to do right.

Testing in Firefox, the test text in these files shifts "‹›«»" downwards when the language is set to "hy" with no diff visible between old and new dependencies. I propose we drop one test and change the other to `‹գ›«գ»`, to ensure that the downward shift works when the language is set to "hy".

**Comment by chrissimpkins** [comment]
> the kerning of Latin glyphs was lost, because we split kerning into per-script lookups and only run the lookups for the current script

Does this mean that if there is Latin-based text and Armenian-based text in the same document localized to Armenian, there will be no Latin kerning in that document?  I'm not sure that I fully understand if this affects users, or is simply a technicality in our regression testing environment.

**Comment by madig** [comment]
There should be kerning as expected, if the applications does its Unicode correctly. It doesn't happen in our test suite, because we don't segment text into per-script runs and HarfBuzz won't do it either, because it's a higher level concern. So, it's a technicality in our suite. It should not affect users, because some Unicode document says that shaping does not cross script boundaries.

**Comment by khaledhosny** [comment]
> some Unicode document says that shaping does not cross script boundaries.

This is an OpenType concern, not Unicode one (Graphite supports cross-script shaping, for instance).

**Comment by MariannaPaszkowska** [comment]
@madig Hi Nikolaus, did we fixed this in: https://github.com/googlefonts/googlesans/pull/516

**Comment by madig** [comment]
I believe so, by manually unmixing the test strings.
