### ISSUE TITLE
Add Odia script support

### ISSUE THREAD

**Issue by kalapi** [googlefonts/googlesans#515]
Hello @madig, @belluzj, and @chrissimpkins 

Attaching the latest Google Sans Odia package here. The QA toml files will be available later today.

Please let me know if I need to fix anything.

Many thanks!

[2022-07-22_GoogleSansOdia_V1.000_BETA01.zip](https://github.com/googlefonts/googlesans/files/9167467/2022-07-22_GoogleSansOdia_V1.000_BETA01.zip)

**Comment by chrissimpkins** [comment]
> The QA toml files will be available later today.

@kalapi Will you please push the toml regression string definitions when you have a chance? Ty!

**Comment by madig** [comment]
We also noticed that the danda glyphs have different names between uprights and italics. Please fix them.

**Comment by Hoolean** [comment]
Hello @kalapi : ) I have a draft merge of the Odia script at #518, and FontBakery has raised a few concerns: https://github.com/googlefonts/googlesans/runs/7520495537?check_suite_focus=true#step:7:229

Would you be able to take a look and see if the warnings suggest problems?

**Comment by kalapi** [comment]
Hello @chrissimpkins & @madig 

Adding a new package with the .toml files and the danda & doubledanda glyphname fix.

[2022-07-26_GoogleSansOdia_V1.000_BETA02.zip](https://github.com/googlefonts/googlesans/files/9190385/2022-07-26_GoogleSansOdia_V1.000_BETA02.zip)

**Comment by kalapi** [comment]
Hi @Hoolean 👋🏽

```
FAIL The following glyphs could not be attached to the dotted circle
     glyph: uni0B3F and uni0B01
```
Upstream dottedCircle requires anchor 'topcenter', and 'candra'. I'll add these to my sources and also include them in the 'import_glyphs.txt' files

```
WARN The following spacing glyphs may be in the GDEF mark glyph class
     by mistake: uni0B48 (U+0B48), uni0B4B (U+0B4B), uni0B4C (U+0B4C),
     uni0C3E (U+0C3E), uni0C41 (U+0C41), uni0C42 (U+0C42), uni0C43
     (U+0C43), uni0C44 (U+0C44), uni0C4A (U+0C4A), uni0C4B (U+0C4B) and
     uni0C4C (U+0C4C) [code: spacing-mark-glyphs]

WARN The following non-mark characters should not be in the GDEF mark
     glyph class: U+0B48, U+0B4B, U+0B4C, U+0C41, U+0C42, U+0C43 and U+0C44
     [code: non-mark-chars]
```
I checked the GDEF warnings and both warning are false-positives. The glyphs in question are spacing-combining marks.

**Comment by Hoolean** [comment]
@kalapi Thanks for taking a look at the FontBakery issues :+1: I have just been looking at merging in the new BETA02 ZIP, and noticed some changes in the `psts` feature, compared to the previous merge; are these all well and good?

![image](https://user-images.githubusercontent.com/2150762/181037394-3d35f83a-f2ad-461c-b957-769ff85a53bf.png)

**Comment by kalapi** [comment]
Hi @Hoolean,

Adding a package with updated dottedCircle anchors as well as adding it to the `import_glyphs[...].txt` list.

The changes to `psts` are intentional :)

[2022-07-26_GoogleSansOdia_V1.000_BETA03.zip](https://github.com/googlefonts/googlesans/files/9190822/2022-07-26_GoogleSansOdia_V1.000_BETA03.zip)

**Comment by Hoolean** [comment]
Hi @kalapi,

Thank you for the anchor changes :) I also spotted that "aiMatra"/`U+0B48` has changed, is this wanted too?

![image](https://user-images.githubusercontent.com/2150762/181041574-b306a045-4c60-4376-98a0-84740678f6bf.png)

**Comment by kalapi** [comment]
> Hi @kalapi,
> 
> Thank you for the anchor changes :) I also spotted that "aiMatra"/`U+0B48` has changed, is this wanted too?
> 
> ![image](https://user-images.githubusercontent.com/2150762/181041574-b306a045-4c60-4376-98a0-84740678f6bf.png)

Yes, this is because the anchor now activates 'automatic positioning' on top of the `dottedCircle` in the composite glyph, absolutely fine.

**Comment by Hoolean** [comment]
Super; that is the version I have now merged in :+1:

On adding the snapshot tests, it appears that `/dottedCircle` has different spacing in "Text Regular Italic" and "Text Bold Italic" to upstream.

![image](https://user-images.githubusercontent.com/2150762/181067866-49f00d77-dc71-418f-96a1-2424f1100e8d.png)

Would you be able to base the anchor change on the original upstream glyph?

**Comment by kalapi** [comment]
I'm not sure how i'd go about doing so. Is it off just by a unit?

**Comment by Hoolean** [comment]
No worries! I have attempted a fix by copying the correctly spaced glyph from the Italic Display fonts into the Italic Text fonts.

This matches the behaviour in the main build of Google Sans, which shares an identical `/dottedCircle` glyph across all italic sources.

The glyph was indeed off by just a unit; if a new version of the package is needed later, you could correct it on your side by copying the `/dottedCircle` glyph from the display italics into the text italics too :)

---

With this resolved, the merge is not showing any errors from QA (aside from the false-positives we found earlier, see googlefonts/fontbakery#3040).

Thank you for your help; I am pleased to be able to share the current build, if you would like to double check the font looks as you intend before review:

[Google Sans with Odia.zip](https://github.com/googlefonts/googlesans/files/9200403/Google.Sans.with.Odia.zip)

**Comment by chrissimpkins** [comment]
@kalapi The DaMa design team will begin a review on Monday.  Please let us know if you have any concerns about the builds that Harry linked above.  Ty!

**Comment by kalapi** [comment]
Completed checking the binaries attached above. Please proceed with your review :)

**Comment by jonpinhorn** [comment]
Hi, Kalapi!

Please find below the results of our Odia checks:

- /nna-oriya/ll_ka-oriya have open/looped corners that need to be removed. This is also true for many glyphs in the Italic DS

![ODIA_4](https://user-images.githubusercontent.com/8477580/183067102-abc464dd-284c-4823-a7ba-37452295eab7.png)

- /l_ka-oriya/ll_ka-oriya - Both glyphs have a mix of composite and contour outlines, and this differs from the Upright
![ODIA_3](https://user-images.githubusercontent.com/8477580/183067196-06534d72-c90b-4237-94c1-f56ea83462b9.png)

- /tta-oriya/pa-oriya/t_pa-oriya/p_ta-oriya/p_na-oriya/ss_ka-oriya - Check anchor placement of 'top' across all the DI's
![ODIA_2](https://user-images.githubusercontent.com/8477580/183067238-97f03b33-3bb5-4581-87f9-94b82232f168.png)

- /dd_ga-oriya - Check interpolation consistency in this DI

![ODIA_1](https://user-images.githubusercontent.com/8477580/183066745-57fc100b-441e-4518-be82-87aafdd77e45.png)

- Line 3  of the oriya.fea file: "@ORI_wideBases" - Prefix should be @ODI_widebases"

Thanks!

**Comment by chrissimpkins** [comment]
Thank you Jonny!

**Comment by kalapi** [comment]
Hi @jonpinhorn, thanks for this. Will fix this and upload a new package next week.

**Comment by chrissimpkins** [comment]
> Hi @jonpinhorn, thanks for this. Will fix this and upload a new package next week. 

Thanks Kalapi!

**Comment by kalapi** [comment]
Hello @jonpinhorn & @Hoolean 

Fixed the reported issues + a few other minor inconsistencies I've found. Adding a new package herewith. 

[2022-08-08_GoogleSansOdia_V1.000_BETA04.zip](https://github.com/googlefonts/googlesans/files/9279234/2022-08-08_GoogleSansOdia_V1.000_BETA04.zip)

**Comment by Hoolean** [comment]
Cheers, Kalapi! I have merged in your latest changes, and will pass on the newest builds to Jonny :+1:

**Comment by jonpinhorn** [comment]
Hi Kalapi & Chris,

Thanks for the update last week. There's still some outstanding outline issues related to contour direction and open corners.

- /ss_tta-oriya
- /ssa-oriya
- /a-oriya

Regards! 

Jonny

![ODIA_5](https://user-images.githubusercontent.com/8477580/183901760-fbe79e78-17ab-4bd7-9f5f-5e2966dc58f4.png)
![ODIA_6](https://user-images.githubusercontent.com/8477580/183901753-e1717937-463c-4065-b363-82339c1a2bbb.png)
![ODIA_7](https://user-images.githubusercontent.com/8477580/183901757-6151cd82-cf56-4490-b729-181f8cf86cc2.png)

**Comment by kalapi** [comment]
Sorry about these, and thanks for reporting. Will upload a fixed version shortly.

**Comment by kalapi** [comment]
Here are the fixed sources:

[2022-08-11_GoogleSansOdia_V1.000_BETA05.zip](https://github.com/googlefonts/googlesans/files/9306420/2022-08-11_GoogleSansOdia_V1.000_BETA05.zip)

**Comment by chrissimpkins** [comment]
Ty!

**Comment by Hoolean** [comment]
Hello all! :)

Kalapi, I have merged in your latest sources, and will be passing over the merged builds to Jonny on Monday :+1:

Chris, during QA, we encountered an issue that exclusively affects the fonts' behaviour under Adobe InDesign 2022. The variable fonts are not correctly shaped.

##### Static Display Regular (correct)

![image](https://user-images.githubusercontent.com/2150762/184347164-4032d60d-306a-4cac-bad7-38d5d31a4caf.png)

##### Variable Display Regular (incorrect)

![image](https://user-images.githubusercontent.com/2150762/184346699-d07dd0b8-cd2d-4685-aac0-07b54675877f.png)

This occurs for both the merged and unmerged fonts, and was not seen in any other applications.

InDesign does have documented incompatibilities with OpenType; is InDesign a target of Google Sans, and, if so, should we investigate further?

**Comment by chrissimpkins** [comment]
Thanks Harry.  Can we confirm that this shaping bug only happens in Adobe products?  Where have you tested? 

@kalapi Any thoughts about what might be going on in the Adobe shaping bug that Harry pointed out above?  Known issue?

To answer your question about InDesign, it is not commonly used by Google designers.  There was a company-wide move to Figma a couple of years ago.  But Google Sans is distributed to teams that might use it.  Branding teams use third party ad agencies and I imagine that InDesign is in use there.

**Comment by kalapi** [comment]
Hello! 

Our contract excludes support for Adobe WRC environments. 

Having said that, InDesign 2022 now uses (or should use) Harfbuzz so this should not be an issue. 

Like you've already said pre-Harfbuzz InDesign has a lot of issues with Indic shaping. This could be one of those instances?

**Comment by Hoolean** [comment]
I am happy to report that Jonny's QA for the latest builds has shown that all of the (non-Adobe) issues he reported have been resolved :tada: Thank you Kalapi!

I will peek at a potential issue with copying over OpenType categories that Nikolaus and I noticed, and then provide a build for review.

---

> Can we confirm that this shaping bug only happens in Adobe products? Where have you tested?

I have checked in with Jonny:
- For Adobe products, the QA only covered InDesign, where we saw the variable fonts issue;
- For various web platforms/browsers, we saw no issue;
- When examining the sources in font editors, we saw no issue.

**Comment by chrissimpkins** [comment]
> I have checked in with Jonny:
>
>- For Adobe products, the QA only covered InDesign, where we saw the variable fonts issue;
>- For various web platforms/browsers, we saw no issue;
>- When examining the sources in font editors, we saw no issue.

Sgtm.  Mind copying and pasting in the text run at issue here so that I can have a quick look before we merge?

**Comment by Hoolean** [comment]
Sure thing Chris; this is the input I was using for the [minimal test case above](https://github.com/googlefonts/googlesans/issues/515#issuecomment-1213035065): `ଙ୍କ`

When reproducing, be sure to [enable the World-Ready Composer](https://helpx.adobe.com/in/indesign/using/arabic-hebrew.html), as before this, the shaping did not work for either of the fonts. In addition, Adobe InDesign does not show the Variable and Static fonts separately, so it is best to only provide it each one at a time.


I have attached the latest build, if that saves you some CPU cycles; please note that there is still the OpenType categories to investigate before a final build is produced.

[Build.zip](https://github.com/googlefonts/googlesans/files/9337831/Build.zip)
