### ISSUE TITLE
Issue regarding semicolon positioning

### ISSUE THREAD

**Issue by gorjious** [googlefonts/googlesans#52]
The position of the semicolon differs from the alignment with comma and colon. This occurs in the regular and bold weights of the max opsz in both upright and slant.

<img width="1392" alt="Screenshot 2020-06-08 at 10 28 30" src="https://user-images.githubusercontent.com/23149420/84062366-63957700-a97c-11ea-8f88-a37a36824da6.png">
<img width="1392" alt="Screenshot 2020-06-08 at 10 28 50" src="https://user-images.githubusercontent.com/23149420/84062371-66906780-a97c-11ea-8aa0-446651d3cae7.png">
<img width="1392" alt="Screenshot 2020-06-08 at 10 29 25" src="https://user-images.githubusercontent.com/23149420/84062372-6728fe00-a97c-11ea-909e-f5a13273eaa3.png">
<img width="1392" alt="Screenshot 2020-06-08 at 10 29 54" src="https://user-images.githubusercontent.com/23149420/84062376-67c19480-a97c-11ea-92ed-5110af2cd6fe.png">

**Comment by chrissimpkins** [comment]
@Colophon-Foundry Thoughts about this issue?

**Comment by Colophon-Foundry** [comment]
Yep, let's shift these down! Is this just in the brace layers?

**Comment by chrissimpkins** [comment]
@dberlow David is this issue addressed in your work?

**Comment by madig** [comment]
I think this is addressed in main?
