### ISSUE TITLE
Google Sans VF test build instance definitions for Figma auto-opsz

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans#521]
**This is a test implementation and not currently intended for production release.**

Figma requires all fvar/STAT instance definitions to be defined at the optical size axis default value in order to toggle automatic VF optical sizing for text size on by default.  Let's build Roman and Italic test VFs that have the following instances, all defined at opsz 18:

- Regular
- Medium
- Bold
- Italic
- Medium Italic
- Bold Italic

The change removes all "Text" instances.  

We'll use this set of fonts to test the static to VF format transition in Figma.

**Comment by belluzj** [comment]
Hello Chris, as per your email we just tested this, it worked after simply removing the 3 "Text" fvar instances from both fonts, by hand in OTMaster, based on the v9.000 release. You can see in the screenshot below by looking at the /G.

![image](https://user-images.githubusercontent.com/3616772/184119415-dbffe782-137d-42cb-8bf3-7e5180a7e86d.png)

The default behaviour of Figma on the original fonts (with all instances) is strange, e.g. when we made it bold in the bottom right corner, it switched from Text Regular to Display Bold...

[variable_figma.zip](https://github.com/googlefonts/googlesans/files/9308068/variable_figma.zip)

**Comment by chrissimpkins** [comment]
Thank you very much Jany!  

> The default behaviour of Figma on the original fonts (with all instances) is strange, e.g. when we made it bold in the bottom right corner, it switched from Text Regular to Display Bold...

Hmm.  That *is* strange. I am in touch with the Figma team about this issue.  Are you able to share that Figma file with me so that they can reproduce it to investigate a fix?

**Comment by belluzj** [comment]
Please find attached the Figma file and the fonts (these are also a copy of v9.000 where I did a quick and dirty rename to "Google Sans Original" to distinguish them from the other ones).

[Google Sans VF Test for Chris.zip](https://github.com/googlefonts/googlesans/files/9309247/Google.Sans.VF.Test.for.Chris.zip)
[variable_original.zip](https://github.com/googlefonts/googlesans/files/9309249/variable_original.zip)

**Comment by chrissimpkins** [comment]
These files work great Jany.  Thank you very much for preparing them.  I am circulating the fonts and Figma file around to the designers who were interested in this default auto-opsz behavior.  We may need a new Figma-specific VF build target to support it if we decide to use the approach in Figma (only).  I'll chat with you about this in more detail when I hear back.

**Comment by belluzj** [comment]
TODO @Hoolean add a pipeline step to make the Figma VF

**Comment by MariannaPaszkowska** [comment]
@belluzj @Hoolean Is this edit only on the fvar, or are we also editing the STAT table here?

CC @chrissimpkins

**Comment by belluzj** [comment]
This edit was only on the fvar, here is the only diff between the Figma file and the v9.000 release:

![image](https://user-images.githubusercontent.com/3616772/192984812-9be04f80-9278-4353-815c-126a8ffe7069.png)

(the other diffs near the top are the checksum and timestamp).

**Comment by belluzj** [comment]
I see now in Chris' first message that he said that Figma also required the STAT entry to be deleted, and I forgot to do that when I prepared the file, if you want I can delete it and send you the file again.
![image](https://user-images.githubusercontent.com/3616772/192985480-f859d68c-5dd6-410f-a9ad-8e10bfbbf5da.png)

**Comment by MariannaPaszkowska** [comment]
ok, thanks for clarifying that, I'll chat with @chrissimpkins and will get back to you. @belluzj

**Comment by chrissimpkins** [comment]
The file works with only fvar instances removed.  Marianna recommended that we keep the STAT instance definitions consistent in these Figma builds.  I agree with her.  

These are builds that will be pushed to the Figma corporate distribution at each release.  Are we prepared to add this new build target as of the v10 release in the next week’ish or in the week or two after?

**Comment by belluzj** [comment]
> Marianna recommended that we keep the STAT instance definitions consistent in these Figma builds. I agree with her.

@chrissimpkins @MariannaPaszkowska By that, do you mean consistent with non-Figma Google Sans, meaning we keep all the STAT entries, or consistent with the Figma-only Google Sans, meaning we delete the Text STAT entry?

> Are we prepared to add this new build target as of the v10 release in the next week’ish or in the week or two after?

We'll check the state of the PR and come back to you.

**Comment by belluzj** [comment]
Conclusion: keep the STAT entries. TODO @Hoolean integrate in the pipeline, just after v10.000 release

**Comment by chrissimpkins** [comment]
We decided earlier this week to move the post-production Figma edits outside of our repository build pipelines.  The same changes will be required on all GS derivative projects and it seems more optimal to maintain one set of sources to address the issue outside of the repo rather than multiple sources across all GS repos.  Marianna and I would like to discuss the script in https://github.com/googlefonts/googlesans/pull/524 with you so that we can decide how to make it apply to any GS project VF builds, then we'll set up the post-build prod process to address it. No need to add to the repository build workflow.

Thanks!

**Comment by belluzj** [comment]
@chrissimpkins The script from Harry can work on any TTF so it can be moved outside of the repo to a new one that covers all the fonts in the Google Sans family. The script takes file names as arguments and doesn't make any Google Sans-specific assumptions.

**Comment by anthrotype** [comment]
> Figma requires all fvar/STAT instance definitions to be defined at the optical size axis default value in order to toggle automatic VF optical sizing for text size on by default.

this feels abritrary to me and overly self-limiting, why can't one have both automatic optical sizes and also define named instances along opsz? Have you contacted Figma about this?

**Comment by chrissimpkins** [comment]
Completely agree with you Cosimo.  The issue is that this is the way that auto-opsz is on *by default*.  You can get to that behavior with a toggle buried in their VF panel, but it requires a UX designer to seek out that panel, understand what optical size is, correctly set it for every text size that they use, then carry on with their design work. @davelab6  wants it to be on everywhere by default and transparent to UX teams, so they don't even need to know that it happens, it just works behind the scenes.  For that, we need 'on by default', and this is the 'on by default' approach that Figma went with.

**Comment by anthrotype** [comment]
ok.. thanks for the clarification
