### ISSUE TITLE
Add Gujarati script

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans#525]
Sources will be on the repository Sept 16

cc @Hoolean @madig @belluzj

**Comment by chrissimpkins** [comment]
Status @kalapi?

**Comment by kalapi** [comment]
@chrissimpkins Making final fixes, will upload the package tomorrow.

**Comment by kalapi** [comment]
Hello! Apologies for the delay in getting you the sources, we're working through resolving some last-minute QA issues and i'm hoping to upload them by end of day today.

**Comment by kalapi** [comment]
@chrissimpkins @MariannaPaszkowska @Hoolean @madig @belluzj 

Adding the latest BETA package here. The only thing remaining are the regression test TOML files. I'll add these here tomorrow.

[2022-09-20_GoogleSansGujarati_V1.000_BETA01.zip](https://github.com/googlefonts/googlesans/files/9606302/2022-09-20_GoogleSansGujarati_V1.000_BETA01.zip)

**Comment by Hoolean** [comment]
Hello @kalapi 👋

We have made an initial merge but require some changes:

1. In upright, `/nga-gujarati` is incompatible across sources (different number of segments), which prevents the variable font from compiling.

2. Some glyphs do not have the final production name set (e.g. `/aiMatra_reph-gujarati` has `aiMatra_rephgujarati`, but needs to have `uni0AC80AB00ACD`).

3. The upright and italic have different glyphs in the "base" category:
   - "base" in upright but not in italic: `/five-gujarati` `/ja_iiMatra-gujarati` `/s-gujarati` `/zha_iiMatra-gujarati`
   - "base" in italic but not in upright: `/ai-gujarati` `/e-gujarati` `/k_la-gujarati` `/k_va-gujarati`

5. Some spacing in the provided TTFs is different to in the original Google Sans (e.g. different /space width, different x-height).
   - As an example, here is `/space` in Text Bold Italic. While this glyph is not imported, it does affect the visual comparison of the TTFs:

|Google Sans|Supplied Gujarati TTF|
|-|-|
| ![image](https://user-images.githubusercontent.com/2150762/191318107-431b4649-183b-4da9-9a29-b0da7e586c2e.png) | ![image](https://user-images.githubusercontent.com/2150762/191318295-284400a6-7216-4c86-834e-181bb9e3a275.png) |

Thank you for the new script, and do let us know if you have any queries on any of these :)

**Comment by kalapi** [comment]
Many thanks, will send you a new package in a bit.

**Comment by MariannaPaszkowska** [comment]
@kalapi  Just so we know where we are with the schedule, how much time would you need to address this?

**Comment by kalapi** [comment]
Dear @Hoolean & @MariannaPaszkowska ,

I'm attaching an updated package here:

> 1. In upright, /nga-gujarati is incompatible across sources (different number of segments), which prevents the variable font from compiling.

- [x] This is strange, the VF was compiling through my version of `fontmake`. It's probably because it had a transformed component, which i've now fixed

> 2. Some glyphs do not have the final production name set (e.g. /aiMatra_reph-gujarati has aiMatra_rephgujarati, but needs to have uni0AC80AB00ACD).

- [x] This should be fixed now, i've also included an updated `GlyphData.xml` for your reference

> 3. The upright and italic have different glyphs in the "base" category:
> 
> "base" in upright but not in italic: /five-gujarati /ja_iiMatra-gujarati /s-gujarati /zha_iiMatra-gujarati
> "base" in italic but not in upright: /ai-gujarati /e-gujarati /k_la-gujarati /k_va-gujarati

- [x] This should be fixed with the glyph data update.

> 4. Some spacing in the provided TTFs is different to in the original Google Sans (e.g. different /space width, different x-height).

- [x] I've updated the advance on the space glyph in the Italic master (sorry, this keeps slipping through my QA for some reason; added a hard-check to test for this for future scripts). I'm guessing that the `x-height` is not an issue since it's over-written by the upstream metadata, and won't affect visual comparison?

[2022-09-21_GoogleSansGujarati_V1.000_BETA02.zip](https://github.com/googlefonts/googlesans/files/9619258/2022-09-21_GoogleSansGujarati_V1.000_BETA02.zip)

**Comment by Hoolean** [comment]
Thank you for the fixes @kalapi! I have merged them in, and will be passing them on to Jonny to start his QA tomorrow morning 🚀

I will also attach them here, in case you wish to confirm they still work as desired: [GoogleSansGujaratiMergeBeta02.zip](https://github.com/googlefonts/googlesans/files/9628381/GoogleSansGujaratiMergeBeta02.zip)

**Comment by Hoolean** [comment]
Hello all!

Our QA has now concluded, with the full feedback available in an internal doc.

Aside from trouble with InDesign, no problems were reported :tada: Thank you @kalapi!

The issue with InDesign was more severe than in Odia. Unusually, the OpenType shaping was not functional at all, both pre- and post- merge, and in both the static and variable builds. Despite this, Noto worked as expected.

@MariannaPaszkowska @chrissimpkins All behaviour was correct in Chrome, and I understand that InDesign is not a platform we prioritise; should we investigate any further?

**Comment by chrissimpkins** [comment]
Thank you very much Harry!

We have a regular meeting with the Adobe fonts eng team.  I will try to identify the appropriate contacts on the Adobe side so that we can raise these issues with them.  I don't see this as a blocking issue unless anyone in this thread is aware of a way to 'fix' it at the font level for Adobe apps.  This may not be in our ability to address.

**Comment by chrissimpkins** [comment]
@kalapi Do you have thoughts about why Noto might shape appropriately in InDesign whereas GS does not so that we can discuss this with the Adobe team?

**Comment by kalapi** [comment]
@chrissimpkins The only reason I can think about is the omission of the older OpenType script tag `gujr` in favour of the newer `gjr2`. I'm looking into this now.

**Comment by kalapi** [comment]
Okay, I tested both (variable & statics) on InDesign 2021 and the fonts (i've generated) are shaping perfectly fine. 

I'm adding a screenshot below of the conjunct test.

<img width="1012" alt="Screenshot 2022-09-28 at 5 10 11 PM" src="https://user-images.githubusercontent.com/15804460/192889441-f3675a54-c258-46d6-876c-94e2c51948cf.png">

**Comment by kalapi** [comment]
Works also on Adobe Illustrator 2022 (v26.5)

<img width="1031" alt="Screenshot 2022-09-28 at 6 00 04 PM" src="https://user-images.githubusercontent.com/15804460/192896727-766ce2de-e192-4b0b-8a14-6b1e9965bc33.png">

**Comment by MariannaPaszkowska** [comment]
@Hoolean Do we have .json .toml files ready?

**Comment by Hoolean** [comment]
Hi @MariannaPaszkowska! As I understand it, @kalapi will be sharing these, and so we are waiting on that to add them.

**Comment by kalapi** [comment]
Sorry, I'd finished this yesterday. But forgot to upload it on this thread. Please find the TOML files attached below. 

Also let me know if the Adobe issue is now resolved. Thanks!

[shaping_input.zip](https://github.com/googlefonts/googlesans/files/9674749/shaping_input.zip)
