### ISSUE TITLE
/A rasteriser workaround

### ISSUE THREAD

**Issue by Hoolean** [googlefonts/googlesans#527]
During the Lao Loopless QA, Hanna commented on the construction of /A in our Latin sources:

> Spotted the /A is drawn with the bar as 2 segments. Is this correct? If it is intentional, 
	what is the benefit of this construction?
> ![image](https://user-images.githubusercontent.com/2150762/188868747-d1d56294-2938-4566-8447-f18b26711e6f.png)

@MariannaPaszkowska suggests that this prevents bugs with older rasterisers, and so it is almost certainly intentional.

Is there anything further we need to look into here?

**Comment by m4rc1e** [comment]
Welcome to hell. @MariannaPaszkowska is correct. See http://twardoch.github.io/test-fonts/varia/160413-EvenOddTT/ and  https://github.com/google/fonts/issues/2602 for more info.

**Comment by m4rc1e** [comment]
I should add that we tend to ignore this issue for most families. However, for Roboto and Open Sans, we do tweak the overlaps so this issue doesn't happen.

**Comment by MariannaPaszkowska** [comment]
Thanks, Mark! Yes, that's exactly what I meant.

śr., 7 wrz 2022 o 14:55 Marc Foley ***@***.***> napisał(a):

**Comment by chrissimpkins** [comment]
OK to close?
