### ISSUE TITLE
Remove `r` ligature forms

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans#528]
Creative directors on the project decided to remove all `r` ligature forms.  Let's add this to the v10 release

cc @MariannaPaszkowska

**Comment by chrissimpkins** [comment]
Defined in this fea file block

https://github.com/googlefonts/googlesans/blob/b9987ae02d5e8bfc22f82fe84254fc5e994195cb/source/GoogleSans/family.fea#L352-L380

**Comment by MariannaPaszkowska** [comment]
@chrissimpkins Should we remove the `r` ligature forms only from the `liga`, or also from the `dlig` feature? 
Are we removing the ligated glyphs?

**Comment by chrissimpkins** [comment]
Yes, please remove the fea file definitions everywhere but let's keep the outlines.  IMO we don't need to add them to non-export lists. It is only a few glyphs and we will strip them at the subsetter stage of the build process.

**Comment by chrissimpkins** [comment]
Closed by https://github.com/googlefonts/googlesans/pull/529
