### ISSUE TITLE
Proposal for redefining period and colon kerning groups

### ISSUE THREAD

**Issue by gorjious** [googlefonts/googlesans#53]
Currently, the following punctuation marks (period, comma, colon, semicolon) are dividing into these two kerning groups:

Kerning group: Period
Period [ . ]
Comma [ , ]

Kerning group: Colon
Colon [ : ]
Semicolon [ ; ]

I would like to propose redefining these kerning groups to reference the shape of the base component:

Kerning group: Period
Period [ . ]
Colon [ : ]

Kerning group: Comma
Comma [ , ]
Semicolon [ ; ]

In the case of the Armenian script, there are various horizontal bars that occur along at various levels between the x-height and descender depth. The position of these bars affects the amount of kerning necessary for each type. It would be helpful to be able to control kerning for the period-type punctuation differently than the comma-type.

To take it one step further, would it make sense to group period differently than colon? This would be in order to account for combinations such as ժ։ժ. where the x-height bar limits the position of the [ ։ ] but allows for [ . ] to kern under the bar. Or, is it better to handle these cases as Kerning Exceptions? 

<img width="654" alt="Screenshot 2020-06-08 at 11 40 36" src="https://user-images.githubusercontent.com/23149420/84062669-ec141780-a97c-11ea-9574-11fa94ccfa5d.png">

**Comment by chrissimpkins** [comment]
@Colophon-Foundry Thoughts about this issue?

**Comment by Colophon-Foundry** [comment]
My only thoughts with that is the colon/semicolon clashing with some uppercase forms.
For example `W.` and `W:` require different kern values. I'd imagine there will be some more, but we'd have to go through and check.

![Screenshot 2020-06-12 at 16 52 13](https://user-images.githubusercontent.com/32193288/84521617-2fe48500-accd-11ea-9126-1c5860a3e5ca.png)

**Comment by gorjious** [comment]
If the kerning groups are redefined with colon and period being in the same group, would it make sense to set combinations such `W.` or `Ժ.` as exceptions? Or is better to avoid exceptions and have each in a separate group?

I imagine that other scripts sharing Latin punctuation (or have similar marks based on the Latin shapes) which can also benefit from being able to differentiate kerning based on 1 [ . ,  ] or 2 [ : ; ] level/story punctuation marks (maybe there is a better term to help define the kerning group name), as well as if the form of the bottom base glyph is dot-shaped or comma-shaped.
