### ISSUE TITLE
Shaping behaviour in Sinhala

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans#531]
During testing, I observed some shaping inconsistencies between Sinhala in Noto Sans Sinhala and Google Sans. Could you please clarify if that's intentional? @kalapi @Hoolean @belluzj

<img width="506" alt="Shaping_Sinhala" src="https://user-images.githubusercontent.com/22956348/192282289-2e3c84a3-3d58-4682-8c9b-4d745c713daa.png">

 ල්‍රි ළ්‍රි ල්‍රී ළ්‍රී
 
_That's a snapshot from Figma_

CC @chrissimpkins

**Comment by kalapi** [comment]
Hi @MariannaPaszkowska,

These combinations are supported by Noto but are considered unpronounceable in Sinhalese. Rakaar conjunct of `la-sinhala` & `ra-sinhala`. You can perform a simple Google search of every combination in the string above and check the results.

**Comment by chrissimpkins** [comment]
Thank you very much Kalapi!

**Comment by MariannaPaszkowska** [comment]
Hi @kalapi, thanks a lot for the quick reply! I noticed today that I missed a couple of glyphs in my report yesterday; apologies. Could you confirm that those are also intentional? `ල්‍ර` `ළ්‍ර`

<img width="510" alt="Screenshot 2022-09-27 at 10 44 19 AM" src="https://user-images.githubusercontent.com/22956348/192465326-e1998bdf-7275-43f3-9b6e-395469f8221f.png">
_That's a snapshot from Figma_

CC @chrissimpkins

@belluzj After confirming, could we please update the .toml and .json files to exclude these?

**Comment by belluzj** [comment]
Yes I take a note to update the TOML and JSON

**Comment by kalapi** [comment]
@MariannaPaszkowska This is the same as previous issue. @belluzj Ill update the TOML files on my end to remove any superfluous combinations, especially ones we're not shaping. Apologies for including them.

**Comment by chrissimpkins** [comment]
We discussed this with Kalapi today.  The characters that will be removed from shaping text runs do not require replacement.  He feels that the remaining characters appropriately cover the newly added layout source.

**Comment by MariannaPaszkowska** [comment]
Thank you @kalapi @belluzj! This issue is now closed.

**Comment by belluzj** [comment]
Just to clarify @MariannaPaszkowska @kalapi should we receive updated TOML files to merge or are we good as it is now? Thanks in advance!

**Comment by kalapi** [comment]
I'm sending updated TOML files, but I'll need some time.

**Comment by chrissimpkins** [comment]
IMO we should update the shaping definitions and confirm that we lock in expected HB shaped output values before we merge.  But I think that this is just removal of a few glyphs, no?  Can Jany remove the ones that need to go away Kalapi?  Or did you have larger edits to the text runs planned?

**Comment by kalapi** [comment]
@chrissimpkins Removals only

Attaching the updated TOML files here. Let me know if you'd like this as part of the entire package together.

[shaping_input.zip](https://github.com/googlefonts/googlesans/files/9668391/shaping_input.zip)

**Comment by MariannaPaszkowska** [comment]
Thank you @kalapi

**Comment by belluzj** [comment]
Thanks Kalapi, I will merge the new TOMLs.
