### ISSUE TITLE
Add Direct Current Symbol Form Two (U+2393) 

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans#535]
The symbol will be used in laser etching on product surfaces, including plastics and metals, at very small text sizes (demo at 3.2pt today). The team attempted to use the symbol available in Noto and found that the top and bottom strokes have a tendency to overlap/blend at these laser etched text sizes. We'll need to take this into consideration as we develop the outlines.  The team is willing to test the designs as we develop. 

@MariannaPaszkowska

**Comment by chrissimpkins** [comment]
Example of the symbol in use and problems that the team encountered at small size:

<img width="996" alt="BRcFUie9t6ankaC" src="https://user-images.githubusercontent.com/4249591/193823187-0f938230-c0b4-491c-ba92-c963a2af0b2c.png">

**Comment by chrissimpkins** [comment]
DaMa design will work on this during Q4 2022.  v11 milestone is added to the issue and is correct

**Comment by madig** [comment]
It's for all masters, right? Wght, Ital, GRAD?

**Comment by chrissimpkins** [comment]
Correct!

**Comment by chrissimpkins** [comment]
I reached out to the team reviewing the latest round of changes this week.  I'll be in touch with feedback timing as soon as I hear back from them.

**Comment by chrissimpkins** [comment]
Feedback round 2:

### Questions for DaMa

1. How was baseline shift determined? Glyph sits higher than y-center (mid-point between baseline and cap height). Centered is PG preference.
2. Text version now has larger gaps between dashes (previously Reg had larger gaps). This update seems good but what’s the thinking? Has this been done so Text feels more open than Regular?


### Feedback to DaMa

1. Alignment at ends is good.
2. Even widths of dashes is good.

@elenaperaltad

**Comment by belluzj** [comment]
@chrissimpkins about question number 2: we provided the different spaces in Text and Regular because that was one uncertain parameter to test. Initially Elena proposed to provide 2 test fonts with different gaps, but in the Monday meeting on 13 Dec 2022 ([see the Google Doc](https://docs.google.com/document/d/1nC4XIB-gX6sbDW33qWpJux-qzhf_wnj-_EbeaOTW_C0/edit#bookmark=id.7py1xariypdk)) it was decided to provide the two options in a variable way, to allow the testing team to choose the best one.

**Comment by belluzj** [comment]
I have the answer from Elena about question number 1:

> The alignment on the first round followed the equal sign alignment. After their testing and round of feedback they requested to raise the symbol to be cap height centred, so we optically centred it. If they want we can mathematically center it.

![image](https://user-images.githubusercontent.com/3616772/212978985-c4dbcf26-75b3-4066-90d3-5b8af8d19bdb.png)
![image](https://user-images.githubusercontent.com/3616772/212979010-a74e2ef7-c859-49f9-b12e-b402d97e0620.png)


@chrissimpkins I hope that helps, let me know what we can do next, e.g. center mathematically if that's the preferred option.

**Comment by chrissimpkins** [comment]
> @chrissimpkins about question number 2: we provided the different spaces in Text and Regular because that was one uncertain parameter to test. Initially Elena proposed to provide 2 test fonts with different gaps, but in the Monday meeting on 13 Dec 2022 ([see the Google Doc](https://docs.google.com/document/d/1nC4XIB-gX6sbDW33qWpJux-qzhf_wnj-_EbeaOTW_C0/edit#bookmark=id.7py1xariypdk)) it was decided to provide the two options in a variable way, to allow the testing team to choose the best one.

I discussed this with the team today.  All good on this question.  Thanks!

**Comment by chrissimpkins** [comment]
re: question (1)

I discussed the optical centering with the team today and they request mathematic centering.  Illustration to support the new request below:

<img width="866" alt="872LnRM6zhfh8A3" src="https://user-images.githubusercontent.com/4249591/213788711-03aea14a-2b83-4657-b291-cdd1a55e3193.png">

No change is required in the glyph outlines.  They are really happy with where things are there.  

They request that you center the glyph so that dimensions `a` in "Google Sans" = opsz 18 masters and `b` in "Google Sans Text" = opsz 17 are the same number of units between the top / bottom and centered on the upper case `V` to the left (cap height, not figure height that changes across opsz axis).  The spacing between the upper and bottom horizontal contours are different over the opsz axis making the `a` value different from the `b` value in the two designs.  This will also future proof us when the cap height figure transition lands #387 

Please let me know if I've explained this adequately.  Happy to discuss in more detail.

**Comment by belluzj** [comment]
Hello @MariannaPaszkowska and @chrissimpkins, it looks to me that the next step on this issue would be for @elenaperaltad to make the changes as per the latest round of feedback (requesting vertical centring as above). Are you OK for us to proceed?

**Comment by chrissimpkins** [comment]
Please do, thanks!

**Comment by chrissimpkins** [comment]
We received the latest round of revisions from Elena and the files have been distributed to the Google team for testing. I'll update here when we have additional feedback. Thanks!

**Comment by chrissimpkins** [comment]
The latest revisions were approved by the requesting team.  Thank you very much for all of your help here!

@MariannaPaszkowska https://github.com/googlefonts/googlesans/pull/545 can be merged to land this new glyph in the v11 release whenever DaMa thinks that the time is right.

**Comment by belluzj** [comment]
Thanks @chrissimpkins and @MariannaPaszkowska . Before you merge, should we add the final design to the italics as well? (with the appropriate slant). @elenaperaltad can work on it next week.

**Comment by chrissimpkins** [comment]
Please do! Thanks
