### ISSUE TITLE
Add Gurage support

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans#542]

**Comment by chrissimpkins** [comment]
@NeilSureshPatel Will you please provide a tentative source delivery date when you have a chance? Ty!

**Comment by NeilSureshPatel** [comment]
I'll touch base with Mark tomorrow and get you a tentative date

**Comment by NeilSureshPatel** [comment]
@chrissimpkins It looks like we could deliver as soon as tomorrow or early next week.

**Comment by NeilSureshPatel** [comment]
@chrissimpkins Quick question about delivering sources. In the past we had put the sources in my [google-sans-ethiopic](https://github.com/NeilSureshPatel/google-sans-ethiopic/tree/master/source/GoogleSans) repo. A lot has changed since then. Would it be better to fork this repo and upload the Gurage updates? Also, should we convert them to UFO or will that happen during the onboarding. I assume we will need to update import_glyphs.txt as well. Thanks.

**Comment by chrissimpkins** [comment]
It is ok to drop the Glyphs format sources with shaping code, glyph name import list, and text runs required for the regression tests in a zip archive in this issue thread.  Make it simple on yourself. It would be worth **storing** them in one of your git repos for safe keeping and future reference.  But we don't need a repo to transfer the data and import.  Thanks!

**Comment by MarkJamra** [comment]
Google Sans Ethiopic Gurage is attached.
[GoogleSans_Ethiopic_Gurage.zip](https://github.com/googlefonts/googlesans/files/9840922/GoogleSans_Ethiopic_Gurage.zip)

**Comment by chrissimpkins** [comment]
Thank you very much Mark!

@belluzj @MariannaPaszkowska Let's discuss timing on this relative to other scripts on Monday.

**Comment by madig** [comment]
During conversion to UFOs, I'm getting a message about how the public.kern1.ethi_hhwagurage kerning group does not exist. Is this a leftover?

**Comment by madig** [comment]
Also, the fea file does not compile because blocks are missing their name at the end, like in `feature bla { ... } bla;`, what editor are you using?

**Comment by madig** [comment]
Also, the import glyph list is incomplete. I had to add geez part 11 or some such, and it now complains about ethi_num (referenced in ethiopic.fea). Can you please double check the list? Or is ethi_num the feature group name? If so, can you please fix the feature file to compile when using fontmake?

**Comment by NeilSureshPatel** [comment]
> During conversion to UFOs, I'm getting a message about how the public.kern1.ethi_hhwagurage kerning group does not exist. Is this a leftover?

Are kerning class names case sensitive for fontmake? This is a real class but the in our Glyphs file the class is spelled ethi_hhwaGurage. Not sure if this is causing the problem.


> Also, the fea file does not compile because blocks are missing their name at the end, like in `feature bla { ... } bla;`, what editor are you using?

We'll fix this.


> Also, the import glyph list is incomplete. I had to add geez part 11 or some such, and it now complains about ethi_num (referenced in ethiopic.fea). Can you please double check the list? Or is ethi_num the feature group name? If so, can you please fix the feature file to compile when using fontmake?

We'll rename some of the components to be more consistent and double check the list. ethi_num is class that is used for substitution. Not sure why it is complaining about that. We'll have to see what happens after cleaning up the other stuff.

**Comment by NeilSureshPatel** [comment]
Ok give these files a try. The kerning class error seems to have been something that was stuck in the kerning table that was not obvious. I ran a clean-up on the kerning pairs in Glyphs and now I don't get the error when converting to UFO.

[GoogleSans_Ethiopic_Gurage.zip](https://github.com/googlefonts/googlesans/files/11215077/GoogleSans_Ethiopic_Gurage.zip)

**Comment by madig** [comment]
Thanks. What is the relation between ethiopic.fea in the Zip file and the features inside the glyphs files?

**Comment by madig** [comment]
Also, I see that various geez parts are marked non-export; I'll set them to export to reduce file size.

**Comment by NeilSureshPatel** [comment]
> Thanks. What is the relation between ethiopic.fea in the Zip file and the features inside the glyphs files?

The features in the glyphs file have some redundancies that are there for proofing on our end on different platforms. When we released the first version of the GS Ethiopic Chris and I spoke about which OT features should be supported in GS and we settled on just the ones that are in the ethiopic.fea file. 


> Also, I see that various geez parts are marked non-export; I'll set them to export to reduce file size.

Ahh yes, thanks. I assumed the final export list would be defined by the import_glyphs.txt file and not what is set in the glyphs file.

**Comment by madig** [comment]
Ok, I used the ethiopic.fea file for features. Can you please give the fonts in https://github.com/googlefonts/googlesans/suites/12288059283/artifacts/651068826 a lookover to see if they are broadly in order?

**Comment by NeilSureshPatel** [comment]
Ok gave the fonts a look through. The glyphs look good and seem to work properly when sliding the axes. All of the features are present and seem to work as well. The only thing I wanted to double check is if we used a Stylistic Set in the previous release to disconnect the numerals. Is there an easy way to find the previous release? Thanks.

**Comment by madig** [comment]
Yes, you can find it in here: https://github.com/googlefonts/googlesans/releases/download/v10.001/GoogleSans-v10.001.zip

**Comment by NeilSureshPatel** [comment]
Excellent. Thanks. I took a look and there are no stylistic features implemented in the previous version. Everything seems to check out.

**Comment by madig** [comment]
Thanks. I will now pass the fonts along for internal review.

**Comment by madig** [comment]
@NeilSureshPatel Could you please also provide your compiled fonts you tested with plus any test docs you can give us?

**Comment by NeilSureshPatel** [comment]
@madig Here are the static fonts and and few testing resources. Aside from the additional glyphs added for Gurage, nothing else has changed from the previous version of the GSans Ethiopic. Let me know if there is anything else you need.
[GSansEthiGurage.zip](https://github.com/googlefonts/googlesans/files/11324235/GSansEthiGurage.zip)

**Comment by madig** [comment]
Thanks. Did you also test with variable fonts?

**Comment by NeilSureshPatel** [comment]
We did not test with variable fonts. The Glyphs sources fail to export variable fonts due to some issues with alternate forms in the Greek and Latin sets.

**Comment by madig** [comment]
@NeilSureshPatel our QA finished his review and wrote up just two minor things in an internal doc, can you please take a look?

**Comment by NeilSureshPatel** [comment]
@madig thanks. I have requested access to the doc. Once I can view it, I will take a look.

**Comment by madig** [comment]
@NeilSureshPatel just for coordination purposes, are you going to make changes to the locl feature?

**Comment by NeilSureshPatel** [comment]
@madig yes, I will update the fea file and send it over.

**Comment by NeilSureshPatel** [comment]
Here is the updated .fea file with a new locl feature.
[ethiopic.fea.zip](https://github.com/googlefonts/googlesans/files/11408214/ethiopic.fea.zip)

**Comment by madig** [comment]
@NeilSureshPatel oh, did any of the regression strings change for Gurage? If not, can you please provide some test strings exercising features?

**Comment by madig** [comment]
I actually see some changes in the ethiopic_locl test, advance width changes from what I can see. Are these intentional?

**Comment by madig** [comment]
And: A bunch of glyphs didn't get production names:

* hhya-ethiopic
* hhyu-ethiopic
* hhyi-ethiopic
* hhyaa-ethiopic
* hhyee-ethiopic
* hhye-ethiopic
* hhyo-ethiopic
* hhwi-ethiopic
* hhwee-ethiopic
* hhwe-ethiopic
* hhwaGurage-ethiopic
* mwiGurage-ethiopic
* mweeGurage-ethiopic
* qwiGurage-ethiopic
* qweeGurage-ethiopic
* qweGurage-ethiopic
* bwiGurage-ethiopic
* bweeGurage-ethiopic
* kwiGurage-ethiopic
* kweeGurage-ethiopic
* kweGurage-ethiopic
* gwiGurage-ethiopic
* gweeGurage-ethiopic
* gweGurage-ethiopic
* fwiGurage-ethiopic
* fweeGurage-ethiopic
* pwiGurage-ethiopic
* pweeGurage-ethiopic

Also intentional?

**Comment by chrissimpkins** [comment]
Postponing to v12 release to avoid the dependency update requirement for the massive GPOS addition that is coming with this addition.  The dependency updates are likely to lead to additional pixel level screenshot diffs.  We'll roll this out in a future release after we ship the Kannada and Malayalam support that is required for UI/content

**Comment by NeilSureshPatel** [comment]
> @NeilSureshPatel oh, did any of the regression strings change for Gurage? If not, can you please provide some test strings exercising features?

The features don't change for Gurage specifically, so I didn't provide any new test strings. If you need just a string with Gurage text to make sure some of the glyphs appear properly though I can do that.


> I actually see some changes in the ethiopic_locl test, advance width changes from what I can see. Are these intentional?

Could you point specifically which advanced width changes you are seeing? 



> And: A bunch of glyphs didn't get production names:

This isn't intentional. Where do the names get assigned in the fontmake workflow? If we were exporting final files directly from Glyphs, we have to use a custom GlyphsData.xml file to define those since they are pretty new. I am not sure what happens in the GSans build flow.

**Comment by MariannaPaszkowska** [comment]
This family will be released separately in a new repository.

**Comment by madig** [comment]
@NeilSureshPatel can you please run the following script on the Glyphs sources and pass them again?

```
# MenuTitle: Embed Glyph Metadata in Current Font

"""Embeds production name, category and sub category into each glyph of the
current font."""

for glyph in Glyphs.font.glyphs:
    glyph.storeProductionName = True
    glyph.storeSubCategory = True
    glyph.storeCategory = True
```

This will store production names in the file, as we don't have your GlyphData.xml file. Please also ensure that 

* the features are the latest and compile with fontmake
* all glyphs are exported (check the geez components)

@MariannaPaszkowska @chrissimpkins The sources already contain Latin, etc., do you want me to compile the sources as they are? Merging becomes error prone if the set is already (partly) there, so I'd like to either request a Gurage-only source or have the team import the desired Latin base set themselves.

**Comment by MariannaPaszkowska** [comment]
@NeilSureshPatel, could you provide us with Gurage-only sources? We want to ensure we release the latest version of Latin with Gurage. :)

**Comment by NeilSureshPatel** [comment]
> @NeilSureshPatel can you please run the following script on the Glyphs sources and pass them again?
> 
> ```
> # MenuTitle: Embed Glyph Metadata in Current Font
> 
> """Embeds production name, category and sub category into each glyph of the
> current font."""
> 
> for glyph in Glyphs.font.glyphs:
>     glyph.storeProductionName = True
>     glyph.storeSubCategory = True
>     glyph.storeCategory = True
> ```
> 
> This will store production names in the file, as we don't have your GlyphData.xml file. Please also ensure that
> 
> * the features are the latest and compile with fontmake
> * all glyphs are exported (check the geez components)
> 
> @MariannaPaszkowska @chrissimpkins The sources already contain Latin, etc., do you want me to compile the sources as they are? Merging becomes error prone if the set is already (partly) there, so I'd like to either request a Gurage-only source or have the team import the desired Latin base set themselves.

@madig do you want me to run this script on the full Ethiopic source or just the Gurage only source?

**Comment by madig** [comment]
Gurage only is fine.

**Comment by NeilSureshPatel** [comment]
Ok I think the Gurage-only sources are ready. I will post them to the new repo the @chrissimpkins create for GS Gurage. https://github.com/googlefonts/googlesans-gurage

**Comment by madig** [comment]
@NeilSureshPatel I'm getting the feature compilation error

> "ha-ethiopic" is not a glyph in the font, and it can not be split into a range of known glyphs

in the Italics. Can you please fix this and whatever other errors you see when compiling the sources with fontmake?

**Comment by NeilSureshPatel** [comment]
I built those sources with a fresh install of fontmake before I posted them, and I had no errors.
I built them with `fontmake -g <source>`. Are you using different options? I would like to reproduce the problem. Thanks.

**Comment by madig** [comment]
Hm. Are you using the newest fontmake? Are the source files supposed to use ethiopic.fea? I ran `fontmake -g file -o variable`.

**Comment by NeilSureshPatel** [comment]
Ok, Thanks. Let me try to building the variable font and see if I get the same error.

**Comment by NeilSureshPatel** [comment]
The ethiopic.fea file is not needed. I just included in case you needed it depending on the workflow. I updated fontmake just in case and built the variable fonts with no issues. I used local sources files. I pulled the sources down from github and I was able to reproduce the error you are seeing. I am not sure why since my local copies and what's is in repo have the same timestamp. I am going upload the sources again.

**Comment by NeilSureshPatel** [comment]
Updated the [sources](https://github.com/googlefonts/googlesans-gurage/tree/main/source). Give it a try now.

**Comment by madig** [comment]
@NeilSureshPatel hi! I noticed that Glyphs.app complains that some slanted glyphs' alignment is off:

![image](https://github.com/googlefonts/googlesans/assets/380829/841b5434-5a60-4fa1-b8d8-f10f6597a454)

Is this something to fix?

**Comment by NeilSureshPatel** [comment]
Hi @madig. Which version of glyphs are you using? Generally, we have been keeping the existing alignment as we change versions of Glyphs. Let me take a look and double check.

**Comment by madig** [comment]
I'm using the latest stable 3.1.2.

**Comment by madig** [comment]
Also, what's the purpose of the name table entries?

![image](https://github.com/googlefonts/googlesans/assets/380829/5bd2ba4e-86f6-4662-aa87-f596ad3ac8f5)

**Comment by NeilSureshPatel** [comment]
Thanks @madig for the Glyphs version. I am about to present a workshop. I'll check both of those things out after.

**Comment by NeilSureshPatel** [comment]
Ok. I took a look. For the alignment warnings in Glyphs we can go ahead and select all the glyphs and keep them as is. This is the usual Glyphs thing that happens when a glyph is made up completely from components. 

Regarding the names table entries. These are carried over from the full Google Sans release. I am not sure what the stand-alone Gurage font will be named. I can change these to be whatever we want.

**Comment by madig** [comment]
Ok. Another one: I see that there are various opsz variants of commas and quotes with the `.varAlt01` suffix... should they be there? Are they important for Gurage?

**Comment by NeilSureshPatel** [comment]
I didn't even realize that there were alternate commas, quotes, etc since those were design by the Latin team. I am not sure how or when the alternates get used in Google Sans. We do need that punctuation for Gurage but we don't necessarily need the alternates. That being said I think we may need input from @MariannaPaszkowska before removing them. If the alternates are for specific Latin use cases, then we could safely remove them. However, if they are used with all scripts for certain design needs then we should probably keep them.

**Comment by madig** [comment]
I think they were introduced by some conversion process, looking into it.

BTW, can you please fix the starting points here, they differ between display and text sources:

![image](https://github.com/googlefonts/googlesans/assets/380829/4c4297fc-19a1-4c6e-b3ae-0bdc163837d3)

**Comment by madig** [comment]
I believe we removed the bracket layers for quoteright, quoteleft, quotedblright, quotedblleft, quotedblbase, quotesinglbase, semicolon and comma (which is where the varAlt01 glyphs here are coming from, inserted by glyphsLib). We import that stuff from upstream anyway. @chrissimpkins @MariannaPaszkowska

**Comment by NeilSureshPatel** [comment]
@madig. I am fixing the start nodes. While I have the files open should I just remove custom name table entries? Also, should I give the font a name other than Google Sans? If so, what should the name be? Thanks.

**Comment by madig** [comment]
Please do, yes. The family name is "Google Sans Gurage", with the Text variants being their own "Google Sans Gurage Text" family. Please also remove the [18] layers, we import and overwrite the basic stuff from upstream.

**Comment by NeilSureshPatel** [comment]
Quick question. The old Google Sans sources had the Text family names over ridden like this.

<img width="997" alt="image" src="https://github.com/googlefonts/googlesans/assets/46502494/92a2890a-1449-4a82-b99a-d81f07f7672a">

Should I still follow this method? It seems like it is more straight forward to just use a Localized Family Name custom parameter and keep the style name as "Bold" instead of "Text Bold"

**Comment by madig** [comment]
Hm, I think it's good enough to insert "Gurage" where appropriate?

**Comment by NeilSureshPatel** [comment]
Got it, thanks.

The updated sources are posted to Github. [e5e02bb](https://github.com/googlefonts/googlesans-gurage/commit/e5e02bb8a032cf96311d4996918503d80eb9ea97)
