### ISSUE TITLE
Remote branch cleanup

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans#543]
We're approaching 50 remote branches.  I imagine that most of these are not required and were intended to be temporary working branches.  Let's plan to review and do a branch cleanup in October following the v10 release and before we dive back into script imports.

@MariannaPaszkowska @belluzj

**Comment by belluzj** [comment]
Noted, will do

**Comment by belluzj** [comment]
I cleaned a few branches just now, we're at 17. Most remaining sound related to yet-unresolved issues, or are archives of unmerged work.

![image](https://github.com/googlefonts/googlesans/assets/3616772/9f7f9d6a-0596-4c1a-9d49-02a1e077f71e)

**Comment by MariannaPaszkowska** [comment]
Many thanks!
