### ISSUE TITLE
Kerning of "

### ISSUE THREAD

**Issue by davelab6** [googlefonts/googlesans#55]
Kerning of `"` in GS Text Beta has some gaps:

<img width="261" alt="Screen Shot 2020-06-08 at 4 32 39 PM" src="https://user-images.githubusercontent.com/261579/84077719-c2bbb180-a9a5-11ea-898c-b4611a9a15e4.png">

<img width="607" alt="Screen Shot 2020-06-08 at 4 40 15 PM" src="https://user-images.githubusercontent.com/261579/84078335-c00d8c00-a9a6-11ea-927b-09f273594cbe.png">

Since this is the older Beta, I guess this has been resolved in the v3, but I'm filing this issue to track and confirm.

**Comment by chrissimpkins** [comment]
What build are you viewing?

**Comment by davelab6** [comment]
Its the GST Beta build in GSuite Prod.

**Comment by chrissimpkins** [comment]
Got it.  Yep we will take a look. Thanks for pointing it out.

**Comment by chrissimpkins** [comment]
D/W Edd and he did not feel that this required adjustment

**Comment by davelab6** [comment]
Maybe `,"` should be kerned closer

**Comment by dberlow** [comment]
Should be, and to ., L, and it's friend ’ to .,L.

Spot changes like this are up to you guys as far as timing. 

My main concerns now are getting all of the glyphs and axes working with the existing, upstream gsub and gpos and documenting my changes

**Comment by chrissimpkins** [comment]
> My main concerns now are getting all of the glyphs and axes working with the existing, upstream gsub and gpos and documenting my changes

Understood.  No problem.  We will address this down the road.

**Comment by chrissimpkins** [comment]
David addressed this downstream and the changes are now in #240 

Update will be released in v4.000

**Comment by chrissimpkins** [comment]
Kerning changes in #240

```
left                right               value               string
period              quoteright          -80                 .’
period              quotedblright       -80                 .”
ellipsis            uni0374             -80                 …ʹ
period              uni0374             -80                 .ʹ
comma               quotedblright       -80                 ,”
comma               quoteright          -80                 ,’
comma               uni0374             -80                 ,ʹ
ellipsis            quotedblright       -80                 …”
ellipsis            quoteright          -80                 …’
```

**Comment by chrissimpkins** [comment]
Merged to main
