### ISSUE TITLE
Add Kannada script

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans#562]

**Comment by kalapi** [comment]
Hello @MariannaPaszkowska @chrissimpkins @madig 

Adding the Kannada package below. 

[2022-11-29_GoogleSansKannada_v1.000_BETA01.zip](https://github.com/googlefonts/googlesans/files/10121104/2022-11-29_GoogleSansKannada_v1.000_BETA01.zip)

**Comment by MariannaPaszkowska** [comment]
Thank you, @kalapi!

**Comment by belluzj** [comment]
@MariannaPaszkowska Nikolaus has imported the sources from Kalapi into the [PR linked above](https://github.com/googlefonts/googlesans/pull/573), and doesn't have questions so far. @jonpinhorn will start looking at the merged fonts on Thursday.

**Comment by belluzj** [comment]
There is an internal document that we'll use later to report any questions or review comments. (Nothing actionable now, I'm just flagging the doc in advance)

**Comment by madig** [comment]
@kalapi I gave you access to the doc, please have a look at the issues Jonny found :)

**Comment by kalapi** [comment]
Hi @madig I've now responded :)

**Comment by MariannaPaszkowska** [comment]
Hi @kalapi @madig @chrissimpkins 
I completed my review. Kannada is ready to be merged!  🥳
