### ISSUE TITLE
Bad `ignore sub` in Bengali feature file

### ISSUE THREAD

**Issue by behdad** [googlefonts/googlesans#569]
```
WARNING:fontTools.feaLib.parser:/home/behdad/googlesans/source/GoogleSans/bangla.fea:107:16: Ambiguous "ignore sub", there should be least one marked glyph
WARNING:fontTools.feaLib.parser:/home/behdad/googlesans/source/GoogleSans/bangla.fea:131:16: Ambiguous "ignore sub", there should be least one marked glyph
```

**Comment by madig** [comment]
Specifically, these two lines trigger the warning:

https://github.com/googlefonts/googlesans/blob/e67a8938978044cb304cda284a6615839815ea13/source/GoogleSans/bangla.fea#L107

https://github.com/googlefonts/googlesans/blob/e67a8938978044cb304cda284a6615839815ea13/source/GoogleSans/bangla.fea#L131

**Comment by MariannaPaszkowska** [comment]
Hi @kalapi, any ideas about what might be an issue here?

**Comment by madig** [comment]
I think I fixed this, Simon suggested to add ticks to all glyphs and groups in the statement.

**Comment by MariannaPaszkowska** [comment]
#516
