### ISSUE TITLE
Fix the soft dotted characters (make the dot dissapear)

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans#576]
Fix the following strings: į̀ į́ į̂ į̃ į̄ į̌ і́

see fail: https://github.com/googlefonts/googlesans/actions/runs/4796497188/jobs/8533124125#step:5:524

**Comment by belluzj** [comment]
Hello Marianna, I can work on that this week

**Comment by MariannaPaszkowska** [comment]
useful resource: https://googlefonts.github.io/gf-guide/diacritics.html#soft-dotted-glyphs
