### ISSUE TITLE
Shaping review - conjuncts Malayalam

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans#580]
Hi @kalapi, Thanks a lot for the delivery! I noticed that those conjuncts are shaping differently in Noto than in GS, could you please confirm if this all is intentional? I tested shaping in Harfbuzz.

- [x] /ssamlym /viramamlym /ttamlym ഷ്ട 
- [x] /pamlym /viramamlym /tamlym പ്ത 
- [x] /kamlym /viramamlym /ttamlym ക്ട 
- [x] /bamlym /viramamlym /damlym ബ്ദ
- [x] /gamlym /viramamlym /damlym ഗ്ദ 
- [x] /bamlym /viramamlym /dhamlym ബ്ധ 
- [x] /nnamlym /viramamlym /ddhamlym ണ്ഢ 
- [x] /nnamlym /viramamlym /ddhamlym ണ്ഢ
- [x] /nyamlym /viramamlym /chamlym ഞ്ഛ 
- [x] /shamlym /viramamlym /chamlym ശ്ഛ 
- [x] /gamlym /viramamlym /dadhamlym ഗ്ദ്ധ
- [x] /ssamlym /viramamlym /ttattamlym ഷ്ട്ട 
- [x] /pamlym /viramamlym /tatamlym പ്ത്ത

<img width="800" alt="Screenshot 2023-06-16 at 4 19 06 PM" src="https://github.com/googlefonts/googlesans/assets/22956348/884d7c75-5a95-4c95-bf60-5561ac58096c">

- [x] /kamlym /viramamlym /ttamlym /viramamlym /pamlym ക്ട്പ
- [x] /kamlym /viramamlym /ttamlym /viramamlym /samlym ക്ട്സ
- [x] /ssamlym /viramamlym /ttamlym /viramamlym /pamlym  ഷ്ട്പ
- [x] /kamlym /viramamlym /ttamlym /viramamlym /rramlym ക്ട്റ 
- [x] /kamlym /viramamlym /ttamlym /viramamlym /namlym ക്ട്ന
- [ ] /yayamlym /viramamlym /tamlym യ്യ്ത 
- [x] /kamlym /viramamlym /ttamlym /viramamlym /camlym ക്ട്ച
- [x] /ssamlym /viramamlym /ttamlym /viramamlym /tthamlym ഷ്ട്ഠ 
- [x] /damlym /viramamlym /gamlym /viramamlym /damlym ദ്ഗ്ദ 
- [ ] /yayamlym /viramamlym /mamlym യ്യ്മ
- [x] /kamlym /viramamlym /ttamlym /viramamlym /mamlym ക്ട്മ
- [x] /ssamlym /viramamlym /ttamlym /viramamlym /mamlym ഷ്ട്മ
- [x] /kamlym /viramamlym /ttamlym /viramamlym /bamlym ക്ട്ബ
- [x] /pamlym /viramamlym /tamlym /viramamlym /kamlym പ്ത്ക 
- [x] /kamlym /viramamlym /ttamlym /viramamlym /phamlym ക്ട്ഫ

<img width="1147" alt="Screenshot 2023-06-16 at 12 34 12 AM" src="https://github.com/googlefonts/googlesans/assets/22956348/ee6c3bbb-099c-46e9-a095-a2343f0b7e84">

- [x] /ssamlym /viramamlym /ttamlym /viramamlym /rramlym ഷ്ട്റ 
- [x] /kamlym /viramamlym /ttamlym /viramamlym /bhamlym ക്ട്ഭ 
- [ ] /yayamlym /viramamlym /gamlym യ്യ്ഗ 
- [x] /ssamlym /viramamlym /ttamlym /viramamlym /kamlym ഷ്ട്ക 
- [x] /ssamlym /viramamlym /ttamlym /viramamlym /samlym ഷ്ട്സ 
- [x] /jamlym /viramamlym /pamlym /viramamlym /tamlym ജ്പ്ത 
- [x] /kamlym /viramamlym /ttamlym /viramamlym /tamlym ക്ട്ത
- [x] /vavamlym /viramamlym /kamlym വ്വ്ക 
- [ ] /yayamlym /viramamlym /pamlym യ്യ്പ
- [x] /kamlym /viramamlym /ttamlym /viramamlym /jamlym ക്ട്ജ
- [x] /shamlym /viramamlym /bamlym /viramamlym /damlym ശ്ബ്ദ
- [x] /rramlym /viramamlym /kamlym /viramamlym /ttamlym റ്ക്ട
- [ ] /yayamlym /viramamlym /samlym യ്യ്സ
- [x] /ssamlym /viramamlym /ttamlym /viramamlym /namlym ഷ്ട്ന 
- [x] /samlym /viramamlym /ssamlym /viramamlym /ttamlym സ്ഷ്ട 
- [x] /bamlym /viramamlym /damlym /viramamlym /jamlym ബ്ദ്ജ
- [ ] /yayamlym /viramamlym /rramlym യ്യ്റ 
- [x] /ssamlym /viramamlym /ttamlym /viramamlym /jamlym ഷ്ട്ജ 
- [x] /ssamlym /viramamlym /ttamlym /viramamlym /gamlym ഷ്ട്ഗ 
- [ ] /yayamlym /viramamlym /camlym യ്യ്ച
- [x] /ssamlym /viramamlym /ttamlym /viramamlym /tamlym ഷ്ട്ത
- [ ] /vavamlym /viramamlym /rramlym വ്വ്റ
- [ ] /yayamlym /viramamlym /nnamlym യ്യ്ണ

<img width="1153" alt="Screenshot 2023-06-16 at 4 57 08 PM" src="https://github.com/googlefonts/googlesans/assets/22956348/8633a123-ddba-48c7-bf34-ae0fd052fd0f">

- [x] /kamlym /viramamlym /ttamlym /viramamlym /ddamlym ക്ട്ഡ 
- [x] /ssamlym /viramamlym /ttamlym /viramamlym /bamlym ഷ്ട്ബ
- [x] /bamlym /viramamlym /dadamlym ബ്ദ്ദ
- [x] /pamlym /viramamlym /tamamlym പ്ത്മ 
- [x] /gamlym /viramamlym /damlym /viramamlym /namlym ഗ്ദ്ന
- [ ] /vavamlym /viramamlym /pamlym വ്വ്പ 
- [x] /thamlym /viramamlym /ssamlym /viramamlym /ttamlym ഥ്ഷ്ട
- [x] /ssamlym /viramamlym /ttamlym /viramamlym /bhamlym ഷ്ട്ഭ
- [x] /nyamlym /viramamlym /chamlym /viramamlym /tamlym ഞ്ഛ്ത 
- [x] /jamlym /viramamlym /gamlym /viramamlym /damlym ജ്ഗ്ദ
- [x] /kamlym /viramamlym /bamlym /viramamlym /damlym ക്ബ്ദ 
- [x] /tamlym /viramamlym /ssamlym /viramamlym /ttamlym ത്ഷ്ട 
- [x] /pamlym /viramamlym /tasamlym പ്ത്സ 
- [x] /ssamlym /viramamlym /ttamlym /viramamlym /camlym ഷ്ട്ച
- [x] /bamlym /viramamlym /damlym /viramamlym /gamlym ബ്ദ്ഗ
- [x] /nnamlym /viramamlym /kamlym /viramamlym /ttamlym ണ്ക്ട
- [ ] /vavamlym /viramamlym /bamlym വ്വ്ബ 

<img width="1165" alt="Screenshot 2023-06-16 at 4 58 34 PM" src="https://github.com/googlefonts/googlesans/assets/22956348/e9d9e699-b2c0-4388-93e2-9c3389c9ee7a">

- [x] /bamlym /viramamlym /dhamlym /viramamlym /namlym ബ്ധ്ന 
- [x] /yamlym /viramamlym /pamlym /viramamlym /tamlym യ്പ്ത
- [x] /tamlym /viramamlym /kamlym /viramamlym /ttamlym ത്ക്ട 
- [x] /ramlym /viramamlym /ssamlym /viramamlym /ttamlym ര്ഷ്ട
- [x] /bamlym /viramamlym /damlym /viramamlym /mamlym ബ്ദ്മ 
- [ ] /vavamlym /viramamlym /shamlym വ്വ്ശ 
- [x] /samlym /viramamlym /bamlym /viramamlym /damlym സ്ബ്ദ 
- [x] /ssamlym /viramamlym /ttamlym /viramamlym /phamlym ഷ്ട്ഫ 
- [x] /pamlym /viramamlym /tamlym /viramamlym /shamlym പ്ത്ശ 
- [ ] /vavamlym /viramamlym /namlym വ്വ്ന 
- [x] /ssamlym /viramamlym /ttamlym /viramamlym /damlym ഷ്ട്ദ
- [ ] /yayamlym /viramamlym /jamlym യ്യ്ജ 
- [x] /gamlym /viramamlym /dadamlym ഗ്ദ്ദ 
- [x] /gamlym /viramamlym /kamlym /viramamlym /ttamlym ഗ്ക്ട 
- [x] /samlym /viramamlym /pamlym /viramamlym /tamlym സ്പ്ത
- [x] /gamlym /viramamlym /damlym /viramamlym /mamlym ഗ്ദ്മ
- [x] /kamlym /viramamlym /pamlym /viramamlym /tamlym ക്പ്ത 
- [x] /ssamlym /viramamlym /ttamlym /viramamlym /papamlym ഷ്ട്പ്പ 

<img width="1171" alt="Screenshot 2023-06-16 at 5 00 40 PM" src="https://github.com/googlefonts/googlesans/assets/22956348/e95c02f4-e65d-475e-8cef-987df21fb18c">

- [ ] /yayamlym /viramamlym /kakamlym യ്യ്ക്ക 
- [x] /kamlym /viramamlym /ttamlym /viramamlym /samlym /viramamlym /mamlym ക്ട്സ്മ 
- [x] /bamlym /viramamlym /damlym /viramamlym /tatamlym ബ്ദ്ത്ത 
- [x] /kamlym /viramamlym /ttamlym /viramamlym /samlym /viramamlym /kamlym ക്ട്സ്ക 
- [x] /kamlym /viramamlym /ttamlym /viramamlym /samlym /viramamlym /pamlym ക്ട്സ്പ 
- [ ] /yayamlym /viramamlym /nanamlym യ്യ്ന്ന
- [x] /ssamlym /viramamlym /ttamlym /viramamlym /ramlym /viramamlym /pamlym ഷ്ട്ര്പ
- [ ] /yayamlym /viramamlym /kakamlym /viramamlym /jamlym യ്യ്ക്ക്ജ 
- [x] /pamlym /viramamlym /tasamlym /viramamlym /tatamlym പ്ത്സ്ത്ത 
- [x] /samlym /viramamlym /pamlym /viramamlym /ssamlym /viramamlym /ttamlym സ്പ്ഷ്ട
- [x] /samlym /viramamlym /yayamlym /viramamlym /rramlym സ്യ്യ്റ
- [x] /pamlym /viramamlym /tamlym /viramamlym /papamlym പ്ത്പ്പ 
- [x] /yamlym /viramamlym /kakamlym /viramamlym /kamlym /viramamlym /ttamlym യ്ക്ക്ക്ട
- [ ] /narramlym /viramamlym /samlym /viramamlym /bamlym /viramamlym /dhamlym ന്റ്സ്ബ്ധ 
- [x] /lapamlym /viramamlym /pamlym /viramamlym /tamlym ല്പ്പ്ത 
- [x] /kamlym /viramamlym /ttamlym /viramamlym /cacamlym ക്ട്ച്ച 
- [x] /samlym /viramamlym /ramlym /viramamlym /ssamlym /viramamlym /ttamlym സ്ര്ഷ്ട 
- [x] /kamlym /viramamlym /ttamlym /viramamlym /samlym /viramamlym /tamlym ക്ട്സ്ത 
- [ ] /yayamlym /viramamlym /sathamlym യ്യ്സ്ഥ 
- [x] /pamlym /viramamlym /tasamlym /viramamlym /camlym പ്ത്സ്ച 
- [x] /bamlym /viramamlym /jamlym /viramamlym /kamlym /viramamlym /ttamlym /viramamlym /samlym ബ്ജ്ക്ട്സ 
- [ ] /yayamlym /viramamlym /tanamlym യ്യ്ത്ന 

<img width="1260" alt="Screenshot 2023-06-16 at 5 03 44 PM" src="https://github.com/googlefonts/googlesans/assets/22956348/589373b7-19c5-42f6-aa27-777af768c232">

- [x] /bamlym /viramamlym /damlym /viramamlym /ngangamlym ബ്ദ്ങ്ങ 
- [x] /kamlym /viramamlym /ttamlym /viramamlym /samlym /viramamlym /ddamlym ക്ട്സ്ഡ
- [x] /ssamlym /viramamlym /ttattamlym /viramamlym /ttamlym ഷ്ട്ട്ട 
- [x] /pamlym /viramamlym /tatamlym /viramamlym /namlym പ്ത്ത്ന 
- [x] /damlym /viramamlym /gamlym /viramamlym /dadhamlym ദ്ഗ്ദ്ധ
- [x] /kamlym /viramamlym /ttamlym /viramamlym /samlym /viramamlym /rramlym ക്ട്സ്റ
- [x] /ssamlym /viramamlym /ttamlym /viramamlym /ngangamlym ഷ്ട്ങ്ങ 
- [ ] /vavamlym /viramamlym /hamlym /viramamlym /samlym വ്വ്ഹ്സ 
- [x] /gamlym /viramamlym /damlym /viramamlym /yamlym /viramamlym /tamlym ഗ്ദ്യ്ത 
- [ ] /yayamlym /viramamlym /samlym /viramamlym /kamlym യ്യ്സ്ക 
- [x] /dadamlym /viramamlym /gamlym /viramamlym /damlym ദ്ദ്ഗ്ദ 
- [x] /rramlym /viramamlym /kamlym /viramamlym /ttamlym /viramamlym /mamlym റ്ക്ട്മ 
- [x] /yayamlym /viramamlym /kamlym /viramamlym /papamlym യ്യ്ക്പ്പ 
- [x] /pamlym /viramamlym /tatamlym /viramamlym /samlym പ്ത്ത്സ 

<img width="1237" alt="Screenshot 2023-06-16 at 5 04 35 PM" src="https://github.com/googlefonts/googlesans/assets/22956348/cd2b0bbd-c830-485f-9072-be7ecf3b6c1a">

**Comment by kalapi** [comment]
CC @joanaranito

**Comment by joanaranito** [comment]
Hi Marianna,

I've been looking through these, and I wanted to give you a quick update before our meeting today:

- v_va-malayalam and y_ya-malayalam were missing from the opentype features, so I've added them to the code. 

- For the majority of the other conjuncts, the GS shaping is what we would expect. It looks like Noto has the conjunct outlines in the set, but some of them are not forming. Here's an example:

<img width="284" alt="Screenshot 2023-06-21 at 11 57 47" src="https://github.com/googlefonts/googlesans/assets/4913245/26c3c091-ee3f-48b6-91a5-40a0d3b0f9d0">

<img width="488" alt="Screenshot 2023-06-21 at 12 01 40" src="https://github.com/googlefonts/googlesans/assets/4913245/23271bd7-b5a3-4f02-8644-2e0de672d0c0">

- I can't replicate the odd virama position in your second screenshot. There, the GS virama seems to be positioned between the glyphs, instead of attaching to the first glyph. But when I test the fonts, it attaches to the first glyph as expected. Here's an example: 

<img width="280" alt="Screenshot 2023-06-21 at 11 41 20" src="https://github.com/googlefonts/googlesans/assets/4913245/4cb4aa9e-2027-46c1-988c-9e348d1e1537">

I'm not sure what could be causing this! I know you're testing in Harfbuzz, but what software/OS are you using? Just so I can try to replicate the environment as much as I can :)


See you in today's meeting!

**Comment by joanaranito** [comment]
Hey Marianna,

These are the combinations from the second screenshot (where the virama appears misplaced), tested on FontGoggles after our meeting:

<img width="748" alt="Screenshot 2023-06-21 at 15 23 53" src="https://github.com/googlefonts/googlesans/assets/4913245/0270f70e-8f38-4f77-a2f8-91f503f69ae0">

Strings: ഷ്ട പ്ത ക്ട ബ്ദ ഗ്ദ ബ്ധ ഞ്ഛ ഗ്ദ്ധ ഷ്ട്ട പ്ത്ത

So it seems that in the screenshot, not only was the virama not being positioned correctly, but the conjuncts were also not shaping! Could it be an issue in the string input?

I also double-checked the placement of the virama in the single base glyphs from the screenshot, just for peace of mind, and I can confirm it looks correct:

<img width="543" alt="Screenshot 2023-06-21 at 15 28 05" src="https://github.com/googlefonts/googlesans/assets/4913245/4f309210-98b0-4a1f-81b9-f52537104211">

Strings: ഷ് പ് ക് ബ് ഗ് ബ് ഞ് ഗ്ദ് ഷ്

**Comment by joanaranito** [comment]
Hey @MariannaPaszkowska, I've ticked off all the clusters that were shaping as expected, and left the ones that involve y_ya, v_va, and n_rra viarama (which were clashing), in case you want to double-check them :)

**Comment by MariannaPaszkowska** [comment]
Thanks, Joana, I tested it again in different environments, and I cannot recreate it anymore.
Thanks for your quick response and new delivery! 🚀
