### ISSUE TITLE
Add uppercase Eng alternate character

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans#588]
TBD

**Comment by chrissimpkins** [comment]
We are attempting to improve the support for sub-Saharan Africa Latin-based languages.  Here are additional details of the requirement for this request (source: https://jamrapatel.github.io/font-lang-support-afr-priority/repairing-fonts.html#variant)

<img width="1481" alt="989TM7baDrDUPTp" src="https://github.com/googlefonts/googlesans/assets/4249591/bf348d1f-ca06-4fd6-8ca8-05729a57863d">

Shaperglot indicates that we are missing the variant form of the glyph as shown on the right. I believe that the GRAD=0 masters are supported in Denis Jacquerye's development work.  If so, we will only need to add the GRAD= +200 and GRAD= -50 masters.
