### ISSUE TITLE
Improve the spacing of the `1)` sequence

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans#589]
User report:

> I noticed while typing up a google doc that (1) renders a little weirdly
>
>Details:
>
>OS: OSX
Browser: Chrome
App: docs.google.com
Font Size: 11
Font: "Google Sans Text"
compared with some other common body-text fonts in Google Docs: http://screen/8YGyrcde269H58J
>
>Normally I am used to being able to type out (1) detail one (2) detail two (3) detail three in a list and this is the first time I think I've encountered a font where I've found a number looking this imbalanced.
>
>My specific criticism is about the closing paren ) being too close to the 1. The remaining digits all look great.
>
>I think Roboto will probably always look better by virtue of using a fixed width for numbers but if it's possible to add a little more space between the 1 and the ) in Google Sans Text I think this will look considerably better.

![8YGyrcde269H58J](https://github.com/googlefonts/googlesans/assets/4249591/8bd51014-a97f-4043-85c2-6c3a22ef57b4)

**Comment by chrissimpkins** [comment]
Confirming that this is still in scope for the v12 release?

**Comment by Hoolean** [comment]
> Confirming that this is still in scope for the v12 release?

Update: yes, Eduardo prepared a fix for this; I have included it as part of the other respacing in #333 now :)
