### ISSUE TITLE
.notdef is not the first glyph in the glyphOrder

### ISSUE THREAD

**Issue by anthrotype** [googlefonts/googlesans#590]
the ufos in source/ directory all contain public.glyphOrder key in their lib.plist, however the .notdef glyph is not listed as the first glyph, as it should be.
This is relying on the fact that ufo2ft will ignore this and automatically reorder the .notdef (if present) to be the first glyph in the font. This is required otherwise whatever happens to be the first glyph in the font with glyph index 0 will behave as if it has no mappings in the cmap table thus unaccessible.
currently fontc takes the provided pubic.glyphOrder at face value and applies it as is without any such reordering of the .notdef glyph, leading to invalid placement of the .notdef glyph.
We can definitely fix this in fontc compiler but I would also recommend that you fix this in the sources by moving .notdef glyph at the top of the public.glyphOrder, as it already is the case for the compiled fonts anyway.

**Comment by schriftgestalt** [comment]
Not sure if the glyphOrder should require to start with the .notdef. Any compiler should reorder it in any case.

**Comment by anthrotype** [comment]
> Any compiler should reorder it in any case.

sure, as I said, I will fix the compiler to do the reordering, but why bother adding an explicit glyphOrder that doesn't match the built font and needs to be changed on compile?

**Comment by chrissimpkins** [comment]
Thanks for the report Cosimo! We'll address it.

**Comment by schriftgestalt** [comment]
> but why bother adding an explicit glyphOrder that doesn't match the built font and needs to be changed on compile?

the glyphOrder is not only for the .notdef, but for all other glyphs, too. I would say only for all other glyphs.

**Comment by belluzj** [comment]
Fixed by https://github.com/googlefonts/googlesans/pull/533
