### ISSUE TITLE
Investigate the language support impact of the Latin subsetter in GS

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans#596]
Q: Are we preserving all of the Latin African languages in the web API pipeline? 
This will be checked by a new FB check "Check for codepoints not covered by METADATA subsets"

**Comment by madig** [comment]
We are, if the glyphs in question are reachable via codepoint or features. Otherwise, they are, well, unreachable anyway.

**Comment by chrissimpkins** [comment]
This is an internal subsetter definition issue.  Separate from our repository side subsetter defs.

**Comment by chrissimpkins** [comment]
There is a new fontbakery check to assess this by comparing codepoints in fonts vs. codepoints defined across all of our internal pipeline subsetter definitions.  We'll need to understand if we need to add new subsetter metadata configuration, or expand existing subsetter definitions to support the full set of Latin-based langs we are attempting to support in GS (and GSF).

It gets into complexities of having base forms and mark forms in different subset definitions and browsers being unable to compose glyphs on the fly across different subset fonts delivered through the CSS API

**Comment by MariannaPaszkowska** [comment]
@chrissimpkins I run the latest fb locally on the release 11.001 and got a **warn**. It's something we will need to investigate, there are over 400 glyphs that might not be accessible: 
<img width="586" alt="Screenshot 2023-10-16 at 6 53 43 PM" src="https://github.com/googlefonts/googlesans/assets/22956348/bed91e4e-084b-4ba4-ab60-b34cd0264d84">

We do have defined some of the mentioned in the check subsets, but a few seem to be missing. From our METADATA.pb
subsets: "armenian"
subsets: "bengali"
subsets: "cyrillic"
subsets: "devanagari"
subsets: "ethiopic"
subsets: "georgian"
subsets: "greek"
subsets: "gurmukhi"
subsets: "hebrew"
subsets: "khmer"
subsets: "lao"
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
subsets: "tamil"
subsets: "telugu"
subsets: "thai"
subsets: "vietnamese"

**Comment by chrissimpkins** [comment]
Ty! Will you point me to the METADATA.pb file that you used for that analysis?

**Comment by MariannaPaszkowska** [comment]
@chrissimpkins https://github.com/googlefonts/googlesans/blob/main/metadata/METADATA.pb

**Comment by chrissimpkins** [comment]
https://github.com/googlefonts/googlesans/issues/601#issuecomment-1775515339

**Comment by MariannaPaszkowska** [comment]
Closing this, discussion moved to #601
