### ISSUE TITLE
Remove the "Text" fvar instance definitions

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans#602]
Let's remove the 17pt instances from the fvar - in a similar way that we did that for GSF.
It's a change following a request from the design team. We'd like to support automatic optical sizing in Figma.
We will still build static instances and include "Text" instances in the STAT table.

**Comment by belluzj** [comment]
Fixed by https://github.com/googlefonts/googlesans/pull/524
