### ISSUE TITLE
Interpolation issues

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans#606]
- [x] Glyph f_f_t was not compatible: 
    Contour order differs: [0, 1, 2] in '', [1, 0, 2] in 'opsz=17.0'

<img width="564" alt="Screenshot 2023-11-16 at 2 21 00 PM" src="https://github.com/googlefonts/googlesans/assets/22956348/5754740e-4be9-491c-8adc-a49d655441de">

- [x] Glyph uni09260941 was not compatible: 

    Contour order differs: [0, 1, 2, 3] in '', [0, 2, 1, 3] in 'opsz=17.0'

- [x] Glyph uni0B320B17 was not compatible: 

    Contour order differs: [0, 1, 2, 3] in '', [0, 2, 1, 3] in 'opsz=17.0'
    Contour 1 start point differs: '', 'opsz=17.0'
    Contour 2 start point differs: '', 'opsz=17.0'
    Contour 1 start point differs: '', 'opsz=17.0 wght=700.0'
    Contour 2 start point differs: '', 'opsz=17.0 wght=700.0'

- [x] Glyph uni0B380B1F was not compatible: 

    Contour order differs: [0, 1, 2, 3, 4] in '', [0, 2, 1, 3, 4] in 'opsz=17.0'
    Contour 1 start point differs: '', 'opsz=17.0'
    Contour 2 start point differs: '', 'opsz=17.0'
    Contour 1 start point differs: '', 'opsz=17.0 wght=700.0'
    Contour 2 start point differs: '', 'opsz=17.0 wght=700.0'

- [x] Glyph uni19EB was not compatible: 

    Contour order differs: [0, 1, 2, 3, 4] in '', [0, 3, 2, 1, 4] in 'opsz=17.0 wght=700.0'
<img width="249" alt="Screenshot 2023-11-16 at 2 32 11 PM" src="https://github.com/googlefonts/googlesans/assets/22956348/f01d6b7d-57d5-4113-9006-e2d11be29fd2">

- [x] Glyph uni19FB was not compatible: 

    Contour order differs: [0, 1, 2, 3, 4] in '', [2, 1, 0, 3, 4] in 'opsz=17.0 wght=700.0'

<img width="226" alt="Screenshot 2023-11-16 at 2 32 34 PM" src="https://github.com/googlefonts/googlesans/assets/22956348/d441e0d9-5b87-4b60-9331-3275c0c89335">

**Comment by MariannaPaszkowska** [comment]
Here is a PDF with the images of all bugs: [GoogleSans.pdf](https://github.com/googlefonts/googlesans/files/13379172/GoogleSans.pdf)
Thank you, @behdad!

**Comment by MariannaPaszkowska** [comment]
@belluzj this might be also worth to include in the anchors PR

**Comment by belluzj** [comment]
Yes, I forward to Eduardo as well, thanks!

**Comment by behdad** [comment]
It looks to me like these are fixed in the latest release?

I added two new tests to the tool: a kink detector, and an "underweight" detector. Both of which make a lot of noise that might be fine ignoring. I'm still tuning them both.

Attaching the new report. I'm interested to hear what you think and how useful this is.
[out.pdf](https://github.com/googlefonts/googlesans/files/13565162/out.pdf)

**Comment by belluzj** [comment]
@behdad it looks like your report is for Flex, but this is the repo for Google Sans (not Flex)

**Comment by behdad** [comment]
Err. My bad. Lemme generate a new one. I'm testing v11.001.

Note that the new tests (kink, underweight) add a lot of noise. But I've made it show the more important issues first.

[GoogleSans.pdf](https://github.com/googlefonts/googlesans/files/13601959/GoogleSans.pdf)
[GoogleSans-Italic.pdf](https://github.com/googlefonts/googlesans/files/13601960/GoogleSans-Italic.pdf)

**Comment by belluzj** [comment]
Thanks! I think that among the reported kinks, those between 17 and 18 opsz won't be of interest because the transition is forced to be "hard" by a mapping, so the midway are never seen. Could they be filtered out maybe? I've just skimmed the report and will let Marianna comment further

**Comment by behdad** [comment]
> Thanks! I think that among the reported kinks, those between 17 and 18 opsz won't be of interest because the transition is forced to be "hard" by a mapping, so the midway are never seen. Could they be filtered out maybe? I've just skimmed the report and will let Marianna comment further

Thanks for the feedback. Let me think about it.
