### ISSUE TITLE
Fix ` ю` in BGR localisation 

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans#607]
Hi @belluzj I noticed that ` ю`  glyph has a new issue: 
<img width="457" alt="Screenshot 2023-12-04 at 6 15 55 PM" src="https://github.com/googlefonts/googlesans/assets/22956348/c0b74e95-2fd3-490d-a950-b517a01647d5">

The top fonts shown here are from this branch, and the bottom is the release. It seems like a wrong component order. 

I merged this PR so as not to hold on to the work on kerning, but can we fix this one? Perhaps in a new PR?

_Originally posted by @MariannaPaszkowska in https://github.com/googlefonts/googlesans/issues/598#issuecomment-1838986981_

**Comment by belluzj** [comment]
@MariannaPaszkowska Sorry about that, I forwarded the issue to Eduardo and if that's OK he'll push it to a PR along with the anchor fixes?

**Comment by MariannaPaszkowska** [comment]
Works well for me, thanks! 
Any chance he could also review/retouch those:

5: proportion of the belly with the top, it might need checking all design sources to aim for a similar balance:
<img width="46" alt="Screenshot 2023-12-04 at 5 38 43 PM" src="https://github.com/googlefonts/googlesans/assets/22956348/27bb2c14-ceb7-429f-b8ab-c4823938d833">

Vertical position of the small element in the middle might need balancing:
<img width="55" alt="Screenshot 2023-12-04 at 5 38 36 PM" src="https://github.com/googlefonts/googlesans/assets/22956348/21ad8af2-5105-4b13-925b-feb45d99639e">

Position of the diagonal bar needs retouch in some DS:
<img width="77" alt="Screenshot 2023-12-04 at 5 38 32 PM" src="https://github.com/googlefonts/googlesans/assets/22956348/7b7e8967-af3d-4ae9-b055-5bb69485dc93">
<img width="88" alt="Screenshot 2023-12-04 at 5 41 17 PM" src="https://github.com/googlefonts/googlesans/assets/22956348/e89a531c-7915-482a-91ae-b732a77dd13f">

**Comment by belluzj** [comment]
@MariannaPaszkowska yes, I forward these as well to Eduardo. We'll recap in the PR description the list of what is fixed.

**Comment by belluzj** [comment]
@MariannaPaszkowska Hello Marianna, Eduardo is wondering if you could clarify what should be changed with the 5, do you want it matched to something specific? Or just generally improved?

**Comment by MariannaPaszkowska** [comment]
@belluzj Thanks! I noticed that in the height update only the top of the "five", and not its belly moved up, and the proportions look just slightly off. I thought just reviewing it across all masters would be good.

**Comment by belluzj** [comment]
Thanks, I forward this to Eduardo and the PR with the fixes will come shortly!

**Comment by belluzj** [comment]
Fixed by https://github.com/googlefonts/googlesans/pull/608
