### ISSUE TITLE
Interpolation issues in GS Italic

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans#614]
Hi @belluzj, I reviewed the build in the mail, and there still are a couple of minor interpolation issues outside of the 17/18 ops transition. 
I reviewed this build: https://github.com/googlefonts/googlesans/actions/runs/7251645463 
Is this something that your team could have a look at? 

<img width="650" alt="Screenshot 2024-01-09 at 11 43 35 AM" src="https://github.com/googlefonts/googlesans/assets/22956348/c8dc3c2b-e2a1-451c-8c96-ab2ad8c8c2b5">
<img width="675" alt="Screenshot 2024-01-09 at 11 43 16 AM" src="https://github.com/googlefonts/googlesans/assets/22956348/2e14773a-a9b8-4adb-a5a8-fae2bb4809e9">
[GS12ItalicReport.pdf](https://github.com/googlefonts/googlesans/files/13874341/GS12ItalicReport.pdf)

**Comment by belluzj** [comment]
> Is this something that your team could have a look at?

Hello Marianna, certainly, I'll forward the task to the team.

**Comment by belluzj** [comment]
The glyphs in question are /archaicii-malayalam.part /rr_rra-malayalam
