### ISSUE TITLE
Add encodings for superscript and subscript figures

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans#623]
We appear to be missing the cmap Unicode encodings for our superscript and subscript figures based on an internal report.

Let's look into adding these encodings.

![7KCAPpeyxhw5yre](https://github.com/googlefonts/googlesans/assets/4249591/c3bd6822-072a-4f5f-844d-043e50c522c1)

**Comment by belluzj** [comment]
Is this something we should look into? I see that @MariannaPaszkowska is currently assigned

**Comment by MariannaPaszkowska** [comment]
It seems that all those codepoints are covered. 

I checked: 

U+2070 `⁰`, U+00B9 `¹`, U+00B2 `²`, U+00B3 `³`, U+2074 `⁴`, U+2075 `⁵`, U+2076 `⁶`, U+2077 `⁷`, U+2078 `⁸`, U+2079 `⁹`, U+2080 `₀`, U+2081 `₁`, U+2082 `₂`, U+2083 `₃`, U+2084 `₄`, U+2085 `₅`, U+2086 `₆`, U+2087 `₇`, U+2088 `₈`, U+2089 `₉` 

<img width="1351" alt="Screenshot 2024-09-03 at 2 07 05 PM" src="https://github.com/user-attachments/assets/d37157f6-10e1-4502-9c7e-0c844d06818e">

**Comment by MariannaPaszkowska** [comment]
@chrissimpkins could this be an issue with our API?

**Comment by chrissimpkins** [comment]
I can confirm that we no longer show tofu on the front end across Google Sans, Google Sans Text (static) and Google Sans Flex.  There appears to be no further issue to address here.  It sounds like this may have been an internal subsetter issue that has since been addressed.
