### ISSUE TITLE
Fix tt ligature crossbar to be pixel perfect on Android

### ISSUE THREAD

**Issue by davelab6** [googlefonts/googlesans#624]
Per https://github.com/googlefonts/googlesans-flex/issues/901 I propose that in the next release of GS that the tt ligature fix in GSF be backported to GS :)

**Comment by MariannaPaszkowska** [comment]
Thanks @davelab6 ! I noticed that this issue might affect other glyphs, too. Here is a list of all glyphs and a suggested solution: 

** All glyphs to fix:** 
` t_t ` 
` f_t  t_f  f_f  f_f_t  f_f_i  f_f_b  f_f_h  f_f_j  f_f_k  f_f_l`

**Suggested solution:**
Add three glyphs and replace where necessary:
`tlig.2`, `flig3` and `flig4`
<img width="271" alt="Screenshot 2024-03-15 at 12 02 56 PM" src="https://github.com/googlefonts/googlesans/assets/22956348/4f4d32c6-39c2-4f92-a5af-675b05ef6df9">

<img width="502" alt="Screenshot 2024-03-15 at 12 15 51 PM" src="https://github.com/googlefonts/googlesans/assets/22956348/b50551d2-fe5e-4f0b-a714-e232cb13231e">

<img width="387" alt="Screenshot 2024-03-15 at 11 58 40 AM" src="https://github.com/googlefonts/googlesans/assets/22956348/3c2fb68f-e329-4c52-bb9c-ee22a714260c">

**Comment by davelab6** [comment]
I'm confused by this proposal. Can you join the Friday dev call to discuss?:)

**Comment by MariannaPaszkowska** [comment]
Yes, of course, I'm planning to join the meeting. IN the meantime, here is some more info.
If the partly overlapping crossbar is causing an issue to the t_t ligature, the other ligatures with partly overlapping crossbars would have issues, too. I say would, because I couldn't reproduce it. Partly overlapping crossbars are present in 11 ligatures. Instead of decomposing them, we could introduce 3 new ligatures that would fix the issue. 
Font has already: 
flig1 - (flat top f, for 'fl' type of combinations) used for glyphs: f_b, f_h,  f_k f_l - here it should stay as is; and it is also used where its crossbar partly overlaps: f_f_b f_f_h f_f_k f_f_l , here should be replaced with a new glyph that wouldn't partly overlap. 
flig2 - used for glyphs:  f_f, f_i, f_j, f_t, f_f_k, f_f_l, f_f_b - here it should stay as is; it is also used as first and second component here: f_f_i, f_f_j, f_f_t  - the second component should change.

**Comment by schriftgestalt** [comment]
If there are two bars that fully overlap, that part will still render thicker as the parts of the bar on the outside that don't overlap. So the components should be set up in a way that there is only one bar from one side and the other components has nothing.

**Comment by belluzj** [comment]
@MariannaPaszkowska Eduardo is working on fixing the ligatures, and he reports an inconsistency in the original outlines:

It appears that /flig2 is behaving in different ways depending on the master.

In bold display the hook part is made narrow to have more space between the top part and the dot, in other masters is exactly the same width as the standard /f hook, and in others is even longer. Should I correct this?

Proposed solutions:
1. Just use /longs (the hook part of /f) without changing the width (and avoid adding an extra /longs.liga to account for these variations) then adjust the width and placement of this component and bar.
2. Or add a /longs.liga and make it a touch shorter in all masters, as in the bold display, but then I would adjust the width of glyphs to progress in a similar fashion in all masters.

For now Eduardo will keep this behaviour, but you can let him know tomorrow if you'd prefer a fix.

Screenshots: (the light grey fill shows the ligatures as they are now; the brown outline in the background is the /f)

![image](https://github.com/googlefonts/googlesans/assets/3616772/240543c3-96ca-479f-9943-ded1dbb67797)

![image](https://github.com/googlefonts/googlesans/assets/3616772/0ee5817b-0204-44b1-b30c-b6deaf5b60c5)

![image](https://github.com/googlefonts/googlesans/assets/3616772/f69d99a4-c004-4cc2-b022-ee1b5d2054a9)

![image](https://github.com/googlefonts/googlesans/assets/3616772/71a77302-90d5-4f07-9a41-6322577073e2)

![image](https://github.com/googlefonts/googlesans/assets/3616772/2ae81c50-b13d-417f-ae0f-0bb2aa405288)

![image](https://github.com/googlefonts/googlesans/assets/3616772/ca378810-3804-4d68-97e0-6b7dd30688b5)

**Comment by davelab6** [comment]
@octaviopardo could you explain any design rationale for this?

**Comment by octaviopardo** [comment]
Nope, those seem to be issues that need to be corrected :/ 

We introduced them when changing the approach we had to ligatures, which was done a few days/couple of weeks before delivery. 

(I ve gone through my notes and chats trying to remember the reason why we changed it; Maybe @schriftgestalt can help me there, as those days were quite intense, we were addressing many QA things at the same time, and most discussions were happening on video meetings instead of chats or issues. We may have changed it because we discovered that the previous approach was causing problems while producing the grades with alignments, spacing, and overlaps; or maybe we discovered something else). 

That was when we might have introduced those inconsistencies that @belluzj reported. @belluzj if you want, send me a list of the places where you've spotted the issues so I can look at them and adjust them myself. Or I will review it myself, that's fine too :)

@ MariannaPaszkowska idea sounds good. I ll give it a thought to see if I come up with another idea.

**Comment by davelab6** [comment]
Perfect answer, thanks!

AFAIK @octaviopardo nothing for you to do on GS Classic at this time, AFAIK :) Marianna and DaMa will look into how to best solve this, especially for file size considerations :)

**Comment by schriftgestalt** [comment]
> We introduced them when changing the approach we had to ligatures, which was done a few days/couple of weeks before delivery.

The ligatures where build from repeating outlines. And they would have needed a lot repetitive work to fix the rounds.

and stuff like this:
<img width="530" alt="Screen Shot 2024-03-19 at 09 35 48" src="https://github.com/googlefonts/googlesans/assets/174660/23412846-c217-4af5-bbcd-2f551c62208e">

**Comment by MariannaPaszkowska** [comment]
Hi, this is an issue in font rasteriser, but it was reported in the text set in Google Sans. @schriftgestalt @octaviopardo I think you're talking about GSF; this is important but not related to this issue. 
@belluzj, we should update the design to make it more consistent. 
In the `fi fj` ligatures, the hook should be as long as the hook in `f`, not longer. We are keeping the dot in the `i`, and not replacing it with a longer hook, so there is no reason for the hook to get longer than it is in the regular `f`. And we should keep it consistent across all of the design space. If the design demands it, it can consistently get shorter. The goal is better legibility and good rhythm for readability.

**Comment by MariannaPaszkowska** [comment]
@schriftgestalt I also cannot recreate the issue you're showing in the screenshot in the GSF v2.0 release. I also tested the Grade and Weight axes... See the screenshots. Is this the source data? Or font import in Glyphs All? Could you point me to the exact place where you found this issue in this ligature? 


<img width="669" alt="Screenshot 2024-03-19 at 5 25 43 PM" src="https://github.com/googlefonts/googlesans/assets/22956348/06788998-c7d5-460d-9bfb-9f877ecf2f96">
<img width="669" alt="Screenshot 2024-03-19 at 5 25 30 PM" src="https://github.com/googlefonts/googlesans/assets/22956348/d974b2c8-d790-420c-b34a-23a5abc8832b">

**Comment by MariannaPaszkowska** [comment]
@davelab6, we're first exploring your suggestion to rebuild the f and t with stems+crossbar and then use stretch for a crossbar in ligatures.

**Comment by schriftgestalt** [comment]
I think some of the issue were fixed by Octavio. The screenshots where from before we worked on it.

**Comment by belluzj** [comment]
@MariannaPaszkowska I forwarded your comment [here](https://github.com/googlefonts/googlesans/issues/624#issuecomment-2007476904) to Eduardo and he is on the case.

**Comment by davelab6** [comment]
All sounds good, thanks all

**Comment by belluzj** [comment]
@MariannaPaszkowska Eduardo has finished the uprights with the component stretching idea, and when he started the italics he noticed that there will be an issue: stretching in the italic changes the angle of the ends of the bar component.

![image](https://github.com/googlefonts/googlesans/assets/3616772/4c9bca49-8a78-4799-8f98-09a0544374c7)

In terms of resolutions for this, to avoid just decomposing the ligatures, he proposes to add different bar components with different sizes to be used in different glyphs/ligatures, but that would mean adding extra glyphs.

What do you think?

**Comment by schriftgestalt** [comment]
You could use a smart component for this. 
One problem I see it that the length of the parts of the bar that stick out is difficult to get consistent. So I would cut the bar in pieces. One part that sticks out to the left, one bar the goes between two stems and one sticking out on the right. And then you shapes that look like a "longs" between them. Use "#exit" and "#entry" anchos to connect them together.

**Comment by belluzj** [comment]
@schriftgestalt Eduardo thought about using a smart component, but I believe that the smart component would end up being decomposed, right? That would mean decomposing the whole ligature, and I think the point was to avoid decomposing?

(that's apart from the fact that I'm not sure we can support smart components in the current pipeline for GS)

**Comment by schriftgestalt** [comment]
That's why I suggested the second approach.

**Comment by MariannaPaszkowska** [comment]
Thanks everyone for your contributions. As we discussed in the meeting, we will switch back to the ligature approach and will avoid overlapping crossbars at all, in a way that @schriftgestalt is suggesting.
