### ISSUE TITLE
Move the production of Android builds in-repo

### ISSUE THREAD

**Issue by Hoolean** [googlefonts/googlesans#650]
Take from: googlefonts/pixel-brand-fallback-stack#1

**Comment by Hoolean** [comment]
We can update the branch that #648 tracks with the newer changes from the downstream PR above

**Comment by Hoolean** [comment]
Scripts and subset lists have now been copied over; initial QA profile to follow, pending #633

**Comment by Hoolean** [comment]
#633 is now merged - thanks Marianna! I will look at copying the QA infrastructure over tomorrow

**Comment by Hoolean** [comment]
QA infrastructure has now been copied too; when #648 is merged, everything should be here.

The reporting infrastructure (e.g. that shows clipping for glyphs and words in each font) is still in a different PR in the Pixel repository; we should find a long-term home for this too.

**Comment by RickyDaMa** [comment]
This was decided against as we're also pulling in the Google Sans subfamilies, and it's easier for us to engineer working from a clean slate
