### ISSUE TITLE
Android subsets are missing `('latn', 'CAT ')` language system

### ISSUE THREAD

**Issue by Hoolean** [googlefonts/googlesans#651]
The check added today that compares language system coverage between the original full fonts and the new Android subsets (3fff5597548e20ab7ca3b7dab9c150e66e99cd3e) shows that Catalan is going missing from the GSUB of both the upright and italic subsets.

Next week, on #648 we should:
1. [x] See how the language tag is used in the original fonts; and
2. [x] See why it is going missing

**Comment by Hoolean** [comment]
Used here:

https://github.com/googlefonts/googlesans/blob/2f27b34d869f69265a28681ef8f6c3e600e36998/source/GoogleSans/family.fea#L209-L212

**Comment by Hoolean** [comment]
Explanation: /periodcentered is currently in the 'punctuation' subset, which is not included in LatinGreekCyrillic

**Comment by Hoolean** [comment]
If we put all of the codepoints that we have already shipped to Android in a single subset TTF then this will resolve itself; otherwise, we will need to apply the same solution that we decide on for all other `.locl` variants

**Comment by jackmcDaMa** [comment]
Closed as we have moved our testing of Android subsets over to the [Pixel Fallback Stack repository](https://github.com/googlefonts/pixel-brand-fallback-stack/). We have addressed the specific issues discussed above in this commit [here](https://github.com/googlefonts/pixel-brand-fallback-stack/commit/63f699a24965f3a6c097a4fe6128fca49f1d1617).
