### ISSUE TITLE
Failed test of Github Actions for Ethiopic builds

### ISSUE THREAD

**Issue by NeilSureshPatel** [googlefonts/googlesans#77]
Ran a quick test to see if could get an Ethiopic font to build with Actions (branch: build-ethiopic-test). I took the current Google Sans source and just added a few Ethiopic characters to it. The build fails with the font-bakery check of the expected glyph set. The *.glyphdefset files only seem to cover the LGC character set. However, it doesn't look like there are special definition files in the build-hebrew branch. As a result, I am not entirely sure where to start looking for what to change in the font to get a successful build.

**Comment by chrissimpkins** [comment]
We have a hard-coded set of glyph name and glyph order files defined and use these in our fontbakery based char set checks.  This acts as a prompt to know when something inadvertently changes a glyph name or glyph order.  The tests will always fail in areas of the project that are in development with glyph additions or removals.  The CI tests are intended as a gateway for merges into the master branch and these char set tests can be ignored as you develop.  We will make them pass by updating the expected character set lists as the merge takes place into the upstream source files.  

You can find the builds from your build-ethiopic-test branch here: https://github.com/googlefonts/googlesans/actions/runs/208922579.  The CI fail does not prevent you from building WIP fonts.

If you want to review the fontbakery results as you develop, you can run the fontbakery tests locally **without the character set test checks**.  Use the following commands from the root of the repository with the font path updated to indicate the path to the fonts that you downloaded (or to the local builds if you choose to set up a venv and build locally):

### General QA checks for the project

This includes our custom project specific checks along with those released in the upstream fontbakery "Universal" profile.

```
$ fontbakery check-profile --loglevel WARN qa/check-googlesans.py [path/to]/*.ttf
```

### Fea tag checks for the project

These will fail if you add new features or remove existing features.  

```
$ fontbakery check-profile --loglevel WARN qa/check-fea.py [path/to]/*.ttf
```

Both commands above should pass on the static "Expert" builds and 2-axis VF "Expert" builds.  The "Default" builds are a WIP and we have not transitioned yet.  Internal design teams have requested that we remove all alternate glyph forms and the `aalt` feature code to eliminate the ability to access alternate shapes in this brand font.  They want the brand defined in the defaults.  The alternates will be preserved in "Expert" builds for select users.  "Default" has a different character set and feature tag set c/w the "Expert" build targets.
