### ISSUE TITLE
Accidentally pushed a GoogleSans-Italic source update to master branch

### ISSUE THREAD

**Issue by NeilSureshPatel** [googlefonts/googlesans#78]
I was troubleshooting a build issue and accidentally pushed a GoogleSans-Italic to the master branch instead of the build-ethiopic-test.

**Comment by chrissimpkins** [comment]
https://github.com/googlefonts/googlesans/commit/75a4e68971f1c99588b40b10e83369bdea5d4500 reverts that commit.  Please be careful about the branches that you are working in and always confirm that you are not in master before you push to the remote. Thanks.

**Comment by NeilSureshPatel** [comment]
Thanks, Chris. Sorry about that. I when back to the master to make sure I had a recent fetch and accidentally forgot to switch the branch back.

**Comment by chrissimpkins** [comment]
No worries.  We can trace back through the history to get the old files. This may become a problem for branches based on sources before that commit if we try to rebase.  We will be able to address it.
