### ISSUE TITLE
Remove [DEPRECATED]-GoogleSans?

### ISSUE THREAD

**Issue by davelab6** [googlefonts/googlesans#95]
Can `/googlesans/source/[DEPRECATED]-GoogleSans/` be removed? It went untouched for 7 months now

**Comment by chrissimpkins** [comment]
#24, #26 

I think so. I've just been too chicken to do it :)  

@Colophon-Foundry are you ok with the removal of the deprecated source file directory at this stage?  These are your old files.  They will be preserved in the git history but not immediately available in the HEAD commit of a branch.

**Comment by Colophon-Foundry** [comment]
All good from me! There might be some very old concept files (looking at the x-height etc), but really only useful for historic/reference uses!. Remove away!

**Comment by chrissimpkins** [comment]
#96
