### ISSUE TITLE
Graph filesize impact on Pixel devices

### ISSUE THREAD

**Issue by davelab6** [googlefonts/googlesans#97]
@chrissimpkins, I'd like to have a page/sheet like https://rsheeter.github.io/android_fonts for Pixel system images, so we can chart the file size impact of GS to date, and forecast it, on Pixel phone system images.

No rush on this, but hopefully you can do (or we can ask someone to do) this in Q4 2020 :)

**Comment by chrissimpkins** [comment]
@davelab6 To clarify this is for the Google Sans file size payload impact only?  And we are going to assume the two-axis variable font builds only?

**Comment by chrissimpkins** [comment]
Will the new reporting in the CI serve the purpose here?  It will provide file sizes and some summary statistic data at any commit that you need, including every release commit.
