### ISSUE TITLE
Semi-Colon mixed contour and composite

### ISSUE THREAD

**Issue by dberlow** [googlefonts/googlesans#98]
The comma is a composite, the dot is a contour. 

Is this being resolved in production to two contours?

**Comment by Colophon-Foundry** [comment]
Which dot are you referring to? The period is a contour also?

**Comment by Colophon-Foundry** [comment]
Ah, the semicolon.. Hmm. You can change it to a contour if it helps? Is it being a composite causing issues?

**Comment by dberlow** [comment]
As far as I know, it is not compliant with the format to mix the two in a glyph. 
It either has to be all composites or all contours.

**Comment by Colophon-Foundry** [comment]
Interesting! Then in that case, let's decompose and move to contours all round.

**Comment by chrissimpkins** [comment]
This is fixed in the grade axis expansion sources that will be merged for the v4 release.

**Comment by chrissimpkins** [comment]
Merged to main
