### ISSUE TITLE
Add superscript H and subscript L

### ISSUE THREAD

**Issue by davelab6** [googlefonts/googlesans#99]
A customer team requested (in internal deck "Google Sans Text in Health projects") to add the 2 unicodes `ᴸᴴ` (edit, superscript H, subscript L) to the project; I just tested Version 3.003 (from https://github.com/googlefonts/googlesans/releases `/build\ 2/GoogleSans/static/expert/GoogleSans-Regular.ttf`) and it doesn't have them (edit, as encoded glyphs). 

<img width="1512" alt="Screen Shot 2020-10-15 at 2 18 50 PM" src="https://user-images.githubusercontent.com/261579/96170529-b3b7b380-0ef1-11eb-8501-c29c661ad124.png">

**Comment by moyogo** [comment]
ᴸ and ᴴ are in the superscript capital set of the typographic Latin global set. They are in the cmap like capital modifier letters and with the sups feature for L and H.

**Comment by davelab6** [comment]
I misread the feature request! It was

> “H” and “L” are often use in health data for abnormal status. We hope to add:
> * H for superscript
> * L for subscript
>
>
<img width="597" alt="Screen Shot 2020-10-15 at 3 40 09 PM" src="https://user-images.githubusercontent.com/261579/96177977-ba97f380-0efc-11eb-9607-f5f6e474f246.png">

I see there is a lowercase l subscript (`0x2097 ₗ`) but apparently no uppercase.

**Comment by davelab6** [comment]
Also customer said, 

> This is a very modest 'L' subscript. it might not be below the bottom-line enough. It feels asymmetrical with the H superscript. Additionally, the XX moving up and down the box as a result of having the sub/super-script also seems a bit strange.

**Comment by davelab6** [comment]
I guess the baseline shift occurs as a side effect of font fallback, where the line reacts to the fallback font's vertical metrics being introduced. 

@moyogo thanks for the quick reply! :)

> ᴸ and ᴴ are in the superscript capital set of the typographic Latin global set. They are in the cmap like capital modifier letters and with the sups feature for L and H.

Okay great! 

(a) Why not encode these glyphs, when they are encodable?

(b) Will the `subs` and `sups` OT features in Google Sans address the line height change?

**Comment by chrissimpkins** [comment]
This request was discussed with core team and rejected at the time as it was felt to be too niche to support.  Happy to revisit that decision.  Particularly if these alphabetic outlines for subs/sups are coming in the Latin global set anyways.  FIle size considerations were the factor that tipped the scale at the time.

**Comment by MariannaPaszkowska** [comment]
Closed as this seems to be a duplicate of #27
